### ISSUE TITLE
Utiliser le template print pour l'impression des onglets

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1003]
Lui passer une variable locale pour que ça n'imprime que l'onglet choisi

**Comment by kemenaran** [comment]
J'ai l'impression qu'on n'a pas de demande usagers là dessus, et qu'on ne va pas s'en occuper tout de suite. Je ferme.

**Comment by gregoirenovel** [comment]
J'ai le souvenir d'avoir vu ça passer au support
