### ISSUE TITLE
ETQ Administrateur, je veux pouvoir router (pré affecter), des dossiers à des accompagnateurs

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#1031]
Ce routage s'effectuera selon les valeurs des champs des dossiers.

**Comment by CamilleGarrigue** [comment]
Antoine.B (Versailles)

**Comment by gregoirenovel** [comment]
`#2254`

**Comment by fredZen** [comment]
Helpscout `#2472`

**Comment by LeSim** [comment]
Helpscout `# 2471` 
200 closes sociales au niveau national
Educ nat, routage sur les académies

**Comment by mmagn** [comment]
HS 8796

**Comment by LeSim** [comment]
HS 11057, demande de l'instructeur de ne pas recevoir les notifications hebdomadaires sur des zones qui ne la concerne pas

**Comment by LeSim** [comment]
Résumé du mécanisme que l'on souhaite implémenter :

- une démarche est rattachée à n groupe d'instructeur, ceux-ci sont créés par les administrateurs de la démarche
- chaque groupe d'instructeur possède des chefs qui peuvent nommer/révoquer des instructeurs
- chaque groupe d'instructeur possède obligatoirement un label unique (par exemple 'Val-de-Marne')
- une liste déroulante de routage est automatiquement ajouté à la démarche. Elle contient la liste de tout les labels ('Val-de-Marne', 'Isère' ...)
- un dossier usager est automatiquement routé au groupe d'instructeur selon la valeur du champ routage sélectionnée

points d'attention :

- coordonnées des services
- recherche
- modification du label
- suppression / ajout d'un groupe

**Comment by emsnytech** [comment]
Précision complémentaire de la DIE.
- attribution d'un dossier nouvellement arrivé à un évaluateur au sein du PED  (à voir car pas visible des consultants / procédure interne au PED pouvant être prise en charge dans l'outil de gestion a priori) ;
