### ISSUE TITLE
Les lignes du tableau ne semblent pas s'afficher sous une certaine version de FF

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1064]
Voir avec l'ordi de @CamilleGarrigue 

![bug](https://user-images.githubusercontent.com/1333173/33777259-688841a0-dc44-11e7-80ae-42bea78f3ec1.png)

**Comment by kemenaran** [comment]
@CamilleGarrigue est-ce que tu as toujours ce problème chez toi ?
