### ISSUE TITLE
ETQ Instructeur, je veux pouvoir trier mes dossiers par département

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#1090]
Lorsque mon dossier possède un champ code postal.

Demandé par Dreal Paca (639)

**Comment by gregoirenovel** [comment]
Est-ce que ça ne serait pas un sous-cas d'une issue "permettre de filtrer les dossiers par des sous-parties de la valeur" (et là pour le coup on est p-e pas dans un type de champ "string" mais "code postal") ?

**Comment by LeSim** [comment]
oui, on peut le généraliser de cette façon.
