### ISSUE TITLE
Une notification sur la page d'avis n'est pas forcément visible sur la page de liste des dossiers

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#1112]
Pour reproduire :
- Demander un avis à un autre compte
- Remplir cet avis depuis l'autre compte
- Aller sur la page de liste des dossiers de la procédure
- Constater l'absence de notif sur le dossier en question

Si besoin de plus de détails demander à Ivan.

**Comment by LeSim** [comment]
non reproduis, je veux bien la faire avec toi @icollombet
