### ISSUE TITLE
Améliorations sur le tri des procédures sur la page procédures d'un Instructeur

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1144]
Éventuellement à scinder en plusieurs issues.

- Problème 1 : on explicite pas le tri sur cette page, donc on ne comprend pas par quel critère le tri est fait (si tri il y a, car on ne s'en rend pas forcément compte)

- Problème 2 : actuellement, on tri par date de publication, mais certains utilisateurs aimeraient un tri alphabétique (`#690`), d'autres par notifications (Philippe, mais peut-être est-ce le rôle de la vue activité ?).

- Problème 3 : doit-on permettre aux utilisateurs de choisir le critère de tri ?

**Comment by kemenaran** [comment]
J'ai l'impression que cette issue est trop méta pour qu'on puisse en faire quelque chose ; vous en pensez quoi ?
