### ISSUE TITLE
Sur les dossiers, écrire les timestamps et pas l'état lors du changement d'état

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1187]
Pour le moment, on écrit l'état et ensuite on a un callback qui update les timestamps en fonction.

À la place, écrire les timestamps et l'état dans la même méthode.

**Ce sont les timestamps qui sont la référence pout l'état**, l'attribut état ne sert qu'à accéder plus rapidement à cet état.

Au passage, penser dans le cas d'un retour en construction à repasser en_instruction_at à nil, ce qui n'est pas fait aujourd'hui et on se trouve donc dans un état incohérent entre l'état et les timestamps (cela dit ça permettait, ça permet de garder un peu d'historique et de savoir qu'on a fait une réouverture, information que l'on perd avec les changements proposés).

Penser aussi, lors de la même opération, à réécrire la date en_construction_at ?

**Comment by mmagn** [comment]
Il me semble qu'il y a une question juridique derrière cela (ex: date du premier passage en instruction faisant foi pour les délais), à confirmer.
