### ISSUE TITLE
ETQaccompagnateur sur la nouvelle interface, lorsque je clique sur "télécharger" une pièce-jointe, le téléchargement ne se lance pas systématiquement

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#1188]

**Comment by gregoirenovel** [comment]
Dans la cas d'images, ça les affiche

**Comment by mmagn** [comment]
Du coup c'est un bug ou une feature ?

**Comment by fredZen** [comment]
Je pense que j’étais avec Camille le jour où on a créé cette fiche, et qu’on considérait ça comme un bug (après tout le bouton dit « télécharger », pas « afficher »)
