### ISSUE TITLE
Les sauts de ligne dans les balises empêchent leur reconnaissance

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#1288]
Les balises dans un template de mail ou d’attestation ne sont pas reconnues si elles sont interrompues par un saut de ligne, comme dans l’exemple ci-après

```
Bonjour, votre dossier a bien été reçu le --date de
dépôt--, il va être examiné dans les délais légaux.
```

**Comment by gregoirenovel** [comment]
Je propose de fermer cette issue car pour moi ce n'est pas un bug que nous devons régler, de la même manière qu'on ne va pas détecter et signaler à un admin qu'il a un mot quelconque dans son template qui est tronqué par un saut de ligne. C'est sa responsabilité, pas la notre.

**Comment by mmagn** [comment]
Je change d'avis après avoir passé 30 minutes sur du support sur un cas similaire, https://github.com/betagouv/tps/issues/1573. Je pense que c'est au système d'être intelligent pour éviter à l'utilisateur de se tordre le cerveau.

Peut être qu'on peut corriger le template au moment ou l'administrateur l'enregistre ? Sans toucher au moteur de template.

**Comment by gregoirenovel** [comment]
Est-ce qu'en vrai c'est pas juste notre système de balises qui est merdique. Et qui a bien d'autres problèmes, comme celui des champs avec le même libellé qu'on ne gère pas. Ou encore le changement de libellé une fois la procédure en prod (on ne va *jamais* vérifier si on n'a pas pété un template au passage).

Et je reste convaincu qu'on n'a pas à changer l'input, en tout cas sans en informer l'utilisateur.

Solution miracle-lol : on arrête avec les `--libelle--`, et on passe sur du `--type_de_champ_id--`, sauf qu'on fait un bel éditeur pour les admins pour qu'ils puissent glisser-déposer directement des balises `libelle` (représentées graphiquement par une pilule par exemple, pour les distinguer du reste du texte), mais la "value" que nous on traite derrière c'est le tdc_id et pas le libellé.

**Comment by mmagn** [comment]
HS : 1882
