### ISSUE TITLE
ETQ accompagnateur je souhaite avoir un numéro de dossier propre à ma procédure et suivant la chronologie de dépôt des dossiers.

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#1289]
Exemple de la procédure d'inscription sur le registre des revendeurs d'objets mobiliers de la préf du Rhône. Les dossiers doivent avoir un numéro de 1 à ... suivant l'ordre d dépôt des dossiers sur leur registre.
@A.Raichl (Rhône)

**Comment by CamilleGarrigue** [comment]
Demande renouvelée par @J-N. P (pref Rhône) qui a besoin de compteurs indépendants du numéro de dossier (chaque mairie possède sa propre numérotation des demandes de permis de construire)

**Comment by emsnytech** [comment]
Demande des collectivités locales, ministère des finances, (140 000) ministère de l’écologie

**Comment by tchak** [comment]
Garder en tête que ce changement va avoir une grosse implication sur la qualité/facilité du support client

**Comment by fredZen** [comment]
Oui, je me disais aussi qu’on risque de voir débouler quantité de gens qui ont un problème sur le dossier numéro 5. Jusque là ça n’était pas un problème car le numéro de dossier était unique, et on pouvait donc retrouver le dossier et la procédure.

**Comment by fredZen** [comment]
Est-ce que ce serait acceptable d’avoir des numéros de dossier en deux parties ? Un préfixe unique identifiant la procédure, suivi d’un identifiant séquentiel ? Genre, au lieu de parler des dossiers 1, 2, 3, ..., on parlerait des dossiers DPCT-1, DPCT-2, DPCT-3, ... (avec la contrainte que si un préfixe est déjà pris par une procédure, il n’est plus disponible pour une autre)

**Comment by fredZen** [comment]
@emsnytech Au fait, qu’est-ce qu’on appelle « l'ordre d dépôt des dossiers sur leur registre » ? 

Est-ce qu’on numérote les dossier par ordre de passage en construction ? en instruction ? autre ? Est-ce que les brouillons ont un numéro ?
