### ISSUE TITLE
ETQ Instructeur/Expert l'url n'est pas toujours la même pour accéder à un dossier

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#1294]
Cela oblige à penser à chaque fois qu'on affiche un lien dossier si l'utilisateur doit voir le dossier ETQ accompagnateur ou ETQ Expert. 
Si c'est fait sur une liste de dossier, risque de N+1.

Possibilités :
- on fusionne tout, les urls seront les mêmes, c'est les templates qui gèrent d'afficher tel ou tel contenu
- on redirige tout vers le controlleur d'accompagnateur, qui gère les cas ou le dossier est visible uniquement en expert
- ...

**Comment by gregoirenovel** [comment]
Apparitions : résultats de recherche, lien vers un autre dossier...
