### ISSUE TITLE
Clarifier la relation de dépendance entre Entreprise et Etablissement

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1312]
Pas ex dans TagsSubstitutionConcern, on accède à l’établissement via l’entreprise, alors qu’on demande lors de l’identification un SIRET, donc numéro d’établissement, et non pas un SIREN, numéro d’entreprise. On est donc sensé avoir à tous les cas un établissement, et éventuellement une entreprise liée. Donc on aurait plutôt du faire `dossier.etablissement` au lieu de `dossier.entreprise.etablissement`, et ensuite faire `etablissement.entreprise`, alors qu’on fait l’inverse ici

Lié à #1311

**Comment by fredZen** [comment]
En résumé, les `Entreprise`s et `Etablisssement`s ne semblent pas représenter des entités autonomes, mais simplement le résultat de l’appel à l’API d’entreprise lors de la création d’un dossier donné.

Dans la suite de ce commentaire, par « dossier », il faut comprendre « dossier pour une procédure demandant un SIRET » (par opposition aux dossiers pour une procédure portant sur une personne physique). Les dossiers portant sur une personne physique sont associés à 0 établissements et entreprises.

On aurait pu croire que chaque dossier est associé à 1 établissement, qui serait lui-même associé à 1 entreprise (ou éventuellement 0 pour les cas du type association). Réciproquement, une entreprise serait associée à N établissements, et chaque établissement associé à N dossiers.

Ce n’est pas du tout le cas.

Le code dit que les dossiers, établissements et entreprises entretiennent une relation 1-1 (voir notamment `DossierService#dossier_informations!` et `DossierController#siret_informations`).

On voit en #1311 que l’histoire racontée par les données est encore un peu plus complexe, sans doute entre autres à cause d’appels API en erreur ou de suppressions de dossiers incomplètes.

**Comment by tchak** [comment]
done
