### ISSUE TITLE
ETQ administrateur je veux pré-remplir un formulaire avec des données externes

### ISSUE THREAD

**Issue by guillett** [betagouv/demarches-simplifiees.fr#1317]
Lorsque l'instruction suit une étape de simulation, je voudrais éviter aux personnes qui répondent de ressaisir les informations déjà indiquées.

Par exemple : 
Une personne qui finit [une simulation sur mes-aides.gouv.fr](https://mes-aides.gouv.fr/foyer/resultat?situationId=5a4fa28cab31d64c4fe87905à) et qui souhaite commencer une démarche sur TPS pour une aide donnée pourrait être redirigé vers https://tps.apientreprise.fr/commencer/démarche-pour-aide avec [les informations saisies](https://mes-aides.gouv.fr/api/situations/5a4fa28cab31d64c4fe87905).

Techniquement, je vois par exemple un POST avec du `json` sur https://tps.apientreprise.fr/commencer/démarche-pour-aide.

WDYT ?

**Comment by LeSim** [comment]
Alors pourquoi pas dans l'absolue.

Maintenantm tu es le premier à exprimer ce type de besoin qui me semble assez éloigné des demandes de nos autres partenaires.

A moins d'un revirement important, je ne vois pas cette fonctionnalité implémentée à moyen terme malheureusement.

**Comment by guillett** [comment]
J'ai peut-être mal exprimé le besoin. Je serai ravi de discuter des prochaines fonctionnalités prévues. Vous acceptez les PRs ? 🙂

**Comment by LeSim** [comment]
Mais certainement ! Viens donc causer :)

**Comment by emsnytech** [comment]
Ce sujet va etre d'actualité quand nous allons commencer à travailler à l'API de données rentrantes. Mais il va falloir une approche générique, et que nous trouvions plusieurs cas d'usages
