### ISSUE TITLE
Expliciter qui sont ldes "Personnes invitées" dans l'onglet "Personnes impliquées"

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1319]
Je n'ai pas compris à quoi renvoie les personnes invitées...

![personnes invitees a consulter ce dossier](https://user-images.githubusercontent.com/35567048/35156951-c1fa4d50-fd32-11e7-901f-2f859d3b63a4.png)

**Comment by LeSim** [comment]
Il est possible pour un usager d'inviter une personne pour l'aider à compléter son dossier. Cette fonctionnalité est pour l'instant peu utilisé (mauvaise UX) et sera refondu lors de la nouvelle interface utilisateur.

**Comment by AnthonyBrunelli** [comment]
Ah! Fonctionnalité très intéressante et qui correspond à des besoins de mon côté; bon à savoir merci.

Effectivement, fonctionnalité à expliciter sur les interfaces des différents profils.

**Comment by kemenaran** [comment]
On a modifié la formulation côté Instructeur depuis un bon moment.
