### ISSUE TITLE
Structure du champ adresse

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1320]
J'ai vu que les données adresse étaient récupérables?
https://tps.gitbooks.io/tps-documentation/content/pourquoi-utiliser-tps.html
"récupération automatique d’informations sur les demandeurs via API Entreprise et France Connect et récupération d'informations géographiques via BAN et API Géo"

Comment cela fonctionne-t-il?

Est-il possible d'avoir un bloc adresse prêt et paramétré par défaut?

En effet, il y a une grosse problématique au niveau du bloc adresse, qui doit respecter des standards (NF Z10-011), avec des enjeux importants dans le cadre de fusion de communes. Pour info (extrait d'un CR):

•	L’essor des communes nouvelles est amené à s’amplifier, le Gouvernement ayant réaffirmé son soutien au regroupement de communes et confirmé l’incitation financière, en rehaussant même le seuil d’éligibilité (déplafonnement quasi-total).
•	La création de nouvelles communes par regroupement de plusieurs communes existantes provoque des problèmes d’adresse, notamment – mais pas uniquement – pour la distribution du courrier : en effet, les communes nouvellement créées peuvent avoir plusieurs rues ou places portant le même nom (par exemple si deux anciennes communes regroupées avaient chacune une « Rue de la République »). 
•	Face  à ce problème, la mesure de simplification annoncée à Alençon le 5 décembre 2016, consistant à ajouter, sur les formulaires Cerfa, une ligne pour inscrire le nom des communes déléguées entre le nom de la voie et le nom de la commune ne constitue pas une modification normative. En effet, la norme postale (NF Z10) contient déjà six lignes dont l’une (la cinquième) a pour fonction de recevoir les informations complémentaires (par exemple le lieu-dit) ; la  commune déléguée peut être indiquée dans ce champ.
•	L’Association des Maires de France demande donc que cet aspect soit pris en compte dans les formulaires Cerfa et dans les démarches en ligne de l’administration.

**Comment by emsnytech** [comment]
Je souhaite que nous examinions bien cette proposition, dont je ne partage la cible.
Les 7 lignes sont une contrainte incompréhensible des usagers, uniquement là pour satisfaire des back offices anciens. Ce n'est pour moi pas une priorité... La question est comment en récupérant ue adresse auto complété ( c'est quand même mieux que d'avoir à saisir 7 lignes !) les clients des données de TPS éclatent cela en 7 lignes. Certains l'ont déjà fait.

**Comment by AnthonyBrunelli** [comment]
@LeSim J'ai un point avec le spécialiste de la question cette semaine, je te confirme tout ça. A priori je dirais que c'est bon - et intéressant de savoir que la Ban te donne le nom de la commune déléguée entre parenthèses après le nom de rue.

Outre la restitution des données usagers grâce à France Connect, API etc., il faut penser au cas où il lui faut renseigner une adresse autre (ex. un agent RH qui renseigne l'adresse d'un nouvel arrivant), d'où ma question d'un 'bloc' adresse déjà préformaté dans les normes...

Je ne sais pas si je suis clair, mais on peut en reparler.

**Comment by LeSim** [comment]
ok, j'attends ton retour.

Pour le bloc, je suis d'accord, je propose :
- ligne 1 : civilite nom prénom (préremplie si nous avons les données d'identité)
- ligne 2 : numéro d'appart ...
- ligne 3 : numéro de batiment
- ligne 4 : champ actuel auto-complété qui nous fourniera par l'api, les lignes standards 4, 5 ,6

**Comment by AnthonyBrunelli** [comment]
@LeSim Nous avançons sur le sujet, je vous tiens au courant quand c'est stabilisé. Par ailleurs:

♦ Sais-tu si l'API entreprise restitue l'adresse postale ou l'adresse physique? Visible, c'est une nuance importante, les deux ne correspondant pas forcément (par exemple, une administration qui a en charge des contrôles sera plus intéressées par l'adresse physique que par l'adresse postale).
♦ Dans tous les cas, il faudrait prévoir la possibilité d'insérer des blocs 'vides' (ie. non renseignés par API/France connect), par exemple si un particulier doit indiquer l'adresse de sa résidence secondaire ou autre...
♦ L'usager aura-t-il la possibilité de modifier les données dans le cas où elles sont restituées?
♦ (optionnel et a priori non crucial) Quid d'une case à cocher pour recopier une adresse déjà saisie? (comme sur les sites de vente en ligne pour indiquer que l'adresse de facturation est la même que l'adresse de livraison, et éviter une double saisie).

**Comment by LeSim** [comment]
- on sort les données de `https://entreprise.api.gouv.fr/documentation#etablissements`. Il précise "Les informations d’adresse sont issues des adresses géographiques et normalisées. Nous ne prenons pas en compte l’adresse déclarée". Je n'en sais pas plus.
- ok pour ajouter un champ vide complémentaire
- oui, l'usager pourra les modifier
- c'est prévu :)

**Comment by CamilleGarrigue** [comment]
@X.O Ddt Indre
