### ISSUE TITLE
ETQ Usager, le lien vers la notice est incorrecte lorsque l'administration la spécifié avec une adresse relative

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1321]
J'ai vu qu'il y avait une aide accessible, mais qui n'est pas propre à une démarche.

Sur un essai sur une procédure existante, j'ai également vu qu'il y avait possibilité d'avoir un lien vers une aide propre à la procédure (même si le lien était ko pour la procédure en question):
![aide en ligne](https://user-images.githubusercontent.com/35567048/35158113-66c00606-fd36-11e7-8c1c-07708775b97c.png)

Où et comment se paramètre cette aide propre à la démarche?

**Comment by LeSim** [comment]
L'aide propre au procédure se configure lors de la création d'une procédure, dans la partie description, dans la partie lien notice.

Il y a néanmoins un bug : si l'adresse du lien n'est pas absolue (https://www.google.com), l'application renvoie un mauvais lien (https://tps-dev.apientreprise.fr/user/.../www.google.com)
