### ISSUE TITLE
ETQ Administrateur, je souhaite avoir des informations sur la démarche d'homologation CERFA

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1322]
Pour en discuter:

A priori, l'outil TPS concerne la même cible que les critères d'homologation Cerfa des démarches en ligne:
http://references.modernisation.gouv.fr/homologation-cerfa

Est-il possible d'inclure dans la livraison à une administration d'une démarche paramétrée dans TPS une communication sur les critères?

**Comment by LeSim** [comment]
@AnthonyBrunelli je te propose d'inclure dans l'espace réserver aux adminsitrateurs un encart contenant un lien vers le lien homologation-cerfa pour les inciter à faire la démarche.

Qu'en penses-tu ?

**Comment by AnthonyBrunelli** [comment]
@LeSim Ça me semble très bien. Y a-t-il besoin que je ponde 3 lignes de présentation/explication?

**Comment by LeSim** [comment]
oui, si tu peux nous la rajouter ici, comme ça on aura tout sous la main lors du dévelopement.
