### ISSUE TITLE
ETQ Usager, l'interface doit être accessible (RGAA)

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1324]
#649 

Un des critères Cerfa concerne le RGAA; où en est TPS sur ce point?

15	La démarche en ligne respecte les exigences du référentiel général d’accessibilité pour les administrations (RGAA). La déclaration de conformité au RGAA - ou la date de publication prévue - est accessible à partir du pied de page.

Pour information, je vous transmets ci-après l'information de notre expert accessibilité Antoine Cao a transmis à Philippe, et que Philippe nous a demandé de vous transmettre:

Le lien vers le plug-in Extension de navigateur permettant d'auditer des pages web en suivant le référentiel RGAA: https://github.com/DISIC/assistant-rgaa

Les extensions permettent de tester environ 35% des aspects RGAA si j'ai bien compris. Pour plus d'information: antoine.cao@modernisation.gouv.fr

**Comment by LeSim** [comment]
L'interface actuel ne respecte pas les contraintes RGAA.
La prochaine le fera.

**Comment by kemenaran** [comment]
On a une issue sur "Passer un test d'accessibilité", ça me semble plus spécifique.

J'ai déplacé l'issue générale vers https://demarches-simplifiees.featureupvote.com/suggestions/77377/usager-pouvoir-naviguer-dans-une-interface-accessible
