### ISSUE TITLE
ETQ Administrateur : je veux pouvoir configurer le pied de page de mes procédures

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1325]
Un des critères Cerfa concerne le pied de page:

18	Le pied de page doit faire figurer des liens vers les pages suivantes :
- Contact ;
- Plan du site ;
- Mentions légales ;
- Accessibilité ;
- Horaires et plans d'accès (si la page existe) ; 
- Démarches en ligne (si la page existe).

Ce point rejoint l'issue #648 sur la possibilité de paramétrer le pied de page. Avez-vous des informations à ce sujet?

**Comment by LeSim** [comment]
Nous allons ajouter ces données lors de la refonte de l'interface usager

**Comment by AnthonyBrunelli** [comment]
Il y a aussi "SGMAP" à remplacer (pas trop vite, la Dinsic risque de changer de nom si j'ai bien compris). Je sais que ça doit être pris en compte dans la nouvelle interface, mais pour mémoire...

**Comment by LeSim** [comment]
SGMAP remplacé avec https://github.com/betagouv/tps/pull/1299

**Comment by AnthonyBrunelli** [comment]
Auriez-vous des informations sur ce sujet? Merci!

**Comment by LeSim** [comment]
on est en train d'en parler maintenant 
https://github.com/betagouv/tps/pull/2099

**Comment by AnthonyBrunelli** [comment]
Cool! vu merci!
