### ISSUE TITLE
ETQ Usager, les pages que je consulte doivent avoir moins de 5 erreurs sur le validateur w3c

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1326]
Un des critères Cerfa concerne la détection des erreurs de code:

19	La page d'accueil comporte moins de 5 erreurs de code (https://validator.w3.org/).

Lorsque j'ai fait le test il y a un mois, 4 erreurs et 2 points d'attention ont été remontés... mais c'est du polonais pour moi. Je vous laisse faire le test de votre côté et estimer sa pertinence...

**Comment by kemenaran** [comment]
Je crois que Simon a fait une passe là dessus récemment, et qu'on est bon maintenant.
