### ISSUE TITLE
ETQ Utilisateur des API, je veux que la données exportées soit aux normes RGI (interop sémantique)

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1328]
Un des critères Cerfa concerne le RGI:

21	La démarche en ligne utilise des standards ouverts, interopérables, soutenus et matures. Elle applique le référentiel général d'interopérabilité (RGI).

J'ai bien lu que TPS était "intégré à l’écosystème numérique public : récupération automatique d’informations sur les demandeurs via API Entreprise et France Connect et récupération d'informations géographiques via BAN et API Géo"

https://tps.gitbooks.io/tps-documentation/content/pourquoi-utiliser-tps.html

Mais comme je ne maîtrise pas ces aspects, j'attire votre attention sur ce point.

**Comment by LeSim** [comment]
À la lecture du document http://references.modernisation.gouv.fr/sites/default/files/Referentiel_General_Interoperabilite_V2.pdf , il apparaît que nous sommes compatible avec le RGI sur les volets techniques et syntaxiques.

- interopérabilité technique : ok :  HTTPS / TPC / IP4|6
- interopérabilité syntaxique : ok : UTF8 / HTML / JSON /GEOJSON / PDF / CSV (à destination des gestionnaire)
- interopérabilité sémantique: vérification à effectuer

L'application, si l'interopérabilité sémantique est correcte, semble correspondre au profil P1 (P5 pour ce qui est de la donnée géographique) d'intéropérabilité

**Comment by AnthonyBrunelli** [comment]
@LeSim Ok vu merci. Je n'ai pas tout compris, mais je vais me pencher sur la question.

**Comment by kemenaran** [comment]
J'ai l'impression que ce n'est plus d'actualité.

Je ferme, à ré-ouvrir au besoin.
