### ISSUE TITLE
ETQ Usager, je veux que les formulaires soient interprétable par une lecteur d'écran (Accessibilité)

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1334]
Le titre de la page (titre de la procédure) n’est pas lu par le lecteur d’écran.

La partie à gauche est OK (« Ma procédure, Mes informations, Les informations de bases vous concernant »)

Les champs de saisie ne sont pas tous restitués par le lecteur d’écran (étiquette texte manquante ou incorrecte ?) - dans le test sur dev. "Procédure d'arrivée sur le site de Fontenoy-Ségur", c'est notamment le cas des champs en saisie libre.

Civilité (menu déroulant) : OK
Nom (saisie libre) : KO
Prénom (saisie libre) : KO
Date de naissance (champ date) : OK

**Comment by LeSim** [comment]
Pourrais-tu nous expliquer la technique utilisée pour tester notre interface avec un lecteur d'écran ?

**Comment by AnthonyBrunelli** [comment]
@LeSim 

Réponse rapide: NVDA (logiciel libre), voire Jaws.

Réponse longue: j'ai fait faire le test par Antoine Cao, notre expert accessibilité (l'issue est le copié-collé de son retour). Vous pouvez (assez?) facilement faire un test de votre côté avec NVDA. Pour information, comme ces problématiques sont d'après Antoine assez compliquées d'un point de vue développeur, il va mettre en place un réseau d'agents avec des handicaps; ces agents pourront procéder à des tests à la demande de développeurs pour une meilleure prise en compte de ces problématiques - si vous êtes intéressés: antoine.cao@modernisation.gouv.fr

**Comment by kemenaran** [comment]
On a corrigé pas mal de choses à dessus récemment. Je ferme, on pourra ré-ouvrir des issues plus spécifiques.
