### ISSUE TITLE
ETQ Usager, je veux que l'interface m'indique clairement le champ qui a le focus (Accessibilité)

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1335]
Le focus n’est pas suffisamment visible/mis en avant, particulièrement - mais pas uniquement - pour la case à cocher.

Cf. ci-dessous (le focus est sur le prénom):

![focus peu visible](https://user-images.githubusercontent.com/35567048/35161058-517606a2-fd3f-11e7-93d5-fde5c7236534.png)

**Comment by fredZen** [comment]
Voir aussi #1571

**Comment by kemenaran** [comment]
Depuis des changements relativement récents le focus est maintenant très clair.
