### ISSUE TITLE
ETQ Usager, les messages d'erreur doivent avoir un constraste suffisant

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1337]
Message d'erreur : contraste de couleur trop faible entre le texte et le fond (3,38 alors que le minimum est de 4,5)

![donnees effacees 1](https://user-images.githubusercontent.com/35567048/35161313-1be2ce5c-fd40-11e7-82aa-b4e3f9940c6a.png)

![ratio contraste](https://user-images.githubusercontent.com/35567048/35161296-0b7b0052-fd40-11e7-9552-8703af8dbe88.png)

**Comment by kemenaran** [comment]
On est maintenant bien meilleurs là dessus, avec le nouveau design. On peut fermer.
