### ISSUE TITLE
ETQ Instructeur, les champs oui/non remonte true/false dans la vue tableau d'une procedure

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1341]
Nouvelle interface accompagnateur.

1/ Mineur. Lorsque dans un tableau on paramètre la restitution d'un info en oui/non, c'est true/false qui apparaît.

2/ Par ailleurs, à quoi renvoient les champs Nom (FC) et Prénom (FC)? Que veut dire "FC"?

**Comment by emsnytech** [comment]
FC veut d'ire que l'information vient de FC ( quand l'usager s'est connecté avec FC)

**Comment by AnthonyBrunelli** [comment]
Ah, France Connect! Rien à voir avec le FC Metz donc... Merci.
Il faudrait l'indiquer quelque part (guide ou autre...).

**Comment by mmagn** [comment]
Normalement réglé par cette PR : https://github.com/betagouv/tps/pull/995

**Comment by maatinito** [comment]
Déjà réglé mais illustre peut-être d'autres problèmes: 
Avec une démarche contenant un engagement, une case à cocher, un champ oui/non:
![image](https://user-images.githubusercontent.com/15379878/49967206-3e7a9200-fec6-11e8-8e9d-c234cf895e54.png)

1. La valeur du champ  oui/non est écrite en minuscule. Je crois comprendre que les décorateurs ne sont plus utilisés mais eux décrivent Oui/Non en CamelCase. Doit-on faire qqc de cette incohérence dans le code ? Reste-t-on en minuscule ? 
1. Dans l'export, les cases à cocher et engagement sortent en anglais (on/off). Veut-on des valeurs écrites en Français ? (cochée, non cochée?)
1. Veut-on une valeur spécifique pour l'engagement ?
1. Les champs Etablissements sortent systématiquement même avec des démarches sans SIRET. Bug ?

**Comment by LeSim** [comment]
Salut @maatinito !
1)
- si des décorateurs en sont plus utilisés et que tu peux les shooter, ça serait top
- conservons les oui/non en minuscule pour éviter de casser des macros utilisateurs ...
2) case à cocher : utilisons oui/non pour être cohérent avec l'ui
3) engagement : soyons original avec ... oui/non (en vrai, un jour prochain on fusionnera tous ces champs)
4) Je me prononce pas ... 

Merci pour ton taff !
