### ISSUE TITLE
ETQ Usager, je ne veux pas que le button de validation de la page d'identité soit rouge

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1343]
(on est d'accord, c'est du mineur-mineur)

Est-il possible de choisir une autre couleur que le rouge pour le bouton de validation, le rouge évoquant plus une alerte?

**Comment by LeSim** [comment]
Résolu par la nouvelle ui : https://projects.invisionapp.com/share/YZCBK5PFG#/screens/240738632

**Comment by AnthonyBrunelli** [comment]
@LeSim Super!
Par contre, vous avez fait un test de contraste sur le bouton "Soumettre"? (mon collègue m'a transmis un document pour faire ce genre de test facilement avec Paint et un outil gratuit en ligne, si ça vous intéresse).

**Comment by LeSim** [comment]
non, nous n'avons pas encore réalisé le test de contraste et oui, nous voulons bien la référence de l'outil :)

**Comment by AnthonyBrunelli** [comment]
@LeSim Voilà, avec le document d'Antoine Cao sur le comment faire (je n'ai pas trouvé comment joindre un document dans Github)

https://sandbox.cryptpad.info/file/#/1/KoemHLildXFhF7OvPscFTaCqEwm6yWU2/56+tFgXlQS7L7pqKVXld+nELdzvT0xM2rdEonVbjojw=/

http://contrast-finder.tanaguru.com/
