### ISSUE TITLE
ETQ usager: je veux voir l'explication d'un champ sous son libélle

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1345]
Y a-t-il une raison pour laquelle le champ "description" (ie. précision associée à l'intitulé du champ) apparaît sous le champ à saisir plutôt que sous l'intitulé concerné?

(spontanément, ça me semble plus logique sous l'intitule plutôt que sous le champ à saisir).

**Comment by LeSim** [comment]
Ce pb sera résolu par la nouvelle interface

**Comment by kemenaran** [comment]
Résolu par la nouvelle interface.
