### ISSUE TITLE
ETQ Usager: je ne veux pas de titre de section en majuscules

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1346]
(je rapporte un retour utilisateur, perso suis pas choqué)

Les titres de section sont convertis automatiquement en majuscule: y a-t-il une raison particulière? Un lien avec l'accessibilité?

**Comment by LeSim** [comment]
Ce pb sera résolu par la nouvelle interface : https://projects.invisionapp.com/share/YZCBK5PFG#/screens/240738124

**Comment by kemenaran** [comment]
Résolu par la nouvelle interface.
