### ISSUE TITLE
ETQ Usager, je veux facilement lire les longs libellés de champ et explications

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#1350]
Question:

Le dossier, lorsqu'il n'est pas en saisie, a les intitulés 'compressés' dans une colonne à gauche sur la feuille de style. Potentiellement, ce point pose un pb de présentation si l'intitulé est un critère, car il s'agit d'un intitulé long : http://references.modernisation.gouv.fr/homologation-cerfa

Question (pas eu l'occasion de contrôler ce point): si j'utilise un champ "explication", est-ce que celui-ci s'affiche sur la largeur de la page?

**Comment by LeSim** [comment]
La maquette de la nouvelle UI résout ce pb : https://projects.invisionapp.com/share/YZCBK5PFG#/screens/240738124

**Comment by kemenaran** [comment]
On a maintenant implémenté la nouvelle maquette depuis un moment déjà. Le prblème ne se pose plus.
