### ISSUE TITLE
ETQ Instructeur, je souhaite mettre une PJ à disposition des Experts invités à rendre un avis sur le dossier 

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#1357]
Sachant que cette PJ doit être invisible de l'usager et que les annotations privées ne sont pas ouvertes aux experts invités. 
@P.Dubois (préf P-d-C)
@ M.Laure (Dinamic)

**Comment by Benjamin-Doberset** [comment]
# 6026 
Urgent, à prioriser. Possibilité de mettre une pièce jointe dans les deux sens (quand j'invite et quand je réponds)

**Comment by kemenaran** [comment]
J'imagine que pour l'instant la solution de contournement est d'envoyer la pièce-jointe sur un service externe (genre wetransfert), et de copier-coller le lien dans la messagerie pour l'expert.

On est d'accord que dans une option "Tout dans DS", c'est pas fou. Mais au moins ça permet aux accompagnateurs d'avancer en attendant.

**Comment by LeSim** [comment]
À communiquer pour sicoval `HS #6337`
engagement pour début novembre

**Comment by Benjamin-Doberset** [comment]
A communiquer pipe 5255

**Comment by benjaminhenkel** [comment]
HS 30036

**Comment by kemenaran** [comment]
- HS #17441
- Mie de @jscs.gouv.fr
- HS #15278
- Admin #4020
- HS #15256

**Comment by kemenaran** [comment]
C'est la feature la plus demandée sur Feature Upvote.

Contributions externes acceptées.
