### ISSUE TITLE
Titre et Bouton déconnecté mal positionné (Chrome 64 - Linux Ubuntu)

### ISSUE THREAD

**Issue by jdauphant** [betagouv/demarches-simplifiees.fr#1518]
Voici comment le titre et le bouton "se déconnecter" apparaisse sur mon ordi :
![image](https://user-images.githubusercontent.com/1238254/36844010-218a99d0-1d51-11e8-98b5-13ff1e955b59.png)

Chrome 64 - Linux Ubuntu

**Comment by mmagn** [comment]
Merci pour le retour !
Cela va être réglé par la nouvelle interface dans les prochains jours.
