### ISSUE TITLE
ETQ usager, je veux comprendre ce qu’il se passe quand une procédure sur laquelle j’ai un dossier en cours est supprimée

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#1523]
`#1462`

> J'ai supprimé la procédure après le test pour pouvoir la re-publier après certaines corrections. Aucun message n'est envoyé à l'usager pour l'informer de cette suppression, il constate juste, s'il se connecte, que les liens précédemment envoyés ne fonctionnent plus. Même si effectivement les procédures ne sont pas prévues pour être supprimées, il faudrait prévoir l'information des usagers ayant un dossier en cours en cas de suppression.

**Comment by gregoirenovel** [comment]
Ce cas de figure n'est pas sensé se produire
