### ISSUE TITLE
ETQ accompagnateur je trouve que la fonctionnalité d'envoi d'un dossier n'est pas claire. Je ne sais pas quelle action sera déclechée au moment de l'envoi. 

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#1529]

**Comment by mmagn** [comment]
@CamilleGarrigue 
C'est un retour utilisateur ?
De quel envoi parle t'on ?

**Comment by gregoirenovel** [comment]
C'est Camille qui m'a demandé ce que faisait ce bouton, elle ne savait pas ce que ça allait provoquer et supposait que ça allait attribuer le dossier à la personne sélectionnée.
