### ISSUE TITLE
Enlever les procédures dont contact@ est admin ou gestionnaire

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1531]
Cette adresse n'a pas à être admin ou gestionnaire de quoi que ce soit

**Comment by emsnytech** [comment]
ATTENTION, c'est mon id avec des démarches en production, notamment toutes les démarches qui permettent de suivre les demandes de création de comptes APIENTREPRISE !!!!!
Les transférer alors sur mon autre identifiant ph.vrignaud@me.com
