### ISSUE TITLE
[Accessibilité] page "Créer un compte" : nb de caractères min. du mot de passe --> pas dans le placeholder

### ISSUE THREAD

**Issue by dzc34** [betagouv/demarches-simplifiees.fr#1567]
Pour l'accessibilité du formulaire  "Connectez-vous", l'usage de l'attribut `placeholder`  pour le champ  mot de passe n'est peut-être pas correct.

ressources:
- https://www.opquast.com/20170131placeholder-attribut-maudit/
- https://blog.atalan.fr/placeholder-et-accessibilite/
- https://developer.paciellogroup.com/blog/2011/02/html5-accessibility-chops-the-placeholder-attribute/
- https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Placeholder_Research

![Copie d'écran du formulaire "Connectez-vous"](https://user-images.githubusercontent.com/6709977/37064026-c19822c8-219b-11e8-9f43-6660f011a12f.png)

**Comment by fredZen** [comment]
Hello, merci pour le retour.

Dans le cas de ce placeholder en particulier, j’ai l’impression que le champ reste utilisable même si le texte du placeholder est perdu. Je dis ça surtout parce qu’il s’agit d’un champ de saisie d’un mot de passe existant, l’information « 8 caractères minimum » est à mon avis dans ce cas-là du bonus, presque superflue.

Ok pour fermer cette issue, et garder à l’esprit la remarque sur l’accessibilité pour d’autres placeholders ?

**Comment by dzc34** [comment]
Hello,

oui effectivement, cette issue n'est pas pertinente pour ce formulaire : je me suis mélangé les pinceaux entre la création d'un compte et la connexion. En fait, ce placeholder pour un formulaire de connexion est un peu trompeur... au début, à cause de ce placeholder, j'ai cru que je pouvais créer un compte...

Dans le cas d'un formulaire de création de compte, par contre, ce type placeholder poserait problème.

**Comment by kemenaran** [comment]
C'est maintenant le cas sur le sign-up.
