### ISSUE TITLE
[Accessibilité] Indicateur de focus du clavier absent

### ISSUE THREAD

**Issue by nicolasbocquet** [betagouv/demarches-simplifiees.fr#1571]
# Résumé
Une indication visuelle doit être présente sur tous les éléments de navigation recevant le focus.

# Détail
Lors d'une navigation au moyen de la touche tabulation du clavier, le bouton "Connexion" sur https://www.demarches-simplifiees.fr/ devrait changer afin d'indiquer que celui-ci est activable, et que le curseur clavier s'y situe.
La page https://www.demarches-simplifiees.fr/users/sign_in, est elle aussi concernée.

La propriété CSS prévue à cet effet `outline` a visiblement été retirée au `:focus` de l'élément.

Deux solutions s'offrent à vous :
- Rétablir la propriété `outline` au  `:focus` de l'élément concerné.
- Modifier l'élément lorsque celui-ci est sélectionné au clavier (Toujours `:focus`). Attention à bien respecter les règles liées aux contrastes, entre autres.

# Quelques ressources :

http://www.outlinenone.com/
https://www.w3.org/TR/2008/REC-WCAG20-20081211/#navigation-mechanisms-focus-visible
http://contrast-finder.tanaguru.com/

**Comment by kemenaran** [comment]
Effectivement. C'est corrigé sur demarches-simplifiees.fr depuis quelques mois.
