### ISSUE TITLE
Réouverture suspecte d'un compte

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1586]
À propos du dossier de prod `40918` (suivi par l'accompagnateur C. P.).

L'usagère (à la DINSIC) m'indique l'enchaiement suivant :

- 8/3 @ 11h01 : message de passage en instruction (+ email qui va avec)
- 8/3 @ 17h05 : message d'acceptation (+ email qui va avec)
- 9/3 @ 10h00 : *possibilité d'éditer ce dossier* (cf. timestamps d'édition des champs)
- 9/3 @ 14h04 : message de passage en instruction (+ email qui va avec)
- 9/3 @ 14h09 : message d'acceptation (*mais pas d'email*)

À comprendre :

- pourquoi a-t-il été possible d'éditer ce dossier malgré le fait qu'il n'était pas re-passé en instruction ?
- pourquoi ce dossier est-il repassé en instruction ?
- pourquoi n'a-t-on pas envoyé de mail pour le second message d'acceptation ?

À communiquer : `#1177`

**Comment by gregoirenovel** [comment]
Hier C.P. instruit et accepte le dossier. Cet après-midi il s'est rendu compte que ce dossier était en instruction alors qu'il ne devait pas l'être (car annotation privée "numéro BIEP" était déjà renseigné (c'est lui qui l'a fait hier), ce qui ne concerne que les dossiers instruits). Il a donc repassé en instruction puis accepté ce dossier.

**Comment by mmagn** [comment]
Du coup c'est réglé ?

**Comment by gregoirenovel** [comment]
Non
