### ISSUE TITLE
Le champ date dans la partie "identité" est pas top

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1587]
- Le placeholder dit "format : AAAA-MM-JJ", pourquoi on demande ce format et pas JJ-MM-AAAA ?
- pourquoi ça marche si on rentre JJ/MM/AAAA ?

À communiquer : `#1177,  #835`

**Comment by gregoirenovel** [comment]
Il est également possible, sous IE, de renseigner un texte et de passer à l'etape suivante, sans erreur.

À communiquer : `#3090`

**Comment by LeSim** [comment]
comment c'est possible alors qu'on a le champs en type date dans la bdd ?
