### ISSUE TITLE
[Accessibilité] Liens avec target=_blank : ne pas utiliser ou avertir l'utilisateur

### ISSUE THREAD

**Issue by dzc34** [betagouv/demarches-simplifiees.fr#1590]
plusieurs écoles :

- ne pas utiliser target=_blank :
  -  "it’s bad for accessibility. Leave the decision of opening in a new window or tab to the user"
      https://twitter.com/vavroom/status/971803768789577731

- avertir l'utilisateur : 
   - RGAA "Test 13.2.1 : Dans chaque page web, pour chaque ouverture d'une nouvelle fenêtre effectuée via un lien (attribut target) ou une commande JavaScript, l'utilisateur est-il averti ?"
  https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#crit-13-2
  - "L’utilisateur ou l’utilisatrice doit être prévenu·e lorsqu’on lui force l’ouverture d’un lien dans une nouvelle fenêtre"
   https://www.lelutinduweb.fr/alternatives-textuelles-attribut-title/

**Comment by dzc34** [comment]
voir : https://github.com/betagouv/demarches-simplifiees.fr/pull/6054

**Comment by kemenaran** [comment]
L'utilisateur est maintenant averti par une icône à côté des liens qui ouvrent une nouvelle fenêtre (#6054).

![footer](https://user-images.githubusercontent.com/1111966/113700038-a0ceb080-96d6-11eb-9a7d-26df7d4075d9.png)
![footer_users](https://user-images.githubusercontent.com/1111966/113700040-a1674700-96d6-11eb-8a4d-89da2c9bd893.png)

Mais effectivement les lecteurs d'écran ne [donnent pas d'information](https://www.powermapper.com/tests/screen-readers/navigation/a-target-blank/) sur le lien (p-ê parce que ça ferait trop de bruit cognitif de dire après tout les liens "Nouvelle fenêtre").

J'ai tendance à penser que la solution utilisée par VoiceOver est la bonne : il ne prévient pas particulièrement l'usager, mais fait en sorte que le bouton "Retour" fonctionne normalement, même dans la nouvelle fenêtre.

En tout cas je suis plus pour laisser l'indication textuelle/vocale de si un lien est "blank" au lecteur d'écran, plutôt que de surcharger tous les liens nous même (ce qui peut être pénible dans le cas d'une longue liste).

**Comment by dzc34** [comment]
N'étant pas expert en accessibilité, je n'ai pas d'avis plus poussé sur ce point.
C'est un auditeur ou un expert qui pourra répondre sur ce point précisément.

nota: je vous laisse fermer ce ticket.

Ressource statistique complémentaire :
https://webaim.org/projects/screenreadersurvey8/#primary

ci-dessous, mon commentaire dans la PR #6054
> La solution d'ajout d'un icône via CSS n'est peut-être pas totalement accessible.
> Il manque une alternative à cet icône.
> 
> ```css
> a[target="_blank"]::after {
>   content: url(data:image/png;base64,iVBORw0KGgo...);
> ```
> 
> Solution possible : 
> https://www.accede-web.com/notices/html-et-css/recommandations-complementaires/signaler-louverture-des-nouvelles-fenetres/
> ```diff
>  <a class="footer-link"
>      target="_blank" 
>      rel="noopener noreferrer" 
> +    aria-label="Mentions légales (nouvelle fenêtre)"
>      href="https://doc.demarches-simplifiees.fr/mentions-legales">Mentions légales</a>
> ```

**Comment by kemenaran** [comment]
Merci pour l'archive du message !

Je ferme pour l'instant ; on pourra rouvrir si ça remonte dans un audit d'accessibilité.
