### ISSUE TITLE
ETQ Instructeur je veux effectuer des actions de masse sur les dossiers

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#1617]
Pour le traitement de forts volumes.

HS : 1882

**Comment by gregoirenovel** [comment]
HS : 2287

**Comment by gregoirenovel** [comment]
`hs #7032`

**Comment by gregoirenovel** [comment]
HS 7091

**Comment by kemenaran** [comment]
Cas d'usages évoqués aujourd'hui en équipe DS :

- Le matin, je suis 25 dossiers pour m'indiquer que ce sont ceux que je veux traiter aujourd'hui
- Demander un avis à la même personne pour ces dix dossiers (#2013)
- …

Pour l'instant ça n'a pas l'air encore assez cadré.

**Comment by r1-v3t0** [comment]
Je remonte cette demande mais ça concerne uniquement le passage de plusiers dossiers en "archivés". Dans notre flux, le passage en "archivé" a une signification et il est effectué par demandeur qui peut avoir fait plusieurs demandes. Filtrer sur le demandeur, tout sélectionner et archiver serait utile.
