### ISSUE TITLE
Problème d'affichage du menu de profil

### ISSUE THREAD

**Issue by taniki** [betagouv/demarches-simplifiees.fr#1618]
![screenshot-2018-3-14 demarches-simplifiees fr](https://user-images.githubusercontent.com/27315/37417080-af925cc8-27af-11e8-831f-a21a6f3630b1.png)

L'encart est un peu cassé et il y a un bouton qui semble être caché par la barre de défilement.

Firefox sur Ubuntu

**Comment by gregoirenovel** [comment]
Merci, ça sera reglé avec la nouvelle interface usager

**Comment by tchak** [comment]
n'est plus d'actualité
