### ISSUE TITLE
Pouvoir avoir plusieurs administrateurs sur une même démarche

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#1626]
Découpée en plusieurs parties :
- [x] #3510 
- [x] Mettre à jour l'aide et la doc

Demandé par :
Helpscout `# 1929`

**Comment by gregoirenovel** [comment]
Erwan L. (Univ Nantes)

**Comment by Benjamin-Doberset** [comment]
Marie Cooche (Metropole de Lille)

**Comment by kemenaran** [comment]
Ça a l'air d'une bonne idée – se serait-ce que dans les cas où un administrateur part en vacances, pour qu'il puisse laisser la main à quelqu'un d'autre.

J'imagine que ça pourrait se faire en :

**v0**

- Modification de la relation en hasMany
- Ajout d'un admin supplémentaire en console

**v1**

- Page pour qu'un administrateur puisse en inviter un autre
- Un admin peut révoquer un autre admin

**Comment by gregoirenovel** [comment]
Il faut réflechir pour voir si on met bien ça au niveau des admins ou au niveau du Service.

@kemenaran `Modification de la relation en hasMany` : j'ai justement rajouté cette relation (avant c'était du hasOne) dans le contexte de cette issue

**Comment by Benjamin-Doberset** [comment]
Prefecture de l'Allier (N Desternes)

**Comment by Benjamin-Doberset** [comment]
Ministère de l'enseignement supérieur et de la recherche (S Nissen)

**Comment by mmagn** [comment]
HS 8321

**Comment by kemenaran** [comment]
`HS #8520` (Collectivité Territoriale de Martinique)

**Comment by fredZen** [comment]
`HS 9253`

**Comment by gregoirenovel** [comment]
L'idée à terme (selon moi) c'est qu'un service a plusieurs démarches et admins. Donc pas besoin de repartager chaque nouvelle démarche avec les autres admins de ton "groupe".

Mais ça suppose de gros changements à la fois techniques et dans l'UI, le Service devenant notre god-object et non plus la Démarche.

Perso, j'aime bien *a priori* cette idée, j'imagine bien quand tu créées un compte admin
- soit que t'aies éte invité par un autre admin à rejoindre directement un service et t'as tout de suite accès à ce service et ses démarches
- soit que tu demandes un compte sans invitation et alors
  * tu demandes à rejoindre un service existant (trouvé via une liste / moteur de recherche) 
  * tu créées un nouveau service

**Comment by gregoirenovel** [comment]
Dit autrement : de manière pragrmatique, je suis d'accord on peut partir tout de suite sur du multi-admin (j'avais d'ailleurs commencé le boulot là-dessus, il me semble que j'ai créé la table de jointure qui va bien) ; et quand on a le temps on peut (si tout le monde est d'accord) changé la manière dont on traite la partie admin (= l'orienter autour du service), faire les changements nécessaires et migrer de l'ancien système de partage de démarches (has_many_through) au nouveau (via service).

**Comment by kemenaran** [comment]
À communiquer : `Clément C.` (betagouv)

**Comment by kemenaran** [comment]
Pour l'instant la solution préconisée pour administrer une démarche à plusieurs est de se partager le compte admin.

Mais avec le login-par-lien-sécurisé-pour-les-instructeurs, tous les Admins qui sont aussi Instructeurs ne peuvent plus se partager de compte facilement.

J'imagine qu'il faudrait faire remonter ça à la prochaine priorisation.

**Comment by n-b** [comment]
@benjaminhenkel ouh, c’est réglé depuis un moment ça. Le ticket parlait de mettre à jour la doc, je ne crois pas que ça a été fait mais si c’est pas prévu et que personne ne se plaint, c’est peut-être que la doc actuelle est suffisamment claire. On peut fermer?
