### ISSUE TITLE
Sortir la date de naissance de l'écran d'identité

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#1643]
Et inviter par un wording à créer un champ dans le formulaire à la place.

Reprendre les procédures + dossiers avec des authentifications personnes physiques, et migrer en champ Date de naissance dans le formulaire.

**Comment by kemenaran** [comment]
Quelle est la motivation derrière ce changement ?

**Comment by mmagn** [comment]
Il semble que la date de naissance avait été introduite (il y a bien loooongtemps) pour se protéger des homonymes. Il se trouve que sur certaines démarches, ça fait tiquer les usagers de donner leur date de naissance, donc on l'a rendu facultative. Mais on a pas vraiment besoin de cette info au niveau dossier, puisqu'on pourrait l'obtenir avec un champ classique.

**Comment by kemenaran** [comment]
C'est vrai que ça semble raisonnable de garder ça facultatif 👍 

Donc si je comprend bien : la passer en champ ça fait un special-case de moins ; mais la garder dans l'identité ça permettrait par exemple de la mettre dans l'attestation.

**Comment by gregoirenovel** [comment]
À moins qu'on permette de mettre n'importe quel champ dans l'attestation

**Comment by fredZen** [comment]
Je dirais même plus, on peut déjà mettre n'importe quel champ dans l'attestation

**Comment by kemenaran** [comment]
@fredZen ah oui ? On fait comment ?

Si c'est possible et qu'on se sent de le gérer sur le long-terme, je documente ça.

**Comment by fredZen** [comment]
Tu vas sur l’onglet attestation de ta procédure `https://www.demarches-simplifiees.fr/admin/procedures/12345/attestation_template/edit` et dans le titre ou le corps du document, tu utilises une balise `--le libellé de mon champ--`. Elles sont d’ailleurs listées (en rouge sur fond rose) sous le champ de saisie.

Seul « petit » problème : si plusieurs champs ont le même libellé.

**Comment by Keirua** [comment]
La PR correspondante:
https://github.com/betagouv/demarches-simplifiees.fr/pull/4244/files
