### ISSUE TITLE
Envoyer de la doc aux administrateurs nouvellement inscrits sans procédure

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#1645]
Automatiser l'accompagnement.
Pour tous les administrateurs qui n'ont pas créé de procédure au bout de X jours, envoyer un email qui contient des liens vers la video et vers la doc.

**Comment by LeSim** [comment]
Je propose qu'on l'envoie directement via le message d'activation de compte

**Comment by gregoirenovel** [comment]
@LeSim c'est déjà le cas et ça va toujours être le cas une fois les 2 messages (activation + bienvenue) unifiés.

Là c'est pour relancer les admins qui dorment
