### ISSUE TITLE
Résultats dupliqués dans la recherche par mot-clé

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1674]
> Lorsque je recherche un dossier par un mot clé, il me ramène plusieurs lignes pour le même dossier, à quoi cela est-il dû ?
(HS `#2028`)

À communiquer : HS `#2028`

**Comment by fredZen** [comment]
Ça sent le `LEFT JOIN`. Ça pourrait se résoudre avec un `SELECT DISTINCT` mais gaffe, ça va mettre de la charge sur la BDD.

**Comment by gregoirenovel** [comment]
On peut mettre un `.uniq` en fin d'appel aussi
