### ISSUE TITLE
Permettre de notifier par email plusieurs personnes

### ISSUE THREAD

**Issue by kemar** [betagouv/demarches-simplifiees.fr#1676]
Dans le cas de WorkInFrance, l'[article R5221-17](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006072050&idArticle=LEGIARTI000018495600&dateTexte=&categorieLien=cid) du code du travail nous oblige de notifier à la fois l'**employeur** et l'**étudiant étranger** en cas d'obtention d'une autorisation provisoire de travail.

Or aujourd'hui, les notifications par e-mail sont envoyées uniquement à la personne ayant créé le compte DS.

Nous souhaiterions pouvoir envoyer au moins la notification d'acceptation avec l'attestation à plusieurs e-mails.

**Comment by gregoirenovel** [comment]
Éventuellement le faire via la co-construction d'un dossier

**Comment by DanielBMY** [comment]
Notre pb selon les textes concerne plus la délivrance de l'autorisation finale... Pour l'instant on dit à l'un (employeur ou étudiant) de transmettre à l'autre dans la notification de délivrance de l'autorisation...
