### ISSUE TITLE
ETQ Usager, je veux changer mon mot de passe

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1708]
À communiquer : `HS #2106`

**Comment by Benjamin-Doberset** [comment]
+1 , # 5588

**Comment by kemenaran** [comment]
À noter qu'en workaround un Usager peut déjà demander une ré-initialisation de mot de passe. Il reçoit alors un lien par mail, qui lui permet de changer son mot de passe.
