### ISSUE TITLE
Gérer le cas de API Asso down

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1714]
Si, dans `rna_adapter.rb`, on remplace le contenu de `#data_source` par `throw RestClient::Exceptions::ReadTimeout` (équivalent de API Asso down), pour l'usager qui rentre un SIRET, il rentre son numéro, clique sur le bouton, ça mouline, puis le bouton se remet en "Valider" sur fond vert.

~~Faire en sorte qu'on affiche une erreur à l'usager~~ -> que ça ne soit pas bloquant et qu'on puisse soumettre son dossier

**Comment by tchak** [comment]
Le cas "l'usager qui rentre un SIRET, il rentre son numéro, clique sur le bouton, ça mouline, puis le bouton se remet en "Valider" sur fond vert" c'est le timeout du serveur/navigateur. Ou une 500 (ça n'arrive pas normalement). Dans ce cas on observe bien une erreur dans la console js, mais l'UI ne la reflète pas.

**Comment by tchak** [comment]
Oui. Avec ce que nous avons sur dev, échecs sur API Asso et Exercices ne sont pas bloquants.

J'ai une PR pour gérer les erreurs ajax.
