### ISSUE TITLE
Valider la formule de Luhn sur les SIRET

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1716]
Cf. https://fr.wikipedia.org/wiki/Syst%C3%A8me_d%27identification_du_r%C3%A9pertoire_des_%C3%A9tablissements#Calcul_et_validit%C3%A9_d'un_num%C3%A9ro_SIRET

Afficher une erreur précise en cas de non validation

**Comment by kemenaran** [comment]
@gregoirenovel C'est déjà le cas, non ?

**Comment by gregoirenovel** [comment]
Yes, mais pas sur le champ SIRET, juste sur l'identification entreprise. Et faudrait donc porter le validateur direct dans le modèle du type de champ je pense, ping @tchak (cf. `models/siret.rb` et `SiretFormatValidator`).

D'ailleurs je ferais 2 validateurs plus disctincts qu'actuellement :
- la longueur du numéro
- le lunh

**Comment by gregoirenovel** [comment]
(et l'issue portait surtout sur le fait qu'actuellement les messages d'erreur sont cryptique : "Erreur SIRET" dans tous les cas (problème d'API, de format, etc.), sans plus de distinction)
