### ISSUE TITLE
Se faire une page status

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1718]
Avec :
- Nos serveurs
- FC
- MailJet
- API Entreprise
- ...

**Comment by kemenaran** [comment]
J'ai l'impression que pour l'instant c'est une idée, mais qu'on ne va pas agir dessus. On ferme, pour garder le github actionnable ?

**Comment by kemenaran** [comment]
Pour l'instant, vu nos moyens, le mieux est sans doute un bandeau sur le site, ou une page de la doc. Je ferme.
