### ISSUE TITLE
Enlever la possibilité de mettre en forme les templates de mail

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1765]

**Comment by kemenaran** [comment]
J'ai l'impression que la mise en forme simple (gras, etc) est plutôt utile pour hiérarchiser l'information.

Parfois, si on veut vraiment que l'usager voit une info, ça se tient de la mettre en rouge et en gras. C'est moche, mais ça fonctionne.
