### ISSUE TITLE
Champs répétables

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1769]
À communiquer : `#2194, #2254`

**État :**

- [x] Nouvel éditeur de champ
- [x] Rendre les champs répétables disponibles en test
- [ ] Exporter les données des champs répétables sur l'API (#3670)
- [ ] Exporter les données des champs répétables dans les exports tableur (#3919)

**Comment by red1bush** [comment]
à contacter dès résolution: 
claudine.burtin@bas-rhin.gouv.fr

**Comment by LeSim** [comment]
IRA de metz `hs #2442`

**Comment by emsnytech** [comment]
La demande est partagée par ministère des affaires sociales (agrément) , MTES (navire), Intérieur .
Prioritaire ....

**Comment by emsnytech** [comment]
Prioritaire pour ministères des finances (point essentiel pour la généralisation à partir d’avril.

**Comment by CamilleGarrigue** [comment]
Prioritaire pour la VAE @E.Tanguy (ministère du travail et de l'enseignement supérieur)

**Comment by Benjamin-Doberset** [comment]
HS # 5414

**Comment by kemenaran** [comment]
C'est utilisable en test.

Pour l'ouverture à tout le monde, c'est en attente de l'export dans l'API (#3670).

**Comment by tchak** [comment]
done
