### ISSUE TITLE
ETQ Admin, je veux modifier le libellé et la description dans les champs des procédures publiées

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#181]
C'est une demande récurrente de nombreux utilisateurs, notamment au MEDE, de pouvoir modifier le plus d'éléments possible dans une procédure. On s'était dit qu'on pouvait peut-être rendre les libellés et les descriptions modifiables mais je me demande si ça ne risque pas de poser des problèmes de compréhension / légalité : ex. j'ai remplis un formulaire, les libellés changent et ça changent automatiquement les questions dans mon dossier ??? Trop bizarre.

**Comment by gregoirenovel** [comment]
À communiquer : 169

**Comment by kemenaran** [comment]
J'ai l'impression que le besoin est toujours d'actualité. On a encore eu hier un admin qui voulait changer les libellés de sa démarche, et ça nous prend du temps.

Par ailleurs le besoin est vraiment légitime. Si on veut que les admins améliorent leurs démarches quand les usagers ont des problèmes, et nous génèrent moins de support, un premier pas est vraiment qu'iels puissent modifier les libellés, et rajouter des explications plus claires aux démarches.
