### ISSUE TITLE
Ajouter une étape de vérification manuelle pour passer une procédure de l'état test à l'état "publiée"

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1814]
- Ça rajoute un état "en vérification" ?
- Faire une page du Manager dédiée à ça
- Faire un role tournant pour ces vérifications
- Dans notre manager, afficher les champs sensibles pour la procédure dans la page de review
- Et dans la foulée supprimer le job de notification des champs sensibles
- Afficher au reviewer les règles de bonne rédaction d'une procédure (pas de libellés en capitales, pas de fautes d'orthographe, etc.)
- Intégrer avec Pipedrive pour passer automatiquement le deal dans une colonne "en production" ?

**Comment by LeSim** [comment]
pas de consensus. On en reparle ensemble ?
