### ISSUE TITLE
Rendre paramétrable l'heure d'archivage automatique des procédures

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#182]
2 raisons :
- Le changement d'heure pour l'archivage vise à ce que l'équipe TPS puisse corriger d'éventuels bugs juste avant l'heure limite dans la journée plutôt qu'au milieu de la nuit.
- Eviter les problèmes de compréhension par les administrateurs de 00h00 (est-ce minuit du jour précédent ou 00h00 du jour en cours) - les heures limites légales sont en général exprimées à minuiit

**Comment by gregoirenovel** [comment]
A étudier pour un prochain sprint

**Comment by Benjamin-Doberset** [comment]
L'issue devient urgente car elle est rencontrée par de nombreux utilisateurs. Serait-il possible de rendre l'horaire personnalisable plutôt qu'imposer 12h00 (et surtout ne mettre 11h59 et non 12h00 tqui est trop ambigu).

**Comment by Benjamin-Doberset** [comment]
+ 1, HS # 5588 (au moins 23H59)
