### ISSUE TITLE
Étoffer les possibilités de l'état « test » des procédures

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#1837]
Permettre aux administrateurs, pour les procédures en test, de
- modifier les labels
- éventuellement modifier le type des champs et leur ordre (avec suppression des dossiers pour faire ça proprement)

**Comment by gregoirenovel** [comment]
Pour clarifier : je pense donc qu'il ne faille plus d'état `test`, mais qu'on modifie l'état `brouillon` :
- on doit désormais définir une URL pour le brouillon
- à la publication, ça efface tous les dossiers
- à la modification de la démarche, ça efface tous les dossiers

**Comment by kemenaran** [comment]
C'est fait.
