### ISSUE TITLE
Ne plus envoyer de mail automatique dès que l'usager initie un dossier mais plutôt dans le cas où il clique sur enregistrer un brouillon

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#1866]
Confusion pour ceux qui ont soumis leur dossier. Ils retrouvent deux emails : un pour leur dire qu'ils ont un brouillon puis un d'accusé de réception. 
@ A.R (Rhône funéraire)
@ DITP

**Comment by gregoirenovel** [comment]
`#2957`

**Comment by CamilleGarrigue** [comment]
@A.Ortega
