### ISSUE TITLE
Le logo ajouté sur l'attestation apparait hachuré

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#1893]
https://secure.helpscout.net/file/53d8d0af004dda87/234964/1554093519/125307348/document/ 
https://www.demarches-simplifiees.fr/admin/procedures/4193/attestation_template/preview

**Comment by LeSim** [comment]
On a un problème sur certains types d'image dans l'attestation (png en particulier). Cela peut également provoquer des erreurs serveur.

`HS #2565`

**Comment by CamilleGarrigue** [comment]
Le problème persiste pour l'université de Nantes. Le logo de l'attestation apparait bien net sur la prévisualisation mais lorsque qu'il est sur le pdf (en pj de l'email d'acceptation) alors il apparait tout hachuré.
