### ISSUE TITLE
ETQ usager, je souhaite pouvoir déposer un dossier en reprenant des informations déjà saisies dans un dossier précédent. 

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#1906]
Par exemple : pour la procédure des médailles les entreprises doivent parfois saisir 100 dossiers pour inscrire leurs employés. Les entreprises souhaiteraient ne pas avoir à renseigner à chaque fois les champs concernants l'entreprise. 
@J.G (Rhône) 
@B.R (Rhône)

**Comment by emsnytech** [comment]
Je suis totalement favorable avec cette issue, qui est une des toutes première énoncé par les usager, surtout quand on traite de dossiers à répartition de même nature.

**Comment by Benjamin-Doberset** [comment]
Demande de Benoit Deschamps de l'ANFR, helpscout : 2885

**Comment by LeSim** [comment]
dup de #1353 ?

**Comment by gregoirenovel** [comment]
Mots clés pour la recherche : cloner / dupliquer

**Comment by gregoirenovel** [comment]
`HS #8338`

**Comment by kemenaran** [comment]
Discuté avec @CamilleGarrigue il y a quelques jours.

On a plusieurs possibilités :

0. Proposition 0 : apprendre aux gens à simplifier leurs démarches (par exemple utiliser le n° de SIRET plutôt que de demander 1000 infos), et à utiliser l'auto-complétion de leur navigateur.
1. ETQ Usager, un bouton "Créer un dossier avec les mêmes infos", qui duplique toutes les infos remplies dans le dossier précédent. _Pour moi gros risque d'oublier de modifier certaines infos, et donc d'envoyer un dossier boiteux._
2. ETQ Admin, pouvoir marquer certains champs comme "à dupliquer". Quand un nouveau dossier est ouvert à partir d'un précédent, seuls ces champs sont dupliqués.
3. ETQ Usager, créer un bookmarklet qui préremplit certaines infos spécifiques à la démarche.

Pour l'instant, vu le peu de bande passante de développement, je suggèrerais bien le bookmarklet.

**Comment by gregoirenovel** [comment]
Le bookmarklet ça veut dire "l'usager doit l'installer dans son navigateur" ? Je pense que ça sera difficile à utiliser comme.

Je vote 1., c'est pas si compliqué et tant pis pour ceux qui se plantent.

**Comment by kemenaran** [comment]
Mmm, faire une fonctionnalité avec des risques d'erreur, ça veut dire un mauvais produit (et du support derrière qu'on se ramasse). Dans le cas présent, je préfère largement rien plutôt que mauvais.

**Comment by gregoirenovel** [comment]
Sinon on test and learn ? (quand on a le temps pour ça)

**Comment by gregoirenovel** [comment]
HS 8338

**Comment by kemenaran** [comment]
Pour faciliter le remplissage d'un nouveau dont les champs sont sensiblement les mêmes.

`HS 11424`

**Comment by fredZen** [comment]
utile notamment pour les démarches où seul un champ varie d'une fois à l'autre (comme la date, ou le lieu).
Eventuellement faire cocher cette feature à l'admin, car cela peut être très adapté pour des démarches (exemple: vol de drone) et beaucoup moins pour d'autres.

à communiquer: HS #12822

**Comment by CamilleGarrigue** [comment]
Le sujet ressort de nouveau via les appels à projets des direccte : les appels à projets fonctionnent,,e,t parfois par vagues et du coup une personne recalée à la vague 1 peut (et est parfois encouragé à le faire) déposer le même dossier à la phase 2 puis 3. Du coup aujourd'hui il doit remplir le même dossier au moins deux fois...
