### ISSUE TITLE
ETQ qu'invité à donné un avis, je souhaite que mon interface soit la même qu'en tant qu'accompagnateur

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#1910]
L'interface pour donner des avis doit pouvoir proposer les mêmes fonctionnalités quand on arrive sur une liste de dossiers:
- triés par procédures.
- Choisir ses colonnes
- Rechercher dans la liste des dossiers avec avis
Etc.

**Comment by gregoirenovel** [comment]
@emsnytech C'est à communiquer à qui
