### ISSUE TITLE
ETQ Instructeur je veux changer mon mot de passe

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#192]
Pour pur accompagnateur : page spéciale cachée https://tps.apientreprise.fr/gestionnaires/password/new

**Comment by benjaminhenkel** [comment]
A FranceAgrimer

**Comment by Flightan** [comment]
+1

**Comment by gregoirenovel** [comment]
Deux sujets :
- changement de mdp
- mdp oublié

**Comment by fredZen** [comment]
Mdp oublié fonctionne maintenant pour tous les comptes (admin, instructeur et usager).

Je laisse ouvert car il n’y a pas encore de moyen ergo de changer de mdg (on détourne justement la fonction mdp oublié)

**Comment by kemenaran** [comment]
Issues "Je veux changer mon mot de passe" associées :

- Pour les Usagers : #1708 
- Pour les Admins : #471
