### ISSUE TITLE
ETQ Administrateur je veux pouvoir typer les champs sensibles d'une procédure

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#1932]
De façon à les détruire automatiquement à la fin du traitement.
Quid des attestation générées qui peuvent contenir ces données ?

**Comment by emsnytech** [comment]
Les attestation devront etre détruite aussi. Ce qui veut dire que la question d’un dispositif permettant de garder le document et concerner son H dans le reste du dossier en ligne... a creuser ( piste aussi du RSSI)
