### ISSUE TITLE
ETQ Usager je veux pouvoir exporter mon dossier

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#1933]
Créer une archive avec le dossier en pdf + les pièces jointes ?

**Comment by emsnytech** [comment]
Oui, c’est la bonne approche, plus un mail informant que le dossier lui est accessible dans son interface pendant un mois.

**Comment by gregoirenovel** [comment]
Meme chose souhaitée coté instructeur, avec messagerie (HS 6776)

**Comment by Benjamin-Doberset** [comment]
Demande aussi de l'académie de grenoble (Bruno sur le pipedrive)

**Comment by philemon95** [comment]
à communiquer 15667
