### ISSUE TITLE
Faire apparaitre dans une partie compte usager une liste des PJ uploader dans tous les dossiers qu'il a déposé puis lui proposer en accès quand il doit uploader une PJ

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#195]
Cette fonctionnalité rejoint une approche qui consiste à proposer une vue compte usager, qui lui permettrait d'accéder aux PJ commune ( sorte de coffre fort), qui évitera de stoker des PJ redondantes.

**Comment by kemenaran** [comment]
Je comprend l'intérêt – mais j'ai l'impression que ce n'est vraiment pas d'actualité.

On ferme ?

**Comment by gregoirenovel** [comment]
Pareil, je comprends pas le rationale de la fermeture à moins de fermer 75 % des issues

**Comment by maatinito** [comment]
Si je comprends que ca n'est peut etre pas d'actualité, c'est la deuxième question qu'on m'a posé lors de la démo au ministre: 'est-ce que ça veut dire que je n'ai plus besoin de transférer deux fois un document car il est dans le système ?' 
==> 'hum pas _encore_ madame la ministre ;-)'

**Comment by kemenaran** [comment]
Bon, effectivement mon opinion là dessus est que service-public.fr fait déjà portfolio de documents, et que c'est effectivement très chouette – mais qu'on est loin de pouvoir faire la même chose sur demarches-simplifiees.fr l'instant.

Je me dis que c'est peut-être un objectif pour mi-2019, ou plus probablement 2020 – mais que c'est vraiment pas pour tout de suite. Ok pour garder ouvert, en tout cas.

_(Parallèlement j'ai du mal avec laisser des issues ouvertes trop vagues : j'ai l'impression que ça fait juste du bruit, que la liste de 700 issues n'aide à rien, sauf à ceux qui l'ont déjà en tête. Mais ça veut sans doute juste dire qu'il faut que j'ouvre un UserVoice, et on en parle plus :) )_
