### ISSUE TITLE
ETQ usager je peux annuler ma procédure lorsque mon dossier est en construction

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#1970]
Objectif : être sûr que l'usager sait que la suppression de son dossier va entrainer l'arrêt de la procédure.  
Modalité : Remplacer le titre du bouton "supprimer mon dossier" par "annuler la procédure" et envoyer une notification contenant le message suivant.
Contenu du message :
 "Bonjour,

Vous vous apprêtez à supprimer votre dossier ainsi que les informations qu’il contient. Nous vous rappelons que toute suppression entraine l’annulation de la procédure en cours.

Veuillez confirmer votre intention de supprimer votre dossier.

Bien cordialement,

L’équipe de demarches-simplifiees.fr."

**Comment by fredZen** [comment]
J’ai changé le titre car nous ne permettons plus la suppression d’un dossier dont l’instruction a commencé.
