### ISSUE TITLE
ETQ admin je veux paramétrer la fréquence d'envoi des notifications aux accompagnateurs.

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#1977]
S.Chermat Direccte Auvergne

**Comment by gregoirenovel** [comment]
On peut avoir plus de détails ? Ils aimeraient mettre quoi comme fréquence ? Est-ce que c'est le cas "envoyer un email que lorsqu'il y a de nouveaux dossiers" ?

**Comment by CamilleGarrigue** [comment]
En l'occurence elle souhaiterait une notification par dossier déposer et par modification sur un dossier car elle attend peu de volumes. Mais certains souhaiteraient pouvoir régler la fréquence en nombre de jours.

**Comment by Benjamin-Doberset** [comment]
Louis F. Station F

**Comment by Benjamin-Doberset** [comment]
Claire W. Préfecture des Vosges. Procédure de transport des corps à l'étranger

**Comment by fredZen** [comment]
Ce qui m’inquiète avec cette version, c’est qu’on va _a priori_ pouvoir avoir des rythmes de notification différents selon les procédures, et donc qu’on ne va plus aussi facilement pouvoir synthétiser toutes les procédures d’un accompagnateur en un seul mail périodique.

Il va falloir être malin pour éviter de submerger les accompagnateurs sous les mails.

**Comment by clemenceleurent** [comment]
Demande faite également par la ville de Boe : "Est-il possible de programmer l'envoi du mail qui récapitule l'ensemble de l'activité sur la plateforme tous les jours et non une fois par semaine.
Ce mail permettrait d'informer les utilisateurs d'un dépôt d'un dossier." 
# 5449

**Comment by LeSim** [comment]
`HS #10892`
