### ISSUE TITLE
ETQ Gestionnaire, je veux que les champs de type nombre soit uniquement des nombres

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#1990]
Lille Métropole

plusieurs façon de le faire (plusieurs pr)

- mettre une validation dans Champs::NumberChamp
- nettoyer la base puis rajouter une colonne de type de number pour stocker la valeur
- changer les exports excels pour caster la case en nombre

**Comment by fredZen** [comment]
Voir aussi #930
