### ISSUE TITLE
UI : les textarea ne sont pas extensibles et n'affichent pas assez de ligne sur IE (?)

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#1991]
pour Lille Métropole

![image](https://user-images.githubusercontent.com/907405/40714727-bc6ff8b6-6403-11e8-85eb-3f93ce9e7102.png)

Solution possible : mettre un plus grand nombre de ligne par défault (5/10 ?)

**Comment by tchak** [comment]
IE is dead
