### ISSUE TITLE
ETQ accompagnateur je veux demander des avis par batch de dossiers

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#2013]
S.Hugot dép PdC

**Comment by LeSim** [comment]
Discuté avec @CamilleGarrigue , c'est pour éviter que des mm experts reçoivent tous les jours des mails de demandes.

**Comment by Benjamin-Doberset** [comment]
PA Billardon demande si on peut faire une demande d'avis externe pour l'ensemble de la procédure et non pour chaque dossier

**Comment by kemenaran** [comment]
Discuté avec @CamilleGarrigue aujourd'hui : toujours d'actualité.
