### ISSUE TITLE
Changer la logique commentaire / email pour les emails de notification de changement de statut

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#2050]
Aujourd'hui, on envoie un email et ensuite on créé un commentaire. Faire l'inverse : créer le commentaire et envoyer l'email de notif dans un `after_create`. C'est plus logique, et ça permettra par exemple de plus facilement renvoyer des emails non partis

**Comment by gregoirenovel** [comment]
Cf. NotificationMailer

**Comment by kemenaran** [comment]
Dans l'état actuel du code on crée le commentaire, puis on envoie l'email. On ferme ?

**Comment by gregoirenovel** [comment]
Non, c'est pas ce que veut dire le body de cette issue. Là dans le controleur, on appelle une méthode du mailer, qui commence par créer le commentaire puis envoie un email. Ce qu'on veut c'est appeler Commentaire.create directement dans le controleur, et que dans un `after_create` de commentaire, on appelle le mailer.

**Comment by kemenaran** [comment]
Ok. Dans ce cas je pense qu'on pourrait déporter la logique de notification (commentaire + email) dans un Service (appelé par le Contrôleur) – mais l'idée reste la même, effectivement.
