### ISSUE TITLE
ETQ Expert, j’aimerais trouver facilement l’endroit où rendre un avis

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#2078]
Quand l’expert se connecte en suivant le lien _Connectez-vous pour donner votre avis_ dans son email d’invitation, il arrive (en tout cas parfois) sur la page usager, et il est perdu (il faut qu’il passe en vue accompagnateur et aille chercher l’onglet avis)

HelpScout `# 3615`

**Comment by emsnytech** [comment]
Oui, il faut revoir l’interface des personnes saisies pour avis, en la calant sur celle d'accompagnateur par exemple.
