### ISSUE TITLE
Restitution de "Conservation des données" sur la page "Information"

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#2106]
Petit bug de restitution?

![image](https://user-images.githubusercontent.com/35567048/41420155-2656fb20-6ff4-11e8-956a-2114cafd113c.png)

**Comment by fredZen** [comment]
Merci @AnthonyBrunelli . Ce sera corrigé par la mise en prod de #2095.

**Comment by kemenaran** [comment]
On a corrigé par la nouvelle interface.
