### ISSUE TITLE
Message après envoi du dossier à corriger?

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#2107]
De mémoire, un dossier en instruction n'est plus modifiable par l'envoyeur; ce n'est pas ce que semble dire ce message:

![image](https://user-images.githubusercontent.com/35567048/41420234-4c7ef334-6ff4-11e8-8639-4c298b89c841.png)

**Comment by mmagn** [comment]
A ce moment là le dossier n'est pas encore passé en instruction, il est en construction donc modifiable par l'usager.

**Comment by AnthonyBrunelli** [comment]
(et on avait pas dit que le vocabulaire allait évoluer, pour gagner en clarté? En construction devait devenir un truc du style "transmis mais modifiable" non?)

**Comment by kemenaran** [comment]
Maintenant on met juste "Vous pouvez le modifier et échanger avec un instructeur."
