### ISSUE TITLE
ETQ Admin, je veux pouvoir rajouter un champ commune, soit par le Code postal ou le nom commune

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#2129]
Cette nouvelle liste déroulante sera attaché à la Ban, potentiellement conditionné par le chamois département.
Par ailleurs, dans l’export par API, ce champs devrait appeller automatiquement le Num INSEE de la commune, le nom, la géo localisation et le code postal

**Comment by Keirua** [comment]
Hello @emsnytech , pour info c'est en prod

**Comment by tchak** [comment]
done
