### ISSUE TITLE
ETQ usager je veux pouvoir voir la liste de toutes les procédures

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#2153]
Quand je clique sur "Commencer une nouvelle démarche", je suis redirigé vers une page où est affiché :

1. si j'ai déjà répondu à des démarches, la listes de ces démarches (si elles sont encore "ouvertes")
2. Un texte "si vous ne trouvez pas votre démarche, contactez nous à contact@..."
3. la liste de toutes les démarches avec plus de 40 dossiers, groupées par "Service" / organisation (si pas de service)

Bonus : un champ de recherche tout bête

**Comment by kemenaran** [comment]
NB : La page en question est la liste des dossiers.

<img width="1065" alt="empty" src="https://user-images.githubusercontent.com/179923/41925551-31c4813a-796d-11e8-935d-40565275bb07.png">

<hr>

<img width="1057" alt="dossiers" src="https://user-images.githubusercontent.com/179923/41925559-36add11a-796d-11e8-9b8d-110632ac31cb.png">

**Comment by gregoirenovel** [comment]
Réflexion avec Clémence, montrer les dossiers dans cet ordre là :
1. si appliquable, procédures ouvertes sur lesquelles j'ai déjà déposé un dossier
2. procédures ouvertes les plus populaires sur les 15 derniers jours
3. toutes les procédures

**Comment by gregoirenovel** [comment]
Commencé avec #2576
