### ISSUE TITLE
Champ « Point géographique » sur la carte

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#2170]
L’idée est de faire un champ ne permettant de saisir qu’un point sur une carte plutôt qu’une zone.

Actuellement, seule une zone est possible (cadastrale, politique de la ville etc...)
Ici, l'idée serait de rajouter pour l'administrateur l'option "point unique" pour connaître la localisation d'équipements (défibrillateurs, bornes incendies ou que sais-je)

Voir aussi #250

**Comment by gregoirenovel** [comment]
C'est demandé par quelqu'un ?

**Comment by fredZen** [comment]
à communiquer Sicoval

**Comment by LeSim** [comment]
A communiquer Sous préfecture d'étampes

**Comment by fredZen** [comment]
`HS #9998`

**Comment by kemenaran** [comment]
`HS #12007`
