### ISSUE TITLE
ETQ admin, je souhaite pouvoir préciser une longueur maximale pour un champ texte

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#2171]
à communiquer Sicoval

**Comment by kemenaran** [comment]
Quel est le cas d'usage ?

**Comment by fredZen** [comment]
Admin qui n’a pas envie de recevoir un roman

**Comment by gregoirenovel** [comment]
Est-ce qu'on ne veut pas plutôt mettre une longueur pour tout le monde ? (plutôt que de rajouter une option)

**Comment by fredZen** [comment]
@gregoirenovel c’est vrai que la multiplication des options ne va pas rendre notre soft plus simple à utiliser !
