### ISSUE TITLE
ETQ Instructeur, je veux que les pièces jointes lourdes conservent leur nom + extension lors du téléchargement

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#2180]
`hs #9253`

# description du problème
## Étapes pour reproduire
- etq usager, uploader un fichier avec le nom `tableau.csv` sur un champ pièce justificative (lourde).
- etq accompagnateur, télécharger ce fichier

## résultat attendu :
téléchargement d'un fichier nommé `tableau.csv`

## résultat constaté :
téléchargement du même fichier mais avec un nom aléatoire (sdfhsdj23424).

# solution

Passer les champs pièces jointes sous OVH

Tâches

- [x] Supprimer l’override de PieceJustificativeUploader#origianl_filename pour pouvoir mettre à jour Carrierwave
- [x] Mettre à jour Carrierwave afin de pouvoir se passer de la gemme chapeau fog
- [x] Ajouter dans ansible les données de configuration compatibles keystone v3 (2 nouvelles clefs : url version-agnostique et version d’api d’authent à utiliser)
- [x] Déployer la configuration ansible avec les nouvelles données de configuration
- [x] Enlever fog pour pouvoir mettre à jour fog-openstack vers la dernière version
- [x] Mettre à jour fog-openstack. Mettre à jour les fichiers de configuration pour utiliser les données d’authentification compatibles keystone v3
- [x] Faire la non-régression de Carrierwave
- [x] Mettre en production DS avec la nouvelle version de fog-openstack
- [x] Supprimer dans la configuration ansible l’ancienne URL d’authentification qui incluait le numéro de version
- [x] Déployer la configuration ansible sans les anciennes données de configuration
- [x] Ajouter activestorage-openstack (version patchée pour corriger la dépendance sur une mauvaise version de fog-openstack)
- [x] Choisir ou créer un conteneur sur openstack pour les pj : `ds_activestorage`
- [x] Cofigurer la temp url key sur le conteneur
- [x] Configurer CORS sur le conteneur `swift post -m "Access-Control-Allow-Origin: https://www.demarches-simplifiees.fr" ds_activestorage`
- [x] Configurer la temp URL key sur ansible de prod
- [x] Déployer la config ansible de prod avec la temp url key
- [x] Avertir les administrateurs de l’incohérence temporaire sur les pièces joints
- [x] Configurer activestorage de prod pour utiliser OVH
- [x] Purger les données de test du conteneur sur OVH, recopier les pièces jointes de CleverCloud vers OVH
- [x] [Rectifier les types MIME](https://github.com/chaadow/activestorage-openstack/blob/master/lib/active_storage/openstack/railtie.rb) sur OVH
- [x] Mettre en prod DS avec OVH comme fournisseur activestorage
- [x] Refaire la copie CleverCloud -> OVH pour les pièces jointes qui ont été rajoutées entre temps
- [x] Refaire la rectification des types MIME
- [x] Vérifier s’il reste d’autres fichiers hébergés sur CleverCloud (feuille de style helpscout etc), les déplacer vers OVH
- [x] Décomissionner CleverCloud
- [x] Passer les champs pièce jointe en generally available
- [x] Exposer les champs PJ comme les anciennes PJs sur l’API
- [x] Interdire la création d’anciennes PJs
- [x] Afficher le nombre de PJ migrées
- [x] Migrer les anciennes PJs vers les champs PJ
  - [x] Vérifier que les PJs sont marquées comme analysées par l'anti-virus
  - [x] Migrer une unique démarche de prod, et vérifier que ça se passe bien
  - [x] Faire des stats sur le temps de migration
  - [x] Écrire une tâche pour migrer toutes les démarches
  - [x] Lancer la tâche dans un screen
- [x] Supprimer le code de support des anciennes PJs
- [x] Migrer les autres utilisations de Carrierwave (logos) vers Activestorag
- [x] Décommissionner Carrierwave

**Comment by LeSim** [comment]
Semble être du à l'interraction entre Active Storage (version Cellar) et Riak cs qui ne comprend pas les query parameters `content-disposition`

**Comment by philemon95** [comment]
excusez moi de revenir sur l'issue, mais c'était pour savoir où ça en était :)

**Comment by fredZen** [comment]
- L’issue (je veux que les pièces jointes lourdes conservent leur nom + extension lors du téléchargement) est corrigée
- Maintenant que le problème d’accès aux nouvelles PJ est corrigé :crossed_fingers: , on va pouvoir reprendre la migration des anciennes PJ vers les nouvelles PJ :smile:

**Comment by kemenaran** [comment]
@tchak est-ce qu'on a du progrès sur cette issue ? Des choses encore à faire, ou on peut décommissionner ?

**Comment by tchak** [comment]
Je pense que c'est fait

**Comment by kemenaran** [comment]
Donc à priori on n'a plus qu'à décommissionner CarrierWave :

- [ ] Supprimer le code lié à CarrierWave
- [ ] Supprimer les fichiers sur le bucket
- [ ] Supprimer la facturation CarrierWave

**Comment by kemenaran** [comment]
Les dernières étapes sont déportées dans #4533

Fin de l'issue de l'angoisse ! \o/
