### ISSUE TITLE
Mismatch dans le nombre de dossier sur la page de recap d'une procédure

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#2209]
- Dans "Dossiers", total 54
- Dans "Supprimer la procédure", 69

![image-1](https://user-images.githubusercontent.com/1333173/42323663-320ead14-8061-11e8-9fb3-ae2f2fa73b0d.png)

**Comment by fredZen** [comment]
Le décompte dans _Supprimer la procédure_ prend sans doute en compte les brouillons
