### ISSUE TITLE
Les datepickers sont inefficaces, utiliser des champs textes à la place

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#2215]
C'est toujours bien relou d'aller chercher une date assez ancienne, on perd des usagers là dessus, et en plus le format derrière est pas standard donc on fait toute un traitement pour gérer correctement tous les navigateurs.

Je propose de faire du `JJ/MM/AAAA` partout (formulaire + identité)

**Comment by kemenaran** [comment]
Sur les mobiles récents le date picker a l'air de fonctionner vraiment bien – et sûrement mieux qu'un champ JJ / MM / AAAA.

Est-ce que ça ne serait pas surtout un problème sur des vieux mobiles, ou certaines version d'Android ? Dans ce cas est-ce qu'on ne veut plutôt pas faire de la _feature-detection_ ?

**Comment by gregoirenovel** [comment]
Mon issue ne concerne pas les mobiles mais les navigateurs desktop (je revert donc ton changement de titre). Les datepickers sont compliqués à manier pour bien des utilisateurs, et même pour les utilisateurs plus expérimentés, il faut parfois de nombreux clics pour sélectionner une date. Rentrer la date au format texte `JJ/MM/AAAA` est bien plus rapide dans la majorité des cas.

**Comment by gregoirenovel** [comment]
> Le menu déroulant permettant d'indiquer une date de naissance est peu fonctionnel, nous sommes obligés de faire dérouler ( à un rythme assez lent) les jours, mois ou nombreuses années avant de trouver le choix qui nous concerne, particulièrement pour les années de naissance qui démarrent systématiquement à 2018 ...c'est long est fastidieux pour retrouver l'année de naissance d'un adulte.

HS 7269

**Comment by kemenaran** [comment]
Effectivement il y a toujours un vrai problème avec les date pickers utilisés pour des dates de naissance.

Est-ce que ça ne veut pas surtout dire qu'on veut :

- ajouter un champ spécifique "Date de naissance" (qui utilise un format texte `JJ / MM / AAAA`)
- conserver le champ "Date" avec un date picker (pour les champs du genre "Date du stage")

?

**Comment by gregoirenovel** [comment]
Franchement on va avoir le même problème avec "date d'immatriculation du véhicule" ou "date d'attribution de je sais pas quoi", pour moi c'est une connerie de commencer à se spécialiser

**Comment by fredZen** [comment]
Sur certains mobiles aussi on a des datepickers pourris, sur celui-ci par exemple l’utilisateur ne peut pas (ou ne sait pas comment) changer directement d’année. Des dizaines d’années à scroller mois par mois, ça fait long en effet.

Je ne sais pas si la solution c’est juste de dégager les datepickers ou s’il y a un truc plus fin à faire, mais en tout cas notre solution actuelle pose un vrai problème. À moins que quelqu’un ait une meilleure idée, je serais partisan de désactiver les datepickers.

HS `# 13147`

![image](https://user-images.githubusercontent.com/356570/53655891-d714e880-3c51-11e9-9142-16182bce9fdb.png)
