### ISSUE TITLE
ETQ Administrateur, je veux un moyen clair de communiquer le lien de ma démarche publiée

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/demarches-simplifiees.fr#2217]
Les administrateurs ne comprennent pas toujours qu'ils doivent faire un travail de communication, pour transmettre à leurs usagers les liens des démarches. 

A la fin de la création des formulaire, une fois qu'ils ont cliqué sur "publier", pourrions-nous rajouter un encadré leur expliquant le travail de communication qu'il leur reste à faire.

**Comment by gregoirenovel** [comment]
+ l'URL de la procédure en gros avec un bouton "copier" qui la copie automatiquement dans le presse-papier
