### ISSUE TITLE
ETQ Instructeur, je veux choisir les dossiers des exports

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#2221]
À communiquer : `HS #2028`

**Comment by fredZen** [comment]
`HS  #7864`

**Comment by mmagn** [comment]
HS 9316

**Comment by tchak** [comment]
Avec #3046 les instructeurs un peu débrouillards vont pouvoir utiliser une URL du type `/procedures/42/download_dossiers?ids=1,2,3,4`
