### ISSUE TITLE
Supprimer la partie "libellé", lorsqu'on créé un champ "explication"

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/demarches-simplifiees.fr#2233]
Le champ "explication" n'a pas besoin de libellé particulier, puisqu'il ne s'agit pas de demander qqch à l'usager comme les autres champs. 
Je propose donc de supprimer cette partie "libellé".

**Comment by gregoirenovel** [comment]
De la meme manière qu'il n'y a pas d'explication quand on créé un champ "titre de section"
