### ISSUE TITLE
ETQ accompagnateur je veux classer sans suite un dossier sans avoir à le passer en instruction

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#2238]
C'est le cas pour le traitement de la DETR dans les préfectures. Le passage en instruction atteste de la complétude d'un dossier et selon les textes réglementaire la complétude permet aux collectivités de commencer à engager des fonds dans leur projet. Le service a besoin de d'éliminer des dossier inéligibles d'office sans passer par l'étape passage en instruction pour ne pas donner de messages contradictoires. 
@H.B (Pref Mayenne)

**Comment by gregoirenovel** [comment]
Un état "invalide" conviendrait-il ? (c'est une des possibilités qui ressort du travail sur le "flow" des dossier)

**Comment by CamilleGarrigue** [comment]
Oui tout à fait si cet état peut générer une notification (e-mail) à l'usager.
