### ISSUE TITLE
ETQ usager je ne reçois pas le mail pour activer mon compte

### ISSUE THREAD

**Issue by red1bush** [betagouv/demarches-simplifiees.fr#2243]
Plusieurs cas ce sont présentés: 

https://secure.helpscout.net/conversation/618684422/4612?folderId=1948973

**Comment by gregoirenovel** [comment]
Note : pour ce cas précis, on a bien envoyé des emails (vérifié dans Mailjet), et l'utilisatrice dit ne rien avoir dans ses spams

**Comment by kemenaran** [comment]
Si on a de nouveaux cas, ou de nouveaux éléments pour investiguer, je suis preneur.

Sinon on peut fermer – et rouvrir si de nouveaux cas se présentent.
