### ISSUE TITLE
ETQ Instructeur, je souhaite qu'un dossier archivé passe en lecture seule

### ISSUE THREAD

**Issue by red1bush** [betagouv/demarches-simplifiees.fr#2244]
Plusieurs usagers remontent le fait qu'ils envoient plusieurs messages via la messagerie pour obtenir des infos sur leur dossiers classés sans suite ou refusés sans réponse.

Notamment sur les capacités de transport & Permis de conduire, 

Le footer service peut aider mais il faut rendre visible ces messages aux instructeurs.

**Comment by red1bush** [comment]
Voici l'une des personnes ayant remonté le pb, finalement ca ne concerne pas les dossiers en instruction (elle avait le bug mais ds le cas où usager=accompagnateur.
aurore.quaranta@sicoval.fr

**Comment by mmagn** [comment]
HS `#4623`

**Comment by kemenaran** [comment]
C'est aussi le problème de #2291

**Comment by gregoirenovel** [comment]
`HS #7656`

**Comment by mmagn** [comment]
HS 12261

**Comment by mmagn** [comment]
Après discussion, l'archivage d'un dossier doit empêcher l'écriture de nouveaux commentaires, la modification d'annotations privées, l'ajout et l'édition d'avis.

**Comment by kemenaran** [comment]
Je vais m'occuper rapidement de désactiver la messagerie sur les dossiers archivés. Parce que bon, si les instructeurs ne voient pas les messages envoyés par les usagers, c'est vraiment pas cool pour les usagers :)

Mais du coup, question : si les instructeurs archivent les dossiers juste après les avoir terminé (accepté/refusé/sans-suite), ça coupe la messagerie immédiatement. Et donc les Usagers ne peuvent plus demander des explications sur la décision.

_(J'aimerais bien voir si statistiquement les dossiers sont archivés très vite après la décision – mais on n'a pas de `archived_at`, seulement `archived`. Zut.)_

Du coup :

1. Est-ce qu'on veut vraiment empêcher les usagers de contacter l'instructeur via la messagerie quand le dossier est archivé ?
2. Si oui, ça vous va si, pour les dossiers archivés, on remplace le bloc "Répondre" de la messagerie par un texte :
  > Le dossier est archivé, et la messagerie est donc désactivée. Contactez l'administration via [email de la démarche] ou [téléphone de la démarche]

Je me demande quand même si on n'est pas en train de créer une solution à un mauvais problème. Est-ce que le plus simple ne serait pas de garder la messagerie utilisable même après archivage ?…

**Comment by mmagn** [comment]
1 - on était plutôt d'accord pour le faire oui
2 - oui top ta proposition ! on peut mettre toutes les infos de contact du service

**Comment by kemenaran** [comment]
On n'est pas encore entièrement d'accord sur le fonctionnement à avoir (usage de la messagerie, usage pour les usagers, usage pour les instructeurs). À cadrer plus finement tous ensemble.

**Comment by kemenaran** [comment]
En cours d'implémentation dans #3663
