### ISSUE TITLE
Administrateur: je veux pouvoir modifier les champs et les menus déroulants pour MAJ après mise en ligne/publication

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/demarches-simplifiees.fr#2246]
Hello,
Je ne sais pas si cette demande existe déjà. Y a-t-il une raison technique ou métier derrière le blocage de l'édition du formulaire après publication? Exemple: quid de la possibilité de mettre à jour un menu déroulant reprenant la liste des ministères?

**Comment by kemenaran** [comment]
On a fait des issues plus séparées pour ces améliorations (et qui sont par ailleurs progressivement migrées progressivement sur FeatureUpvote)
