### ISSUE TITLE
Enlever la possibilité de mettre en forme les emails dans la partie usager

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#2262]
Les nouvelles interfaces Instructeur et Usager ne permettent plus de formatter des messages (par exemple avec du gras ou de l'italique). On peut donc supprimer la fonctionnalité.

- [ ] Supprimer l'éditeur rich-text dans le code
- [ ] Faire tourner une moulinette pour passer les messages existants en plain-text

**Comment by kemenaran** [comment]
À faire à l'occasion – mais ce n'est pas obligatoire pour activer la nouvelle interface Usager (qui affiche très bien les messages rich-text existants).

<img width="729" alt="capture d ecran 2018-09-24 a 17 25 55" src="https://user-images.githubusercontent.com/179923/45961790-ae901f00-c01f-11e8-862c-a4a82288703a.png">
