### ISSUE TITLE
Utiliser les bang methods tout le temps

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#2265]
`save!`, `update!`, etc. quand c'est possible

**Comment by kemenaran** [comment]
Pourquoi ?

**Comment by gregoirenovel** [comment]
Parce qu'on s'est fait mordre la semaine dernière par un save qui failait silencieusement, avec flash de succès et tout le bazar, on en a parlé avec Simon, on préfère failer de manière dégueu qu'en silence

**Comment by tchak** [comment]
Je suis plutôt pour. Même raison que @gregoirenovel

**Comment by kemenaran** [comment]
J'ai l'impression qu'il y a consensus, et qu'on le fait au fur et à mesure.

On ferme ?

**Comment by gregoirenovel** [comment]
Je ne crois pas trop au "fur et à mesure" perso, je préfererais que quelqu'un se saississe du sujet et le plie
