### ISSUE TITLE
Formatage incohérent des champs datetime en base

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#2296]
Selon le cas, la valeur va être formatée en `"%d/%m/%Y %H:%M"`
https://github.com/betagouv/tps/commit/c690d3819e379a72f8880812d2bceb8901a30935#diff-cf73120705e00233bfe712a2e3c56346R17

ou en `%Y-%m-%d %H:%M`
https://github.com/betagouv/tps/commit/c690d3819e379a72f8880812d2bceb8901a30935#diff-cf73120705e00233bfe712a2e3c56346R12

**Comment by gregoirenovel** [comment]
Slightly related: #2215
