### ISSUE TITLE
Champ SIRET : rechercher par nom d'entreprise

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#2316]
Un utilisateur demande s'il serait possible, pour les champs SIRET, de faire le même genre de recherche que sur https://entreprise.data.gouv.fr​ – c'est à dire de pouvoir rechercher par nom de l'entreprise.

Pour le jour où on voudra améliorer ça, ça me semble une bonne idée.

**Comment by gregoirenovel** [comment]
Ça serait cool de faire la même chose pour le "SIRET" à renseigner dans le "Service"
