### ISSUE TITLE
Coté usager fournir au début de chaque dossier, une durée estimée de remplissage 

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#237]
version simple : on se base sur le nombre de champs 
version moins simple : on pondère en fonction du type de champs
Exemple :
<img width="492" alt="capture d ecran 2017-05-03 a 14 43 25" src="https://cloud.githubusercontent.com/assets/847942/25660978/ea1be60a-300e-11e7-97d4-f28f3506fe39.png">

**Comment by kemenaran** [comment]
C'est en prod, derrière un feature flag, qui sera très bientôt activé à tout le monde.

On pourra supprimer le feature-flag ensuite.
