### ISSUE TITLE
Avoir plus de statistiques sur le parcours des Usagers

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/demarches-simplifiees.fr#2381]
Pour avoir une meilleure visibilité sur l'utilisation du produit par les usagers, on pourrait mettre en place plusieurs outils stats : 

**- Piwick :** pour connaitre le nombre d'utilisateurs, les pages les plus consultées, d'où viennent les utilisateurs,...
On pourrait se greffer au piwick de beta.gouv, mais aujourd'hui ils n'ont pas un forfait assez gros pour nous inclure . On est en train d'étudier la possibilité d'analyser seulement 10% du traffic.

**- indicateur de satisfaction :** pour avoir une idée de la qualité de notre site pour les usagers. On teste cette semaine un indicateur sur l'interface usager. Avec NosDemarches on pourra aussi mettre un indicateur au bas des formulaires pour évaluer la qualité des démarches faites par les administrations, plus que la qualité du site DS en lui même

**- flux de conversion usager :** détailler le chiffre "40 000 dossiers" en observant les dossiers/statuts/procédures. Cela permettrait d'Identifier les procédures problématiques où la plupart des dossiers sont en construction (ex : ivoire)

**- Analyse Helpscout :** en analysant les tickets Helpscout régulièrement (par ex 1fois/mois), on peut connaitre la part de tickets venant des usagers/administrations, voir si les questions concernent le produit ou pas,... 
Par ex sur la semaine du 1er au 8 aout, on a eu 200 tickets, dont la moitié venaient des administrations, 1/4 venaient des usagers avec des questions sur le produit, 1/4 venaient des usagers avec des questions ne nous concernant pas directement. 

**- taux de contact**

**Comment by kemenaran** [comment]
Pour le suivi :

- [ ] Piwik : en cours
- [x] Indicateur de satisfaction : implémenté
- [ ] Flux de conversion usager : pas démarré
- [ ] Analyse HelpScout : ?
- [ ] Taux de contact : discussion en cours
