### ISSUE TITLE
Avoir un site responsive

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/demarches-simplifiees.fr#2420]
Pour les personnes qui font leur démarches sur téléphone, il faut que DS soit le plus responsive possible.

**Comment by LucienMLD** [comment]
Testé sur un écran de 5,5 pouces
- Page de connexion avant d'acceder à une démarche le contenu fait bien la taille de l'écran mais on peut scroller à droite à cause du champs de recherche en haut (je pense).
- Page du formulaire :  le contenu prend bien la taille de l'écran mais comme la page de connexion on peut scroller sur la droite.
- Page de remerciement après avoir soumis un dossier : on peut scroller a droite aussi
- Page de la messagerie : Pas du tout responsive mais l'application du nouveau design sur cette page est en cours
- Liste des dossiers : la page ne prend pas toute la largeur par defaut

<img width="325" alt="capture d ecran 2018-08-17 a 14 55 55" src="https://user-images.githubusercontent.com/22002486/44267232-c0ff8780-a22d-11e8-8ca6-1a6bc97c6dbc.png">
