### ISSUE TITLE
ETQ accompagnateur je veux pouvoir faire remonter des balises dans le fil de messagerie

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#2421]
ETQ accompagnateur je veux pouvoir faire remonter des balises dans les messages envoyé via le fil de messagerie. Cela me permet de signaler à l'usager les pièces / informations manquantes lorsque son dossier n'est pas complet. Aujourd'hui le seul moyen d'automatiser le processus est l'utilisation des emails de passage en instruction or ceux ci veulent normalement dire que le dossier est complet.

**Comment by gregoirenovel** [comment]
C'est demandé par qui ? Y'a un a-communiquer ? Les accompagnateurs peuvent pas copier-coller le libellé du champ problématique ?
