### ISSUE TITLE
ETQ Admin je souhaite conserver mon mot de passe lorsque je deviens accompagnateur

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#2422]
J'ai un compte administrateur avec un mot de passe X pour celui-ci.

Ensuite, on me désigne accompagnateur. Je reçois donc un email qui m'a indique de cliquer sur un lien, et ce lien m'emmene vers la page « définition de mots de passe ».
Si j'entre un mot de passe Y, alors qaund je souhaite me reconnecter je dois saisir ce mot de passe Y plutôt que le X (le Y a écrasé le X).

· Actuel : plutôt que de demander un mot de passe qui va écraser le mot de passe déjà configuré pour le compte existant

· Proposition : demander le mot de passe actuel du compte existant, et simplement le vérifier

**Comment by gregoirenovel** [comment]
Sera fait avec la fusion des usagers / admin / accomp

**Comment by gregoirenovel** [comment]
Cf. #496
