### ISSUE TITLE
ETQ admin je n'arrive pas à réactiver ma procédure

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#2427]
J'ai archivé automatiquement ma procédure et je souhaite la réactivé. j'ai modifié la date d'archivage automatique pour une date ultérieur, je clique sur réactiver, un bandeau bleu s'affiche "la procédure est publiée" mais la procédure reste dans la catégorie archivée et le bouton réactiver est toujours disponible.

**Comment by tchak** [comment]
j'ai l'impression que c'est le même problem: https://secure.helpscout.net/conversation/652760366/6072?folderId=1653799
