### ISSUE TITLE
ETQ usager invité à coconstruire un dossier, je souhaite recevoir un mail quand un message est déposé dans la messagerie

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#2429]
Actuel : ETQ invité à coconstruire un dossier je ne reçois pas de mail quand un nouveau message est dans la messagerie

Proposition : Comme pour l'usager, l'invité reçoit un mail

**Comment by kemenaran** [comment]
**Cas d'usage**

Je suis travailleur·euse social·e. Pour aider des gens à effectuer leurs démarches, je commence le dossier avec eux – puis je m'ajoute en tant qu'invité·e.

Pour pouvoir suivre le dossier du demandeur, j'aurais besoin d'être notifié·e des messages dans la messagerie.

**Comment by kemenaran** [comment]
**Cas d'usage**

Je suis gérante d'une crèche. Je dépose donc des dossiers de demande de subvention. La personne précédente a quitté son poste, et je ne peux plus accéder à ses dossiers en cours.

Je voudrais qu'elle m'ajoute en tant qu'invité sur les dossiers, pour pouvoir ensuite suivre moi-même l'évolution des dossiers déjà ouverts.
