### ISSUE TITLE
ETQ Instructeur je veux voir le lien public de diffusion d'un démarche

### ISSUE THREAD

**Issue by chaibax** [betagouv/demarches-simplifiees.fr#2433]
Afin de réduire la diffusion de mauvais lien vers une  téléprocédure  , il faudrait permettre aux accompagnateurs d'obtenir le lien vers la téléprocédure facilement. Avec un bouton de partage par exemple. Celui-ci permettrait de récupérer dans un popup le lien complet vers la téléprocédure (qui fini par /commencer/XXXX).

Suggestion de présentation : 

<img width="1275" alt="capture d ecran 2018-08-21 17 50 04" src="https://user-images.githubusercontent.com/3593868/44413349-72bef100-a56b-11e8-83d8-e78af846d6b2.png">

**Comment by gregoirenovel** [comment]
C'est quoi une TS ? Et les accompaganteurs sont pas sensés s'occuper de la diffusion du lien mais juste de son instruction donc je ne comprends pas trop cette issue.

**Comment by chaibax** [comment]
Oups, je voulais dire une téléprocédure

**Comment by gregoirenovel** [comment]
J'aimerais qu'on confirme bien le besoin sur cette issue.

**Comment by chaibax** [comment]
C'est bien ca Pierre. Ca me semble très bien ce que tu propose. 

Le besoin Grégoire c'est de faciliter la diffusions du bon lien vers la procédure par les instructeurs. Actuellement, certains renvoi vers "le site de démarche simplifiée."

**Comment by gregoirenovel** [comment]
Pourquoi les instructeurs diffuseraient le lien ?

**Comment by chaibax** [comment]
Je pense que plus il y aura de personnes (admin et instructeurs) avec **le bon lien,** moins on aura de personnes qui diffuseront un mauvais lien (ou parlerons du site de DS sans plus de détail). 

On ne peut pas se plaindre que de mauvais liens circulent, et  limiter le nombre de personnes y ayant accès. 

Si on veut savoir si ça a une utilité, comptons le nombre de cliques sur le lien.

**Comment by LeSim** [comment]
chaud pour le test and learn
