### ISSUE TITLE
ETQ instructeur, je veux que les heures dans mon tableau de bord soient exprimée dans mon fuseau horaire

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#2477]
Pour l’instant elles s’affichent en UTC (cf capture d’écran), les afficher en heure parisienne à la place

![capture d ecran de 2018-08-28 16-40-56](https://user-images.githubusercontent.com/356570/44730557-875a3680-aae1-11e8-88cb-25eda72f4da1.png)

**Comment by fredZen** [comment]
HS `#5995`

**Comment by gregoirenovel** [comment]
Lié à #2439

**Comment by mmagn** [comment]
L'heure n'est plus affichée, uniquement la date au format dd/mm/yyyy .
On ferme l'issue ou on rajoute l'heure proprement ?
