### ISSUE TITLE
ETQ qu'Usager, je veux ouvrir un nouveau dossier sur la même procédure

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#2551]
Certaines procédures sont clairement récurrentes : un usager peut être amené à déposer un dossier régulièrement dans le temps, ou plusieurs fois au même moment.

(Pour donner une idée, environ 12 % des usagers ont déjà déposé au moins deux dossiers sur une même procédure.)

Une requête récurrente est de pouvoir facilement ouvrir un dossier sur une procédure existante. Mais on n'est pas sûr de comment faire :

- Il faut que ça soit accessible ;
- Mais il ne faut pas que ça pourrisse l'UI pour une fonctionnalité rarement utilisé.

Une approche a été tentée dans #2428, mais sans être totalement satisfaisante. On cherche une meilleure solution.

**Comment by gregoirenovel** [comment]
Cf. #2576 pour un premier pas

**Comment by Benjamin-Doberset** [comment]
a communiquer # 5414
