### ISSUE TITLE
Ne plus permettre l'édition du path dans le dialogue de publication de démarche

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#2566]

**Comment by n-b** [comment]
Je ne sais pas exactement quelle idée était derrière ça, mais en tout cas #4048 la rend caduque. Je ferme.

**Comment by gregoirenovel** [comment]
Contexte : avant quand tu cliquais sur le bouton pour publier ta démarche, dans le dialogue de confirmation de publication, tu pouvais changer le path de ta démarche.

L'idée était de supprimer cette possibilité, car il semblait plus fluide de définir ce path en amont de la publication, directement dans le formulaire des détails (titre, administration, description, etc.) de la démarche.
