### ISSUE TITLE
Vérifier que l'email donné par l'admin est correct

### ISSUE THREAD

**Issue by chaibax** [betagouv/demarches-simplifiees.fr#2574]
**Contexte : Etape 2 : validation inscription**

Deux soucis font qu'on peut s'inscrire a DS et ne jamais recevoir l'email de validation de l'inscription : 

1 - Car on peut encore s'inscrire avec un email non correct syntaxiquement (ex : xxx@toto ) 

2 - Car on peut encore s'inscrire avec un email correct syntaxiquement, mais qui n'existe pas  : faute de frappe,  bounce pour diverses raisons (mailbox pleine, etc) 

Il existe plusieurs services externes qui permettent de vérifier en live une adresse email, et nous permettraient de refuser l'inscription en cas de mauvais format. 

- https://trumail.io/
- https://mailboxlayer.com/ (avec un didyou mean) 
- https://www.mailgun.com/email-validation 

Il faudrait empêcher la soumission du formulaire dans ces cas 

Ce problème touche 14.25% des admin , soit 218 personnes en tout.

**Comment by gregoirenovel** [comment]
Je propose plutot de suggérer à l'usager qu'il a fait une erreur en utilisant une librairie JS comme [Mailcheck](https://github.com/mailcheck/mailcheck), qui évite d'envoyer les emails de nos clients aux américains 😉 

Ça ne valide par contre que le format, mais c'est un premier pas.

**Comment by mmagn** [comment]
Version plus light : ajouter un attribut `pattern` sur l'input de type email pour forcer le domaine à contenir un `.`. 
https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/email#Validation

**Comment by chaibax** [comment]
+1 

Encore un cas aujourd'hui  

![capture d ecran 2018-11-15 10 15 24](https://user-images.githubusercontent.com/3593868/48542559-c5385100-e8bf-11e8-8f4e-dd88d6e978e3.png)
