### ISSUE TITLE
ETQ usager, je veux que le champ civilité / nom / prenom soit automatiquement remplis si j'utilise France Connect 

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#2588]
`HS 6337`

**Comment by emsnytech** [comment]
Suite à des retours usagers, je propose de remettre en place cette option, qui est assez logique.
Si je rentre par FC et que je suis dans une démarche qui demande de remplir l'identité de la personne (entrée personne physique), les champs peuvent être préremplis. Dans le cas où la démarche est effectuée pour une autre personne, marginal, l'usager remplace par le nom et le prénom par ceux de la bonne personne.
