### ISSUE TITLE
Rajouter un validateur au champ nombre pour rejeter les décimaux

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#2623]
Lié à #420

**Comment by emsnytech** [comment]
Pas d’accord avec cette issue. Il faut en fait des champs nombre qui puisse accueillir les décimales.
Cette issues est un contournement d’un pb qui existe depuis trop longtemps.

**Comment by gregoirenovel** [comment]
Rollbacké
