### ISSUE TITLE
Quand un Usager clique sur le lien d'un avis, on ne le connecte pas au bon profil

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#2627]
Cf. `HS #6648`

L'usager clique sur le lien d'invitation à donner son avis et se retrouve sur un profil usager.

**Comment by kemenaran** [comment]
Tu veux dire dans le cas où la personne est déjà connectée en tant qu'Usager ?

**Comment by gregoirenovel** [comment]
Probable, mais pas clair.

Cas à tester :
- personne sans compte du tout
- personne avec compte usager, connecté en usager
- personne avec compte usager, mais déconnectée
