### ISSUE TITLE
ETQ instructeur je veux joindre un document lors de la validation d’un dossier directement dans la saisie de la motivation

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#2631]
Il s'agit simplement de donner la possibilité au valideur ( instructeur qui remplie la motivation) la possibilité d'uploader un document ( un arrêté signé par un supérieur hiérarchique qui n'utiliserait pas DS, une attestation ). Du coup, ce document est un peu celui qui a une valeur plus "légale" Cela est d'autant plus nécessaire que tout le monde ne va pas utiliser l'attestation (et nous évitera de devoir trop travailler cette édictique dans un premier temps (on verra cela plus tard). Cela évite qu'après avoir pris la décision, quand il y a un document à uploader, l'instructeur ne soit obligé de faire cela dans un message. Cela va avec la création d'un profil éventuellement "valideur"

**Comment by gregoirenovel** [comment]
Tu peux détailler le besoin stp ? C'est quel genre de document ? On communique à qui ?

**Comment by emsnytech** [comment]
Il s'gait simplement de donner la possibilité au valideur ( instructeur qui remplie la motivation) la possibilité d'uploader un document. Cela est d'autant plus nécessaire que tout le monde ne va pas utiliser l'attestation.

**Comment by gregoirenovel** [comment]
C'est pas `legal`, c'est pas `quick-win` non plus, et sans référence, c'est pas `a-communiquer`.

**Comment by gregoirenovel** [comment]
Et on a déjà la messagerie qui permet de faire ça dans une certaine mesure.

**Comment by emsnytech** [comment]
Je ne partage pas ce commentaire.
Issues à examiner sous l'angle technique, pas en opportunité.
S'agissant du volet juridique, l'immense de l'approche, c'est que le commentaire écrit mis dans le volet est immédiatement lié à un document qui porte la décision. Dans le cas où nous devrons mettre en oeuvre un stockage pour preuve des décisions, nous aurons un lien direct entre la prise de décision, et le document associé (horodatée, hachage). Ce point a été vu aussi dans le cadre des travaux de sécurité. 
Merci

**Comment by fredZen** [comment]
Ce sera un document de plus, à côté de l’attestation.
Penser à prévoir une balise lien dans le template de mail

**Comment by fredZen** [comment]
`HS 9253`

**Comment by Benjamin-Doberset** [comment]
PD : 2585

**Comment by emsnytech** [comment]
Ok pour moi ! une première PR !!!

**Comment by kemenaran** [comment]
@Keirua ça m'a l'air intéressant, et l'issue est déjà relativement bien cadré. Ça a l'air d'une bonne possibilité pour les contributions.

À vue de nez, il faudrait sans doute :

- Faire un mockup d'UI rapide
- Implémenter dans l'UI la possibilité d'uploader le document externe
- Voir si on veut pouvoir modifier ou supprimer le document (comment on rectifie si on a envoyé le mauvais document, quoi)
- Éventuellement rajouter une balise contenant le lien vers le document externe (qu'on peut mettre dans le template de l'email).

Questions ouvertes :

- Est-ce que c'est un réglage au niveau de la démarche ? ("Joindre un document externe au moment du passage en (acceptation/refus/sans-suite) du dossier", et le document est obligatoire) ? Ou est-ce qu'on affiche ça dans l'UI à tout le monde, même sur les démarches qui ne s'en servent jamais ?
- Pour intégrer la balise avec le lien vers le document externe dans l'email, il faudra décider comment ça se comporte si pour un dossier l'instructeur n'a pas uploadé de document : on laisse le lien vide, on supprime la phrase dans l'email, on plante ?

**Comment by Keirua** [comment]
Merci pour ces retours, j'avancerais sur ce sujet un peu plus tard (idéalement cette semaine)
A mon sens, il n'est pas possible de modifier un avis envoyé (sinon, je me dis que sa valeur devient discutable). Par contre, tu peux toujours envoyer un message après pour corriger. Mais cette fois-ci, c'est la valeur du message de correction qui est discutable. Pas évident!
Concernant le paramètrage: on peut l'afficher pour tout le monde, mais rendre la PJ optionnelle, donc moins d'info à paramétrer

**Comment by Keirua** [comment]
Je n'avais pas répondu concernant l'intégration de la PJ dans le mail. Je n'ai pas de bonne réponse! Je vois 3 manières de faire:

Si on choisit d'**ajouter une balise dans le mail**, on peut:
 - afficher l'url avec un lien si le fichier est présent
 - afficher "Pas de justificatif" si c'est le cas
Problème: ça risque de faire de phrases bizarres, du genre "Vous pourrez télécharger le dossier ici: Pas de justificatif."

Autre solution: **Forcer l'affichage du lien vers le justificatif** à l'extérieur du template fourni par l'utilisateur. On incluerait donc nous ce lien dans le message dans le mail de justificatif.
Inconvénient:
 - on passe outre ce qui est fait par les utilisateurs
 - on risque d'afficher des choses après la signature des mails

Autre solution: **ajouter automatiquement le justificatif en PJ du mail**. Problème: si le justificatif est trop lourd, ou pour tout un tas de raisons aléatoires, on aura des problèmes de délivrabilité de ce mail essentiel.

**Comment by Keirua** [comment]
J'ai l'impression que la manière la moins intrusive de faire serait d'**ajouter une balise dans le mail**. Mais ça pose une question que j'avais oubliée: quid de la rétrocompatibilité pour ceux qui ont déja personnalisé leurs mails? (et donc, auront le champ d'upload mais pas de lien dans leur mail de validation?)

Pour récapituler le périmètre tel que je le comprends (et interprète), il faudrait donc:

 * Faire un mockup d'UI rapide. 3 choses au plus:
    - afficher le bouton de téléchargement
    - Afficher ce justificatif si dispo dans l'interface coté utilisateur
    - Afficher ce justificatif si dispo coté instructeur
    - (les 2 derniers sont potentiellement optionnels, mais nécessaire si aucun mail ne contient ce justificatif)
 * Implémenter dans l'UI la possibilité d'uploader le document externe
 * Pas de possibilité de modifier le document une fois l'avis envoyé (avant l'envoi on change autant qu'on veut).
 * Rajouter une balise contenant le lien vers le document externe.
 * Pas de règlage au niveau de la démarche, c'est disponible pour tout le monde (je vous laisse me dire si vous êtes OK avec ça)
 * Intégrer la balise avec le lien vers le document externe dans les templates de mails par défaut pour:
  - Accepter
  - Classer sans suite
  - Refuser
 * Exposer la piece jointe éventuelle dans l'api, à coté de la motivation?

Est-ce que ça vous parait OK?

**Comment by kemenaran** [comment]
Comme plan ça me semble bien.

Pour la question de **comment envoyer le document dans l'email** d'acceptation/refus/classement-sans-suite, j'ai l'impression qu'il y a effectivement deux problèmes avec une balise : la **rétro-compatibilité** avec les démarches existantes et **le cas où le document joint n'est pas présent**.

J'ai gratté un peu, et j'ai peut-être des solutions à proposer :

1. Balise dans l'email + La possibilité d'ajouter un document est une option sur la démarche. _Comme ça on s'attend à toujours avoir un document joint._
	* 👍 Pas de problème de balise vide : on s'attend toujours à avoir un document
	* 👍 Ça résout la rétro-compatibilité : quand un admin active l'option, il faut penser à mettre la balise dans l'email
	* 😞 Ça ne permet pas de faire des démarches qui ont parfois un document joint, et parfois pas
	* 😞 Il faut coder des options pour les trois types d'acceptation

2. Le document est uniquement en PJ de l'email
	* 👍 On n'a pas à rajouter de balise (plus simple)
	* 👍 On n'a pas à rajouter d'option sur la démarche (plus simple)
	* 👍 Pas de problème de balise vide
	* 👍 Ça résout la rétrocompatibilité (pas besoin de modifier les templates)
	* 👍 Le document est archivé chez l'utilisateur, immutable et tout
	* 👍 DS n'a pas à stocker ce document (plus simple)
	* 👍 les admins qui le veulent peuvent ajouter un texte dans le template qui dit "Voir le document en pièce jointe".
	* 😞 L'usager ne peut pas récupérer le document dans son interface
	* 😞 Le document n'est pas disponible dans l'API

3. Le document est en PJ de l'email, et DS le stocke aussi :
	* 👍 On n'a pas à rajouter de balise (plus simple)
	* 👍 Pas de problème de balise vide
	* 👍 Ça résout la rétrocompatibilité (pas besoin de modifier les templates)
	* 👍 DS n'a pas à stocker ce document (plus simple)
	* 👍 les admins qui le veulent peuvent ajouter un texte dans le template qui dit "Voir le document en pièce jointe".
	* 👍 L'usager peut récupérer le document dans son interface plus tard
	* 👍 Le document est disponible dans l'API
	* 😞 DS doit stocker le document

@Keirua tu en penses quoi ?

**Comment by Keirua** [comment]
Merci pour ce récap. Je pense que tu as raison, la solution de la balise sera souvent problématique. Je ne pense pas qu'on puisse se passer d'un stockage chez DS (à cause des problèmes que tu cite, et comme solution de secours en cas de problèmes d'envoi), donc j'opterais plutot pour la **solution 3** (qui, du coup, ne serait pas une option, mais dispo pour tout le monde)

**Comment by Keirua** [comment]
Dans l'idée, coté UI ça pourrait se présenter ainsi:

# Le dépot d'un justificatif

(le champ est dispo pour acceptation/refus/classer sans suite)

![demande-justificatif](https://user-images.githubusercontent.com/1223316/53185489-66d9e780-35ff-11e9-991d-138e9aa2c5aa.png)

# La vision coté instructeur

Bon c'est pas ouf mais j'ai pas mieux…

![justif-instructeur](https://user-images.githubusercontent.com/1223316/53185508-71947c80-35ff-11e9-8c0b-6c83c13fc5f7.png)

# La vision coté demandeur

![justif-demandeur](https://user-images.githubusercontent.com/1223316/53185521-78bb8a80-35ff-11e9-8231-f8827abf68e8.png)

**Comment by kemenaran** [comment]
Pour **Le dépot d'un justificatif**, ça m'a l'air bien. Je me demande si, plutôt que d'avoir le champ visible tout le temps, on gagnerait à avoir plutôt du dévoilement progressif : du genre un lien gris "Ajouter un justificatif (optionnel)", qui quand on le clique affiche le file picker. Mais je ne suis pas certain.

Pour le côté "Vue du dossier", je me demande comment tout ça va se jouer dans les cas où il aura à la fois une attestation et un justificatif ? On affiche les deux ? On se dit que c'est mutuellement exclusif ?

J'imagine que ça serait pas mal, dans les cas où on a les deux, qu'il y ait le moins de confusion possible entre l'attestation (générée automatiquement) et le justificatif (envoyé à la main). Mais je n'ai pas de pistes plus précises à part ce vague questionnement :)

**Comment by emsnytech** [comment]
SUper.
Je propose en effet que l'on puisse garder la possibilité d'avoir les deux, justificatif et attestation...

**Comment by Keirua** [comment]
Bonne remarque d'avoir un bouton "ajouter un justificatif (optionnel)" qui fasse apparaitre le champ d'upload, je vais faire ça.

Effectivement, ça ne se substitue pas au attestations générés automatiquement : justificatif et attestations jouent des rôles différents, donc il faudra laisser les deux.
Et en effet, ça pourra faire bizarre d'avoir les avis et les justificatifs à proximité. Pour les utilisateurs, ils téléchargeront probablement les deux pour comprendre comment passer à la suite. Pour les instructeurs, on peut essayer de détailler un peu le champ pour les aider.

**Comment by fredZen** [comment]
Hello,

J’ai quelques éléments pour éclairer le débat sur le mail (lien vers document VS document en PJ)

Il n’y a pas si longtemps, les attestations étaient envoyées en PJ avec le mail d’accusé d’acceptation. On a changé ça il y a environ un an, avec #1563 . Notre motivation était d’éviter d’envoyer un document contenant potentiellement des informations confidentielles via le mail, moyen de communication peu sûr. Nous avons préféré mettre dans le mail un lien vers l’attestation, ce qui force l’usager à s’authentifier sur DS, et est donc plus sûr.

Détail d’implémentation si on choisit quand-même d’envoyer le document en PJ : pour des raisons de délivrabilité, bien penser à limiter la taille du document (à partir de 10 Mo, on commence à avoir des bounces pour PJ trop grosse)

**Comment by Keirua** [comment]
Yes, la délivrabilité est un risque, d'où mon hésitation.
J'ai déjà l'envoi en PJ de mail, on garde ou pas du coup? Si on garde, j'ajoute une balise?

**Comment by fredZen** [comment]
Report depuis #321 

À communiquer : France Agrimer
À communiquer : sicoval `hs #6337`

**Comment by philemon95** [comment]
à communiquer HS 14867
