### ISSUE TITLE
Rendre exceptionnellement la motivation optionnelle pour les procédures ARS suivantes

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#2670]
Rendre pour les procédures art 51 des ARS la motivation non obligatoire , :

- Innovation en santé : Plateforme régionale de dépôt des projets article 51- ARS Provence Alpes Côte d'Azur , ID7803
- Art 51 Plateforme régionale ARS Pays de la Loire 7806
- Plateforme de dépôt des projets du dispositif "Innovation en santé - Article 51" de l'Agence Régionale de Santé de Nouvelle-Aquitaine ID 7468
- Article 51 Plateforme régionale ARS de Normandie ID7557
- Article 51 Plateforme régionale de dépôt ARS Auvergne Rhône - Alpes #6263
- Plateforme régionale Innovation en Santé - Agence Régionale de Santé (ARS) et Coordination Régionale de l'Assurance Maladie (DCGDR) Ile de France #6793
- Article 51 - Plateforme régionale ARS Hauts-de-France #7822
- Article 51 Plateforme régionale ARS Guyane #7574
- Procédure type dépôt dossier - Article 51 Plateforme régionale ARS Corse #6989
- Procédure Article 51 Plateforme régionale ARS Bretagne #7627
- Article 51 Plateforme régionale ARS BFC #6064
- Article 51 Plateforme régionale ARS Océan Indien #7756
- Plateforme ARS Occitanie - Innovation Article 51 #7824
- Article 51 Plateforme régionale ARS Martinique #6957
- https://www.demarches-simplifiees.fr/commencer/art51-ars-gua-stm-stb

**Comment by kemenaran** [comment]
On parle de la motivation d'acceptation ou de rejet du dossier ?

(Et aussi, est-ce qu'une phrase-type qu'ils copient-colle dans le champ ne fonctionnerait pas aussi bien ?)

**Comment by Benjamin-Doberset** [comment]
En fait, ils avaient établi tout leur processus pour guider les agents dans leur motivation (via annotation privé et email automatique). L'objectif c'est d'avoir une motivation qualitative. Du coup, on ne peut pas trop mettre une phrase type.

**Comment by gregoirenovel** [comment]
Je réponds à ta question @kemenaran : on parle de la seule motivation obligatoire, celle de refus ou classement sans suite. Faut mettre un `if` pour ces démarches car concues avant qu'on ait rendu ces motivations obligatoires, et ça leur casse trop leur workflow si on leur demande de s'adapter.

**Comment by kemenaran** [comment]
Je comprends pour le "ça casse leur workflow", mais je ne suis pas très chaud pour le if.

Est-ce qu'on ne peut pas hacker leur demande pour rajouter un champ dans les "Annotation privée", qui leur servira de la même manière que l'annotation ?

**Comment by gregoirenovel** [comment]
Parles-en directement avec @Benjamin-Doberset mais ça me semble compliqué, c'est pour ça qu'on avait acté une exception pour ce cas particulier
