### ISSUE TITLE
Trop de code dans NewGestionnaire::DossiersController#terminer

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#2677]
Ce code se retrouve dupliqué dans `AutoReceiveDossiersForProcedureJob#perform`. Extraire un service ?

**Comment by mmagn** [comment]
On avait pour projet de passer sous AASM, ça règlerait le problème non ?

**Comment by fredZen** [comment]
Ça peut être l'occasion, oui

**Comment by Keirua** [comment]
Passage sous AASM fait. Les 2 implémentations sont différentes et ne peuvent être synthétisées plus. Je clos.
