### ISSUE TITLE
Propositions sur la fonctionnalitée cartographique

### ISSUE THREAD

**Issue by jpotel** [betagouv/demarches-simplifiees.fr#2694]
Bonjour,

je suis un nouvel utilisateur et j'ai testé la fonctionnalité cartographique de démarche-simplifiée j'ai quelques suggestions à vous faire sur la fonctionnalité cartographique de démarche simplifiée : 

1. pouvoir mieux se repérer dans l'espace en proposer d'autres fonds que celui d'openstreetmap et notamment des fonds souverains comme ceux diffuser par l'IGN par l'API Géoportail
2. dessiner à main lever avec une sourie est plutôt difficile, proposer de dessiner point par point et proposer plusieurs type de géométrie (point, polygone, ligne, multipoint, multipolygone, multiligne, collection...)
3. pouvoir intégrer n'importe où dans le formulaire la carte pour que l'utilisateur puisse produire la donnée géographique qu'on souhaite qu'il produise.
4. offrir la possibilité d'import de données géographique à la place de dessiner (format gpx, geojson...)

Les cas d'usage serait de pouvoir par exemple délimiter un projet, tracé un itinéraire d'une course à pied par exemple dans le cas des autorisations sportives, délimiter la zone d'une manifestation, instruction de nouveau périmètre réglementaire, etc, etc...

à votre disposition pour tout complément

Cordialement

**Comment by gregoirenovel** [comment]
Bonjour,

Merci pour vos suggestions, nous allons réflechir à tout ça. Cette fonctionnalité date un peu, et il est vrai qu'elle a bien besoin d'un peu d'attention.

Pour votre point numéro 3, c'est déjà quelque chose de prévu : #250.

Pour votre point numéro 4, pourriez-vous nous donner des exemples de démarches pour lesquelles une telle fonctionnalité serait pertinente ?

Merci beaucoup

**Comment by gregoirenovel** [comment]
Merci pour vos examples. Mais pour les cas que vous évoquez, est-ce qu'utiliser un champ de type "pièce jointe" ne serait pas une bonne solution ? Quel serait l'avantage d'utiliser un champ "carto" ? Une meilleure visualisation de la donnée ajoutée par l'usager ?

**Comment by jpotel** [comment]
Un des gros avantages serait de pouvoir récupérer via l'API la géométrie des objets  dans un format directement réutilisable (geojson) dans les outils cartographiques (web, qgis,...)
Pour l'usager, ça serait de pouvoir numériser un tracé sans outil IG spécifique.

**Comment by emsnytech** [comment]
en plus, c'est déjà utilisé par le CGDD nos données API CARTO...

**Comment by LeSim** [comment]
Faire un tracé pour décrire une course.
Pouvoir y ajouter des points d'intéret avec une information litérale lié (ce point correspond à la position d'un poste de secours dans le cadre d'une course cycliste).

A communiquer Sous préfecture d'étampes

**Comment by fredZen** [comment]
Voir aussi #2170

**Comment by AudreyBramy** [comment]
Bonjour,

Je suis membre de l'équipe Pitchou et nous utilisons DS pour le dépôt de demande de dérogations Espèces Pro.

J'interviens dans cette issue, bien qu'elle soit complété, car j'ai une demande d'une utilisatrice qui est en lien avec la prossibilité d'impro de données géo au format Shapefile.

La demande n'est remontée qu'une fois pour le moment, et la personne à trouvé le moyen de convertir son fichier en GPX ou KML, elle ne me semble pas prioritaire.
Mais je me demandais pour quelle raison vous n'avez pas intégré ce format là dans les formats attendus ? 

Merci pour votre retour.
