### ISSUE TITLE
ETQ qu'admin, je souhaite désigner un ou plusieurs instructeur en tant que valideur

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#2718]
Sans parler de work flow, ... il est souhaité que certains instructeurs puissent être les seuls à valider les décisions.

Proposition de mise en oeuvre. Sans toucher quoi que ce soit au principe actuel, créer un attribut à de valideur pour les instructeurs, seul à pouvoir activer les fonctions de validation.

Par défaut, un instructeur désigné est automatiquement valideur.

Conservation dans la décision des nom, prénom et qualité du valideur (application réglementation sur les décisions prises en ligne)

**Comment by kemenaran** [comment]
État des discussions d'équipe : ce n'est pas une fonctionnalité que nous voulons faire à moyen terme.

## Raisons

- demarches-simplifiees valorise plutôt le contrôle _a posteriori_. C'est pour cela qu'il est déjà possible à tout moment de savoir qui a pris une décision sur un dossier.
- Avoir différents profils de validateurs va à l'encontre d'organisations lean, qu'on essaie plutôt d'encourager.
- Ne pas pouvoir valider un dossier va plutôt dans le sens d'une dépossession des agents.
- La fonction de validateur est essentiellement une question organisationnelle, qui n'a pas forcément vocation à être intégrée niveau technique.

## Solutions alternatives

- Il est possible d'avoir différents profils d'instructeurs au niveau de l'organisation du service. Comme lors d'un traitement papier, c'est à l'équipe de s'assurer que les agents n'outrepassent pas leurs droits.
- Techniquement, il est possible d'ajouter une annotation privée "Dossier à valider". Cela permet ensuite à un agent validateur de filter les dossiers en attente de validation dans son tableau de bord.
