### ISSUE TITLE
Rendre la nouvelle UI usager compatible RGAA

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#2735]

**Comment by mfaure** [comment]
https://asqatasun.org/ et Adullact pourraient aider ;)

**Comment by tchak** [comment]
@mfaure tu pourrais nous dire en deux mot qu’est-ce que propose https://asqatasun.org ? Je pensais mettre en place quelque chose comme https://github.com/dequelabs/axe-core – tu pourrais nous expliquer la différence ?
