### ISSUE TITLE
ETQ Usager je ne dois pas voir les 3 dernières années de CA

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#2738]

**Comment by gregoirenovel** [comment]
Juste pour confirmation : ça reste visible par les instructeurs ?

**Comment by mmagn** [comment]
Oui.

**Comment by gregoirenovel** [comment]
Ok, comment on fait comprendre à l’administrateur cela ? Car désormais quand il teste le dépôt d’un dossier, s’il ne va pas jusqu’au dépôt puis dans l’interface instructeur, rien n’en lui dit qu’on te cette donnée.

**Comment by gregoirenovel** [comment]
D’ailleurs c’est quoi le rationale derrière ca ? C’est de la donnee privée que tout le monde pourrait voir en mettant le numéro SIRET d’une boîte qu’il n’est pas la sienne ?

**Comment by mmagn** [comment]
1) On affiche que la donnée est fournie à l'administration "visible uniquement par le service instructeur"
2) En quelque sorte

**Comment by CamilleGarrigue** [comment]
@la personne qui nous a remonté le problème. Elle paye info greffe pour que ses exercices restent confidentiels mais sur DS on les affiche à n'importe quelle personne qui rentre son SIRET. De plus notre info ne nous vient pas d'infogreffe comme mentionné à l'usager mais de la DGFIP.

**Comment by fredZen** [comment]
Est-ce qu’on peut fermer ?

**Comment by gregoirenovel** [comment]
(J'étais certain d'avoir laissé le commentaire qui va suivre sur cette issue il y a une semaine)
Non, il reste `_etablissement.html.haml` qui leak de la donnée coté usager, j'en ai parlé avec @tchak, on va faire du chiffrement minimal sur ces données entre client et serveur

**Comment by gregoirenovel** [comment]
J'ai retrouvé, c'est dans le body de #2855, c'est pour ça d'ailleurs que les commits ne font que `Ref` et pas `Fix`
