### ISSUE TITLE
ETQ Instructeur, je veux pouvoir masquer mon nom dans la messagerie

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#2739]
Certains instructeurs voudraient anonymiser leur prénom et nom dans les contacts avec les usagers. Or aujourd'hui la messagerie affiche le début de l'email des instructeurs - qui correspond souvent au Prénom + Nom.

C'est souvent des cas où les gens craignent des comportements agressifs ou de représailles de la part des usagers.

**Comment by gregoirenovel** [comment]
@CamilleGarrigue à communiquer à qui ?

**Comment by fredZen** [comment]
On veut continuer distinguer les instructeurs entre eux => on fait au plus simple, on identifie les instructeurs par leur id.

> *instructeur 468423* a écrit
> *instructeur 48613* a écrit

**Comment by tchak** [comment]
https://secure.helpscout.net/conversation/693440117/8179?folderId=1653799

**Comment by gregoirenovel** [comment]
- pas chaud pour rajouter une option supplémentaire coté admin, c'est déjà assez l'usine à gaz comme ça

- très contre le fait de mettre `"instructeur #{id}"`, on est des humains, pas des numéros ; j'ai d'ailleurs eu l'occasion d'avoir une discussion à ce sujet avec un instructeur, cf `HS #7573`, extrait ci-dessous (ses mots) :
> De plus, bien qu'une volonté de dématérialiser les actes administratifs, il serait opportun de faire savoir au demandeur, qui suit sont dossier. Pour avoir eu à faire à l'ANTS, je peux vous dire que ce site est une honte pour l'administration, et de plus les réponses apportées sont anonymes, probablement préconçues, et que bien qu'habitué aux démarches administratives, je peux vous dire que ce site est imbuvable. Je pense que la dématérialisation ne doit pas pour autant, être inhumaine. J'en fait suffisamment la propagande auprès des administrés qui me contactent.

- je pense qu'une fois la fusion des roles faite (Usager / Instructeur / Administrateur -> User), on pourra rajouter sur cet objet les champs "Prénom" et "Nom", qui nous permettront de mieux identifier nos usagers, de pré-remplir des dossiers (comme fait précédemment avec FC), et surtout, pour ce qui nous intéresse ici, d'afficher des infos partielles sur une personne. On peut par exemple imaginer afficher `Prénom N.` à l'usager quand son instructeur lui répond, ce qui me semble être un bon compromis.

**Comment by tchak** [comment]
> On peut par exemple imaginer afficher Prénom N.

J'ai l'impression qu’il y'en a qui se sentent insultés d'être appelé par le prénom...

**Comment by tchak** [comment]
Je suis d'accord avec @gregoirenovel sur le fond. Maintenant, il y a la réalité – le fait que les fonctionnaires soient ciblés par du harcèlement en ligne parce qu’on affiche leurs nom/prénom peut aussi être un problème bien réel.

**Comment by gregoirenovel** [comment]
> J'ai l'impression qu’il y'en a qui se sentent insultés d'être appelé par le prénom...

On peut écrire les initiales `P. N.`, ou `P. Nom` (même si dans ce second cas l'identification de l'agent est possible, mais pas immédiate) pour éviter cela.

> le fait que les fonctionnaires soient ciblés par du harcèlement en ligne

Certes, mais là dessus je veux bien qu'on me le confirme ("on a eu X cas l'année Y"), pour être bien certain qu'on n'est pas ici face à un équivalent "d'optimisation prématurée" mais niveau privacy.

**Comment by fredZen** [comment]
> pas chaud pour rajouter une option supplémentaire coté admin, c'est déjà assez l'usine à gaz comme ça

Pas chaud non plus. 

> je pense qu'une fois la fusion des roles faite (Usager / Instructeur / Administrateur -> User), on pourra rajouter sur cet objet les champs "Prénom" et "Nom"

Je pense que c'est une bonne idée, et que c'est assez orthogonal à la fusion des rôles (i.e. on pourrait même la faire demain).

Et si, plutôt que de demander le nom + prénom puis de définir nous même des règles d'anonymisation, on laissait simplement les agents instructeurs comment ils veulent être identifiés dans l'appli ? Libre à eux de mettre "Sylviane Nicolo", "S. Nicolo", "Sylviane N.", "S.N.", "Mme Nicolo", ou autre chose, en fonction de ce qui est pertinent dans leur contexte ?

**Comment by LeSim** [comment]
Je propose de résoudre en 2 étapes, mais rapidement, car je comprends que la situation peut être insupportable du coté de certains instructeurs.

1 on fout des ids, ça nous fait très mal, on déteste, on va changer vite.
2 profil

**Comment by gregoirenovel** [comment]
> la situation peut être insupportable du coté de certains instructeurs
Encore une fois, est-ce que l'on peut avoir les éléments qui soutiennent cela ?

**Comment by fredZen** [comment]
Un élément : `HS #8179`

**Comment by fredZen** [comment]
Pour ma part : 

:+1: pour aller vite avec des ids numériques, et faire mieux dans la foulée

**Comment by gregoirenovel** [comment]
Yes, mais justement on a que ce ticket là, non ? Qui représente donc une unique démarche, et un nombre indéterminé de problèmes. Ma crainte c'est qu'on bosse pour un cas particulier et pas un cas général.

**Comment by gregoirenovel** [comment]
Et pour "certaines personnes appellent mes agents par leurs prénoms", y'a des malpolis partout, ça m'embête que ça soit un problème qu'on considère. J'aimerais aussi bien savoir à quel points les problèmes rencontrés sont dus aux 21 jours de traitement des dossiers.

**Comment by gregoirenovel** [comment]
https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000031367321&cidTexte=LEGITEXT000031366350&dateTexte=20181026

**Comment by mmagn** [comment]
HS 8179

**Comment by kemenaran** [comment]
Pour ce que ça vaut, je suis contre afficher des numéros (`Instructeur 4`).

Si le problème est avéré, que ce n'est pas qu'une crainte (certes légitimes mais peut-être prématurée), et qu'on veut corriger rapidement (avant de séparer proprement Nom et Prénom), je préfèrerais une heuristique moche à base de `full_name.split(' ')[0] + full_name.split(' ')[1].chars.first`.

**Comment by kemenaran** [comment]
J'ai l'impression que le lien Légifrance posté par Grégoire est assez clair :

> Toute personne a le droit de connaître le prénom, le nom, la qualité et l'adresse administratives de l'agent chargé d'instruire sa demande ou de traiter l'affaire qui la concerne ; ces éléments figurent sur les correspondances qui lui sont adressées.

Est-ce que ça ne veut pas dire qu'on devrait fermer cette issue, faire une réponse-type aux personnes qui nous demandent l'anonymat des instructeurs (et au besoin voir comment mitiger les conséquences négatives réelles s'il y en a) ?

**Comment by fredZen** [comment]
Tu triches :-) Juste après ta citation, il y a aussi écrit 

> Si des motifs intéressant la sécurité publique ou la sécurité des personnes le justifient, l'anonymat de l'agent est respecté

Mais oui, ça dit clairement que l’option par défaut est de divulguer l’identité de l’agent instructeur.

Du coup je suis d’accord pour se concentrer sur ce cas par défaut. Cela veut dire aussi que si une démarche exige l’anonymat de l’agent instructeur, alors DS n’est pas l’outil adapté.

**Comment by kemenaran** [comment]
HS #33318 (démarche VTC)

**Comment by kemenaran** [comment]
Je pose aussi une ressource utile ici : une discussion sur l'équilibre des droits entre les usagers et les agents.

[Injures et menaces : Protection des agents par l’établissement](https://reponse-expert.hospimedia.fr/identification-des-agents-sur-leurs-blouses-2/)

**Comment by kemenaran** [comment]
Nouvelle demande du bureau des VTC.

Discussion :
- On va appeler le bureau des VTC pour en savoir plus
- @emsnytech regarde juridiquement où on en est
- Éventuellement mettre un feature-flag, mais avec pour l'activer quel engagement de la part de qui dans l'administration ?

**Comment by kemenaran** [comment]
Copie du message de @Keirua dans l'issue en doublon :

> - Ajout d'un feature-flag au niveau de la procédure qui remplace le mail/nom de l'instructeur par un identifiant.
> - La fonctionnalité sera activée sur demande depuis le manager, donc pas d'ajout à prévoir dans l'interface administrateur/instructeur à ce sujet

**Comment by Keirua** [comment]
Déployé hier.
Dispo avec le feature-flag `hide_instructeur_email` au niveau des procédures.
