### ISSUE TITLE
ETQ usager, le message qui apparait lors du dépôt dans le cas d'une procédure déclarative doit être changé

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#2748]
le texte qui apparait dit " Votre dossier est complet".... 

Hors dans le cas d'une démarche déclarative, il ne peut être dit que le dossier est complet, puisque pas instruit

Je proposerai de ne pas mettre cette phrase, qui porte à confusion ( et pas très légale)

**Comment by gregoirenovel** [comment]
Le support des démarches déclaratives est pour le moment très expérimental, il n'est pas facile détecter si une démarche est déclarative ou pas au moment de l'envoi des emails.

De plus, le contenu de cet email est déjà configurable par les administrateurs.

Je propose de fermer cette issue et de se reposer la question lorsque nous gérerons de manière plus officielle les démarches déclaratives.

**Comment by fredZen** [comment]
En effet, difficilement adressable par du logiciel en l'état actuel. Par contre, c'est peut-être un point d'attention à avoir à chaque fois que nous mettons en place une démarche déclarative : vérifier la formulation du mail.

**Comment by emsnytech** [comment]
Pb, c’est que j’ai fait cela sur la démarche drone qui est entré en prod hier, et qui réagit comme une précédère déclarative. J’ai décidé en effet de tester en live toute nouvelle procédure en prod. Il apparaît donc que le message qui apparaît à l’usager quand il arrive sur son bilan est trompeur, et porte un risque juridique fort. Il est donc souhaité que l’on puisse proposer une alternative.

**Comment by fredZen** [comment]
Philippe, tu viens de me faire penser à une solution simple.

Ce qu'on peut faire en Quick Win : au lieu de créer à la main, comme on le fait jusque là, le job de réception des dossiers pour une procédure déclarative, on peut empaqueter la création du job dans une tâche rake. Et cette même tâche pourra vérifier si la procédure a un mail personnalisé ou pas, et si ce n'est pas le cas (mail par défaut), elle pourra substituer un mail personnalisé pour les procédures déclaratives.

Ça me fait penser qu'il faut qu'on fasse une passe sur les procédures déclaratives existantes pour amender le mail et prévenir l'administratrice ou l'administrateut que désormais un mail sera envoyé à réception du dossier. Je veux bien m'en charger.

**Comment by emsnytech** [comment]
Expliques moi cela de vive voix demain ?
 J’ai constaté un bug ce matin. Les mêmes dossiers déposés sont dupliqués à la fois en construction, et en instruction...
Peut être l’activation du lien test.
Je vous fais une copie écran ...

Envoyé de mon iPhone
