### ISSUE TITLE
ETQ Administrateur je veux pouvoir créer des sous-titres de section

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#2779]
HS 7381

**Comment by gregoirenovel** [comment]
Ca va être gratuit avec les blocs de Simon :)

**Comment by emsnytech** [comment]
yes !

**Comment by kemenaran** [comment]
Pas chaud :

- Ça complexifie vachement le formulaire
- On devrait surtout avoir un layout clair qui rende ça inutile (ce qui n'est pas le cas aujourd'hui) #2227
- Y'a un workaround simple de mettre des champs "Explication"
