### ISSUE TITLE
ETQ admin je souhaite pouvoir créer des démarches dont l’instruction prendra plus de 36 mois

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#2782]
Enlever la limite de conservation des données sur DS à 36 mois Elle n'a plus de raisons d'être et elle est source d'inquiétude pour les administrateurs sur la pérennité de la plateforme.

`HS #9196`

**Comment by gregoirenovel** [comment]
@Benjamin-Doberset Tu peux nous donner des détails ? A priori on n'a pas été informés du point "Elle n'a plus de raisons d'être"

**Comment by Benjamin-Doberset** [comment]
J'en ai reparlé avec philippe. Depuis le RGPD notre déclaration CNIL ne sert plus à rien puisqu'on quitte le régime juridique du déclaratif

**Comment by Benjamin-Doberset** [comment]
Confirmation perica

**Comment by gregoirenovel** [comment]
Pour autant on continue à supprimer les données de chez nous à un moment donné, et si l'administrateur souhaite que ça soit plus tôt que tard selon les données demandé, ça me semble raisonnable de lui laisser le choix.

**Comment by emsnytech** [comment]
Le pb, c'est que l'on ne peut pas supprimer tant que l'on a pas donné la possibilité pour l'usager de récupérer son dossier, et comme pour lui, son interface, c'est son interface perso, il ne comprend pas pourquoi on supprimerait ses dossiers, après 1, 5 ou XX mois... Donc pour l'instant, on ne supprime rien. Si on veut le faire, en fait il faut garder une trace du dossier, une ligne dans son tableau de bord, avec par exemple le numéro de la démarche, la date de dépôt, la date d'acceptation bref des éléments de métadonnées... Tous cela n'est pas mûr... on crée un usage que la RGDP n'avait pas imaginé...

**Comment by gregoirenovel** [comment]
Oui et tout ce que tu dis on va le faire, et en attendant que ca le soit, je trouve ça bien de commencer à faire comprendre aux usagers que leurs dossiers ne seront pas gardés indéfiniment chez nous.

**Comment by fredZen** [comment]
La formulation actuelle de l’issue, « suppression de la durée limite de conservation des données », me semble trop radicale. Ça nous aide vraiment de savoir qu’on n’a plus besoin de garder certaines données et qu’on peut s’en débarrasser. Comme ça, on évite le plus possible de constituer un Gros Tas De Données Intéressantes :tm: pour les personnes malveillantes.

**Comment by fredZen** [comment]
Mais j’ai bien l’impression qu’il y a quelque chose à assouplir, par exemple pour les dossiers style urbanisme ou il y a des échanges au long cours (plus de 36 mois). C’est pour ça que j’ai mis le `hs` à communiquer.

**Comment by kemenaran** [comment]
+1 pour reformuler le titre de l'issue.
