### ISSUE TITLE
ETQ qu’instructeur (quand il y en a plusieurs) je souhaiterai que les point orange des dossiers ne soient supprimé que quand j’ai pris connaissance des modification

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#2807]
Peut être même garder la trace des prises de connaissances par les autres instructeurs

**Comment by gregoirenovel** [comment]
> je souhaiterai que les point orange des dossiers ne soient supprimé que quand j’ai pris connaissance des modification

C'est le cas. Le point ne s'enlève que lorsque tu te rends sur l'onglet en question. Donc soit il y a un bug, soit on ne parle pas de la meme chose, dans tous les cas, est-ce que tu peux donner plus de détails ou fermer cette issue ?

**Comment by fredZen** [comment]
Non, normalement c’est chacun son point, sinon c’est qu’il y a un bug.

**Comment by emsnytech** [comment]
Oui, vérifions en effet
