### ISSUE TITLE
ETQ instructeur je souhaite pouvoir signaler des dossiers sur lequel un traitement de ma part est attendu.

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#2808]

**Comment by emsnytech** [comment]
Retour utilisateur qui a de nombreux dossiers à instruire.

**Comment by gregoirenovel** [comment]
Je ne comprends pas trop : si tu traites au fil de l'eau, il ne reste dans tes dossiers suivis que les dossiers pour lesquels tu attends une action de l'usager, qui te sera alors signalée par une notification.

Tu peux préciser et donner plus de détails stp, en l'état c'est difficile de comprendre le besoin. Merci !

**Comment by emsnytech** [comment]
En fait, certains instructeurs ne traitent pas tout de suite ( les cadres qui travaillent le soir)
Ils voudraient marquer les dossiers qu’ils doivent revoir impérativement ( to do).
Cela me parait etre une bonne idée, qui peut en plus avoir un autre usage, filtrage personnel sur une case à cocher.

**Comment by gregoirenovel** [comment]
Ce système peut déjà se mettre en place via des annotations privées, et le filtrage fonctionnera dessus
