### ISSUE TITLE
ETQ instructeur je souhaite que les avis externes demandés ne puissent plus être modifiés une fois le dossier traité

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#2814]
@A.Ortega

**Comment by CamilleGarrigue** [comment]
@mmagn Pas d'accord pour restreindre les demandes d'avis. Parfois on demande des avis après pour consultation uniquement.

**Comment by emsnytech** [comment]
Je suis OK. Une fois traité, cet avis ne doit plus être modifiable.
De toutes les façons dès que l'on va mettre en place la conservation de l'ensemble des éléments d'un dossier à l'occasion de la décision , les avis seront aussi conservés dans le dossier.

**Comment by fredZen** [comment]
Voir aussi  #2595, #3400, #3401
