### ISSUE TITLE
ETQ Usager je veux que mes brouillons soient enregistrés automatiquement en arrière-plan

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#2859]
Aujourd'hui l'enregistrement du brouillon d'une demande est manuel : on a un bouton "Enregistrer le brouillon" et un bouton "Soumettre".

Mais régulièrement des utilisateurs remplissent leur dossier, mais ne cliquent pas sur "Soumettre". Le dossier reste en brouillon.

On devrait enregistrer automatiquement le brouillon en arrière-plan (avec une indication "Brouillon enregistré il y a 2 minutes"), et n'afficher qu'un seul bouton : "Déposer le dossier".

**NB**: ça nécessite probalement qu'on résolve d'abord le problème des utilisateurs qui créent un nouveau brouillon au lieu de retrouver le leur (#2860)

**Comment by kemenaran** [comment]
Y'a beaucoup d'exemples qui passent, que je vais essayer de noter ici.

Exemple : une personne usager qui a déposé 5 brouillon, mais n'en a soumis aucun – et s'étonne de ne pas recevoir de mail de confirmation. `HS #7857`

**Comment by gregoirenovel** [comment]
Je pense que ce problème est du en grande partie à l'absence de page de garde, j'aimerais bien avoir de la vraie data sur "régulièrement des utilisateurs remplissent leur dossier, mais ne cliquent pas sur "Soumettre"".

**Comment by kemenaran** [comment]
> Je pense que ce problème est du en grande partie à l'absence de page de garde

Le problème de création de brouillons multiples, oui – mais ça n'explique pas pourquoi les usagers ne cliquent pas sur le bouton "Soumettre", si ?

**Comment by gregoirenovel** [comment]
C'est ce que je dis ensuite dans mon commentaire précédent : j'aimerais bien qu'on me confirme avec de la donnée et pas des suppositions que les usagers ne cliquent pas sur "Soumettre".

**Comment by emsnytech** [comment]
Pour répondre à ta question @gregoirenovel , il faudrait regarder la manière dont en effet les usagers se comportent sur la page.
Mais l’idée de faire des enregistrements en tache de fond est bonne !

**Comment by gregoirenovel** [comment]
> Mais l’idée de faire des enregistrements en tache de fond est bonne !
J'aimerais qu'on fasse des tests pour confirmer cela, ma théorie est que les usagers, en particulier les plus éloignés du numérique, ne sont pas familiers de ce paradigme.

**Comment by Benjamin-Doberset** [comment]
Autre cas d'usage : si je veux enregistrer pour ne pas perdre mon travail je dois descendre tout en bas, ce qui n'est pas pratique pour les longs formulaires. Or ce sont eux qui nécessite des enregistrements réguliers pour ne pas perdre le travail effectué.

HS 19054

**Comment by kemenaran** [comment]
Pour limiter les conséquences des erreurs lors de l'envoi des pièces jointes (#4432), je vais partir là dessus.

**Comment by kemenaran** [comment]
J'ai un prototype qui fonctionne bien techniquement. C'est l'heure des mockups !

## Objectifs

- Ça Juste Marche™ (pas de boulot ou d'infos inutile)
- Le cas d'usage est clair et rassurant pour l'usager
- Reprise sur erreur autant que possible
- Si la reprise sur erreur n'est pas possible, informer l'usager clairement

Ça veut dire que j'ai jarté le bouton "Enregistrer le brouillon" manuel : la sauvegarde automatique est supposée fonctionner (et si elle échoue, on se dit que le bouton manuel ne fonctionnera pas mieux).

Après faudra voir si on arrive à faire un truc suffisamment fiable (et débogable) pour qu'on puisse se permettre le "Ça Juste Marche".

## Mockup

![wireframe](https://user-images.githubusercontent.com/179923/68383393-db38c480-0155-11ea-917e-b08c6af9b3a0.png)
Lien pour modifier le mockup : [https://wireframe.cc/OJjbbP](https://wireframe.cc/OJjbbP)

Vous en pensez quoi, du mockup ?

**Comment by Keirua** [comment]
Le mockup est très cool, c'est super clair. Bien joué !
Ma seule remarque serait en cas d'erreur d'enregistrement: "impossible d'enregistrer le brouillon", ça n'est pas hyper actionnable pour l'utilisateur.
J'imagine que:
 - ça n'arrive pas souvent (en theorie, on sait sauvegarder des dossiers sur DS)
 - de toutes façons, on ne pourra pas beaucoup aider plus l'utilisateur (erreur http, bdd, ça peut vite être compliqué)

On peut peut-être préciser, quand l'usager fait « Réessayer », que si ça échoue à nouveau il peut nous contacter ?
C'est une zone glissante vers laquelle on ne veut pas trop aller, donc on ne l'affiche pas tout de suite, et on ne laisse pas non plus les utilisateurs en plan sans solution.
On peut peut-être également compléter le message par `impossible d'enregistrer **les dernières** modifications. Une version à 13h43 a bien été enregistrée`

**Comment by benjaminhenkel** [comment]
Je préciserais peut être la fréquence avec laquelle le brouillon est enregistré, du type "Votre brouillon est enregistré automatiquement après chaque modification"

et que pensez-vous d'alterner les phrases  : "Enregistrement du brouillon en cours" puis "brouillon enregistré " avec le check vert ? 

j'ai l'impression que le check vert est trop subtile et on ne comprend pas bien ce que cela signifie en tant que tel

**Comment by kemenaran** [comment]
> Je préciserais peut être la fréquence avec laquelle le brouillon est enregistré, du type "Votre brouillon est enregistré automatiquement après chaque modification"

👍 

>  que pensez-vous d'alterner les phrases : "Enregistrement du brouillon en cours" puis "brouillon enregistré " avec le check vert ?

Mmm, j'hésite : l'enregistrement lui-même est très rapide – et j'ai l'impression que ça rajouterait du bruit cognitif pas forcément très utile.

> j'ai l'impression que le check vert est trop subtile et on ne comprend pas bien ce que cela signifie en tant que tel

C'est possible, oui. J'ai fait une petite animation pour renforcer l'effet ; je vous montrerai.

**Comment by kemenaran** [comment]
En attente de la suppression de Turbolinks (#5039)

**Comment by kemenaran** [comment]
Turbolinks supprimé. Maintenant je sens que j'aurais un peu besoin d'UX, pour virer la barre flottante – il parait qu'on a un UX pour ça.

**Comment by kemenaran** [comment]
La fonctionnalité est en ce moment activée pour 5% des utilisateurs de demarches-simplifiees.fr.

Ça a levé un petit bug (#5470).
