### ISSUE TITLE
ETQ admin, je souhaite pouvoir modifier les modèles de PJ téléchargeables par l'usager après la publication du formulaire

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#2863]
H.Beaudoin : "ces documents sont stockés sur notre site internet qui peut être modifié indépendamment de notre volonté. Ils ne sont alors plus téléchargeables par les usagers.." HS 5289

**Comment by tchak** [comment]
Je confirme, le ficher model est chez nous. Donc je comprend pas le problème.

**Comment by gregoirenovel** [comment]
C'est pour les anciennes PJ qu'il y avait ce comportement. Il faudrait donc fermer cette issue, activer les nouvelles à l'admin, et lui répondre. @CamilleGarrigue tu peux t'en charger ?

**Comment by Benjamin-Doberset** [comment]
a communiquer : corentine neppel ars

**Comment by kemenaran** [comment]
NOB : les SuperAdmin peut déjà faire ça dans le Manager.
