### ISSUE TITLE
ETQ Instructeur, je veux cliquer facilement sur une URL renseignée par un Usager

### ISSUE THREAD

**Issue by bzg** [betagouv/demarches-simplifiees.fr#2865]
Lorsqu'une URL apparaît dans un champ rempli par l'utilisateur, celle-ci n'est pas cliquable par défaut.

Feature request: rendre ces URLs cliquables.

Cas d'usage: les dossiers remplis pour les candidatures EIG, dans lesquels beaucoup de liens sont demandés (par exemple vers des comptes github) - il est fastidieux de devoir copier et coller ces liens dans les barres d'adresse pour les visiter.

**Comment by bzg** [comment]
Bonjour, est-ce qu'il y a de la visibilité sur la suite à donner à cette demande ?  Merci !

**Comment by kemenaran** [comment]
Merci pour le ping ! On a du mal à avoir de la bande-passante de dev sur énormément de choses en ce moment – et du coup les petits sujets facile comme ça sont un peu passé à la trappe (malgré leur utilité).

On devrait se libérer un peu d'ici 2-3 mois. Et sinon, si jamais toi ou quelqu'un d'autres avez moyen d'écrire un tout p'tit peu de code, on est preneur de contributions (ça ne devrait pas être très difficile, y'a sans doute un truc dans Rails pour auto-détecter les URLs et les rendre cliquables).

**Comment by bzg** [comment]
Hello, juste pour savoir où vous en êtes de la bande passante et si jamais cette issue peut remonter.  Ce n'est pas critique pour moi, je fais juste le suivi des issues que j'ouvre.  Merci :)

**Comment by bzg** [comment]
Merci !
