### ISSUE TITLE
ETQ Instructeur je souhaite que lorsque je veux classer par le champ date et heure, le classement s'effectue selon l'ordre calendaire

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#2884]
Lorsqu'on utilise le champ "date et heure", la date s'affiche selon le modele suivant : JJ/MM/AAA. S'il on classe par date, alors le classement s'effectue selon l'ordre des jours et non selon l'ordre calendaire (le 14/11/2018 se retrouve avant le 20 /10/2018). Ce problème n'apparait pas lorsqu'on utilise le champ date, la date s'affichant AAAA/MM/JJ.

**Comment by Benjamin-Doberset** [comment]
a communiquer HS 8008

**Comment by fredZen** [comment]
Ça ira tout seul une fois qu’on aura les champs typés #971
