### ISSUE TITLE
ETQ Instructeur, je veux accepter plusieurs dossiers d'un seul coup

### ISSUE THREAD

**Issue by chaibax** [betagouv/demarches-simplifiees.fr#2955]
Demande remontée par A. Felicite de normandie.gouv.fr .

Elle souhaiterait pouvoir sélectionner plusieurs dossiers (suite à un filtre par exemple) pour tous les accepter en une seule fois. 

Elle a 800 dossiers à accepter, c'est très pénible a faire.

Je pense qu'on peut étendre cette demande aux autres statuts (refus, etc)

**Comment by Benjamin-Doberset** [comment]
# 13536
a communiquer
