### ISSUE TITLE
ETQ Instructeur je veux connaître le temps moyen d'instruction indiqué aux Usagers

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#2971]
Aujourd'hui on indique le temps moyen de traitement (instruction et validation) aux Usagers – mais pas aux Instructeurs.

<img width="1280" alt="48208805-ebb43480-e373-11e8-9434-4238b04bf031" src="https://user-images.githubusercontent.com/179923/48209910-93cafd00-e376-11e8-849d-2b76c1e6eb68.png">

Ça génère des attentes de la part des Usagers – mais des attentes dont les Instructeurs n'ont pas connaissance. (#2970)

Par équité, on devrait aussi afficher ce chiffre aux Instructeurs.

**Comment by kemenaran** [comment]
Vous avez une idée de comment on pourrait implémenter ça ?

Un graphe d'évolution du temps ça serait cool – mais où le mettre dans l'interface ?

**Comment by gregoirenovel** [comment]
Dans la liste des démaches ?
