### ISSUE TITLE
ETQ instructeur, je veux que les champs des données du SIRET remontées par le champs SIRET soient accessibles pour personnaliser les mail, attestation, et export.

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#2977]

**Comment by emsnytech** [comment]
Face le nouveau champ SIRET, les données sont bien affiché dans les interfaces graphique, mais pas accessibles dans l'export, ni pour personnaliser les mails

**Comment by philemon95** [comment]
c'est à closer ça non?

**Comment by fredZen** [comment]
@philemon95 pas que je sache, qu’est-ce qui te fait dire ça ?

Par contre, pour les mails et attestations, ça doit maintenant être relativement facile à réaliser en overridant `tags_for_template` pour les types de champ SIRET.

**Comment by philemon95** [comment]
pour les mails et attestations, si la démarche est pour les personnes morales, tu as automatiquement les balises suivantes: 
--SIREN--
--numéro de TVA intracommunautaire-- 
--SIRET du siège social-- 
--raison sociale-- 
--adresse--

**Comment by fredZen** [comment]
Oui oui, mais cette issue parle de _champs_ SIRET, pas du SIRET utilisé pour s’identifier sur une démarche réservée aux personnes morales.

Le but serait précisément de monter le champ SIRET au même niveau de fonctionnalité que le SIRET en début de démarche.
