### ISSUE TITLE
API changement d'état du dossier

### ISSUE THREAD

**Issue by tchak** [betagouv/demarches-simplifiees.fr#3005]
J'ai investigué le problème. Notamment la question de l'assignation de l'instructeur. Aujourd'hui, on n'enregistre pas l'instructeur qui effectue une opération de changement d'état. Seulement lors du passage en instruction, l'instructeur est automatiquement ajouté dans les follows.

Voici ma proposition :

```http
PATCH /api/dossiers/:id/passer_en_instruction
{ "instructeur_email": String } ou { "instructeur_id": ID }

PATCH /api/dossiers/:id/repasser_en_construction

PATCH /api/dossiers/:id/accepter
{ "motivation": String }

PATCH /api/dossiers/:id/refuser
{ "motivation": String }

PATCH /api/dossiers/:id/classer_sans_suite
{ "motivation": String }
```

_Mots-clefs pour la recherche : API en écriture_

**Comment by tchak** [comment]
C'était l'histoire d'ouvrir la discussion. J'ai préféré proposer l'option la plus controversée pour voir ce que vous en pensez :) Après discussion avec @gregoirenovel dans l'issue #3007 je me dis que si on fait ça en REST ça sera plus simple de faire évoluer les states.

**Comment by tchak** [comment]
Donc deux propositions alternatives :

```http
PATCH /api/dossiers/:id
{ "state": DOSSIER_STATE_TYPE, "motivation": String, "instructeur_email": String }
```

ou

```http
PATCH /api/dossiers/:id/state
{ "state": DOSSIER_STATE_TYPE, "motivation": String, "instructeur_email": String }
```

**Comment by kemenaran** [comment]
J'aime bien la version "REST + un namespace particulier pour indiquer qu'on modifie l'état" :

```
PATCH /api/dossiers/:id/state
{ "state": DOSSIER_STATE_TYPE, "motivation": String, "instructeur_email": String }
```

Mais sinon tout me va :)

**Comment by tchak** [comment]
done (API GraphQL)
