### ISSUE TITLE
[RFC] API v2

### ISSUE THREAD

**Issue by tchak** [betagouv/demarches-simplifiees.fr#3007]
Je voudrais argumenter ici de la nécessité que je vois de passer à une API v2.

* Les noms utilisés dans l’API v1 ne correspondent plus aux noms métiers qu'on utilise aujourd'hui.
* Si l’on commence à proposer l’API v1 des acteurs avec un usage important je ne croie pas une seconde qu'on arrivera à les faire bouger avant des années de l'API v1 – d'où l'importance de ne pas tarder avec le chantier.
* L'implémentation actuelle est basée sur `ActiveModelSerializers` une gem qui n'est plus maintenu du tout. J'ai utilisé cette gem dans divers projets depuis plus de 7 ans. J'ai même essayé de contribuer. Rien ne s'arrange, personne n'est d'accord sur rien. Par conséquent, je considère important de bouger vers une autre solution de sérialisation.
* Opportunité de faire du nettoyage sur les modèles dépréciés (pj, carto).

**Comment by gregoirenovel** [comment]
Je suis d'accord mais pour moi ça serait mieux de finir le ménage interne, en particulier sur les états des démarches et dossiers, avant de s'atteler à ce chantier là, histoire de pas devoir trop changer cette API (sinon on peut dire qu'on fera alors une v3, mais ça fait de la couche de compat à rajouter)

**Comment by tchak** [comment]
Si l’on change les états des démarches ou dossiers, on va devoir faire de la compat sur l'API v1 de toute façon. Je préfère encore le gérer avec la nouvelle archie de sérialisation qui sera potentiellement plus souple.

**Comment by tchak** [comment]
* Nous avons beaucoup de demandes d'ajout sur l'API. Je trouve qu'il y a une meilleure opportunité de migrer nos usagers vers la nouvelle API suite à ces ajouts, plutôt que de leur faire miroité que l'API v1 est bien vivante et qu'ils peuvent investir dessus.

**Comment by gregoirenovel** [comment]
Je précise ma pensée : de manière générale, toutes ces demandes d'API dont tu parles me font assez peur car pour moi ça dilue la vision produit, point sur lequel je préfère qu'on prenne notre temps. Mais c'est mon avis personnel :)

**Comment by emsnytech** [comment]
Qu'elle est l'idée de changer les états d'un dossier. Evolution lourde de sens. A discuter avec les utilisateurs

**Comment by tchak** [comment]
API GraphQL est en prod
