### ISSUE TITLE
Elargir le périmètre des attribus de champs modifiables une fois un formulaire publié

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#305]
ETQ, je souhaite pouvoir modifier des éléments d'un formulaire publié ( attribue de champs par exemple)
- liste déroulante
- descriptif
- champ obligatoire
- changer des valeurs de menu déroulants
- ajouter des champs
- supprimer des champs
- modifier l'ordre des champs

**Comment by gregoirenovel** [comment]
À communiquer : 169

**Comment by gregoirenovel** [comment]
Related: #181

**Comment by gregoirenovel** [comment]
À communiquer : `#1170`

**Comment by LeSim** [comment]
À communiquer : `#1379`
