### ISSUE TITLE
ETQ invité à donner un avis, je souhaite joindre une PJ

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#306]

**Comment by benjaminhenkel** [comment]
Préfecture du Gard

**Comment by gregoirenovel** [comment]
À communiquer : Hauts de Seine Pôle Solidarités

**Comment by gregoirenovel** [comment]
À communiquer : `#1656`

**Comment by mmagn** [comment]
À communiquer : `#2606`

**Comment by guillaume-cellier** [comment]
Bonjour,
La communauté d'agglomération du Sicoval (31) est également demandeuse de cette fonctionnalité.
Merci de bien vouloir nous informer lorsque vous aurez de la visibilité sur une date de mise à disposition.
Cordialement,

**Comment by gregoirenovel** [comment]
`HS #2810`

**Comment by philemon95** [comment]
HS #12823

**Comment by Keirua** [comment]
On a ce problème aussi qui est énormément remonté, si vous êtes OK je le prends maintenant. C'est plus simple que #2631 , je pense qu'il faut simplement:

 - ajouter un champ PJ dans les avis externes
 - afficher la PJ à coté de l'avis

Vous voyez autre chose?

**Comment by chaibax** [comment]
A communiquer à roselyne.marini@herault.gouv.fr

**Comment by Keirua** [comment]
Du coup, ça donnerait ça:
![upload-pj-avis](https://user-images.githubusercontent.com/1223316/53810975-873b6780-3f58-11e9-9ba8-a2d8fa47bc79.png)

je mets uniquement la vision coté donneur d'avis: pour la vision "instructeur", enlevez mentalement le champ de message
