### ISSUE TITLE
Utiliser les données du formulaire d’inscription administrateur pour renseigner un service par défaut

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#3063]
Idée suggérée par @Benjamin-Doberset  : lors du processus d’enrôlement des administrateurs, on saisit une bonne partie des informations nécessaires pour créer un service. Quitte à étendre un poil le formulaire, on pourrait créer un premier service pour l’administrateur dès la création de son compte.

De plus, pour les administrateurs disposant d’un seul service, on pourrait automatiquement affecter celui-ci à toute procédure nouvellement créée. Ainsi, on réduit la friction dans le cas simple.

**Comment by chaibax** [comment]
Je ne pense que ce soit une bonne idée, car à ce stade, le futur administrateur ne sait pas a quoi va servir le service.
Il ne sait pas que ca va apparaitra en pieds de page de sa  démarche. Il pense que ces informations nous sont destinés a nous, et pas aux usagers. 

On peut le prévenir de tout ca, mais la on risque de faire peur et d'avoir un impact négatif sur les demandes de compte administrateur. 

C'est pour moi une fausse bonne idée :)
