### ISSUE TITLE
[RFC] Brander les emails transactionnels moins avec "DS", et plus avec la démarche

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#3064]
Le template des emails est très brandé "demarches-simplifiees.fr". Il y a un énorme logo / bandeau en haut de l'email, l'adresse d'envoi qui apparaît dans la liste est "contact@demarches-simplifiees.fr", c'est assez visible. (cf. #3054)

En tant qu'Usager, quand je reçoit un email transactionnel, je suis intéressé par l'avancement de ma démarche (ou de mes démarches). Aujourd'hui on mentionne vaguement la démarche dans le corps du mail – mais rien dans le titre, rien dans le branding.

Si DS est "Le typeform de l'administration", pour l'Usager on doit **centrer sur la démarche, pas sur l'outil**. On devrait donc mettre plus en avant le titre et le logo de la démarche dans les emails transactionnels – et moins le logo de DS.

Vous en pensez quoi ?

**Comment by chaibax** [comment]
Tout a fait d'accord. 

Actuellement, l'usager ne fait absolument pas la différence entre nous (DS), et l'administration qui utilise DS. C'est dommage. 

On fait de l'auto promo pour DS au prêt des usager dans nos email (et pas que...), ca n'a aucun intérêt, si ce n'est leur faire croire que c'est nous qui traitons les demandes.

**Comment by gregoirenovel** [comment]
> Si DS est "Le typeform de l'administration"

1. Si on pouvait arreter de parler de Typeform, en particulier parce que c'est assez réducteur étant donné que ça occulte complètement la partie instruction qu'on apporte, ça serait cool :)

2. Je suis assez contre cette proposition, car ça introduit je trouve pas mal de confusion. L'email expéditrice est la notre, le dossier est sur notre plateforme, je trouve que c'est créer du flou que de commencer à mélanger les choses. J'aime bien le fait que notre nom soit en gros, que l'usager sache que ça correspond au dossier qu'il a déposé *chez nous*, et que s'il veut le voir il doit aller *sur notre site et pas sur celui de l'administration*. Quand tu reçois un DM sur Twitter, la notif par mail que tu reçois est brandé de partout avec Twittter. Faire le contraire, c'est assumer de faire de la marque blanche, chose qu'on a pour le moment, en tout cas il me semble, pas décidé de faire (et qui ouvre donc la porte à de la personnalisation plus poussée).

3. Par contre, je suis assez partant pour aller dans l'autre sens et bien faire comprendre à l'usager que nous sommes une plateforme qui héberge, comme Twitter ou YouTube.

**Comment by gregoirenovel** [comment]
On peut tout à fait comparer à YouTube. Un service / organisme sur DS c'est comme une chaine qui publie des vidéos, les usagers sont des gens qui comment / likent / intéragissent avec cette vidéo. La personne qui publie a bien un espace de marque disponible (logo, image de cover, etc.), mais tu comprends bien que t'es en permanence sur YouTube.

> En cliquant sur notre logo depuis un email et en arrivant sur notre home, on perd l'usager et on ne lui rend vraiment pas service.

Bah potentiellement si car ça lui permet facilement d'accéder à son espace et de retrouver son dossier ; tout en lui faisant comprendre que DS est la plateforme qui *héberge* des démarches dont celle qu'il a rempli.

**Comment by philemon95** [comment]
suite à une remarque de @mmagn hier, il est vrai que nos mails "de notification", ne fassent plus état de démarches-simplifiées. Actuellement, ils contiennent le logo beta.gouv et le logo DS, et sont signés par l'Equipe démarches-simplfiées, ce qui est une énorme source de confusion pour les usagers (qui ont souvent tendance à y répondre directement).

Propositions:

supprimer nos logos, et mettre ceux du service en charge de la démarche

idem pour la signature (mettre le nom du service)

au passage peut-être ajouter leur numéro de téléphone (on a une réunion avec @Benjamin-Doberset & @emsnytech pour clarifier ça sur les mentions légales d'un AR)

mettre une adresse no-reply (qui transfère sur contact, mais qui permettrait peut-être d'éviter que les gens y répondent) et mettre un lien vers le formulaire de contact
