### ISSUE TITLE
ETQ Administrateur je veux qu'on m'indique de privilégier les formats standards sur les guides de démarches

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#3066]
ex pas de format qui nécessite l'installation de soft (ex, .docx, .odt)
HS 8822

**Comment by gregoirenovel** [comment]
On veut pas forcer le PDF ? Comme ça fin de l'histoire ?

**Comment by kemenaran** [comment]
J'avoue, c'est radical, mais peut-être dix fois plus simple.

**Comment by mmagn** [comment]
Oui on peut.
