### ISSUE TITLE
ETQ Usager je veux avoir un moyen efficace de retrouver une demarche sur DS

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#3074]
Avec @kemenaran on a parlé de ces cas (nombreux) où les usagers arrivent sur DS et ne trouvent pas leur démarche. L'explication la plus fréquente est "On m'a dit d'aller sur demarches-simplifiees".

Globalement si tu cherche une démarche sur DS et que t'a pas cliqué sur un lien (dans un email ou sur un site) t'es mort, tu vas galérer pour la trouver et même nous on aura du mal à t'aider. On a beau éduquer les administrations ou mettre en place un annuaire des démarches, la croissance continuant on va avoir de plus en plus de cas comme ça.

Du coup on réfléchissait à un moyen qui permettrait de résoudre 90% de ces cas d'usager perdus.
On a pensé à une solution, qui serait simple a comprendre et à partager (par téléphone, par oral à un guichet, sur un site, dans le magasine de la commune, etc.), plutôt que de continuer à publier une démarche avec un `lien_demarche`, on créé pour chaque démarche un **code de démarche** un truc genre XRU98 ou DRIEA-PER75 (enfin si on veut bien faire les choses on les génère sans caractères ambigus). C'est moche oui mais c'est très clair.

Tu cherches une démarche sur DS ? Dès la home on te demande ton **code démarche**, et si tu ne l'as pas tu SAIS que tu dois le demander à la personne qui t'a dit "Allez sur demarches-simplifiees". 
Comme ça plus personne ne devra souffrir en cherchant dans l'annuaire la démarche qu'il souhaite, ou en se faisant épeler par téléphone un lien http.
On garde bien sur la fonctionnalité qui permet d'avoir un lien qui mène directement à la démarche...

WDYT ?

**Comment by gregoirenovel** [comment]
Je trouve ça très compliqué. Je préfererais qu'on fasse du travail d'édition sur les démarches et qu'on puisse facilement retrouver une démarche avec liste bien organisée + moteur de recherche. Le code c'est une fausse bonne idée :
- c'est compliqué
- c'est dur à mémoriser
- c'est un truc de plus à transmettre
- tu peux te planter quand tu rentres le code, c'est relou
- je vois pas pourquoi quelqu'un qui dit aujourd'hui "va sur DS" au lieu de "va sur commencer/" dirait demain "va sur DS avec le code XXX"
- je vois pas d'ailleurs pourquoi cette personne connaitrait ce code

J'ai l'impression qu'on complexifie les choses faute de faire le travail de ménage qui nous incombe, à savoir l'édition des démarches et l'éducation des administrateurs.

**Comment by mmagn** [comment]
> c'est compliqué

par rapport au lien /commencer ? on aurait toujours un lien qui garderait la simplicité d'aujourd'hui. Et je parle d'un code de 6-7 caractères. Je trouve ça au contraire plutôt simple, il y a un truc similaire sur amendes.gouv.fr quand tu arrives sur leur home tu sais exactement ce que tu dois faire : trouver le numéro de télépaiement. J'imaginai un truc avec le même degré de complexité.
 
> c'est dur à mémoriser

personne ne mémorise les liens /commencer, le but n'est pas de le mémoriser, c'est de le noter si t'es au téléphone ou à l'oral, ou de l'avoir sur un prospectus que tu as pris au guichet. 

> c'est un truc de plus à transmettre

par rapport à aujourd'hui cela ne changerait rien (toujours le lien), c'est juste que cela permettrait en plus de le communiquer par d'autres canaux (papier et téléphone)

> tu peux te planter quand tu rentres le code, c'est relou

tu peux aussi te planter quand tu cherches dans l'annuaire ou si tu recopie un lien /commencer

> je vois pas pourquoi quelqu'un qui dit aujourd'hui "va sur DS" au lieu de "va sur commencer/" dirait demain "va sur DS avec le code XXX"

l'idée c'est que l'usager qui arrive sur DS et qui voit qu'on lui demande direct un "code démarche", va rappeler la personne qui lui a dit "va sur DS" pour avoir son code démarche. Aujourd'hui on ne demande rien d'explicite, on dit "tu peux chercher dans l'annuaire et sinon envoie nous un email"

> je vois pas d'ailleurs pourquoi cette personne connaitrait ce code

au bout de la troisième fois qu'un usager l'appelera en lui disant "vous ne m'avez pas donné le code démarche qu'on me demande" elle le connaitra. pareil pour le lien actuel, c'est juste qu'il est galère à communiquer oralement. mais je pense que la symbolique du "code démarche" est plus forte, que celle d'un "lien".

> Rappel : on s'appelle demarches-simplifiees.fr

J'ai fait exprès pour rendre la conversation plus crédible... :)


Globalement je ne pense pas qu'on arrivera avec le nombre que l'on est à croitre en démarches et en même temps nettoyer l'annuaire, donc je cherche des solutions alternatives...

**Comment by gregoirenovel** [comment]
J'entends bien que c'est une solution par défaut (de gens, de temps, d'argent), j'aimerais (mais je rêve peut-être) qu'on puisse consacrer notre temps à trouver des solutions à la source de nos problèmes plutôt qu'à des solutions qui, pour moi, semblent plus être des rustines. En terme d'expérience, je persiste à trouver ça assez pauvre.

Si on a pas mieux, je m'incline volontiers hein, c'est juste que quelque part ce code, c'est quoi si ce n'est la partie après "commencer" ? Pourquoi on ne fait pas de la review de ce slug ? Qu'on ne force pas les admins à en mettre des simples (du genre inscription-permis-94), et qu'au final, entre demander ton "code" ou "l'URL", ben ça revient au meme car dans les deux cas on te donnera `inscription-permis-94`, ce qui est simple et mémorisable.

**Comment by mmagn** [comment]
> En terme d'expérience, je persiste à trouver ça assez pauvre.

Oui c'est clair, mais parfois les trucs les plus simples sont les meilleurs (je ne dis pas que cette solution est la meilleure, elle mériterait d'être testée).

> Pourquoi on ne fait pas de la review de ce slug

La review sur les demarches c'est compliqué on en a l'exemple avec celle sur les champs suspects, ou sur les comptes admin aux adresses exotiques.

> J'ai la sensation qu'on réinvente un truc qui existe déjà de manière différente.

Oui c'est vrai qu'en changeant un peu les contraintes du slug on pourrait arriver à un truc similaire. Après cela impliquerait aussi le changement sur la home pour amener l'usager dans cette voie à sens unique : "tu veux remplir une démarche et tu n'as pas le lien" >> "quel est son code".

L'idée n'est pas de se lancer maintenant mais d'ouvrir la discussion. On est pas encore sous l'eau, on verra où l'on sera dans 4-6 mois et si c'est toujours un problème.

**Comment by kemenaran** [comment]
Une autre piste de réflexion (pareil, comme réflexion lancée pour plus tard) qu'on avait évoquée en discutant avec les gens de service-public.fr, c'était de pouvoir associer un "périmètre d'application" à une démarche.

Le périmètre, ça serait les gens pour qui cette démarche est pertinente : arrondissement(s), communes(s), département(s), région(s), etc.

Avec ça, on pourrait améliorer considérablement et facilement le moteur de recherche des démarches :

1. Indiquez votre code postal ;
2. Tapez un ou plusieurs mots clefs pour live-chercher une démarche.

Et on ne montre que les démarches du bon périmètre.

Ça suppose de faire confiance aux usagers pour identifier eux-même la bonne démarche. Donc qu'iels soient en capacité de faire la différence entre "Dépôt de stage 2018" et "Dépôt de stage 2019", entre "Demande d'inscription en candidat libre" et "Demande de renouvellement de NEPH". Mais ça me semble raisonnable : j'ai l'impression qu'iels sont déjà plus capables de faire ça aujourd'hui qu'on ne croit.

Et aussi ça autonomise les gens. Les usagers ont une liste à parcourir, à creuser au besoin ; sans devoir être dépendant du code administratif qu'il faut aller pêcher auprès de l'administration.

**Comment by gregoirenovel** [comment]
Ça ça fait partie d'une des pistes explorées avec Clémence, et ça nécessite un travail de classification des Services de notre côté, ainsi que de "taggage" des démarches.
