### ISSUE TITLE
ETQ Instructeur je veux avoir la trace de toutes les modifications du dossier

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#3087]
Qui a modifié quel champ, quand.
Utile notamment pour les modifications d'annotations privées entre plusieurs instructeurs.
HS 9357

**Comment by tchak** [comment]
ça tombe bien, nous avons un `DossierOperationLog` maintenant :) Il suffit d'ajouter des operations.

**Comment by mmagn** [comment]
Yes

**Comment by gregoirenovel** [comment]
On a vraiment envie de faire ça ? Quid de la confiance ?

**Comment by mmagn** [comment]
Je ne pense pas que ce soit un problème de confiance, s'il y a un problème on a les logs serveurs.
Mais je comprends le besoin d'un point de vue pratique, je suis content par exemple quand j'arrive sur un gdoc partagé de pouvoir consulter l'historique de modifications.
