### ISSUE TITLE
En tant qu’expert, je veux pouvoir ajouter des colonnes personnalisées à ma liste de dossiers

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#3108]
`HS # 9290`

Note : Ce n’est pas aussi évident à faire qu’il n’y parait, car un expert peut être invité sur plusieurs démarches différentes, qui n’ont pas forcément les mêmes colonnes.

**Comment by emsnytech** [comment]
mais cela reste une bonne idée...
Il faudrait tendre en fait vers une présentation de même type pour l'expert et l'instructeur ( ils sont souvent les eux).
On pourrait même se pose la question pour les usagers.
Plus on sera standard et générique, mieux se sera.
