### ISSUE TITLE
ETQ Usager je veux choisir sur un agenda la date dans un champs date

### ISSUE THREAD

**Issue by chaibax** [betagouv/demarches-simplifiees.fr#3115]
HS 9058 

_Lorsque je créé dans un formulaire un champ "date et heure", je peux choisir ma date directement en cliquant sur les jours et les mois.
Par contre, si je créé un champ "date" uniquement, je dois saisir la date au format JJ/MM/AAAA avec le clavier.
Est-il possible d'avoir le même mode de saisie pour ce champ que pour le champ "date et heure" ?_

**Comment by gregoirenovel** [comment]
Je crois qu'on l'avait fait à une époque puis enlevé, car selon les navigateurs, c'est parfois long et chiant de trouver une date loin dans le passé (la décrémentation des années se fait une par une, donc c'est assez rébarbatif).

Je propose donc de s'assurer que ce cas est bien géré de manière acceptable par tous les navigateurs, et de fermer sinon.

**Comment by kemenaran** [comment]
Pour info, on doit pouvoir tester facilement les vieux navigateurs (y compris Safari Mobile) sur Browserstack.

**Comment by gregoirenovel** [comment]
Cf. aussi #304

**Comment by gregoirenovel** [comment]
> Le menu déroulant permettant d'indiquer une date de naissance est peu fonctionnel, nous sommes obligés de faire dérouler ( à un rythme assez lent) les jours, mois ou nombreuses années avant de trouver le choix qui nous concerne, particulièrement pour les années de naissance qui démarrent systématiquement à 2018 ...c'est long est fastidieux pour retrouver l'année de naissance d'un adulte.

HS 7269
