### ISSUE TITLE
Créer une nouvelle URL pour l'API qui permette de ne récupérer que les metadata d'un dossier

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#313]
Objectif : ne pas avoir à récuperer l'intégralité d'un dossier, juste les infos de base (afin de savoir si on a besoin de charger plus d'infos ou non, par exmple)

Qu'entend-t'on par metadata : [cf. wiki](https://github.com/sgmap/tps/wiki/Ordre-des-donn%C3%A9es-d%27un-dossier)

**Comment by emsnytech** [comment]
Excellente idée. Refaire le point avec France arrimer sur ce qu'ils ont rencontré comme difficultés pour faire leur back office, et ce qu'ils auraient aimé trouvé.

**Comment by tchak** [comment]
done with GraphQL
