### ISSUE TITLE
En tant qu’administrateur je veux être guidé dans mon choix de mot de passe

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#3134]
Aujourd’hui, les administrateurs partent de leur mot de passe favori et essaient de le bricoler en rajoutant quelques caractères, mais ça ne suffit pas à le rendre sécurisé. Une personne a fini par mettre la clef wifi de sa box.

**Comment by kemenaran** [comment]
On soupçonne aussi que ça diminue la conversion, non ?

**Comment by chaibax** [comment]
Oui, le nombre de nouveaux admins qui passent cette étape est de plus en plus faible (70% seulement )
