### ISSUE TITLE
ETQ instructeur, je ne veux pas perdre un brouillon de message si je change d'onglet sur un dossier

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#3135]
HS 7091

> dans la messagerie, si on commence un message et quitte pour consulter
la demande par exemple, le message est à recommencer

**Comment by kemenaran** [comment]
Ah oui, carrément.

Normalement ça se fait assez bien avec en stockant le brouillon dans le localStorage.

**Comment by gregoirenovel** [comment]
Plus ça va plus en fait faut faire une SPA pour la partie Instructeur...

**Comment by kemenaran** [comment]
_Not sure if trolling or serious_ 🤔

**Comment by gregoirenovel** [comment]
Carrément sérieux. Là on va bidouiller des trucs à la con qui vont être complexes pour bien gérer les edge cases, ça me prend déjà la tête, et on s'était déjà posé la question pour d'autres sujets comme :
- parcours du tableau de dossier avec des boutons next/previous
- pas perdre des données lors du changement d'état d'un dossier, cf. #2425

**Comment by gregoirenovel** [comment]
Je suppose que @tchak sera également de mon avis, cf. https://twitter.com/tchak13/status/1070611677752758274

**Comment by kemenaran** [comment]
Ok, merci pour la clarification.

Pour ma part je continue à être sceptique sur les avantages des SPA _à temps-de-développement constant_ (j'ai l'impression que ça peut permettre de faire qqc de plus peaufiné qu'une appli web classique, mais que ça demandera toujours plus de travail). Mais c'est un vaste débat :)

Cela dit, dans ce cas concret, j'ai l'impression qu'on peut résoudre facilement la question en quelques lignes de JS. Et ça permettra aussi de résoudre le même problème qui existe dans la partie Usager :)

**Comment by tchak** [comment]
On peut faire de l'auto-save de brouillon du message comme GitHub

**Comment by kemenaran** [comment]
Oui, tout à fait.

Je me dis juste qu'on est pas obligé de faire l'auto-save côté serveur : le localStorage devrait largement suffire, non ?

**Comment by chaibax** [comment]
A communiquer : maryse.chicoisne@indre-et-loire.gouv.fr
