### ISSUE TITLE
ETQ admin, je veux savoir quelle adresse internet je peux mettre dans la description d'une démarche

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#3198]
Afin d'avoir une meilleur visibilité de la page internet sur laquelle devrait être mis le lien vers la démarches, je propose de renommer "Lien site internet" "lien vers la page du site internet sur laquelle le lien vers la démarche est publié"

**Comment by chaibax** [comment]
Comme ca ? 

![capture d ecran 2018-12-20 09 57 58](https://user-images.githubusercontent.com/3593868/50274530-ccfa9080-043d-11e9-906d-145a0e2386cd.png)

**Comment by chaibax** [comment]
Je propose : 

_Adresse internet de la page où la démarche est (ou sera) disponible au prêt des usagers._ 

En plus petit en bas : 
_Ex : http//www.monsite.com/mademache. 
Vous pouvez laisser vide si vous ne connaissez pas encore cette adresse ou s'il s'agit d'un test._

**Comment by gregoirenovel** [comment]
Je ne comprends pas trop vos deux propositions, je tente ma chance :
> Page de présentation de la démarche sur votre site
