### ISSUE TITLE
Problèmes avec les liens dans les mails envoyés par sendinblue

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#3216]
Ce n’est pas vraiment l’endroit pour ça, mais faute de mieux j’ouvre une issue ici pour qu’on n’oublie pas.

`HS #10221`

deux problèmes

- pour une raison que j’ignore, quand le destinataire a cliqué sur `http://r.email.demarches-simplifiees.fr/xxxyyyzz` , il s’est retrouvé sur `https://r.email.demarches-simplifiees.fr/xxxyyyzz`, qui ne répond pas avec le bon certificat
- quelque chose a transformé en majuscules le lien vers la démarche, ce qui fait qu’elle ne marche pas : `HTTP://WWW.DEMARCHES-SIMPLIFIEES.FR/COMMENCER/ENQUETEOPENLAB` . Peut-être une traduction automatique de html vers texte qui a tenté de produire un équivalent visuel de texte en gras

**Comment by fredZen** [comment]
@chaibax tu pourras peut-être jeter un coup d’œil ?

**Comment by chaibax** [comment]
Pour le 1er point, j'avais remarqué ça avec @Benjamin-Doberset au moment de valider l'envoi. On a quand même envoyé, car le souci était uniquement sur Firefox. On a rajouté le lien en texte en dessous. 

Par ailleurs, j'ai pris un certificat SSL hier pour email.demarches-simplifiees.fr . Après quelques soucis, il est maintenant en place.  J'ai fait un essai, et effectivement, je n'a plus de soucis avec de certificat/sécu. 

Problème réglé.

Pour ce qui est de l'uppercase, je ne sais pas ce qui a pu se passer. Dans le source du message (html et txt), j'ai l'url en minuscule...

<img width="1133" alt="capture d ecran 2018-12-27 14 46 42" src="https://user-images.githubusercontent.com/3593868/50482338-4ff38c00-09e6-11e9-8989-7149f654b432.png">


Je ne pense pas que ca vienne de chez nous...  Je te laisse fermer le ticket @fredZen :)
