### ISSUE TITLE
ETQ admin je veux voir clairement un lien commencer vers ma démarche en brouillon 

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#3226]
En l'état on est obligé d'aller dans description, de copier et coller à la fois la racine et le contenu du champ slug

**Comment by emsnytech** [comment]
Oui, vu en prio.
Mettre un bouton pour copier aussi bien l’adresse de test, comme après celle de prod dans l’onglet publication paraît une bonne reponse

**Comment by n-b** [comment]
C’est déjà réglé, le lien est disponible en entier dans la description: 
<img width="993" alt="image" src="https://user-images.githubusercontent.com/139391/65021604-c008c000-d92f-11e9-8f90-2935c024a95e.png">
