### ISSUE TITLE
Quid du non-affichage des "explications" sur les demandes

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#3239]
Quand un instructeur ou un usager visualiste une demande, on ne montre pas les "explications" ajoutées par l'administrateur.

D'après mon investigation, la raison pour cette décision était à la base pour ne pas les montrer était que dans cette vue, alors uniquement utilisée dans l'interface instructeur, afficher les explications, destinées aux usagers, rajoutait du bruit inutile.

Depuis, cette vue est également réutilisée pour l'interface usager, ces derniers ne voient donc pas non plus les explications.

Sur la non-visibilité par les usagers : je ne suis pas certain que ça soit une bonne idée. J'aime bien le côté "contextuel" du comportement actuel (on ne montre les explications que quand on en a besoin = quand on rempli le formulaire), cela dit, je me demande s'il n'y a pas des effets indésirables : est-ce que montrer ces explications tout le temps ne permettrait pas de se rendre compte d'une erreur à relecture d'un dossier déposé ? Ou de mieux comprendre un message d'un instructeur (car on aurait alors le contexte complet) ? Car là pour retourner dans le contexte original de remplissage de la démarche (avec explications, donc), on est obliger de cliquer sur "Modifier", et rien ne laisse penser avant de cliquer sur ce bouton que la vue formulaire sera plus riche que la vue Demande.

Sur la non-visibilité par les instructeurs : un peu la même réflexion, est-ce que leur donner le contexte complet (avec les explications, donc), ne leur permettrait pas parfois de comprendre pourquoi un usager à rempli un champ d'une manière ou d'une autre ? En fait les instructeurs, à moins de cliquer sur le lien commencer (qu'ils n'ont pas forcément, et qui sera quand même un moyen détourner pour atteindre le but qui va suivre), ne voient jamais le formulaire complet tel que l'usager le voit.

**Comment by kemenaran** [comment]
Je m'étais demandé quand un Instructeur voulait voir les explications dans le print.

Mais en fait c'est parce qu'iel mettait des titres de section dans les explications…

Personnellement, entre :

1. Afficher les explications pour être complet,
2. Masquer les explications pour faire moins de bruit,

J'ai l'impression que la plupart du temps ça fera surtout du bruit. Je préfère laisser en l'état.
