### ISSUE TITLE
ETQ qu'administrateur, je souhaite que les démarches nationales soient reprises automatiquement dans nos-démarches.gouv.fr et sur services-publics.fr

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#3244]
L'affichage des démarches nationales dans nos démarches et sur service-public doit permettre de déployer l'information sur les démarches publiées sur démarches-simplifiees. Piste. 
Proposition;
Ouvrir une API sur les démarches publiées.
Demander dans l'interface au moment de la publication si l'administrateur local souhaite que sa démarche soit publiées sur internet (certaines ne seront pas publiées ( internes ...)
Nous pourrons donc largement diffuser cette API
A prioriser pour les 3 prochains mois !

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/78051/referencer-automatiquement-les-demarches-nationales-sur-servicespublicfr
