### ISSUE TITLE
ETQ Usager, je souhaite pouvoir télécharger l'ensemble de mon dossier en PDF au passage en instruction et à la décision

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#3245]
Afin de donner plus de valeur juridique aux différentes étapes d'un dossier, il est souhaitable de proposer un récépissé du dossier, sur le modèle ci joint, et contenant pour ce qui est de DS, une vue PDF du contenu des champs saisis.
Il serait joint à chaque mail que nous éditons.
Cette approche prépare l'étape d'après qui est l'archivage légal des dossiers.

Exemple de ce que propose un concurrent
[Récépissé 2018-00089173 - 2018-12-29.pdf](https://github.com/betagouv/tps/files/2716438/Recepisse.2018-00089173.-.2018-12-29.pdf)

**Comment by emsnytech** [comment]
Et voici un message HS qui vient confirmer le besoin! 
# 10381

**Comment by Benjamin-Doberset** [comment]
a communiquer : DGITM

**Comment by Benjamin-Doberset** [comment]
Vu avec philippe : l'objectif est que l'usager puisse avoir un document récapitulant l'ensemble de son dossier aux étapes importantes de sa démarche. On peut donc proposer sur la plateforme la création d'un doc pdf téléchargeable au passage en instruction puis un nouveau lors de la décision . ce document reprendrai la demande de l'usager, les pjs et la messagerie. Il serait non modifable

**Comment by Benjamin-Doberset** [comment]
a communiquer : # 15283

**Comment by Keirua** [comment]
première étape: sortir un pdf à partir d'une procédure

nuance importante: il faut générer 2 exports: un pour l'utilisateur, et un pour l'administration, qui peuvent inclure en plus les annotations privées, les avis d'experts, des données sur les entreprises…

plusieurs possibilités ensuite:
 - on peut fournir un zip avec le dossier «normalisé», et toutes les PJs à coté
 - on peut fournit un pdf avec toutes les pj dans le pdf
 - on peut envoyer ce compte rendu des dossiers du mois ou de l'année, en envoyant régulièrement un mail aux administrations pour leur dire de télécharger avant suppression chez nous
 - export via API où les administrations vont chercher les dossiers eux-même


3 moments importants pour le dossier:
 - au dépot, une trace du dossier déposé
 - à la décision: on peut fournir une attestation, mais aussi le dossier qui a servi à faire le dépot
 - à la suppression

**Comment by benjaminhenkel** [comment]
a communiquer # 25648

**Comment by Keirua** [comment]
J'ai un peu avancé sur l'export PDF et du coup, j'aimerais préciser le périmètre. Il y a plusieurs manières de voir ce sujet. Ça vaut le coup de discuter des différentes possibilités.

 - inclure les PJs à la fin du pdf est-il nécessaire ? C'est l'idée de départ mais c'est pas simple. On peut pour les images, mais c'est moche sur les grosses images (ex: plans illisibles), ça alourdit le pdf, et je ne sais pas quoi faire de plein de formats qu'on pourra trouver (zip, exe, txt, doc, xls, ods, mp3…)? Par ailleurs, pengfei me disait que l'armée attend cet export pdf pour l'inclure dans l'archive zip du dossier, avec les PJs dans un répertoire dédié
 - on va jusqu'à inclure quoi dans cet export ?
   - le contenu des champs, ok
   - les annotations privées pour les instructeurs ? (donc prévoir un second export?)
   - les messages entre ?
   - les décisions des invités ?
   - la décision finale ?
 - je ne sais pas quoi faire des champs carte; je ne sais pas comment on peut récupérer la carte sous forme d'image, et sortir les zones sélectionnées et stockées en géojson me parait abérrant

En l'état j'ai 2 types de sorties:
 - le stockage de l'export dans le dossier (via un has_one_attached :export_pdf). Le but étant de supprimer de la donnée, il faut peut-être plutôt une table `archive` avec simplement id du dossier, et l'export
 - le rendu comme une vue, généré à la volée (en modifiant DossierController#show, etq usager et/ou instructeur, pour gérer la sortie pdf à la volée avec les infos spécifiques) 

Du coup, quand générer cet export ?
 - peut-on systématiquement fournir la sortie "vue pdf", générée à la volée, à l'utilisateur et à l'instructeur ? J'ai l'impression que ca intéresse du monde pour l'archivage interne (ex: des prefectures rencontrées récemment)
 - peut-on générer le pdf «instructeur» au moment de l'archivage du dossier, et se dire que c'est lui qu'on garde et qu'on fournit ? Si non, à quel moment ?

**Comment by Keirua** [comment]
Conclusion de l'échange avec Simon:

 - dans une v0, pas de stockage: on génère les informations à la volée lorsque l'utilisateur demande. on verra dans un second temps pour l'archivage à différents moments
 - bien prévoir 2 sorties, usager et instructeur, avec:
   - pour l'usager: son dossier, les échanges, la décision éventuelle
   - pour l'instructeur: pareil, + les annotations privées et les décisions invitées 
 - carte: on met le geojson, c'est moche mais on fera mieux plus tard
 - inclure les pjs est en effet trop complexe, il est plus simple de les stocker à part
 - cette fonctionnalité est attendue par https://github.com/betagouv/demarches-simplifiees.fr/issues/4074 qui pourra joindre le pdf et les pièces dans une archive zip
