### ISSUE TITLE
ETQ instructeur, je voudrais que le contenu des champs à l’export excel soit en français

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#3264]
Ex : accepte ( plutôt que closed...) ...

**Comment by kemenaran** [comment]
Ça me semble possible – mais je pense que ça casserait les scripts des gens qui se basent sur le format existant. Je ne sais pas trop comment faire ça de façon simple, du coup.

**Comment by tchak** [comment]
Il y a plusieurs choses dans les exports qui mériteraient d'être changées. On peut imaginer de versionner et de faire un rollout progressif. Genre afficher une popup - "voulez-vous activer le nouveau format d'export ?"

**Comment by kemenaran** [comment]
On a fait un export v2 qui corrige tout ça.
