### ISSUE TITLE
Ergo : ETQ usager, pourquoi je dois cliquer sur « modifier » plutôt que de pouvoir modifier directement mon dossier ?

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#3278]
`HS #10731`

L’usager ou usagère a vu les champs non éditables, n’a pas été chercher le bouton _modifier_ tout en bas de la page, et en a conclu que son formulaire n’était pas éditable. Franchement, je le ou la comprends.

**Comment by kemenaran** [comment]
C'est pas faux.

Pour moi l'idée, c'est de montrer que oui le dossier a bien été déposé et rempli – même si, si on veut le modifier (le "râturer", en quelque sorte), c'est encore possible.

Je vois deux solutions envisageables :

1. Rendre toute la page directement éditable
2. Rajouter un bouton "Modifier" aussi en haut des champs (plutôt que seulement en bas).

Je préfèrerais 2., parce que c'est tout léger :) Vous en pensez quoi ?

**Comment by kemenaran** [comment]
On a mis le bouton "Modifier" en haut des champs.
