### ISSUE TITLE
ETQ instructeur, je veux que les emails de notification précisent le nom de l'usager ou de l'organisme

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#3291]
Aujourd'hui on leur donne le numéro de dossier et ce n'est pas parlant. 
ARSParis

**Comment by kemenaran** [comment]
C'est vrai. Et comme on a forcément une identité ou un siret, ça devrait être possible de toujours afficher une info pertinente.

**Comment by Benjamin-Doberset** [comment]
Même probléme évoque apr la CNAF et les CAF dans le cadre des AAP.

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/87054/instructeur-indiquer-le-nom-de-lusager-ou-de-lorganisme-dans-les-emails-de-notif
