### ISSUE TITLE
Donner à l'usager la possibilité de répéter certains champs ou blocs de champs

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#330]
DDPP Oise
ANFR
Ministère des affaires sociales
France Agrimer
Affaires Maritimes
Laurent.C (Corrèze)
Université de Nantes VAE

**Comment by mmagn** [comment]
Penser à gérer les templates de mails / attestations

**Comment by fredZen** [comment]
Cf #3353 (merci @CamilleGarrigue !)
