### ISSUE TITLE
ETQ Instructeur je souhaite voir la description relative à un champ 

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3306]
Le bloc description des champs n'apparait pas dans la vue instructeur, ce qui est problématique dans le cas du champ engagement. L'instructeur ne peut voir que le libellé de l'engagement mais pas le détail.

HS: # 11012

**Comment by kemenaran** [comment]
J'ai l'impression qu'on a décidé de ne pas afficher la description dans la vue instructeur, pour simplifier l'affichage qui à cet endroit est supposé être compact.

Sans éléments nouveaux, je pense qu'on ne va pas le faire tout de suite.
