### ISSUE TITLE
ETQ super admin, je veux être tenu au courant des démarches qui ne fonctionnent pas

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3318]
Si l'usager ne m’écrit plus car son message est directement rerouté vers la messagerie de la plateforme, je souhaite toujours pouvoir savoir s'il y a un problème sur la procédure (ex l'instructeur en répond pas, temps d'instruction trop longue)

**Comment by kemenaran** [comment]
@Benjamin-Doberset pour toi quelles seraient les bonnes métriques pour évaluer si une démarche fonctionne ou pas ?

**Comment by kemenaran** [comment]
On n'a pas vraiment de précisions là dessus ; je ferme pour l'instant.
