### ISSUE TITLE
ETQ Instructeur, quand je regarde mon tableau de bord, je ne veux plus avoir l’impression qu’une procédure a été dédoublée alors qu’il s’agit en fait de deux procédures portant le même titre ; en particulier, quand l’une de ces procédures est en test et l’autre en prod

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3333]
ETQ Instructeur les démarches en test sur lesquelles j'ai été nommé demeurent visibles sur mon tableau de bord même quand la démarche a été publiée, j'ai donc deux fois la démarche (une fois en test, une fois en publiée) + les démarches en test apparaissent en premier
Les dossiers sont en plus supprimés.
HS #11346

**Comment by kemenaran** [comment]
Merci pour l'issue !

Normalement une démarche est soit en test, soit publiée. Au moment où une démarche en test est publiée, elle devrait disparaitre du tableau de bord Instructeur.

Si l'instructeur voit à la fois la démarche publiée et la démarche en test, est-ce que ça ne veut pas dire qu'il y a réellement deux démarches – genre que l'administrateur a eu une démarche en test, puis qu'il en a publié une autre ?

Dans ce cas la solution de court-terme serait de demander à l'Administrateur de la démarche de supprimer les démarches résiduelles depuis son interface.

Cela dit, les Administrateurs ne sont pas toujours très réactifs. Ça pourrait être bien aussi que les Instructeurs puissent masquer les démarches en test eux-même, sans être dépendants d'un Admin.

On peut imaginer un bouton "Masquer cette démarche" dans l'interface Instructeur. Ou un onglet "Démarches en test" – activé par défaut quand il n'y a que des démarches de tests dans l'interface ?

**Comment by philemon95** [comment]
Actuellement, quand tu es admin et instructeur, une démarche testée apparaîtra deux fois (publiée et testée), le problème supplémentaire étant en plus que les démarches testées apparaissent en premier.
Un bouton "masquer cette démarche" me semble une bonne solution.

**Comment by philemon95** [comment]
HS #12022 comme exemple

**Comment by philemon95** [comment]
je me permets de soulever à nouveau le problème

**Comment by LeSim** [comment]
Je place ce ticket dans la colonne priorisé

**Comment by emsnytech** [comment]
Cela rejoint l’une des issues proposée il y a qques temps qui est de créer trois onglets coté instructeur, avec démarches en test, démarches en prod, et démarche archivées. 
La première serait démarches en prod.

**Comment by fredZen** [comment]
Je n’ai pas réussi à reproduire le problème. J’ai quand-même audité le code, et j’affirme avec un très fort degré de confiance que le code ne peut pas afficher la même procédure en brouillon et en non-brouillon dans le tableau de bord instructeurs.

Ce qui me semble le plus probable, c’est que les utilisateurs en question avaient deux démarches avec le même intitulé, l’une en test, l’autre en prod. Si j’ai vu juste, et que c’est un problème récurrent, alors je propose de le traiter comme un problème ergonomique. Comment faire comprendre à l’utilisateur que ces deux démarches, bien qu’elles portent le même titre, sont différentes ? Quelques pistes, dont je ne suis pas très satisfait : 

- on pourrait interdire aux administrateurs d’avoir deux démarches avec le même titre (ça me paraît trop contraignant par rapport à la fonction « cloner une démarche », on va se retrouver avec des démarches avec des noms à la xion, un peu comme les copies de fichier sous Windows... « copie de copie de demande d’inscription » ou encore « demande d’inscription 37 » ... :unamused: )
- on pourrait ajouter une information discrète (plus petits caractères ou grisé, par exemple) à côté du titre de la démarche, par exemple l’#id de la démarche ou sa date et heure de création
- on pourrait décider que le remède est pire que le mal et vivre avec le problème, quitte à le documenter dans une FAQ

Par souci d’exhaustivité, voici d’autres explications auxquelles je pense mais ne crois pas
- le bug existerait encore mais je n’ai pas réussi à le trouver
- le bug existait à l’époque mais a été corrigé entre temps (j’ai un peu regardé l’historique)
- j’ai mal compris l’issue, le bug existe mais il affecte un autre écran que celui auquel je pense - moi je pense à cet écran ci : ![image001](https://user-images.githubusercontent.com/356570/55152137-0420c200-5150-11e9-9241-6bba7b2c0480.png)

**Comment by fredZen** [comment]
Mais @LeSim me dit dans l’oreillette qu’il sait reproduire, les jeux ne sont pas faits... suspens insoutenable

**Comment by LeSim** [comment]
nop, fausse alerte, j'ai le cas que tu décris : j'ai cloné une procédure existante avec le mm nom.

**Comment by kemenaran** [comment]
À priori c'est un problème qui peut petre réglé par l'admin en archivant les démarches superflues.

Sinon on pourra travailler sur l'ordre en triant par exemple par la présence de notifications.
