### ISSUE TITLE
ETQ Instructeur, je n'arrive pas a me connecter de manière sécurisée

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#3345]
Les problèmes relevés jusqu'à présent :
1) les mails mettent trop de temps à arriver, les instructeurs demandent de nouveau jeton frénétiquement et ne cliquent jamais sur celui valide
2) les instructeurs ne cliquent pas sur le lien du dernier mail et se retrouvent avec un jeton périmé

Proposition de solution :
- on augmente la durée de vie du jeton à 24h et on renouvelle le jeton que lorsque la période de 24h est dépassé (devrait résoudre 1. et 2. )

**Comment by fredZen** [comment]
En sujet connexe : #3341

**Comment by LeSim** [comment]
@fredZen bien vu

**Comment by kemenaran** [comment]
Ça m'a l'air top 👍 

(Est-ce qu'en bonus on a moyen de contacter la DSI des directions territoriales, pour que nos emails arrivent vite ? Parce qu'1/4h pour pouvoir se connecter, c'est long, quoi qu'il arrive.)

**Comment by LeSim** [comment]
je peux pas renvoyer le jeton car il est stocké hashé ... fail

**Comment by fredZen** [comment]
Éventuellement on peut décider que la relation user - token soit une relation 1-N plutôt que 1-1. Comme ça, quand on génère un nouveau token on n’est pas obligés d’écraser l’ancien.

**Comment by philemon95** [comment]
+ problème des connexions sécurisées à chaque connexion (alors que censé être tous les 30 jours?)

**Comment by LeSim** [comment]
Nouvelle proposition : 
1 - avec @mmagn on cherche a diminuer la criticité de ce jeton. Actuellement, il suffit de l'avoir pour se connecter, du coup on a la trouille d'en émettre plusieurs
=> mettre en place un système ou il faut et se logguer et avoir le jeton
2 - si on a les 2 méchanismes, on peut se mettre à émettre n jetons, on prend l'idée de @fredZen 
3 - on nous remonte des fois que le lien du mail n'est pas ouvert avec le bon navigateur : on propose de faire une page ad hoc de notre site pour que l'utilisateur puis copier le jeton sur la page (gros text input : votre jeton svp). et du coup, peut être simplifier le jeton.

**Comment by fredZen** [comment]
@LeSim est-ce qu’il reste des choses à faire ou bien on peut fermer cette fiche ?

**Comment by LeSim** [comment]
On a implémenté
- le multi jeton
- augmentation de la durée de vie du lien a 7 jours
- la combinaison jeton + login mdp

pas le 3 ieme point, je ne suis pas sur aujourd'hui que ça améliorait la situation.

J'ai eu hier un sidsic (préfecture) qui me faisait par de la config par défaut de ses firefox qui efface les cookies et autres à la fermeture. J'attends confirmation pour savoir si c'est une politique nationale ou locale.

**Comment by LeSim** [comment]
Bon, on me reballade à un autre interlocuteur mais apparemment 

- pour les préfectures, une politique par défaut pour les navigateurs est recommandée par le ministère de l'intérieur
- cette politique provoquerait l'effacement de l'historique, et on suppose des cookies, à chaque fermeture de poste

en attente de confirmation ...

**Comment by LeSim** [comment]
Je me demande si on peut pas faire un truc avec l'ip.

Avec l'hypothèse que les préfectures ont une ip stable. on pourrait peut-être fallback en autorisant n ips pendant un certains temps pour un instructeur si le cookie n'est pas présent.

**Comment by kemenaran** [comment]
J'ai l'impression qu'on ne va pas plus travailler sur cette issue.

@LeSim On ferme ?
