### ISSUE TITLE
Lors de l'export CSV, remplacer le state interne par les etats publique

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#335]
soit passer ici de la partie droite à la partie gauche dans la colonne state du csv

  EN_CONSTRUCTION = %w(initiated updated replied)
  EN_INSTRUCTION = %w(received)
  A_INSTRUIRE = %w(received)
  TERMINE = %w(closed refused without_continuation)

**Comment by mmagn** [comment]
Déjà fait sur l'API : https://tps.apientreprise.fr/docs/1.0/dossiers/show.html
Attribut `simplified_state`

**Comment by tchak** [comment]
done
