### ISSUE TITLE
Amélioration du bloc répétable

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#3353]
Voici mes retours quand à l'utilisation du bloc répétable, on pourra spliter en plusieurs ticket si tu veux.
A part le bug de positionnement des champs au sein d'un bloc répétable, rien ne me paraît bloquant pour une première release en test.

**Bravo pour ton taff !**

### Coté admin
Bug
- [x] Impossibilité de changer la position d'un type de champ dans un bloc répétable
- [x] Deux menu déroulants liés : impossible a remplir si je ne commence pas par la case liste déroulante
- [x] update automatique provoque des bugs : 
  - [ ] texte qui change (je tape 'animaux' il sauvegarde à 'ani', rafraichit la page et je vois 'ani' sur ma texte box
  - [ ] il me semble une perte de focus dans un champ texte
- [x] le clonage d'une procédure ne copie pas l'intérieur des blocs répétables
- [x] la prévisualisation de champs répétable ne fonctionne pas

UX
- [x] flash info, wording : 'Champs enregistrés' -> 'formulaire mis à jour'
- [x] flash alert 'Le libellé doit être rempli'
  - mauvais endroit
  - apparaît dès que l'on choisit le type de champ
- [ ] je trouve l'interface relativement lourde avec toutes ces boites mais je suis **très** mauvais en design, peut-être que magic @mmagn pourrait filer un coup de main ?
- [ ] Comment je fais pour retourner aux autres onglets ? Ajouter un autre moyen que le breadcrumb ?
- [x] Lors de la creation d'une nouvelle demarche, apres la description on arrive sur la nouvelle configuration des champs qui est vide. Pourrait-on mettre un simple champ texte par défaut ?
- [ ] Lors de l'ajout d'un bloc répétable, j'aimerai également avoir un premier type de champ par défaut texte
- [x] Finalement, j'ai une étrange sensation de cursor qui saute lorsque je crée des tdc ... à confirmer

### Coté usager
Bug
- [x] chez moi, le double champ lié ne fonctionne pas

UX
- [x] le bouton supprimer est trop près des autres champs, j'ai cliqué dessus par mégarde 
- [x] peut-on également avoir un premier bloc répétable présent par défault ?

### Coté instructeur : RAS

**Comment by tchak** [comment]
- flash info, wording : 'Champs enregistrés' -> 'formulaire mis à jour' [done]
- flash alert 'Le libellé doit être rempli'
  C'est plus le texte qui n’est pas bon. On ne peut pas enregistrer les changements temps que tous les libelles ne sont pas remplis.
- Pourrait-on mettre un simple champ texte par défaut ? oui, dans une prochaine itération

**Comment by tchak** [comment]
Quelques améliorations dans #3360

**Comment by CamilleGarrigue** [comment]
Je reprends le flash alert de tchak sur "Le libellé doit être rempli", même une fois tous les libellés remplis on a le message de non enregistrement des modifications. 
<img width="1194" alt="capture d ecran 2019-02-05 a 18 07 42" src="https://user-images.githubusercontent.com/33320335/52290841-49efb400-2971-11e9-8b77-0e40600eeb49.png">

**Comment by Benjamin-Doberset** [comment]
BUG 
Deux menu déroulants liés : impossible a remplir si je ne commence pas par la case liste déroulante
Lorsque je duplique un bloc, les champs à l'intérieur de celui-ci n'ont pas conservé le type initial. ex : mon champ adresse est devenu un simple champ texte et mes menus deroulants liés ne fonctionne plus ( seul le premier menu est disponible l'autre n'apparait plus).

UX :
pour avoir un nouveau bloc il est écrit "ajouter une ligne "nom du titre"" peut être mieux dire  dupliquer "nom du titre"

**Comment by LeSim** [comment]
Update,

- [ ] Lorsque je commence une nouvelle procédure from scratch, je tombe directement sur la page de création de champ, une fois remplie, je ne sais pas ou cliquer

**Comment by tchak** [comment]
- [ ] Trouver une solution pour déplacer les champs dans des formulaires longs

**Comment by JeanMichelDHUP** [comment]
Bonjour,

- [ ] Pouvoir créer un champ SIRET dans un bloc répétable

**Comment by philemon95** [comment]
- [ ] pouvoir exporter les infos saisies dans le bloc répétable (à communiquer HS 13795)

**Comment by philemon95** [comment]
- [ ] pouvoir permettre l'enregistrement des données saisies dans un bloc répétable au sein des annotations privées (à communiquer HS 14128)

**Comment by philemon95** [comment]
- [ ] la prévisualisation du bloc répétable ne permet pas d'ajouter un nouveau bloc

**Comment by philemon95** [comment]
**Côté instructeur**

- [ ] pouvoir filtrer les dossiers en fonction de la valeur saisie dans un champ de bloc répétable

**Comment by philemon95** [comment]
- [ ] ajouter un incrémenteur après le titre du bloc (#1, #2...)

**Comment by kemenaran** [comment]
Pour le filtrage, c'est #5193.

Pour le reste, je ferme cette méta-issue, au profit d'issues plus spécifiques.
