### ISSUE TITLE
Pouvoir joindre une solution de paiement à une procédure

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#336]
Par exemple pouvoir remplir un dossier pour un permis et payer sur la plateforme par la mm occasion.

**Comment by kemenaran** [comment]
J'ai l'impression qu'on a un consensus sur "On ne va vraiment pas faire ça tout de suite". On ferme ?

**Comment by gregoirenovel** [comment]
Why not, mais comment on track ce genre de demandes, en particulier pour les prioriser (ce cas était sorti lors d'un des open labs de 2017) ?
