### ISSUE TITLE
ETQ Instructeur, je veux pouvoir remplir une démarche en cliquant sur son lien

### ISSUE THREAD

**Issue by chaibax** [betagouv/demarches-simplifiees.fr#3366]
## Description du problème

Quand je veux remplir un dossier, ou l'instruire, c'est à dire, quand je clique vers un lien me renvoyant vers l'interface instructeur ou usager, je suis automatiquement renvoyé vers /admin/procedures. 

## Reproduire

1. Avoir un compte Administrateur ou Instructeur sur DS
2. Se déconnecter
3. Cliquer sur le lien public d'une démarche (`/commencer/…`)
4. Se connecter
5. Je suis redirigé vers la page d'accueil de mon rôle, au lieu du lien de la démarche.

## Comportement attendu

Quand je clique sur le lien public d'une démarche et que je dois me connecter, je veux être redirigé vers la page de garde de la démarche.

**Comment by chaibax** [comment]
même soucis pour l'instructeur quand il veut tester une démarche : #4314

**Comment by kemenaran** [comment]
Exemple précis :

> Situation : j'ai un compte DS comme instructeur et éventuellement admin
Lorsque je me connecte via un lien de procédure pour faire un test ou utiliser un formulaire, si je ne me suis pas connecté avant à DS, je suis dirigé vers l'interface admin/instructeur sans possibilité d'accéder au formulaire voulu
Il semblerait que cela soit lié au cookie du jeton de connexion.
Est-il possible ou d'avertir via un message ou de résoudre la question ?

**Comment by kemenaran** [comment]
@ErwanLHH a laissé dans #4541 une bonne description d'un cas typique de cette erreur en conditions réelles : on envoie un lien vers une démarche DS à tous les admins, et ils ne peuvent pas facilement la remplir.

**Comment by krichtof** [comment]
Je reproduis ce problème uniquement si je suis instructeur et que lorsque je m'identifie, un jeton m'est envoyé par mail  parce que l'actuel a expiré.
En revanche, si je suis administrateur ou instructeur reconnu (avec un jeton valide), j'arrive bien directement après m'être identifié sur le formulaire.

Du coup, cela ne me parait pas prioritaire.

**Comment by krichtof** [comment]
Je réouvre l'issue suite à cette exception sur plusieurs controllers :

``` 
NoMethodError
undefined method `get_stored_location_for' for #<Users::CommencerController:0x00007f25a434af00>

```
