### ISSUE TITLE
ETQ Administrateur je veux changer de type de compte (instructeur,usager) plus facilement

### ISSUE THREAD

**Issue by chaibax** [betagouv/demarches-simplifiees.fr#3370]
Ce n'est pas très visible pour l'instant et bcp d'admin ne trouve pas le bouton :(

**Comment by emsnytech** [comment]
ancienne UX...

**Comment by fredZen** [comment]
Je réouvre à cause de #3513

**Comment by chaibax** [comment]
Merci @fredZen . Le soucis n'est pas, je pense, le bouton de changement de compte. Le problème est qu'on redirige forcement vers la page Admin quand on est admin, et pas la page de destination initiale (dans l'espace instructeur par exemple).

Je pense qu'on réglant cette issue : #3366 , et en remettant mon code , on pourrait  doublement simplifier la vie des admins qui sont aussi instructeurs
