### ISSUE TITLE
ETQ admin, je souhaite retrouver la possibilité de classer les champs dans le nouvel éditeur de champs

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#3394]
Retour d’un admin. Quand on clone ou modifie un formulaire long, le nouveau dispositif de faire glisser les champs reste difficile.
Le dispositif de numérotation des champs parait fondé à être réintroduit.

**Comment by kemenaran** [comment]
Effectivement le glisser-déposer n'est pas très pratique pour les gros éléments dans des longues listes.

En revanche les numéros ne sont pas très pratiques à manipuler non plus.

On pourrait ré-introduire des boutons ⬆ et ⬇. Est-ce que pour toi ça répondrait au besoin ?

**Comment by emsnytech** [comment]
franchement, les flèches ce n'était vraiment pas top quant on a de long formulaires....
Avec les numéro, nous n'avions plus aucune remarque de personnes... c'était appréciable

**Comment by kemenaran** [comment]
@emsnytech Est-ce que c'est toujours une douleur, ou aujourd'hui ça va ?
