### ISSUE TITLE
ETQ instructeur, je veux pouvoir demander un avis après la décision finale du dossier

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#3400]
@A.Ortega

**Comment by emsnytech** [comment]
Pour l’instant, cela ne me semble pas prioritaire....

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/78072/instructeur-demander-un-avis-apres-la-decision-finale-du-dossier
