### ISSUE TITLE
ETQ Administrateur je veux cloner une démarche avec ses pièces jointes

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/demarches-simplifiees.fr#3440]
Lorsqu’un fichier pour le Cadre juridique est ajouté à la démarche (champ deliberation), le clone échoue si le serveur http impose SSO.
Ce fichier est stocké via active_storage sur le serveur local (mode :local pour active_storage) et non dans le cloud, ainsi l’appel https (via Typhoeus.get(attachment.service_url)) échoue car l’url service_url pointe sur local. Le serveur local http impose que l’appelant soit authentifié (SSO), or le serveur n’est pas authentifié sur lui-même via Kerberos.

Une solution trouvée est de remplacer cet appel d’url Typhoeus.get(attachment.service_url) dans le fichier procedure.rb, méthode clone_attachment par un appel à la méthode download directement sur l’attachement, ceci fonctionne pour le serveur en local. 
Est-ce-que ceci pourrait fonctionner sur DS en cloud ?

**Comment by mmagn** [comment]
Oui normalement c'est bon, il faudra juste faire attention à la gestion des erreurs qui va changer.

**Comment by LeSim** [comment]
j'ai pas trop compris le coup de la gestion d'erreur. Mais on veut bien une pr pour vérifier que ça marche bien chez nous !
