### ISSUE TITLE
ETQ usager je veux pouvoir facilement effectuer à nouveau la même démarche

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3444]
comme on a enlevé le bouton "rechercher une démarche", les usagers qu effectuent régulièrement la même démarche (vols drones, auto-ecoles...)doivent retourner sur le site de leur administration afin d'etre réorienté sur la démarche idoine. 
une solution pourrait être de rajouter un bouton "effectuer à nouveau cette démarche" sur le tableau de bord de l'usager avec la liste de ss démarches (même style que bouton "supprimer", mais bouton "effectuer à nouveau cette démarche")

**Comment by philemon95** [comment]
exemple: HS 12409, HS 12405, HS 12413

**Comment by kemenaran** [comment]
Je trouverais ça cool sur le principe.

Cela dit, j'ai deux réserves :

- **L'opportunité** : depuis la nouvelle page de garde, si on veut effectuer à nouveau une démarche, il suffit d'aller sur la page `/commencer/xxx` de la démarche. Y'a alors un gros bouton "Commencer une nouvelle démarche". Du coup p-ê que le bouton au niveau de la liste des dossiers n'est pas complètement prioritaire. Mais en même temps, si c'est demandé par les usagers, c'est p-ê qu'ils en ont besoin…

- **L'interface** : j'ai peur que rajouter un bouton qui servira plutôt rarement à une minorité d'usagers rajoute beaucoup de bruit cognitif dans la liste des dossiers. Et aussi, sur mobile, ça devient vraiment trop étroit.

Deux pistes :

- Pour l'opportunité :
  - Rajouter une entrée dans la FAQ "Comment faire pour déposer un nouveau dossier sur la même démarche" ?

- Pour l'interface :
  - Soit dans la liste des dossiers, remplacer le bouton « Supprimer » par un menu « Actions » (qui contiendrait les commandes « Supprimer » et « Effectuer à nouveau cette démarche »).
  - Soit dans la vue des détails d'un dossier, ajouter un bouton « Effectuer à nouveau cette démarche » (comme ça on ne pollue pas la liste)

@philemon95 tu en penses quoi ?

**Comment by philemon95** [comment]
Pour l'opportunité, 

- on ne parle pas de la même chose, il me semble que quand on est usager et qu'on est sur la liste de ses dossiers, on ne peut pas retourner sur la "page d'accueil" de la démarche (si c'était le cas effectivement il n'y aurait pas de problème

- au regard du support généré, ça ne concerne pas une minorité d'usagers :)

Pour l'interface: le bouton d'action me paraît très bien, pour la FAQ je gère :)

**Comment by LeSim** [comment]
`HS 12850`

**Comment by chaibax** [comment]
Autre idée : avoir un bouton "copier" (ou dupliquer) la démarche (quelque soit sont statut), qui va créer un dossier a l'identique (au niveau contenu) , mais avec le statut brouillon .

![](https://cdn.icon-icons.com/icons2/1392/PNG/128/duplicate_96659.png)

Ca permettrait plusieurs cas d'usage : 

- saisie multiple de démarche
- saisie d'une démarche a l'identique (on a des demandes usagers en ce sens)

**Comment by fredZen** [comment]
@chaibax Surtout que c'est une demande récurrente #1906

**Comment by philemon95** [comment]
Ca permettrait effectivement de faire d'une pierre deux coups, mais risquerait peut-être d'accroître les mauvaises saisies? A tenter :)

**Comment by mmagn** [comment]
Il me semble que @emsnytech nous avait dit que ça augmentait le nombre d'erreurs de saisies.

**Comment by emsnytech** [comment]
En effet, dupliquer les dossiers dans leur globalité porte le risque de redéposer à la va vite des dossiers. L’effet spam n’est pas à ignorer. Ne faut il pas autoriser la capacité de duplication des dossiers par l'administrateur lors de la création de la démarche ? Le risque dans ces conditions c’est que notre interface « admin » ne devienne un peu plus complexe.

**Comment by chaibax** [comment]
Rien ne prouve pour l'instant que ça rajouterait du SPAM. 
Et si c'est vraiment le cas, on pourra toujours revenir en arrière. 

Je propose qu'on essaie de régler les problèmes actuels plutôt que ceux qu'on a pas encore (spam de dossier).

**Comment by kemenaran** [comment]
@chaibax effectivement.

Cela dit, si on part sur la duplication de dossier, ça ne résout pas l'autre problème de fond, qui est la multiplication des erreurs de saisie

Je propose qu'on garde cette issue dans sa formulation restreinte : proposer un moment d'ouvrir un nouveau dossier sur la même démarche, sans duplication des infos pour l'instant.

**Comment by chaibax** [comment]
@kemenaran : ca me va tout à fait comme proposition

**Comment by emsnytech** [comment]
Tout à fait aussi...c’est ce à quoi j’étais arrivé quand j’avais mis en place cette fonctionnalité dans poliville ... (déjà 18 ans!)
Sinon, trop compliqué pour savoir quel champ on garde et l’autre non...
