### ISSUE TITLE
Images dans les mails tronquées dans certains lecteurs de mail

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#3448]
HS `#11961`

L’éditeur permet aux administrateurs d’insérer des images dans les emails d’accusé personnalisés. Apparemment, dans outlook, ces images s’affichent tronquées.

**Comment by emsnytech** [comment]
N’aurait il mieux pas fallu supprimer la possibilité supprimer la barre de formatages de texte dans les email et la mettre dans l’attestation ?

**Comment by kemenaran** [comment]
À priori corrigé par #3562
