### ISSUE TITLE
ETQ Usager, révoquer l’invitation à co construire un dossier envoyée à un invité

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#3451]

**Comment by Benjamin-Doberset** [comment]
besoin aussi pour le transport fluvial : cas d'usage, j'invite un oragnisme d'expertise mais je veux en changer (notamment parce que sa décision n'est pas bonne)

**Comment by emsnytech** [comment]
Petit rappel d'une feature qui a tout son sens, juridiquement aussi...
