### ISSUE TITLE
ETQ instructeur je veux pouvoir filtrer mes dossiers par instructeur

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3464]
Cas d'usage : Un instructeur est malade. ETQ que second instructeur sur la démarche, je souhaite connaitre rapidement tous les dossiers qu'il est en train d'instruire pour pouvoir les traiter pendant son congé maladie. J'ai donc besoin de pouvoir aller dans 'longlet " tous les dossiers" et filtrer par " Instructeur"

**Comment by kemenaran** [comment]
Carrément, c'est un cas d'usage vraiment légitime qu'on devrait gérer.
