### ISSUE TITLE
ETQ usager je veux connaitre mon numéro de dossier pendant que je remplis mon dossier

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3465]
Situation actuelle : je dois retourner sur mon tableau de bord pour connaitre mon numéro de dossier

Situation souhaitée : Pendant que je remplis mon dossier, mon numéro de dossier est facilement réparable (en dessous du nom de la démarche et sur la même ligne que les boutons "enregistrer en tant que brouillon" et "soumettre mon dossier")

**Comment by kemenaran** [comment]
Ça a été demandé par quelqu'un ? Quel est le besoin d'avoir ce numéro de dossier ?

**Comment by Benjamin-Doberset** [comment]
Oui par la DGITM. Le besoin c'est pour quand je fais un dossier "structure" et un dossier "projet". C'est pour éviter que l'usager ait à revenir sur son tableau de bord pour remplir son dossier projet.

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/78073/usager-connaitre-mon-numero-de-dossier-pendant-que-je-remplis-un-dossier
