### ISSUE TITLE
ETQ Usager je veux réduire/ développer les sections afin de clarifier l'affichage

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3466]
Situation actuelle : l'ensemble du formulaire s'affiche de manière linéaire, avec une impossibilité de modifier

Situation souhaitée : Chaque titre de section me donne la possibilité de réduire / développer les éléments qu'il contient. Exemple : j'ai un titre de section "Identité" avec en dessous les champs Nom, Prénom, date de naissance. En cliquant sur le titre de section je fais apparaitre ces champs, sinon je ne vois que le titre de section "Identité"

**Comment by kemenaran** [comment]
Je comprends le besoin. Cela dit généralement les accordéons repliables comme ça, c'est assez mal compris par les utilisateurs en général. Ce n'est pas un design pattern qui fonctionne très bien.

Ce qui fonctionne bien à la place, c'est généralement de séparer les longs formulaire en plusieurs pages. Une section par page, un chemin de fer en haut pour indiquer la progression, et ça marche bien.

**Comment by Benjamin-Doberset** [comment]
Ok, mais dans les évolutions à mettre en place rapidement est ce que la section par page est envisageable? Notamment au niveau du responsive?

**Comment by kemenaran** [comment]
Au niveau du responsive ça ne change pas grand chose : si on découpe la page verticalement, horizontalement ça reste la même chose – juste avec moins de champs par page, non ?

En revanche c'est plutôt une moyenne-grosse évolution. Rien d'impossible, mais plutôt de l'ordre de 2 semaines.

**Comment by Benjamin-Doberset** [comment]
Ok, et au niveau de remplacer la conditionnalité? Par ce que le plier/déplier semble un bon proxi

**Comment by kemenaran** [comment]
Bin justement, ce que j'essaie de dire c'est que généralement le plier/déplier ça fonctionne assez mal. Ce n'est pas aussi clair qu'on croirait, les gens ont du mal à s'en servir.

Y'a une référence sur les [soucis d'usabilité posés par les accordéons](https://www.nngroup.com/articles/accordions-complex-content/) (et une autre sur le fait que [les accordéons n'améliorent généralement pas les pages de checkout d'un achat en ligne](https://baymard.com/blog/accordion-checkout-usability) (ce qui est un usage commun des accordéons, parce que un formulaire de checkout c'est long)).

Ça ne dit pas que c'est toujours une mauvaise idée – mais plutôt que c'est difficile à implémenter correctement, et que même bien fait ça n'améliore souvent pas tant que ça l'usabilité de la page.

**Comment by fredZen** [comment]
J’ajoute que la pagination est un excellent premier pas vers le conditionnel

**Comment by emsnytech** [comment]
C'est ce que l'on avait mis sur la première version de TPS. Supprimé en effet parce que difficilement compréhensible pour les usagers

**Comment by emsnytech** [comment]
Pagination... Pb sur mobile...et pas très chaud

**Comment by kemenaran** [comment]
Fermé au profit de #2227
