### ISSUE TITLE
ETQ instructeur je voudrai pouvoir voir pour chaque dossier quel instructeur le suit

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3490]
afin de clarifier la vue d'ensemble pour le chef de service, sans pour autant enlever les droits de décision aux instructeurs

**Comment by mmagn** [comment]
Possible d'avoir l'info en exportant les dossiers en format tableur, il y a une colonne qui liste les instructeurs qui suivent le dossier.

**Comment by kemenaran** [comment]
C'est maintenant affiché clairement dans l'interface :

<img width="1104" alt="Capture d’écran 2020-04-07 à 12 10 12" src="https://user-images.githubusercontent.com/179923/78657243-c4df9200-78c8-11ea-8f58-94a0a7ad2a7a.png">
