### ISSUE TITLE
ETQ Utilisateur, je veux voir les charts au premier chargements des pages Stats

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#350]
Cf. la console

> Uncaught Error: Highcharts error #16: www.highcharts.com/errors/16

**Comment by kemenaran** [comment]
Étonnant – et d'ailleurs, un an et demi après, c'est toujours cassé (même s'il n'y a plus d'erreur dans la console).

**Comment by n-b** [comment]
Je vampirise une vieille issue, mais c‘est le même bug: l’initialisation de Chartkick ne se fait pas sur `turbolinks:load` et à la navigation vers `/stats` ou `/procedures/<id>/stats` les graphiques ne sont pas chargés. Au rechargement de la page, tout va bien.
