### ISSUE TITLE
ETQ Admin, je veux créer un champ SIRET dans un bloc répétable

### ISSUE THREAD

**Issue by JeanMichelDHUP** [betagouv/demarches-simplifiees.fr#3500]
Il n'est pas possible de créer un champ SIRET dans un bloc répétable.
La fonctionnalité bloc répétable est très utile pour gérer le cas de co-demandeur d'une démarche.
Un co-demandeur peut être une personne morale.

Projet : permis de construire facile 

Je vous remercie.

**Comment by benjaminhenkel** [comment]
Quach (DGTIM)

**Comment by kemenaran** [comment]
Déplacé dans https://demarches-simplifiees.featureupvote.com/suggestions/77358/administrateur-recuperer-les-informations-politique-de-la-ville
