### ISSUE TITLE
ETQ Admin je veux déplacer un champ dans un bloc répétable

### ISSUE THREAD

**Issue by JeanMichelDHUP** [betagouv/demarches-simplifiees.fr#3502]
On ne peut pas déplacer un champ dans un bloc répétable.
Il n'est pas possible de modifier l'ordre des champs dans un bloc répétable

Jean Michel COSTE

**Comment by guillaumelevieux** [comment]
Même type de problématique de mon côté, le changement d'ordre sur l'interface d'admin ne se reflète pas correctement sur la prévisualisation des annotations privées. Pour atteindre son objectif de classement, il faut sortir de l'édition des annotations privées puis recharger après chaque modification pour voir et modifier le l'ordre enregistré.

**Comment by kemenaran** [comment]
Le problème de ré-organiser les champs dans des blocs répétables est corrigé.

Le changement d'ordre des annotations privées devrait être corrigé lui aussi.
