### ISSUE TITLE
ETQ Administrateur, je veux pouvoir ajouter des balises concernant les champs inclus dans les blocs répétables dans les templates

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/demarches-simplifiees.fr#3522]
J'ai ajouté un bloc répétable:
![image](https://user-images.githubusercontent.com/9320719/53503792-12c47c80-3ab1-11e9-81d8-1a9a6d4a9cf9.png)

Dans l'attestation, je ne vois pas les tages:  "--test--" et "--date--"
![image](https://user-images.githubusercontent.com/9320719/53503840-2a036a00-3ab1-11e9-9672-1e14b3cb22c4.png)

Je propose de créer deux méthodes:
`Dossier.all_champs`
`Procedure.all_types_de_champ`

Et dans `app/models/concerns/tags_substitution_concern.rb`

`types_de_champ_tags(procedure.types_de_champ, Dossier::SOUMIS)` => `types_de_champ_tags(procedure.all_types_de_champ, Dossier::SOUMIS)`

`[champ_public_tags, dossier.champs],` => `[champ_public_tags, dossier.all_champs],`

**Comment by LeSim** [comment]
a communiquer `HS 13591`

**Comment by LeSim** [comment]
@pengfeidong est ce que vous auriez un exemple d'utilisation ?

**Comment by Keirua** [comment]
suite à la réunion avec armées de ce matin, on a vu que ce ticket n'avait pas de cas d'usage chez eux et qu'ils souhaitent le clore
