### ISSUE TITLE
Deux décisions contradictoires envoyées au demandeur

### ISSUE THREAD

**Issue by guillaumelevieux** [betagouv/demarches-simplifiees.fr#3524]
Lors d'un test en formation, deux agents instructeurs ont ouvert le bloc de décision sur un dossier en même temps. Un premier instructeur a accepté la demande et le second a ensuite rejeté la demande.
Le demandeur a reçu une première décision d'acceptation puis une seconde décision de rejet créant ainsi la confusion.
Même s'il est peu probable que deux instructeurs ouvre simultanément le bloc de prise de décision pour rendre des décisions contradictoire cela pose toutefois problème.
L'ouverture du bloc de décision par un agent devrait verrouiller toute autre ouverture simultanée.

**Comment by tchak** [comment]
Verrouiller un contexte à l'ouverture est compliqué, par contre le deuxième instructeur aura dû obtenir une erreur lors de sa tentative de refuser le dossier déjà accepté. C'est un vrai bug. Merci pour le signalement !

**Comment by kemenaran** [comment]
Maintenant une erreur s'affiche si un instructeur a une page périmée, et essaie de rendre une décision sur un dossier déjà terminé.
