### ISSUE TITLE
Passer les titres de colonnes en français pour "exporter tous les dossiers"

### ISSUE THREAD

**Issue by icollombet** [betagouv/demarches-simplifiees.fr#353]

**Comment by tchak** [comment]
superseded by #1116

**Comment by gregoirenovel** [comment]
C'est pas la même issue : #1116 semble concerner le contenu de la colonne `state` (et éventuellement le nom des colonnes `initiated_at`, `received_at`, etc., mais ce n'est pas certain), alors que celle-ci concerne le nom de toutes les colonnes, en particulier `created_at`, `updated_at`, ou d'autres colonnes qui ne semblent pas incluses dans #1116
