### ISSUE TITLE
En tant qu’admininistrateur, je veux pouvoir restreindre les valeurs autorisées dans un champ nombre

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#3532]
`HS #13212`

L’administrateur veut recueillir des numéros FINESS. Il s’agit de numéros à 9 chiffres. Il veut donc imposer de saisir des numéros à 9 chiffres uniquement.

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/88274/administrateur-restreindre-les-valeurs-autorisees-dans-un-champ-nombre
