### ISSUE TITLE
En tant qu’administrateur, je veux que les courriers échangés sur DS soient poussés dans mon système de Gestion Électronique de Documents

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#3533]
À lier sans doute aux questions sur l’archivage

HS `#13212`

> Pour terminer, est-il possible de pousser automatiquement dans une GED les courriers (mail d'accusée de réception et d'acceptation ou attestation) issus de demarches-simplifiees.fr

**Comment by kemenaran** [comment]
J'ai l'impression qu'on ne va pas en faire grand chose. Si le besoin remonte à nouveau, on pourra le bouger dans feature upvote.
