### ISSUE TITLE
Supprimer la possibilité de se créer un compte depuis la home ( /users/sign_in  ) 

### ISSUE THREAD

**Issue by chaibax** [betagouv/demarches-simplifiees.fr#3536]
Bonjour à tous,

Sur une idée de @fredZen que je trouve pertinente, je voudrais avoir votre avis sur le fait de supprimer le bouton "Créer un compte" (*) sur la page https://www.demarches-simplifiees.fr/users/sign_in . 

On ne pourrait se créer un compte que depuis la page de garde d'une démarche. 

L'objectif est de limiter le nombre d'usagers qui se créer un compte sans avoir le lien de la démarche (et donc limiter notre support).

(*) : sur une idée de @Benjamin-Doberset , le bouton pourrait rester mais pointer vers une page d'explication ("il vous faut le lien de la démarche" etc)

**Comment by mmagn** [comment]
Bonne idée.
Après ça risque d'être un peu frustrant pour l'usager mal orienté par son administration, je rajouterai bien un text d'explication qui reprend ce qu'on a mis sur la page des dossiers vide : _"demandez à l'administration le lien /commencer/ , etc."_

**Comment by Benjamin-Doberset** [comment]
Je plussoie cette proposition

**Comment by emsnytech** [comment]
INteressant en effet, un peu frustrant, mais cela éviterait des erreurs...

**Comment by chaibax** [comment]
Bon, si tout le monde est ok, je m'en occupe

**Comment by kemenaran** [comment]
Ok. J'imagine que techniquement ça veut dire « Sur la page `sign_up`, afficher le bouton "Créer un compte" seulement si on est dans le contexte d'une démarche. »

**Comment by chaibax** [comment]
Ce problème est toujours encore présent 😩
