### ISSUE TITLE
Uniformiser l'utilisation (ou pas) de FAQ_URL

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#3537]

**Comment by fredZen** [comment]
À voir en particulier ce qu’on veut faire pour les URLs longues genre `https://faq.demarches-simplifiees.fr/article/34-je-dois-confirmer-mon-compte-a-chaque-connexion`, pour lesquelles on n’a pas pour l’instant de constante.

**Comment by kemenaran** [comment]
On est parti sur une constante, utilisée la plupart du temps.
