### ISSUE TITLE
Remplacer les url_for par rails_blob_path pour les liens vers des fichiers ?

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#3549]
on a vu que les liens de téléchargement se font partout via `url_for`, par ex:
```
# app/views/shared/champs/piece_justificative/_pj_link.html.haml
.pj-link
  - if champ.virus_scan.blank? || champ.virus_scan.safe?
    = link_to url_for(pj), target: '_blank', title: "Télécharger la pièce jointe" do
      %span.icon.attachment
      = pj.filename.to_s
```

Utiliser `rails_blob_path` permet d'ajouter un attribut **content-disposition: attachment**, qui permet de déclencher le téléchargement automatiquement plutot qu'ouvrir le fichier.

```
link_to rails_blob_path(@avis.piece_jointe, disposition: "attachment")
```

**Comment by fredZen** [comment]
Voir aussi #1188

**Comment by kemenaran** [comment]
@Keirua j'ai l'impression que maintenant qu'on n'envoie que des URL court-terme ce n'est plus d'actualité. On ferme ?

**Comment by kemenaran** [comment]
@Keirua je ferme ; à réouvrir au besoin.
