### ISSUE TITLE
ETQ Instructeur je souhaite disposer d'une messagerie privée entre instructeurs

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3552]
ETQ instructeur, je souhaite pouvoir échanger avec les autres instructeurs sans que l'usager ne connaisse ces échanges. Ce serait avoir un équivalent de la messagerie actuelle instructeur - usager mais version annotation privée. Ces dernières ne suffisent pas pour le moment car elles permettent plus des commentaires que des échanges. L'objectif serait de tout regrouper dans le dossier et d'éviter des échanges mails en parallèle.

**Comment by guillaumelevieux** [comment]
+1
Dans une action de co-instruction par différent services la discussion entre agent permet de construire la position de l'administration, souvent préalable à la demande d'un avis formel.
Cette fonctionnalité est très importante dans la phase d'étude de la complétude et la recevabilité, en particulier quand un service d'administration centrale apporte un appuis à un de ses service déconcentré.
Avec l'expérimentation de la démat de certaines demandes de titres miniers, nous sommes contraints de maintenir des échanges par mail. :-(

**Comment by guillaumelevieux** [comment]
Ma vision de ce service serait la suivante :
- on garde les avis d'experts, (qui ne sont pas tjs experts d'ailleurs) requis par les procédures et opposables.
- la messagerie privée est à mon sens à percevoir comme "la note laissé dans le dossier" quand on appelle le service client pour Orange ou SFR et qui permet à l'agent suivant de contextualiser le dossier.  Ca n'a pas vocation à remplacer le coup de téléphone, la réunion, mais à supprimer des mails dans les boites persos pour fluidifier l'instruction.

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/87058/instructeur-disposer-dune-messagerie-privee-entre-instructeurs
