### ISSUE TITLE
ETQ USAGER, je veux pouvoir saisir manuellement les informations relatives au SIRET

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3555]
Dans la mesure où il existe un droit à ce qu'un SIRET ne soit pas diffusé ([article A123-96 du Code de Commerce](https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000020165030&cidTexte=LEGITEXT000005634379)), une personne peut ne pas être référencé dans l'API entreprise et ne pas pouvoir faire sa démarche du fait de l'exercice d'un droit, ce qui pose de sérieux problèmes juridiques. 

Proposition: proposer une alternative où les mêmes informations que celles récupérées par l'API  entreprise peuvent être saisies à la main

à communiquer HS #13491

**Comment by fredZen** [comment]
Cela vaut tout de même la peine de vérifier avec API entreprise si on n’a pas un moyen d’accéder à la donnée. Normalement le droit à l’opposition ne s’applique pas aux administrations.

**Comment by kemenaran** [comment]
On peut maintenant récupérer les données SIRET même des entreprises qui ont demandé à ne pas être diffusées. Cette issue n'a donc plus lieu d'être.
