### ISSUE TITLE
ETQ Admin je voudrais avoir la possibilité de créer une liste déroulante avec l'option "autre" qui permettrait l'entrée d'un texte libre

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3560]
et si cette case est sélectionner, cela pourrait afficher une zone de texte "si autre, précisez"

**Comment by fredZen** [comment]
Si c’est issu d’une demande de support, tu peux rajouter la référence, et un label « à communiquer » STP ?

**Comment by emsnytech** [comment]
HUm, pas d’accord... on veut souvent des listes fermées. Cela doit rester une option.

**Comment by benjaminhenkel** [comment]
HS  29902

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/87059/admin-listes-deroulantes-avec-une-option-autre-qui-permet-dentrer-un-texte-libre
