### ISSUE TITLE
ETQ Administrateur : nouveau et dernier champs masqué

### ISSUE THREAD

**Issue by guillaumelevieux** [betagouv/demarches-simplifiees.fr#3570]
![image](https://user-images.githubusercontent.com/25955430/54023601-ab37bc80-4195-11e9-9147-2f5458ed3196.png)

Une partie du champs est masqué et devient difficile à éditer.

**Comment by emsnytech** [comment]
J'ai le même pb sur iPad

**Comment by guillaumelevieux** [comment]
Au passage, retrouver la possibilité de classer les champs par numéro d'ordre serait pratique.
