### ISSUE TITLE
ETQ instructeur je souhaite que le mail de déicsion soit envoyé aux différentes parties prenantes du dossier

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3581]
Situation actuelle : le mail de décision n'est envoyé qu'à l'usager. 
Situation souhaitée : le mail de décision est envoyé à l'ensemble des personnes impliquées sur l'outil.

Cas d'usage : Je demande l'avis d'un chef de service sur une demande d'un menbre de ses équipes. Je souhaite l'avertir de la décision qui a été rendue sur cette demande.

A communiquer : pipe 2316

**Comment by emsnytech** [comment]
Bonne idée ... mais délicat... sur quel fondements enverrons nous la décision ? A qui, aux invités ? A ceux qui donnent des avis ?
L’agent instructeur choisi. ?
Cela pourrait etre la bonne approche, mais lui demande une tache en plus ( on a déjà la vue « personnes impliquées...qui peut servir de base, en les invitant à revoir le dossier parce qu’une décision a été prise. C’est juste une invitation à aller voir le dossier...)

**Comment by Benjamin-Doberset** [comment]
Je suis assez pour l'idée d'envoyer une notification aux personnes impliquées en leur disant qu'une décision a été rendue

**Comment by kemenaran** [comment]
Déplacé dans https://demarches-simplifiees.featureupvote.com/suggestions/88275/instructeur-envoyer-lemail-de-decision-aux-differentes-parties-prenantes-du-doss
