### ISSUE TITLE
ETQ administrateur, je veux pouvoir modifier l'ordre des champs de façon plus claire

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3603]
Difficile de comprendre de prime abord que les deux lignes noires servent à ordonner les champs, 
je propose qu'on les remplace par des flèches.

![Capture d’écran 2019-03-12 à 17 16 27](https://user-images.githubusercontent.com/40801449/54216947-f67e0200-44ea-11e9-89e9-ca779c0830a8.jpg)
![logo-admin](https://user-images.githubusercontent.com/40801449/54216948-f67e0200-44ea-11e9-9a95-917eab4a726d.jpg)

**Comment by Keirua** [comment]
on a ça qui me semble répondre au problème donc je clos:
![image](https://user-images.githubusercontent.com/1223316/62298492-6299dc00-b473-11e9-9392-b0e532c2aaa7.png)
