### ISSUE TITLE
ETQ Administrateur je souhaiterais que les avis externes soient entièrement paramétrables

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3605]
Sur le modèle des annotations privées pour lesquelles on peut refaire un formulaire entier (différents champs de différents types).

à communiquer HS #13813

**Comment by kemenaran** [comment]
J'ai l'impression qu'on ne va pas se lancer là dessus de si tôt, et que le sujet n'est pas remonté depuis. Je ferme.
