### ISSUE TITLE
ETQ Admin, je souhaite remplir le lien internet au moment de la publication

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3609]
Situation actuelle : le lien vers le site internet est demandé en option dans l'onglet description
Situation souhaitée : plus de  champ

Raison : 
- n'apporte rien : l'usager vient de ce site et si l’instructeur veut transmettre de nouveau ce lien il peut le faire dans la description.
- source de confusion : l'administrateur ne sait pas forcément quoi mettre et perds du temps dessus.

**Comment by emsnytech** [comment]
Je ne suis pas d’accord avec cette suppression.
Le lien vers la page internet de publication du lien est au contraire une donnée essentielle pour garantir que nous n’avons pas de lien direct.
C’est me concernant une information qui permet de voir si le travail de publication est bien fait.
Par contre, cette information, qui arrive en fin de process de création d’une démarche, devrait plutôt etre dans l’onglet publication.

**Comment by Benjamin-Doberset** [comment]
trés bien pour le mettre dans l'onglet publication

**Comment by Keirua** [comment]
fonctionnalité mergée -> je clos
