### ISSUE TITLE
ETQ administrateur je veux pouvoir faire parvenir l'attestation à un tiers

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3610]
Associer les tiers intéressés en fonction du remplissage d'un champ spécifique (par exemple un champ commune, si c'est telle commune, alors l'adresse de tel tiers est la suivante etc...) en leur envoyant la copie d'une attestation.

Valeur potentielle 50,000

A communiquer 13859

**Comment by emsnytech** [comment]
Il me semble que cette issues est à rapprocher d’un autre de @Benjamin-Doberset qui vise à informer plusieurs personnes des décisions prises #3581
Mais tel que décrite, cela ne dit pas de quelle procédure il s’agit.
Et cela se rapproche aussi du sujet « conditionnel » et « routage »

**Comment by kemenaran** [comment]
Je fusionne dans #3581
