### ISSUE TITLE
ETQ Super Admin je veux avoir le code postal de l'usager sur HS

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3612]
Notamment pour numéro NEPH, permis, CAF, évite des échanges de mails superflux.

**Comment by kemenaran** [comment]
@philemon95 tu as une idée de comment on pourrait l'obtenir ? En demandant à l'usager, ou tu vois un autre moyen ?

**Comment by philemon95** [comment]
yep un nouveau champ "code postal" juste après le numéro de dossier, ça me semble le plus simple :)

**Comment by kemenaran** [comment]
Ok :)

Mmm, mais du coup ça m'inquiète un peu de demander encore une information en plus à tous les usagers qui nous écrivent – sachant que dans la plupart des cas on ne s'en servira pas.

Toi qui a une vue sur le support, tu crois que ça serait un bon rapport coût/bénéfices ?

**Comment by philemon95** [comment]
Il serait intéressant de mettre la possibilité de faire apparaître ce champ uniquement pour les procédures relatives au permis de conduire, ce qui implique de créer une nouvelle option dans la liste "Votre problème" (et un texte qui renvoie au gitbook sur les différentes démarches qui existe).

**Comment by kemenaran** [comment]
@ndrianab ça te semble encore utile ?

**Comment by kemenaran** [comment]
Je ferme pour cause d'inactivité.
