### ISSUE TITLE
ETQ instructeur je veux pouvoir modifier facilement la décision d'un dossier

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3613]
Dans les cas où on souhaite passer un dossier refusé / classé sans suite en accepté car de nouvelles pièces ont été communiquées.
On laisse l'impossibilité, sauf cas exceptionnel, de changer la décision d'un dossier accepté.

à communiquer HS #13903

**Comment by LeSim** [comment]
closed by #3683
