### ISSUE TITLE
ETQ Admin je souhaite un nouvelle présentation de la proposition particulier dans la page de description

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3616]
Situation actuelle : 
Particuliers
Cette démarche s'adresse à un public qui ne possède pas (ou pas encore) de numéro SIRET, qui doivent donc s'identifier en tant que personne physique.
- Donner la possibilité de renseigner un SIRET au cours de la construction du dossier.
- Demander la date de naissance.

Problème : ce n'est pas du tout clair pour l'usager, on a un taux d'erreur important

Situation souhaitée : 

Un titre : A qui s'adresse ma démarche?

En dessous de ce titre, une phrase en gras "Ma démarche s'adresse à un particulier"
En dessous en normal : En choisissant cette option, l'usager devra renseigner son nom et prénom avant d'accéder au formulaire

En dessous, un phrase en gras : "Ma démarche s'adresse à une personne morale"
En dessous en normal : En choisissant cette option, l'usager devra renseigner son n°SIRET. Grâce à l'APIentreprise, seront alors automatiquement remontées les informations sur la personne morale type raison social ou adresse du siège social.

En dessous en gras : Si votre démarche s'adresse indifféremment à une personne morale ou un particulier choisissez l'option "Particuliers". Vous pourrez utilisez le champ SIRET directement dans le formulaire.

![image](https://user-images.githubusercontent.com/36986044/54372749-493af380-467c-11e9-877d-17284f8fa5ba.png)

**Comment by kemenaran** [comment]
Ow yeah ❤️ Tellement. Ça me semble une bonne interface, tout ça.

**Comment by kemenaran** [comment]
Corrigé par @Keirua 

![60825512-1fb65280-a1ac-11e9-962d-e1aae6b27941](https://user-images.githubusercontent.com/179923/61702914-dbe15280-ad40-11e9-85ae-a3f29207bf18.png)
