### ISSUE TITLE
ETQ Usager je souhaite désactiver la roulette de la souris pour changer la valeur des champs contenant des nombres

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3631]
Situation actuelle : Lorsque j'écris un nombre, ce dernier peut changer avec la roulette de la souris. Le problème c'est que si je scroll down pour aller vers les champs en dessous sans avoir désélectionner le champ mon nombre varie sans que je m'en apperçoive.

Situation souhaitée : il n'est plus possible de changer le nombre avec la roulette

**Comment by Keirua** [comment]
clone de https://github.com/betagouv/demarches-simplifiees.fr/issues/3983 plus fourni
