### ISSUE TITLE
ETQ Admin je souhaite pouvoir fixer un nombre limite de dossiers déposés

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3639]
pour l'utilisation de DS pour l'inscription à des évènements par exemple.

à communiquer HS#14125

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/88272/administrateur-fixer-un-nombre-limite-de-dossiers-deposes
