### ISSUE TITLE
Gérer l'envoi de notifications sur le modèle

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#364]
Utiliser Dossier#send_notification_email au lieu de le faire sur le controlleur

**Comment by kemenaran** [comment]
C'est maintenant ce qu'on fait ; je ferme.

(Pour ce que ça vaut je suis un peu sceptique sur cette approche ; je mettrais bien ça dans un service. Mais bon :) )

**Comment by gregoirenovel** [comment]
Je rouvre car on fait `NotificationMailer.send_initiated_notification(@dossier).deliver_later` dans `new_user/dossiers_controller.rb`, qui pour moi devrait être geré sur le modèle
