### ISSUE TITLE
ETQ Usager je veux que l'on me propose france connect quand je veux commencer une démarche

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3640]
Situation actuelle : 
![image](https://user-images.githubusercontent.com/36986044/54626065-bbdb1300-4a70-11e9-9f78-4d66b98f2c71.png)

Ce n'est pas clair car on ne comprend pas qu'on peut se connecter avec FC, on a l'impression qu'il faut obligatoirement un compte DS

Situation souhaitée : mettre un bouton FC en plus

**Comment by emsnytech** [comment]
Super !
