### ISSUE TITLE
ETQ Admin quand je clone ma démarche et archive l'ancienne, je veux que les dossiers soient quand même soumis

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3649]
aujourd'hui, si l'admin clone une démarche A, il en résulte une démarche B. Si la démarche B prend le même URL que la démarche A, alors la démarche A est archivée et les brouillons dessus ne peuvent plus être soumis (également enjeu de clarification de ce message d'erreur).

**Comment by kemenaran** [comment]
Maintenant on peut soumettre les brouillons sur une démarche re-publiée (@tchak tu confirmes ?)
