### ISSUE TITLE
ETQ Usager je souhaite voir la description de la demarche lorsque j'utilise mon smartphone

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3658]
Le responsive ne fonctionne pas pour la description de la procédure, dommage pour quelqu'un qui n'utilise que son téléphone
HS # 14195

**Comment by kemenaran** [comment]
Oui, c'est le scandale de notre part.

La raison pour laquelle on masque le texte, c'est qu'il peut être très long, et que les boutons d'actions sont en dessous (donc potentiellement très loin).

On peut donc :

1. Soit afficher les 1ères lignes de la description, et un bouton "Afficher tout" au besoin (mais c'est un peu de taf)
2. Soit faire flotter les boutons d'action en bas de l'écran (mais ça bouffe de l'espace vertical précisément quand on en a besoin.

Pour l'instant on part plutôt sur la 1ère solution, mais ça se discute…

**Comment by kemenaran** [comment]
(Je rajoute cette issue à la liste "Priorisé", bien qu'on en ait pas parlé ensemble, pour deux raisons :

- J'ai très honte de ce truc, et je voulais vraiment m'en occuper vite ;
- Ça nous a été signalé hier par des gens de la French Tech

Si ça vous gonfle que je rajoute ce truc en "priorisé" à l'arrache (ce qui est carrément légitime), dites moi, et je le met en pause jusqu'à la prochaine priorisation.)

**Comment by kemenaran** [comment]
J'ai commencé à faire des tests.

## Position: fixed

Ça rend bien.

Avantages :

- Pur CSS
- Les boutons sont vraiment visibles tout le temps

Inconvénients :

- Difficile de calculer le padding nécessaire en bas de la page
- En fonction de la taille du texte, il se peut qu'on aie la place d'afficher les boutons inline, mais qu'on les fasse flotter bêtement à la place.

### Oh comme ça rend bien sur mobile

<img src="https://user-images.githubusercontent.com/179923/55177882-8b882880-5184-11e9-8e7f-2da4b5bb4018.png" width="375" />

### Oh comme ça rend mal si l'écran est grand et le texte finalement pas si long

![Capture d’écran - 2019-03-28 à 18 06 16](https://user-images.githubusercontent.com/179923/55177902-9a6edb00-5184-11e9-8cbc-a2c515d51a4e.png)

**Comment by kemenaran** [comment]
Deuxième essai, après le `position: fixed` qui n'était pas si fou.

# Bouton "Afficher la description complète"

Sur les petits écrans, la hauteur de la description est limitée à 25 % de l'écran.

Si le texte ne rentre pas dans l'espace disponible, un bout de Javascript le remarque, et affiche un bouton "Afficher la description complète". Quand on clique dessus, la description complète est rendue entièrement visible.

Tout ça est responsive, et réagit correctement aux changements de taille d'écran (du genre "rotation d'une tablette").

## Quand le texte est trop long

![Texte long](https://user-images.githubusercontent.com/179923/55330855-63edd480-5492-11e9-921d-554f47eea407.gif)

## Quand le texte rentre dans l'espace

Dans ce cas on n'affiche pas de bouton.

<img src="https://user-images.githubusercontent.com/179923/55330880-71a35a00-5492-11e9-98bd-0d5f48c0aa65.png" width=375 />

## Quand l'écran est relativement grand

Quand il y a plus de place, une plus grande portion du texte est affichée – mais il est tronqué malgré tout.

![Grand écran](https://user-images.githubusercontent.com/179923/55331016-b929e600-5492-11e9-9aba-7d8774a18419.png)

**Comment by kemenaran** [comment]
Je vais partir sur la solution avec un bouton, plutôt que le fixed. À l'usage ça a vraiment l'air mieux.

**Comment by emsnytech** [comment]
Yes !
