### ISSUE TITLE
ETQ Instructeur je veux que la messagerie soit "gelée" pour l'usager une fois que le dossier a été archivé

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3663]
Car sinon, pas de notification à l'instructeur, ce qui peut être source de frustration. 
Je suggère donc de bloquer la messagerie une fois un dossier archivé/ une fois la décision prise, ou de laisser les notifications sur les dossiers archivés.

**Comment by kemenaran** [comment]
C'est une partie extraite du cadre plus large de #3663.

**Suggestion d'implémentation :**

- Quand le dossier est terminé, désactiver le champ de messagerie.
- En dessous du champ grisé, un pavé de texte indique "Ce dossier a été archivé : la messagerie n'est plus disponible. Pour contacter l'administration, utilisez les coordonnées ci-dessous, en précisant votre numéro de dossier 'XXXXX'" + pavé des infos du service.

**Comment by n-b** [comment]
fixed by #3979
