### ISSUE TITLE
ETQ Usager lorsque je veux déposer un dossier sur une démarche en test sans être connecté on m'indique que la démarche n'existe pas

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3664]
Situation actuelle : je suis un administrateur, je partage mon lien test avec un collègue. Celui-ci clique dessus mais n'est pas encore connecté. Il clique sur j'ai déjà un compte et s'identifie . Malheureusement après, on lui indique que la démarche n'existe pas. Il doit donc cliquer de nouveau sur le lien pour y accéder.

Situation souhaité : après m'être identifié je suis redirigé vers la démarche de test.

**Comment by kemenaran** [comment]
Je viens de tester : ça fonctionne maintenant.
