### ISSUE TITLE
ETQ expert invité, je souhaite que les dossiers soient classés par type de démarche

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#3667]
Comme c'est le cas pour les instructeurs. 
@S.Zobel (pref Charente Maritime)

**Comment by Keirua** [comment]
on peut probablement faire cette séparation pour les usagers également, afin d'uniformiser les vues

**Comment by krichtof** [comment]
Pour un expert, je propose dorénavant ceci

- [ ] Afficher pour une même procédure l'ensemble des dossiers pour un expert
- [ ] Afficher la liste des procédures pour lesquelles un avis est demandé à l'expert
