### ISSUE TITLE
ETQ expert invité, dans le cas d'un dossier lié à un autre dossier, je souhaite pouvoir accéder au dossier initial (chiffrage)

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#3669]
Un expert qui consulte un dossier lié à un autre dossier n'a pas de lien actif vers le dossier antérieur. Le numéro du dossier antérieur qui normalement est clivable pour les instructeur ne l'est pas pour les experts. 
@S.Zobel (pref Charente Maritime)

### Cas d'usage

Cas d'usage DETR

Comme la commune doit déposé une demande auprès de la préfecture et du département, un dossier structure et deux dossiers filles (un pour pref, un pour dept) ont été mis en place afin de réduire les informations à produire en double par la commune.

Durant l'instruction, un instructeur pref doit consulter les autres services de l'Etat sur les dossiers. Dans la situation actuelle, il nomme en avis d'expert ces services. Le problème c'est qu'il sait quel service il doit nommer lorsqu'il lit le dossier filles (puisque c'est ce dernier qui est spécifique au projet et qui conditionne donc quel service de l'Etat il faut consulter). Ainsi, il doit le nommer sur le dossier fille puis regarder le numéro du dossier mère, retrouver le dossier mère et ouvrir le dossier et nommer de nouveau le service de l'Etat.

L'objectif serait que l'instructeur n'ai pas à effectuer toute la tache, juste à nommer une fois l'avis.

### Cadrage

Lors de l'invitation d'un expert, il est automatiquement invité au dossier lié

**Comment by CamilleGarrigue** [comment]
Compliqué de gérer les droits d'accès aux dossiers liés pour les experts. 
C'est une feature qui est très utile pour de nombreuses démarches dont les demandes de subventions. 
Il faut réfléchir à une autre solution sans ajouter une couche de complexité à la feature actuelle.

**Comment by emsnytech** [comment]
Je confirme, ce point est à traiter?
Peut être faudrait il créer un statut de dossier en lecture seule, seulement réservé au dossier ( donc sans la messagerie ni autre chose...

**Comment by benjaminhenkel** [comment]
Cadrage : Lors de l'invitation d'un expert, il est automatiquement invité au dossier lié

**Comment by Benjamin-Doberset** [comment]
Cas d'usage DETR

Comme la commune doit déposé une demande auprès de la préfecture et du département, un dossier structure et deux dossiers filles (un pour pref, un pour dept) ont été mis en place afin de réduire les informations à produire en double par la commune. 

Durant l'instruction, un instructeur pref doit consulter les autres services de l'Etat sur les dossiers. Dans la situation actuelle, il nomme en avis d'expert ces services. Le problème c'est qu'il sait quel service il doit nommer lorsqu'il lit le dossier filles (puisque c'est ce dernier qui est spécifique au projet et qui conditionne donc quel service de l'Etat il faut consulter). Ainsi, il doit le nommer sur le dossier fille puis regarder le numéro du dossier mère, retrouver le dossier mère et ouvrir le dossier et nommer de nouveau le service de l'Etat.

L'objectif serait que l'instructeur n'ai pas à effectuer toute la tache, juste à nommer une fois l'avis.

**Comment by kemenaran** [comment]
Complément au cas d'usage :

Les communes déposent plusieurs dossiers de ce type. Elles ont donc besoin de ne pas avoir à ressaisir à chaque fois les informations de structure.

**Comment by kemenaran** [comment]
## Idée d'implémentation

Dans le formulaire "Inviter un expert", en dessous du champ "Adresse email", mettre une case à cocher en plus :

> [ ] Inviter aussi l'expert sur le dossier lié n° 1234

ou, s'il y a plusieurs dossiers liés :

> [ ] Inviter aussi l'expert sur les dossiers liés n° 1234, 5678 et 9101

**Raisonnement :** ça permet de signaler clairement la fonctionnalité, sans surprise pour les personnes qui invitent.

Après on peut voir si la case à cocher devrait être activée par défaut ou pas.
