### ISSUE TITLE
ETQ Admin, je veux que les données dans les champs répétables soient exportés dans l'API

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#3670]
`HS #13561` , en particulier les pièces jointes.

Voir aussi #3919

**Comment by kemenaran** [comment]
@tchak reprend sur ce sujet, mais pas avant la mi-mai 2019.

On va envoyer un email aux administrateurs qui ont les champs répétables activés pour leur préciser que l'export ne sera pas disponible tout de suite.

**Comment by Wa5p** [comment]
Quel est l'état d'avancement de l'export des données des champs répétables via l'API ?

**Comment by kemenaran** [comment]
C'est un sujet priorisé à court terme. Normalement ce devrait être disponible d'ici un mois ou deux. (ping @tchak)

**Comment by Wa5p** [comment]
@kemenaran Merci pour l'information.
D'ici là, nous utiliserons des champs dupliqués fixes au sein de nos formulaires.
