### ISSUE TITLE
ETQ Admin, j'aimerai pouvoir rajouter un type de champ dossier lié dans un bloc répétable

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#3674]
`hs #14281`

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/77364/administrateur-pouvoir-mettre-un-champ-lien-vers-un-autre-dossier-dans-un-bloc-r
