### ISSUE TITLE
Supprimer la description du champ dans le placeholder "Zone de texte"

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#3682]
Quand un Usager voit un formulaire avec un champ "Zone de texte", la description du champ apparait à la fois entre le libellé et le champ et en placeholder dans le champ.

Ca fait trop d'avoir une répétition dans le texte et dans la zone de texte. 

@Hélène.BJ (DITP)

**Comment by kemenaran** [comment]
Suggestion d'implémentation : ne pas afficher la description du champ en placeholder (ne l'afficher que au dessus du champ).
