### ISSUE TITLE
ETQ instructeur je veux pouvoir repasser un dossier refusé ou classé sans suite en instruction

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#3683]
[CRPA L242-1](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000031366350&idArticle=LEGIARTI000031367657) creuser si on peut aussi donner le droit de réexaminer un dossier accepté.

**Comment by kemenaran** [comment]
- [ ] Ajouter un bouton "Repasser en instruction" pour les Instructeur :
	- Seulement si le dossier est Refusé ou sans-suite
	- Même si la démarche est archivée (parce que notamment les appels à projets traitent des dossiers archivés)
- [ ] Si le dossier est Accepté, mettre un texte qui explique pourquoi on ne peut pas repasser le dossier en Instruction
- [ ] Envoyer un email à l'Usager lors du re-passage en instruction ("Votre dossier a été ré-ouvert")

## Questions ouvertes

- Est-ce qu'on permet à l'instructeur de motiver le re-passage ? Ça peut être bien, mais pas pour l'instant.
