### ISSUE TITLE
Les dates s’affichent en anglais

### ISSUE THREAD

**Issue by fredZen** [betagouv/demarches-simplifiees.fr#3710]
Constaté sur les champs date, les champs date et heure, ainsi que la date de création d’entreprise pour le champ SIRET et le SIRET en début de démarche, en vue instructeur comme en vue usager.

`HS #14591` `HS #14531`

Peut-être dû à #3349 ?

Exemple :
![Screenshot from 2019-03-29 17-43-41](https://user-images.githubusercontent.com/356570/55248653-8392bc00-524a-11e9-8ce6-e5ce26251503.png)

D’autres dates s’affichent bien en français, par exemple la date de dépôt

![Screenshot from 2019-03-29 17-48-08](https://user-images.githubusercontent.com/356570/55248808-da989100-524a-11e9-87ca-2cabdc0525c8.png)

**Comment by mmagn** [comment]
@pengfeidong j'ai approuvé un peu trop vite ta PR, il faut qu'on corrige ça demain, en attendant j'ai revert le commit.

**Comment by DanielBMY** [comment]
@fredZen nous avons eu le même constat ce lundi en lancement de Workinfrance dans le 93. Les agents étaient "surpris"
