### ISSUE TITLE
[RFC] Rediriger les réponses aux emails transactionnels vers l'administration

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#3715]
On a toujours un bon nombre d'emails au support qui sont du "Mauvais interlocuteur" : les Usagers répondent à un email transactionnel en cherchant à joindre l'administration – et tombent sur `contact@demarches-simplifiees.fr`, qui doit leur dire "Contactez plutôt l'administration".

L'expérience est assez mauvaise pour les Usagers – et nous ça nous génère beaucoup de support.

En même temps ça semble important que les Usagers puissent continuer à répondre aux emails (plutôt que d'avoir un `NOREPLY@demarches-simplifiees.fr`).

## Pistes envisagées

Une solution envisagée est de faire en sorte que les emails soient reroutés vers la messagerie du dossier (#1783). Mais c'est un peu compliqué : il faut parser les emails entrants, et tout.

Autre solution : **mettre l'email de l'administration en adresse de réponse**. Comme ça quand les gens répondent à l'email (ce qui n'est pas l'idéal), ils tombent au moins sur l'administration.

**Avantages**

- Pour les emails transactionnels, l'administration est de toute façon un meilleur contact pour l'usager que le contact technique de DS.
- Maintenant que les emails transactionnels vont être plus brandés avec la démarche, et moins avec DS, c'est logique que la réponse aille à l'administration.
- C'est très rapide à implémenter.

**Risques**

- L'administration peut faire la sourde-oreille. (Mais ça ne sera pas pire que nos réponses "Vous contactez la mauvaise personne")
- Si la réponse concerne un dossier déposé, la bonne redirection serait la messagerie (#1783). Et il se peut que l'administration ignore juste le message – au lieu de répondre "Utilisez plutôt la messagerie". Dans ce cas on aura empiré la situation pour l'Usager.

Personnellement je suis plutôt favorable. Ça me semble plutôt un bon changement pour l'usager, et ça devrait permettre de réduire notre charge.

Vous en pensez quoi ? (/cc @philemon95 @chaibax)

**Comment by philemon95** [comment]
très chaud pour l'option simple, qui me paraît rapidement actionnable 👍

**Comment by chaibax** [comment]
C'est une bonne solution, qu'on peut mettre en place rapidement 👍 
On pourra toujours avancer ensuite sur la #1783

**Comment by LeSim** [comment]
Tu n'est pas inquiet sur notre déliverabilité ?

**Comment by chaibax** [comment]
Ça risque d'impacter oui, mais ce n’est pas comme si on changeait le from de l'email. Il faudrait surveiller le taux d'ouverture (et donc activer le tracking des ouvertures pour le sous-compte mailjet). 

Ça reste une solution provisoire en attendant la #1783 qui fêtera cette semaine ces un an :)

**Comment by kemenaran** [comment]
Après discussion avec @benjaminhenkel, on se dit qu'il y a deux catégories de "Mauvais interlocuteur" :

1. L'usager a déjà essayé de contacter l'administration, il nous écrit en désespoir de cause => on veut rediriger vers l'administration autant que possible.
2. L'usager a cliqué sur "Répondre à l'email" par erreur : en vrai il aurait dû utiliser la messagerie.

D'après @benjaminhenkel, au support on reçoit beaucoup plus de 1. que de 2.

Donc si on redirige les emails vers l'administration, on va surtout les spammer avec des erreurs de produit qui sont plutôt de notre fait.

Une idée serait plutôt de rajouter des boutons Call-to-action très clairs dans les emails, pour que les usagers les cliquent (au lieu de faire un "Répondre"). Du genre "Voir le message dans la messagerie", "Répondre à ce message", etc.

**Comment by emsnytech** [comment]
Je propose dans la réponse d’ajouter le lien vers services public.fr.
Ils nous ont proposé il y a longtemps le lien vers leur boîte au lettre aussi
C’est eux qui sont légitimes pour les renseignements administratifs

**Comment by kemenaran** [comment]
Discuté en équipe :

- La solution idéale, ça serait la redirection des emails.
- Mais c'est une solution coûteuse en terme de run : monitorer que le service externe fonctionne, qu'il est bien payé, qu'on ne perd pas les emails des gens, etc.
- On part donc plutôt sur l'amélioration des boutons d'action dans un 1er temps, et on voit où ça nous mène.

**Comment by kemenaran** [comment]
À priori, rediriger les emails des Usagers vers l'email de contact de l'administration est trop risqué : on a aucun moyen de savoir si l'administration va lire le message.

On a de meilleures pistes pour ça (comme #4060 ou #1783). Je ferme.
