### ISSUE TITLE
ETQ Instructeur, je veux que les sauts de ligne des avis soient respectés

### ISSUE THREAD

**Issue by LucSalommez** [betagouv/demarches-simplifiees.fr#3738]
Bonjour,

Contexte du problème :

Je dois donner mon avis sur différents dossiers dans le cadre d'une sélection de projets.
En écrivant mes avis, je prends soin d'aérer mon texte avec des retours à la ligne, des tirets etc ...

Problème rencontré :

Lorsque je valide mon avis, en bas de page se trouve une liste des avis donnés par toutes les personnes concernées par ce dossier.
Mon avis apparaît donc dans cette liste, mais cette fois le contenu est dépourvu de tout retour à la ligne, laissant ainsi place à un énorme pavé indigeste très difficile à lire.

Solution proposée :

Serait-il donc possible de conserver le formatage lors de la visualisation des avis s'il vous plaît ?

Cordialement,
Luc.

**Comment by kemenaran** [comment]
Effectivement, les sauts de lignes sont ignorés. Ça devrait pouvoir se corriger facilement.

**Comment by kemenaran** [comment]
@LucSalommez merci de nous avoir remonté le problème, et pour la description précise de ce qui se passait et où.

C'est corrigé, et ce sera disponible en production sur demarches-simplifiees.fr dans la journée.

**Comment by LucSalommez** [comment]
Merci d'avoir apporté un correctif aussi rapidement.
Bonne journée et bon courage !
