### ISSUE TITLE
ETQ Administrateur je souhaiterais pouvoir supprimer un instructeur

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3760]
Pour l'instant, seulement possibilité de l'"enlever" de la démarche mais pas de supprimer l'adresse mail de la liste

**Comment by kemenaran** [comment]
Il y a la possibilité, depuis un écran un peu planqué.

Ça va être revu au moment de refaire l'interface instructeur au nouveau design.
