### ISSUE TITLE
ETQ Usager je souhaite pouvoir supprimer une pièce justificative que j'ai téléchargé

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3771]
Situation actuelle : après avoir télécharger une pj, je peux la modifier mais je ne peux pas la supprimer

Situation souhaitée : je peux supprimer une pj

**Comment by kemenaran** [comment]
On peut bien supprimer une pièce jointe en ce moment.

Est-ce que ça concerne les anciennes PJ, peut-être ? Si oui, ça va être migré très vite.

**Comment by kemenaran** [comment]
Fait avec la migration des anciennes PJ.
