### ISSUE TITLE
ETQ Usager, je veux savoir que je peux enregistrer mon brouillon

### ISSUE THREAD

**Issue by D-LP** [betagouv/demarches-simplifiees.fr#3776]
Est-il possible d'afficher le bouton « Enregistrer le brouillon » également en haut du formulaire ?

**Comment by kemenaran** [comment]
Oui, c'est une bonne idée.

Sur écrans de PC de bureau ça devrait bien passer. Après il faut voir ce que ça donnerait sur écran mobiles.

C'est sans doute aussi lié à l'auto-enregistrement des brouillons qu'on aimerait bien mettre en place.

**Comment by kemenaran** [comment]
Aujourd'hui on affiche le bouton "Enregistrer le brouillon" dans une barre flottante en bas de l'écran (et on se dirige vers du brouillon automatique).

Le bouton est donc assez visible aujourd'hui.
