### ISSUE TITLE
ETQ Instructeur je souhaite pouvoir joindre une PJ à une demande d'avis

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3785]
ou proposer un modèle à remplir par l'expert qu'il peut ensuite retransmettre dans son champ PJ.

à communiquer HS 15278 + admin # 4020

**Comment by LeSim** [comment]
`HS #15256`

**Comment by CamilleGarrigue** [comment]
Fermeture car doublon de la précédente #3539

**Comment by kemenaran** [comment]
À proposer comme contribution externe
