### ISSUE TITLE
ETQ Instructeur, je souhaite que les champs répétables soient mieux cernées lors de la lecture de la demande

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#3788]

**Comment by tchak** [comment]
Ça veut dire quoi ?

**Comment by emsnytech** [comment]
On a un petit pb d’ergo. Quand un instructeur découvre le dossier déposé avec des champs répétable, leur apparence ne permet pas facilement de les discerner. Peut etre un cadre léger autour des ceux ci permettrait de mieux les lire et les apercevoir.

**Comment by tchak** [comment]
ok

**Comment by benjaminhenkel** [comment]
#4567

**Comment by benjaminhenkel** [comment]
même issue
