### ISSUE TITLE
La partie avis d'un dossier est encore visible sur le dossier meme quand celui-ci est fermé

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#379]
Quand il est accepté / refusé / sans suite, on peut encore demander / remplir les avis

- ne pas permettre à un gestionnaire de redemander un avis
- afficher "L'instruction de dossier est teminée" pour les experts invités
  * afficher ce message également quand l'expert invité a *déjà* rendu son avis

Lié : #381

**Comment by kemenaran** [comment]
Aujourd'hui on ne permet plus à un Instructeur de re-demander un avis.

**Comment by gregoirenovel** [comment]
Par contre le remplissage est encore possible ?

**Comment by fredZen** [comment]
Garder à l’esprit #3400 et #3401
