### ISSUE TITLE
horodatage des dossiers

### ISSUE THREAD

**Issue by tchak** [betagouv/demarches-simplifiees.fr#3790]
## Enregistrement des opération
La table `operation_logs` contient les colonnes suivantes : `id`, `dossier_id`, `operation`, `author`, `subject`, `operation_date`, `keep_until`, `hash`. La colonne `subject` est un attachement `active_storage`. Le `hash` c'est un `SHA256` de toutes les colonnes sauf `keep_until`.

## Horodatage
1. On sélectionne les opérations de la journée
2. On crée un fichier texte `timestamp_yyyy_mm_dd.txt` contenant la liste des `hash` des opérations associées aux `id`.
3. On signe le fichier avec le service d’horodatée.
4. On upload le fichier texte et la signature dans le cold storage.

## Supprimer les vieilles données
1. Une tache `cron` sélectionne toutes les `operation_log` avec `keep_until` dans le passé.
2. On supprime toutes les operation_log sélectionnées

## Vérifier la validité d'une décision
1. Retrouver les `operation_log` du dossier/démarche en question.
2. Si l'`operation_log` n'existe pas – la durée de conservation du dossier/démarche est expirée.
3. En utilisant la `operation_date` retrouvez le fichier texte et la signature.
4. Verifier que l'`id` et le `hash` sons dedans.
5. Validée avec le service d’horodater le fichier texte.

### Service d’horodatage à utiliser
https://www.universign.com/fr/horodatage/

**Comment by kemenaran** [comment]
Les dossiers sont maintenant horodatés.

Pour l'instant on ne stocke pas le dossier sérialisé avec son digest signé.

C'est cool parce qu'on ne stocke pas de données personnelles, mais on n'est pas à l'abri d'un changement de méthode de sérialisation qui invaliderait les digests.

Est-ce qu'on veut stocker le dossier sérialisé avec le système de PJ chiffrées, ou est-ce on considère que c'est bien comme ça ?

**Comment by kemenaran** [comment]
Normalement on peut activer ça, maintenant qu'on a aussi le chiffrage sur les PJ.

**Comment by kemenaran** [comment]
Vu en point pris : @tchak active le feature-flag.

**Comment by kemenaran** [comment]
@tchak a activé le feature-flag.
