### ISSUE TITLE
ETQ instructeur je veux pouvoir voir les personnes impliquées sur un dossier archivé

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3793]
l'option archivage efface les personnes impliquées (même si on désarchive), ce qui est fâcheux

à communiquer: HS 15414

**Comment by philemon95** [comment]
pour être tout à fait exact, après de nombreux essais, si un dossier est suivi par l'instructeur A et l'instructeur B, une fois traité (par l'un ou l'autre), si l'instructeur A archive le dossier, alors on ne verra plus que l'instructeur B dans les personnes qui suivent le dossier dans l'onglet "Archivés". Ce qui est contre-intuitif :)

**Comment by Benjamin-Doberset** [comment]
probleme aussi pour l'ARS ARA
