### ISSUE TITLE
 API en écriture

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/demarches-simplifiees.fr#3795]
L’objectif de l’API en écriture est de pouvoir mettre à jour un dossier à partir d’un SI métier dans lequel l’instruction aura été réalisée.

Exemples :
· Changement du statut du dossier
· Changement des annotations avec dates associées

**Comment by emsnytech** [comment]
précision sur les attentes en API en écriture.
- Le changement de statut des dossiers :
Il s'agit de modifier le champ « statut du dossier » tout au long de la procédure d'instruction du dossier depuis l'application de gestion sans que l'instructeur (PED) ait besoin de transiter par l'application DS.
Concrètement, l'interface entrante devra assurer les mises à jour de statuts suivantes dans DS pour assurer l'information des consultants (usagers) et assurer les envois de courriels automatiques d'information associés :
- attribution d'un dossier nouvellement arrivé à un évaluateur au sein du PED  (à voir car pas visible des consultants / procédure interne au PED pouvant être prise en charge dans l'outil de gestion a priori) ;
- rejet du dossier (et envoi d'un courriel associé par le PED indiquant le motif du rejet) ;
- passation du dossier en instruction et envoi du courriel automatique associé ;
- dossier traité / acceptation du dossier (et envoi de l'avis domanial par le PED)
- archivage du dossier (en interne à l'outil de gestion a priori).
Trois synchronisations par jour sont nécessaires.

**Comment by kemenaran** [comment]
Y'a des bouts de ça qui commencent à passer en prod.

@tchak j'ai vu que tu avais généré une documentation. Est-ce qu'on essaie de documenter ça sur doc.demarches-simplifiees.fr ?

**Comment by kemenaran** [comment]
J'ai l'impression que la majorité des fonctionnalités de l'API en écriture est en production.

Reste la documentation :

- [ ] Documenter l'API en écriture sur https://doc.demarches-simplifiees.fr/
- [ ] Mettre un lien vers la doc Netlify (et documenter le processus de déploiement de la doc ?)

**Comment by kemenaran** [comment]
La doc est là sur https://doc.demarches-simplifiees.fr/, et la doc netlify aussi. Je ferme, on pourra ouvrir des issues plus spécifiques sur l'API en écriture au besoin.
