### ISSUE TITLE
ETQ Usager je voudrais pouvoir faire plusieurs dossiers à la suite

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3800]
Proposition: une fois le message comme quoi le dossier a bien été transmis, pouvoir cliquer sur un bouton qui renvoie sur la page de la démarche (sans avoir à repasser par la liste de ses dossiers puis à cliquer sur le bouton "Actions"> "déposer un nouveau dossier".

**Comment by Keirua** [comment]
fait dans https://github.com/betagouv/demarches-simplifiees.fr/pull/4062
je clos
