### ISSUE TITLE
Ne pas montrer le contenu des dossiers instruits aux experts invités

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#381]
Les informer simplement avec le texte "L'instruction de ce dossier est terminé".

Ne montrer que l'avis qu'ils ont rendu (sans permettre l'édition).

Rationale :
- l'expert n'a pas a savoir si le dossier a été accepté ou non
- ils n'ont pas à avoir accès aux données du dossier une fois ce dernier instruit.

**Comment by fredZen** [comment]
Garder à l’esprit #3400 et #3401
