### ISSUE TITLE
ETQ administrateur je veux que l'heure de clôture automatique soit personnalisable

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3812]
par exemple pour fermer un AAP à 17h.
pourrait peut-être permettre de résoudre à court terme les problèmes rencontrés en outre-mer (en précisant que pour l'instant c'est horaire métropole...) 

à communiquer HS 15667

**Comment by kemenaran** [comment]
On précise maintenant que c'est les horaires métropole \o/ . Pour le reste, on pourra mettre ça dans feature-upvote au besoin.
