### ISSUE TITLE
[RFC] ETQ Super administrateur, je souhaite supprimer la liste des démarches de doc.demarches-simplifiees.fr

### ISSUE THREAD

**Issue by philemon95** [betagouv/demarches-simplifiees.fr#3813]
je propose de supprimer les deux pages suivantes: 
- [démarches les plus populaires](https://doc.demarches-simplifiees.fr/listes-des-demarches/demarches-les-plus-populaires)
- [liste des démarches par administration ](https://doc.demarches-simplifiees.fr/listes-des-demarches/liste-des-demarches)

qui présentent deux problèmes: 
- ne sont pas mises à jour
- peuvent laisser penser à certains administrateurs que les usagers pourront trouver ainsi les démarches (ce qui pourrait les dispenser de communiquer aux usager l'url)

je ne propose pas d'alternative suite à la suppression des deux pages

**Comment by kemenaran** [comment]
J'ai l'impression que pour l'instant on arrive à vivre avec ces pages. On laisse pour l'instant.
