### ISSUE TITLE
Les accents de certains emails ne sont pas affichés correctements

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#3835]
Dans le mail reçu sur ma boîte en tant qu'usager (test) les caractères accentués ne sont pas correctement affichés.
![image](https://user-images.githubusercontent.com/49941223/57080477-e4eaf680-6cf2-11e9-9369-587cdc7c46ad.png)

**Comment by kemenaran** [comment]
Effectivement, c'est un souci.

Quel est le logiciel utilisé pour lire cet email ?

**Comment by ErwanLHH** [comment]
Thunderbird 60.6.1 (32 bits) mais c'est très étrange, maintenant que je retourne sur le mail, il est correctement affiché...

**Comment by kemenaran** [comment]
Je pense que c'était un bug transcient, il ne nous a pas été remonté depuis. À ré-ouvrir au besoin.
