### ISSUE TITLE
ETQ Instructeur je souhaite que les instructeurs qui ont eu accés à un dossier demeurent répertoriés dans l'onglet personnes impliquées

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3842]
Situation actuelle : Lorsqu'un instructeur suit un dossier, on retrouve son adresse e-mail dans l'onglet personnes impliquées. Cependant, s'il arrete de suivre ce dossier, alors il disparait du dossier et nous n'avons pas de moyen de savoir qu'il y a eu accès. Cela pose un problème de traçabilité.

Situation souhaitée : Dés qu'un instructeur suit un dossier, il demeure intégré à la liste des personnes ayant eu accès au dossier. Le mieux serait que dès qu'un instructeur a ouvert le dossier il soit intégré à la liste.

Cette issue va aussi avec l'issue #3793

**Comment by Benjamin-Doberset** [comment]
lié à l'issue 3879

**Comment by DanielBMY** [comment]
Oui @Benjamin-Doberset : je vote pour !!!
