### ISSUE TITLE
J'aimerais pouvoir définir des champs obligatoires dans les annotations privées paramétrables selon l'état du dossier 

### ISSUE THREAD

**Issue by jpotel** [betagouv/demarches-simplifiees.fr#3890]
Certains champs de la partie annotation privée peuvent être utilisés dans la rédaction des courriels automatiques de modification d'état des dossiers. Hors, il n'y a pas de possibilité d'obliger le remplissages de ces champs avant le changement d'état et la réponse automatique devient incomplète. Pire, il n'y a même pas de vérification que l'enregistrement a été effectué avant le changement d'état (ex d'un instructeur qui a rempli un champ puis changé l'état du dossier en ayant oublié d'appuyer sur sauvegarder) .  

Bref l'idée serait de pouvoir dire qu'il est obligatoire de remplir tel et tel champs avant de modifier l'état d'un dossier.

**Comment by kemenaran** [comment]
Je comprends le besoin, effectivement.

Est-ce que ça fonctionnerait si on disait que les annotations privées obligatoires doivent obligatoirement être complétées avant la clôture du dossier (accepté/refusé/sans-suite) ?

Ou il faudrait être plus fin sur "Telle annotation est obligatoire pour passer dans tel état" ?

**Comment by jpotel** [comment]
Je pense qu'il faut proposer quelque chose d'assez fin pour chaque changement d'état à savoir :

- construction -> instruction
- instruction -> accepté
- instruction -> classé sans suite
- instruction -> refus

sachant qu'un même champs doit pouvoir être obligatoire pour plusieurs type de changement pour un dossier qui est déjà en instruction

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/98555/instructeur-rendre-des-annotation-privees-obligatoire-en-fonction-de-letat-du-do#comment185337
