### ISSUE TITLE
Pouvoir afficher la PJ ajoutée au moment de la décision (ou son lien) dans l'email de décision

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/demarches-simplifiees.fr#3909]
Peut-être ajouter une balise côté admin ? 
@A.Ortega (Minefi)

**Comment by emsnytech** [comment]
Yes !comme pour l’attestAtion

**Comment by Keirua** [comment]
fait dans https://github.com/betagouv/demarches-simplifiees.fr/pull/4104
