### ISSUE TITLE
ETQ Administrateur, si je valide ma démarche sans avoir mis un cadre juridique, la démarche est définitivement bloquée 

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#3918]
C'est à dire que même en mettant un lien valide, il m'est impossible de valider la démarche.
![gbdacjeenkhbcjpg](https://user-images.githubusercontent.com/28590367/58864935-ea52ac80-86b5-11e9-99e6-dc36e9aa3186.png)

**Comment by n-b** [comment]
Je n’arrive pas à reproduire… tu vois ça avec quel navigateur? C’est systématique?

**Comment by n-b** [comment]
Reproduit (sur la machine de @benjaminhenkel) sur Chrome 74/macOS 10.14.5 🙎
