### ISSUE TITLE
 ETQ Admin, je veux que les données dans les champs répétables soient dans les exports tableur

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#3919]
Pour exposer les champs répétables à tout le monde (#1769), il faut que les Admins puissent récupérer les données dans les exports tableur (Excel, ODT, etc).

**Comment by kemenaran** [comment]
C'est dispo dans l'export v2, qui est encore derrière un feature flag.

**Comment by chaibax** [comment]
Retour d'un administrateur  : 

> En fait, dans l'idéal, il faudrait que les informations des blocs répétables soient cumulées sur un seul et même ongletSi l'application ne le fait pas, il va falloir le faire manuellement, ce qui ne serait pas trop un problème avec quelques dossiers, mais qui devient beaucoup plus indigeste avec 100 ou 200 demandes.

**Comment by kemenaran** [comment]
@chaibax j'ai testé le nouvel export : en fait c'est bien le fonctionnement attendu.

Si un formulaire a deux bloc répétables différents (par exemple "Prénom-Nom 1 / Prénom-Nom 2 / …" et "Financeur 1 / Financeur 2 / …"), chaque bloc répétable a des colonnes différentes. C'est donc normal que chaque bloc répétable se retrouve dans des onglets différents.

Après, peut-être que le besoin des instructeurs, c'est pas tant d'avoir la donnée structurée que d'avoir tout concaténé dans un tableau. On pourrait proposer une option à l'export, pour ça, si c'est nécessaire.

**Comment by kemenaran** [comment]
En fait c'est bien cassé :

    L'export génère un onglet par champ répétable par dossier
    Ça fait même crasher l'export Excel
    (Par ailleurs l'export est très, très lent)

**Comment by kemenaran** [comment]
@tchak j'ai l'impression que #4151 devrait résoudre le problème. C'est bon pour toi, on peut fermer ?

**Comment by tchak** [comment]
Oui
