### ISSUE TITLE
ETQ Administrateur, je souhaiterais avoir un champ pour mettre à disposition un modèle

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#3929]
Comme les PJ mais sans la possibilité d'importer 

Helpscout 17617

**Comment by kemenaran** [comment]
Je ne comprends pas trop la requête ?

**Comment by emsnytech** [comment]
re préciser en effet le cas d’usage concret .

**Comment by benjaminhenkel** [comment]
Des personnes souhaiteraient pouvoir mettre des documents à disposition de l'usager, sans lui laisser la possibilité d'en uploader un (comme c'est le cas actuellement)

**Comment by kemenaran** [comment]
Est-ce que ce n'est pas la fonction de la notice, par exemple ?

On parle de quel genre de documents ?

**Comment by emsnytech** [comment]
On a combien de sollicitations pour cette feature....

**Comment by benjaminhenkel** [comment]
La notice s'affiche en tant que guide de la démarche 
![Screenshot 2019-07-05 at 15 18 29](https://user-images.githubusercontent.com/28590367/60724976-2d63a200-9f38-11e9-847b-25a3713c5a11.png)

**Comment by benjaminhenkel** [comment]
Pour mettre un document à disposition, il me semble qu'on est obligé de faire comme ceci, ce qui n'est pas très clair
![Screenshot 2019-07-05 at 15 20 07](https://user-images.githubusercontent.com/28590367/60725101-87fcfe00-9f38-11e9-8aef-370f044ed342.png)

**Comment by kemenaran** [comment]
J'ai l'impression que les admins peuvent :

- soit renommer leur modèle en "Guide" ou "Notice"
- soit mettre un modèle attaché à un champ PJ

Je ferme pour l'instant, on réouvrira au besoin.
