### ISSUE TITLE
RFC ETQ Admin, je veux découvrir ce que DS fait économiser à mon Administration

### ISSUE THREAD

**Issue by chaibax** [betagouv/demarches-simplifiees.fr#3942]
L'idée est simple : envoyer un email aux administrateurs de DS pour qu'ils puissent connaitre facilement ce que DS fait économiser à leur administration .

L'email pourrait ressembler à cela .

![Capture d'écran 2019-06-10 15 50 57](https://user-images.githubusercontent.com/3593868/59200083-bd136c00-8b97-11e9-90cc-41fafa08f52d.png)

Il serait envoyé une 1re fois pour test, mais pourrait être envoyé chaque mois, et serait une sorte d'email de suivi de l'activité du compte, à destination des Admin.

Pour info : tout est prêt techniquement, 0 minute temps de dev

**Comment by kemenaran** [comment]
Ça m'a l'air assez cool.

J'imagine qu'il faut faire gaffe à ne pas spammer les admins (on peut envoyer tous les trois mois, par exemple). Mais ça peut être bien.
