### ISSUE TITLE
ETQ Instructeur, je souhaite connaitre le taux de conversion de ma démarche

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#3946]
Objectif : auto-amélioration de la démarche.

**Par exemple :**

- Sur 100 usager ayant un brouillon, 23 au soumis une démarche. => 23% de conversion). 

On pourrait mettre ça dans une page "Tableau de bord de la démarche", qui regrouperait plusieurs statistiques (comme par exemple #3945)

**Comment by chaibax** [comment]
**Iteration 1 :** 
Sur 100 usagers ayant au moins un brouillon, 23 ont soumis une démarche. => 23% de conversion. 

**Iteration 2 :** 
<img width="552" alt="Capture d'écran 2019-06-11 12 32 17" src="https://user-images.githubusercontent.com/3593868/59265130-0372d480-8c45-11e9-80b8-b0b467d1a1ef.png">

**Itération 3 :** 

Afficher le nombre de démarche a chaque étape en plus du % de conversion
Afficher le temps de passage moyen d'une étape a l'autre.
Afficher, pour la colonne traité, le détail : accepté, refusé, classé sans suite.
