### ISSUE TITLE
ETQ Instructeur, je veux savoir si mon appel à projet a des dossiers en cours

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#3948]
**Cas d'usage**

- En tant qu'Instructeur, mon appel à projet ferme dans deux jours – mais je n'ai que trois dossiers déposés. Je veux être rassuré sur le fait qu'il y a des dossiers en brouillon.

On pourrait par exemple afficher le nombre de brouillons (voir aussi #3947)

_En bonus, on pourrait permettre à l'Instructeur d'envoyer un message de relance aux gens qui ont un brouillon. Mais il faudrait limiter le spam, et savoir quelle adresse mettre en Reply-To._

**Comment by kemenaran** [comment]
Ça pourrait aller dans une page "Tableau de bord de la démarche", comme d'autres statistiques qu'on voudrait afficher, tiens.

**Comment by benjaminhenkel** [comment]
https://demarches-simplifiees.pipedrive.com/person/2250
