### ISSUE TITLE
ETQ Usager, je veux une message lors de l'invitation à modifier un dossier

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/demarches-simplifiees.fr#3974]
**Situation actuelle :**
Lorsque l’on clique sur le bouton « Inviter une personne à modifier ce dossier » dans l’application la  fenêtre suivante apparait:
<img width="427" alt="Capture" src="https://user-images.githubusercontent.com/9320719/59751139-4dc90680-9280-11e9-982e-117397434a89.PNG">

**J'ai besoin** de rajouter un message lors de l'invation d'une personne à modifier le dossier en cours de saisie, afin de pouvoir préciser les actions de mise à jour attendues sur le dossier

L’évolution consiste à rajouter un champs texte permettant à la personne faisant l’invitation de détailler son besoin. Ce texte serait utiliser pour le message envoyé à la personne invitée.
L’écran cible serait le suivant :
<img width="441" alt="Capture1" src="https://user-images.githubusercontent.com/9320719/59751148-528dba80-9280-11e9-966d-eb240eb23fb1.PNG">

**Comment by kemenaran** [comment]
Sur le principe ça me semble une bonne idée 👍

Quelques remarques :

- Ça me fait bizarre d'avoir le bouton d'action **au dessus** d'un champ de formulaire. J'ai l'impression qu'on gagnerait à le mettre après les champs.

<img width="441" alt="59751148-528dba80-9280-11e9-966d-eb240eb23fb1" src="https://user-images.githubusercontent.com/179923/59834532-7288b100-9348-11e9-9e6e-c849f1a341c5.png">

- Je pense qu'il faut prévoir un message par défaut – pour que les gens n'aient pas à mettre un texte s'ils ne veulent pas.
