### ISSUE TITLE
ETQ Usager, je veux voir les boutons d'actions disponibles

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/demarches-simplifiees.fr#3975]
**Situation actuelle :**
Dans un dossier les boutons d'actions disponibles sont fixe en bas.

**J'ai besoin** de voir les boutons d'actions disponibles, afin de pouvoir les utiliser lorsque le formulaire à une taille supérieure à la taille de l'écran.
Mettre en place comme lors de la création d’un formulaire un footer flottant toujours visible en bas de pas et contenant les bouton d’action:
<img width="869" alt="Capture3" src="https://user-images.githubusercontent.com/9320719/59751911-a8169700-9281-11e9-8a67-e293fcc7a4e9.PNG">

**Comment by kemenaran** [comment]
Ça me semble une bonne idée : la fonctionnalité d'enregistrement du brouillon est difficilement découvrable aujourd'hui, et ça la rendra plus visible 👍 

## Question : quel layout on veut sur mobile et/ou écrans étroits ?

Pas mal d'usagers utilisent leur téléphone pour faire leurs démarches. Il faut donc que l'interface soit adaptée aux mobiles.

Ici, on va vite manquer d'espace horizontal.

Je proposerais bien quelque chose comme :

### Écrans large

<img width="869" alt="59751911-a8169700-9281-11e9-8a67-e293fcc7a4e9" src="https://user-images.githubusercontent.com/179923/59833222-eaa1a780-9345-11e9-9484-483f3756c194.PNG">

### Écrans moins large

On masque le bouton "Inviter une autre personne". Il reste disponible en haut de la page.

<img width="463" alt="59751911-a8169700-9281-11e9-8a67-e293fcc7a4e9" src="https://user-images.githubusercontent.com/179923/59833411-40764f80-9346-11e9-88d0-9c2cf22f5fae.PNG">

### Écrans étroits / mobile

On manque de place. Les solutions que je vois seraient de :

- Soit **empiler les boutons** l'un sur l'autre, comme on fait en ce moment. Mais ça prend beaucoup d'espace vertical en permanence sur l'écran. Bof.
- Soit **faire rentrer les boutons horizontalement**, en laissant le texte se mettre sur deux lignes. Faut ajuster le CSS des boutons, mais ça permet de libérer de l'espace vertical.

Je partirais bien sur la solution "boutons horizontaux". J'ai l'impression qu'en ajustant la `line-height` des boutons ça peut rendre bien.

<img width="320" alt="Capture d’écran 2019-06-20 à 10 32 18" src="https://user-images.githubusercontent.com/179923/59833736-035e8d00-9347-11e9-838b-e14dce34e0e8.png">

**Comment by pengfeidong** [comment]
Je pense la solution "boutons horizontaux" aussi.
