### ISSUE TITLE
ETQ Administrateur, je veux savoir combien DS me fait économiser

### ISSUE THREAD

**Issue by chaibax** [betagouv/demarches-simplifiees.fr#3986]
Cet email serait envoyé une fois par mois par exemple, a tout les admins ayants plus de 1000 dossiers par exemple. 

![Capture_d_écran_2019-06-10_15 50 57](https://user-images.githubusercontent.com/3593868/60007468-9dd60d80-9672-11e9-925b-acd01ec24266.png)

**Comment by emsnytech** [comment]
Bonne idée !
Il faut juste que l'on rajoute nos sources (le tableau de france stratégie)

**Comment by emsnytech** [comment]
Concrètement, cela se fait comment ?

**Comment by kemenaran** [comment]
Ce sont des données remontées à SendInBlue via une API. Ensuite on configure SendInBlue pour envoyer des emails de ROI automatiquement aux admins.
