### ISSUE TITLE
ETQ qu'instructeur, je ne veux pas voir les démarches archivées dans ma liste de démarches

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#399]

**Comment by LeSim** [comment]
`HS #7031`

**Comment by kemenaran** [comment]
Est-ce qu'on est sûr de vouloir faire ça ? Ça ne va pas manquer à certains instructeurs parfois ?

Si on est sûr, je prends.

**Comment by gregoirenovel** [comment]
À mon avis c'est casse-gueule car il nous manque un état "fermé" pour les démarches. Là si on a une démarche avec fermeture automatique (et donc archivage il me semble), comment les instructeurs vont pouvoir instruire ?

**Comment by kemenaran** [comment]
Bien vu ; merci.

Le besoin me semble pertinent quand même – mais on n'est pas en capacité technique de le faire simplement pour l'instant. Je laisse ouvert, à prendre plus tard au besoin.

**Comment by kemenaran** [comment]
Ce qu'on pourrait faire, c'est masquer les démarches archivées dont tous les dossiers ont été traités.
