### ISSUE TITLE
ETQ qu'Invité je veux que les possibilité d'invitation soient limitées en n+1

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#3993]
Situation actuelle : un invité peut inviter un invité qui pourra lui aussi inviter un inviter qui pourra à son tour inviter un autre invité etc

Situation souhaitée : un invité ne peut inviter un invité que si il est lui même invité par un instructeur (limitation des invitations en n+1)

**Comment by benjaminhenkel** [comment]
c'est le cas maintenant
