### ISSUE TITLE
ETQ Administrateur, je veux pouvoir supprimer un champ (une fois la démarche publiée)

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4006]

**Comment by ErwanLHH** [comment]
Pour moi cela pose un problème juridique de relation à l'usager pour qui une des options qui est proposée n'est plus accessible. Cela demande à tout le moins de sérieuses précautions d'utilisation.

**Comment by emsnytech** [comment]
Idem trop risqué.... incompatible avec le fonctionnement api aussi ....

**Comment by tchak** [comment]
implemented #5847
