### ISSUE TITLE
ETQ administrateur, je veux synchroniser les messageries entre un back office et DS

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#4009]
proposition de la DIE

- La messagerie :
Le courrielleur de la DIE, intégré à l'application de gestion, devra pouvoir communiquer via une connexion sécurisée avec le courrielleur de DS, pour échanger avec les usagers et accéder à l'ensemble des échanges au sein de l'outil de gestion, les courriels adressés depuis l'application de gestion aux usagers étant consultables pour ces derniers dans leur interface DS.
Il s'agit de permettre aux évaluateurs des PED d'échanger sur les dossiers avec les consultants du Domaine via l'outil de gestion. Idéalement, il faudrait que cette synchronisation soit simultanée ou, à minima, il devrait y avoir trois synchronisations par jour.
Le besoin porte :
- sur la réception des courriels adressés par les consultants et des PJ associées : réponses aux demandes du PED réalisées par courriel et PJ associées, autres sollicitations des consultants adressées par courriel avant l'archivage du dossier ;
- sur l'envoi de courriels aux consultants à l'initiative des PED, notamment demandes de pièces ou de renseignements complémentaires par le PED, envoi de l'avis domanial au consultant concomitamment au passage du dossier au statut traité / accepté, autres échanges entre les PED et les consultants.

**Comment by Keirua** [comment]
l'API permet de créer des messages avec des pièces jointes, je ferme
