### ISSUE TITLE
ETQ administrateur, je souhaite que les instructeurs soit automatiquement affectés

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#4010]
Proposition de la DIE

- attribution d'un dossier nouvellement arrivé à un évaluateur au sein du PED  (à voir car pas visible des consultants / procédure interne au PED pouvant être prise en charge dans l'outil de gestion a priori) ;

**Comment by LeSim** [comment]
voir #1031
