### ISSUE TITLE
ETQ Usager, je veux que mon identité soit complétée des données issues de France Connect si je me connecte avec FC

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#4015]
Il convient de revenir sur la #2720
Même si la démarche ne concerne pas celui qui se connecte ( et qui n'est pas la majorité des usages) je souhaite que les informations d'identité soit complété des données de FC.
Condition pour que cela marche:
Etre sur une démarche avec entrée pour personne physique
Se connecter avec FC

**Comment by kemenaran** [comment]
Là où on en était resté, c'était qu'on pouvait **pré-remplir** les données d'identité avec les infos France Connect (mais on laisse quand même l'usager vérifier).

Ça me semble pertinent – mais techniquement faut recâbler la machinerie derrière, quoi.

**Comment by benjaminhenkel** [comment]
J'ai fait un test, et j'avais bien mon prénom et mon nom mais pas ma date de naissance de prérempli. C'est normal ?
