### ISSUE TITLE
Indiquer plus fortement que des filtres sont actifs

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#402]
Si aucun dossier ne correspond aux filtres, rien n'est affiché, on peut confondre ce problème avec un bug.

Afficher un truc du genre "100 dossiers répondants aux critères de filtre / 5000"

**Comment by LeSim** [comment]
@gregoirenovel c'est résolu avec la nouvelle interface ?

**Comment by gregoirenovel** [comment]
Oui, cela dit il faudrait améliorer le placeholder en cas de filtrage pour bien indiquer "Aucun dossier ne correspond aux filtres choisis", histoire d'enfoncer le clou
