### ISSUE TITLE
ETQ Admin, le type de champ "Bloc répétable" n'est plus disponible 

### ISSUE THREAD

**Issue by r1-v3t0** [betagouv/demarches-simplifiees.fr#4028]
Capture ci-jointe:
Même si ça continue à fonctionner en test, ça n'est plus disponible plus en création (j'ai cloné une démarche archivée).
![2019-07-02-142747_1920x1080_scrot](https://user-images.githubusercontent.com/10564828/60512767-cba3fd80-9cd5-11e9-8fc2-4310a2a0f53b.png)

![2019-07-02-152350_1920x1080_scrot](https://user-images.githubusercontent.com/10564828/60516226-9a2f3000-9cdd-11e9-8722-28400de32b9c.png)

Et je profite de cette première (et sûrement pas la dernière) intervention pour vous féliciter pour cette application et vous faire part d'un bon retour de nos gestionnaires (et établissements) qui s'initient à cette application.
Merci :)

**Comment by Benjamin-Doberset** [comment]
Bonjour,

Quelle adresse mail utilisez-vous pour que nous puissions vérifier que nous vous avons effectivement bien activée l'option?

**Comment by r1-v3t0** [comment]
Merci de l'intervention rapide.
