### ISSUE TITLE
ETQ Usager Affichage des blocs répétables

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4037]
Le bouton "Ajouter une ligne" à la fin d'un bloc répétable est trop proche du champ suivant on pourrait réduire l'espace avec le bloc et augmenter la distance avec le suivant pour une plus grande lisibilité du formulaire

**Comment by kemenaran** [comment]
Effectivement ; on a amélioré les marges depuis.
