### ISSUE TITLE
ETQ Administrateur, je veux pouvoir ajouter une annotation privée une fois la démarche publiée

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4040]
`# 18858`

**Comment by ErwanLHH** [comment]
Mon avis, pourquoi pas mais je crains que cela ne facilite pas la tâche pour les API et pour les appels de balises des mails automatiques et attestations

**Comment by kemenaran** [comment]
Pour éviter les problèmes avec l'API et les balises, on part pour commencer sur **l'ajout** d'annotations privées (et pas sur la suppression).

Comme en plus les annotations privées ne sont jamais obligatoires, c'est vraiment plus facile.

**Comment by kemenaran** [comment]
État de la discussion : il faut qu'on discute des pistes d'implémentation technique.

Deux pistes :

- Soit permettre de modifier en live les types de champs d'une démarche (et les champs des dossiers déjà créés) ;
- Soit mettre en place un système de révision des démarches.

**Comment by tchak** [comment]
implemented #5847
