### ISSUE TITLE
ETQ admin, lors de la création d'un formulaire, il m'est impossible d'ajouter un champ directement à la fin du formulaire

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4043]

**Comment by benjaminhenkel** [comment]
le champ se mettra automatiquement en avant dernier (voire plus haut)

**Comment by kemenaran** [comment]
C'est vrai, c'est assez pénible : le bouton "Ajouter un champ" ajoute généralement en avant-dernière position…

**Comment by kemenaran** [comment]
Maintenant le champ est bien ajouté en dernière position.
