### ISSUE TITLE
Erreur lorsqu'un Instructeur passe un dossier en Instruction

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4055]
Depuis le passage des dossiers à AASM, lorsqu'un instructeur essaie de passer en instruction un dossier qui a déjà été passé en instruction par quelqu'un d'autre, une exception est levée.

Concrètement, comme c'est une requête Javascript, l'Instructeur ne voit rien – juste le menu "Changement d'état du dossier" semble bloqué.

Y'en a plein Sentry (140 erreurs en une semaine) : https://sentry.io/organizations/demarches-simplifiees/issues/1096793879/events/e1935d6a67014aadb4b5284419369a31/?project=1429550&query=is%3Aunresolved&statsPeriod=14d

## Solution

On devrait juste signaler à l'Instructeur que le dossier a déjà été mis en instruction, et le laisser continuer.

**Comment by LeSim** [comment]
Autre proposition, créer une transition no-op sur aasm pour autoriser cette opération (c'est @tchak qui m'a dit que c'était possible)
