### ISSUE TITLE
ETQ instructeur je souhaite pouvoir repasser un dossier accepté en instruction

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#4058]
Situation actuelle : je ne peux pas repasser un dossier accepté en instrcutionc ar cela contrevient à l'art l-242-1 du CRPA

Situation souhaitée : je peux repasser le dossier en instruction mais demarches-simplifiees.fr ne sera pas tenu pour responsable en cas de contestation de l'usager.
Lorsque je souhaite repasser en instruction un dossier, le message suivant s'affiche : 

Vous allez repasser en instruction un dossier qui a été accepté. Selon l'art l- 242-1 du CRPA vous ne devez pas abroger ou modifier une décision créatrice de droit. Votre administration prend seule la responsabilité de ce changement de décision et Demarches-simplifiees.fr ne pourra être tenu pour responsable en cas de contestation de la part de l'usager concerné. 
Par ailleurs, si vous décidez de repasser effectivement ce dossier en instruction, nous vous conseillons de prévenir l'usager que son dossier est en cours de réexamen.

**Comment by ErwanLHH** [comment]
Perso je trouve cela dangereux, y compris avec l'avertissement.
Cependant pour élargir le propos il me semble que dans le cas d'utilisation de DS pour des procédures internes ou sans enjeu juridique majeur il serait possible de pouvoir le faire. Mais alors ce serait un paramétrage global de la procédure du type "procédure interne sans conséquence juridique" à choisir lors de la construction de la procédure.

**Comment by Keirua** [comment]
Ce qu'on s'est dit, c'est qu'on va réactiver cette fonctionnalité uniquement pour les superadmin pour gérer le cas par cas, et si c'est trop lourd niveau support, on verra pour faire mieux.

**Comment by benjaminhenkel** [comment]
# 19950

**Comment by benjaminhenkel** [comment]
#19875

**Comment by emsnytech** [comment]
OK !

**Comment by kemenaran** [comment]
Après discussion, on voudrait activer cette fonctionnalité aussi pour les instructeurs (et pas seulement pour les superadmins)
