### ISSUE TITLE
ETQ Instructeur, je veux pouvoir télécharger tous mes dossiers, aussi nombreux soient-ils

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4059]
Démarche n°12222

**Comment by benjaminhenkel** [comment]
date limite 15 juillet

**Comment by kemenaran** [comment]
Solution technique proposée : **rendre l'export asynchrone** + mettre du cache.

- Quand l'Instructeur clique sur "Générer l'export", on lance l'export en tâche de fond.
- On affiche "Export en cours" à l'instructeur
- Quand l'export est bon, on affiche un lien avec la date pour le télécharger + un bouton "Régénérer l'export"

**Comment by Keirua** [comment]
Le problème concernant cette procédure: timeout de la requête avant la fin de la génération du fichier, qui contient 24000 dossiers. Le fichier généré à la main fait 15Mo. Sans que ce soit problématique immédiatement, la question du stockage se pose.

**Comment by Keirua** [comment]
Concerne aussi HS 23062

**Comment by Keirua** [comment]
et 23380

**Comment by benjaminhenkel** [comment]
# 23787
