### ISSUE TITLE
ETQ instructeur, je souhaiterai savoir si un message a été lu par un usager (et réciproquement)

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#4067]
Juridiquement, les administrations souhaiteraient si un message à été lu par un usager.
La question peut être formulée dans l'autre sens.

**Comment by LeSim** [comment]
Je n'ai pas de solution technique en tête crédible pour répondre à ce besoin. Que quelqu'un avec une idée géniale rouvre s'il a une solution.
