### ISSUE TITLE
Etq Instructeur je souhaite voir une image de la pj en la survolant

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#4070]
Pouvoir avoir l’image du contenu des pièces jointes en pdf ou jpeg en survolant le nom de la pièce jointe chargée par l’usager avec la souris. 

JNPonelle (SGar ARA)

**Comment by ErwanLHH** [comment]
Je m'associe, fonctionnalité très agréable en ergonomie d'utilisation !

**Comment by emsnytech** [comment]
bonne idée, la techno existe, mais je ne sais pas si elle est open source

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/98558/instructeur-voir-une-image-de-la-pj-en-la-survolant
