### ISSUE TITLE
ETQ Instructeur, je ne peux pas accepter un dossier 

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4095]
Dossier n°314580 

J'ai testé et je confirme  ==> Rien ne se passe quand on tente de l'accepter. 

Je n'ai pas reproduit le problème sur d'autres procédures

#19349

**Comment by kemenaran** [comment]
J'ai regardé : c'est une erreur [lors de la génération de l'attestation](https://sentry.io/organizations/demarches-simplifiees/issues/976676018/?environment=production&project=1429550&query=is%3Aunresolved) :

> ActionView::Template::Error: image file is an unrecognised format

Je regarde ce que je peux faire pour corriger le bug.

**Comment by kemenaran** [comment]
Sur la démarche en question, l'erreur était que le logo de l'attestation était un fichier `.doc`. Le code générait donc une exception en essayant de créer l'attestation – ce qui empêchait l'acceptation du dossier.

Maintenant, pourquoi on se retrouve avec des `.doc` ? On a pourtant bien une validation sur le type de fichier autorisé. Mais à cause d'un bug, elle n'a pas été active pendant un an (ça n'a été corrigé qu'il y a deux mois). Et donc pendant un an les admins ont pu envoyer des logos invalides.

J'ai regardé en production : il y avait donc 10 logos d'attestations invalides.

```
bad_templates = AttestationTemplate.all.filter { |at| at.logo.present? && !['.jpg', '.jpeg', '.png'].include?(File.extname(at.logo.path)) }
```

J'ai corrigé les données en production, en convertissant les logos et en les ré-uploadant depuis la console Rails. Normalement on ne devrait plus voir cette erreur.
