### ISSUE TITLE
ETQ Usager, je veux accéder plus facilement au bouton modifier le dossier plus facilement lorsque mon dossier est en construction

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4114]
Actuellement le bouton est uniquement disponible tout en bas dans l'onglet "Demande", ce qui n'est pas très visible par l'usager 
![Screenshot 2019-07-17 at 17 32 23](https://user-images.githubusercontent.com/28590367/61389271-eb801780-a8b8-11e9-9411-c20bfcc26d0e.png)

**Comment by chaibax** [comment]
Super idée ! Je propose un PR

**Comment by benjaminhenkel** [comment]
2 propositions pour résoudre cela : 


- rajouter un choix "Modifier le dossier" dans le menu déroulant "Actions" de l'interface usager

![Screenshot 2019-07-17 at 17 36 02](https://user-images.githubusercontent.com/28590367/61389523-5f222480-a8b9-11e9-9ec1-1f7428aa77f8.png)



- Changer le bouton "inviter une personne à modifier ce dossier" par un bouton "Modifier le dossier". 
Le bouton "inviter une personne à modifier ce dossier" est en effet très visible et disponible quelque soit l'onglet sélectionné (Résumé, demande ou messagerie) ce qui peut sembler disproportionné par rapport à son utilité. 

![Screenshot 2019-07-17 at 17 36 58](https://user-images.githubusercontent.com/28590367/61389811-d3f55e80-a8b9-11e9-8cf2-5ac6f8416104.png)

Le bouton "inviter une personne à modifier ce dossier" pourrait être alors placé au même niveau que "déposé le :" ou à l'ancienne place du bouton "modifier le dossier"

![Screenshot 2019-07-17 at 17 40 32](https://user-images.githubusercontent.com/28590367/61389909-0bfca180-a8ba-11e9-8045-9876ba71ddfc.png)

**Comment by benjaminhenkel** [comment]
#19558

**Comment by benjaminhenkel** [comment]
# 19648
