### ISSUE TITLE
ETQ Superadmin, je souhaiterais pouvoir supprimer un compte usager DS

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4127]
Plusieurs retours de personnes en ce sens (1/jour environ ? à quantifier plus précisément)

**Comment by kemenaran** [comment]
Oui, carrément, il faut que ça soit dispo pour les SuperAdmin, sans avoir besoin d'aller chercher en ligne de commande.

## Cadrage

On peut s'inspirer du code existant dans `support.rake`. Concrètement, ça voudrait dire :

- On ne peut pas supprimer un utilisateur qui a déjà un dossier en instruction
- On ne peut pas supprimer un Admin qui a des démarches dont il est le seul admin

Questions : est-ce qu'on autorise quand même la suppression d'admins qui ont des démarches en test ? Dans ce cas, on supprime la démarche ?

**Comment by kemenaran** [comment]
@pengfeidong est-ce que vous avez commencé à travailler à dessus ?

**Comment by krichtof** [comment]
Quelques questions sur le cadrage :

- > On ne peut pas supprimer un utilisateur qui a déjà un dossier en instruction.

On est bien d'accord qu'on parle d'utilisateur qui a un dossier dont l'instruction a commencé (en instruction, accepté, refusé ou sans suite) ?

- > On ne peut pas supprimer un Admin qui a des démarches dont il est le seul admin

Actuellement, la methode `Administrateur#can_be_deleted?` renvoie false quand 
  - l'admin n'a aucun dossier en instruction commencé
  - aucune procédure
On est bien d'accord que ces conditions sont toujours d'actualité et que le fait de ne pas supprimer un admin qui a des des démarches dont il est le seul admin est une condition supplémentaire ?

**Comment by krichtof** [comment]
Autre question : dans la tâche `delete_user_account`, la destruction de l'utilisateur supprime les dossiers, ne fait pas que les cacher (`user.destroy` supprime les dossiers car il y a une dependance `has_many :dossiers` avec `dependent: :destroy`
Est-ce que c'est vraiment le comportement souhaité ?

**Comment by kemenaran** [comment]
> > On ne peut pas supprimer un utilisateur qui a déjà un dossier en instruction.
>
> On est bien d'accord qu'on parle d'utilisateur qui a un dossier dont l'instruction a commencé (en instruction, accepté, refusé ou sans suite) ?

Yep, tout à fait 👍

> Actuellement, la methode Administrateur#can_be_deleted? renvoie false quand
> - l'admin n'a aucun dossier en instruction commencé
> - aucune procédure
>
> On est bien d'accord que ces conditions sont toujours d'actualité et que le fait de ne pas supprimer un admin qui a des des démarches dont il est le seul admin est une condition supplémentaire ?

Si, je pense que le nouveau comportement écrase une partie des conditions précédentes. Pour moi l'idée est de dire :

- Si l'admin a des dossiers dont l'instruction, on ne peut pas le supprimer.
- Sinon, si toutes les démarches de l'admin ont d'autres admins, on peut bien supprimer ce compte : les démarches concernées garderont toute au moins un autre admin.
- Sinon, l'admin a des démarches dont il est le seul admin : on ne peut pas le supprimer.

J'imagine que ça ferait un truc du genre :

```ruby
def can_be_deleted?
  dossiers.state_instruction_commencee.none? && procedures.all { |p| p.administrateurs.count > 1 }
end
```

> Autre question : dans la tâche delete_user_account, la destruction de l'utilisateur supprime les dossiers, ne fait pas que les cacher (user.destroy supprime les dossiers car il y a une dependance has_many :dossiers avec dependent: :destroy)
>
> Est-ce que c'est vraiment le comportement souhaité ?

Pour l'instant, vu qu'on ne supprime jamais des usagers qui ont des dossiers dont l'instruction a commencé, ça me semble correct. On ne supprimera jamais que des dossiers qui n'ont pas commencé à être traités par l'administration.

(J'imagine qu'on pourra ajuster ce comportement plus tard, si on améliore la suppression de compte pour pouvoir supprimer des usagers qui ont des dossiers dont l'instruction a commencé : dans ce cas on voudra garder une trace des dossiers.)

**Comment by krichtof** [comment]
Merci beaucoup @kemenaran , c'est plus clair pour moi maintenant :)

> Pour l'instant, vu qu'on ne supprime jamais des usagers qui ont des dossiers dont l'instruction a commencé, ça me semble correct. On ne supprimera jamais que des dossiers qui n'ont pas commencé à être traités par l'administration.

Du coup, dans la tâche `delete_user_account`, l'appel sur chacun des dossiers à `delete_and_keep_track` me parait superflu. Ou alors il y a un truc qui m'échappe :thinking:

**Comment by krichtof** [comment]
Quand on supprime un utilisateur qui est également admin, actuellement, cela ne supprime pas l'administrateur qui se retrouve ne plus être associé à un utilisateur.
Je suis d'avis à interdire de supprimer un utilisateur s'il est admin.
Un avis @kemenaran ?

**Comment by pengfeidong** [comment]
> @pengfeidong est-ce que vous avez commencé à travailler à dessus ?
@kemenaran On n'a pas travaillé sur le sujet.

**Comment by krichtof** [comment]
@pengfeidong . Oui, j'ai travaillé dessus la semaine dernière : https://github.com/betagouv/demarches-simplifiees.fr/pull/4674

**Comment by krichtof** [comment]
Impossible de supprimer un utilisateur quand il a un dossier en brouillon

**Comment by krichtof** [comment]
# Recadrage

Quand on supprime un administrateur, est-ce qu'on veut supprimer l'utilisateur également ou simplement retirer le droit d'administrateur à un utilisateur ? Même question pour l'instructeur.
J'opte pour le fait que ça retire le droit d'administrateur mais conserve l'utilisateur.

Voilà concrètement le comportement que je propose :

- pouvoir supprimer un instructeur depuis la page instructeur du manager
- empêcher de supprimer un administrateur des pages utilisateur et instructeur du manager
- pour qu'un utilisateur ne soit plus administrateur, il faudra le supprimer depuis la page administrateur. Et ensuite eventuellement le supprimer de la page instructeur puis de la page utilisateur.


- ne pas supprimer un utilisateur qui est déjà manager ou instructeur
