### ISSUE TITLE
ETQ Usager, je ne veux pas que le bouton "modifier mon dossier" apparaisse si mon dossier est en instruction

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4143]
Puisque le dossier n'est plus modifiable, cela me paraît plus logique de ne pas faire apparaître le bouton

![Screenshot 2019-07-26 at 16 20 36](https://user-images.githubusercontent.com/28590367/61958350-7059e800-afc1-11e9-91e3-4b87c121cd7a.png)

**Comment by kemenaran** [comment]
Oups, effectivement. Merci pour la remontée ! C'est en cours de correction.
