### ISSUE TITLE
Permettre l'Hébergement de  données de Santé

### ISSUE THREAD

**Issue by CDAude** [betagouv/demarches-simplifiees.fr#4144]
Bonjour,

L'idée serait d'avoir la possibilité de demander aux usagers de pièces jointes relatives à leur état de santé (exemple: Certificat Médical)

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/98549/administrateur-permettre-lhebergement-de-donnees-de-sante
