### ISSUE TITLE
ETQ Admin, je souhaite pouvoir limiter les formats des pièces jointes (mineure)

### ISSUE THREAD

**Issue by CDAude** [betagouv/demarches-simplifiees.fr#4145]
Bonjour,

L'idée serait d'avoir la possibilité de limiter les formats des pièces jointes (pour limiter aux pdf et fichier image par exemple). Cela facilite l'automatisation en aval de l'utilisation des données du dossier vers des applicatifs ou en GED.

**Comment by Keirua** [comment]
Je ferme car doublon avec https://github.com/betagouv/demarches-simplifiees.fr/issues/5238 en discussion plus active. On ne vous ignore pas !
