### ISSUE TITLE
ETQ Instructeur, lorsque j'envoie le dossier à un autre instructeur, j'aimerais qu'il suive automatiquement ce dossier

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4163]
![Screenshot 2019-08-01 at 12 17 54](https://user-images.githubusercontent.com/28590367/62285745-84389a80-b456-11e9-8034-b8fccf10442a.png)

A ma connaissance, la personne reçoit pour l'instant juste un mail, et n'a donc pas le réflexe de mettre suivre le dossier.

**Comment by benjaminhenkel** [comment]
balu direccte

**Comment by kemenaran** [comment]
> `/trad balu`
> "Boîte-aux-lettres unifiée" : _compte mail partagé entre plusieurs personnes._

**Comment by kemenaran** [comment]
Oui, ça serait bien que l'autre instructeur suive. Dans ce cas on pourrait même l'appeler "Affecter à un autre instructeur".

@Benjamin-Doberset est-ce qu'on est sûr que d'autres gens n'ont pas l'usage de la fonctionnalité telle qu'elle existe en ce moment ? (envoi sans suivre automatiquement)

**Comment by benjaminhenkel** [comment]
Daniel WorkinFrance
