### ISSUE TITLE
ETQ Admin, je dois remplir les voies de recours possibles pour ma démarche en cas de refus/classement sans suite

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/demarches-simplifiees.fr#4173]
Situation actuelle : Je ne renseigne pas obligatoirement les voies de recours en cas de refus d'un dossier sur ma démarche

Situation souhaitée : Je renseigne les voies de recours afin notamment qu'elles soient directement intégrées aux mails de refus.

Comment : dans la page description, en dessous de cadre juridique, une zone de texte obligatoire libellée : Indiquez les voies de recours pour l'usager en cas de refus ou classement sans suite de son dossier .

**Comment by kemenaran** [comment]
Ça me dirait bien qu'on puisse proposer une solution par défaut.

Par exemple, dans les réglages de contact de la démarche ou du service, on préciserait que l'adresse email de contact du service sera utilisée par les usagers pour les recours.

Et ensuite, on met par défaut cette adresse email dans le message de notification.

Si l'admin veut personnaliser ça, il en aurait la possibilité – mais au moins y'aurait un truc par défaut qui fonctionne pour la plupart des démarches.

**Comment by kemenaran** [comment]
Doublon de #3627
