### ISSUE TITLE
Changement de logo de la DRIEA sur notre page d'accueil

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4185]
Retour de la DRIEA qui souhaiterait que l'on mette à jour leur logo présent sur cette page: https://www.demarches-simplifiees.fr/administration

Nouveau logo : 
![bloc marque DRIEA Quadri charte2010](https://user-images.githubusercontent.com/28590367/62770406-41507580-ba9b-11e9-870f-6dcbd1c982e7.png)

**Comment by benjaminhenkel** [comment]
# 20591

**Comment by emsnytech** [comment]
Cela ressemble à faire de la marque blanche ... pourquoi pas !

**Comment by benjaminhenkel** [comment]
Là c'est qqn de la com, qui veut juste qu'on change le logo ici 

![Screenshot 2019-08-12 at 15 04 59](https://user-images.githubusercontent.com/28590367/62867052-9ea22c00-bd12-11e9-9f24-8f0b32cfffe1.png)

**Comment by kemenaran** [comment]
@benjaminhenkel moi je veux bien – mais comme leur logo veut insister à mort sur "PRÉFET", plutôt que sur le nom de l'organisme, bin, on ne lit rien…

Tu crois que ça vaut le coup de faire le changement quand même ?

Sinon on peut aussi les remplacer complètement par une autre institution bien qui nous utilise (l'éducation nationale ?)

<img width="1111" alt="Capture d’écran 2019-08-12 à 15 35 32" src="https://user-images.githubusercontent.com/179923/62868840-d6ab6e00-bd16-11e9-8a86-17ab7bcff0de.png">

**Comment by benjaminhenkel** [comment]
Oui tout à fait d'accord @kemenaran 

Je propose l'université de Nantes, parce qu'ils sont très impliqués et que c'est effectivement un bon représentant de l'éducation nationale !

**Comment by kemenaran** [comment]
@benjaminhenkel ça marche 👍 

Tu as leur logo ?

**Comment by kemenaran** [comment]
On n'a pas changé le logo, mais garder cette issue ouverte n'a plus trop de sens. On pourra refaire une passe sur tous les logos plus tard, je pense.
