### ISSUE TITLE
ETQ Usager, je veux comprendre clairement que l'expéditeur des emails transactionnels est la partie technique de DS

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4207]
Malgré les nouveaux templates d'emails, des usagers continuent à nous poser des questions en cliquant sur "Répondre" à l'email lui-même.

Une piste pour diminuer le nombre de ces messages pourrait être de **modifier l'expéditeur** (et donc l'adresse de réponse) des messages.

On passerait par exemple de 

> **De :** contact@demarches-simplifiees.fr

à quelque chose comme

> **De :** Support technique \<contact-technique@demarches-simplifiees.fr\>

Vous en pensez quoi ? (cc @benjaminhenkel)

**Comment by chaibax** [comment]
Hello,

Je comprend la logique, mais je ne pense pas que ce soit très efficace. 

Voila pourquoi : 

- les usagers ne vont pas forcement prendre en compte l'email d'expedition. contact@ ou contact-technique@: je ne pense pas que ca fasse une grosse différence pour eux. Ils ont recu un seul email apres leur démarche et il vont y répondre car il n'ont pas d'autre email. C'est tout simplement la chose la plus simple, facile et naturelle à faire pour eux. Ils vont répondre au dernier message reçu . 

- il n'y aucune raison logique a ce que l'éxpéditeur d'un email de notification de reception d'un dossier (par exemple) soit envoyé par "le support technique de DS", et pas le service instructeur (ou l'administration)

- support technique c'est pas forcement explicite pour les usagers.

**Comment by chaibax** [comment]
@kemenaran  : apres discussion avec @LeSim @tchak @benjaminhenkel, on partirait sur #4240 .

**Comment by kemenaran** [comment]
Je crois que maintenant c'est à peu près clair.
