### ISSUE TITLE
Blacklister certaines extensions dans les fichiers uploadés

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#4227]
## En attente

- [ ] ~Migration à Rails 6 (#4354)~

**Comment by kemenaran** [comment]
À priori la fonctionnalité est incluse par défaut dans Rails 6.

**Comment by pengfeidong** [comment]
> À priori la fonctionnalité est incluse par défaut dans Rails 6.
OK, je vais faire un test sur Rails 6

**Comment by kemenaran** [comment]
À priori Rails 6 ne va en fait pas changer grand chose.

@kara22 a déjà intégré le mécanisme de validation pour les logos des attestations. On peut l'étendre aux autres pièces jointes uploadées quand on veut.
