### ISSUE TITLE
ETQ Usager, je veux savoir que ma réponse a un email transactionnel ne sera pas lu par l'administration

### ISSUE THREAD

**Issue by chaibax** [betagouv/demarches-simplifiees.fr#4240]
Malgré les nouveaux templates d'emails, des usagers continuent à nous poser des questions en cliquant sur "Répondre" aux emails transactionnel. 

Une proposition a été faite par @kemenaran ici : #4207 .
Je propose une autre approche

Une piste pour diminuer le nombre de ces messages pourrait être de **modifier l'expéditeur** (et donc l'adresse de réponse) des messages.

On passerait par exemple de 

> **De :** contact@demarches-simplifiees.fr

à 

> **De :** Ne pas répondre \<ne_pas_repondre@demarches-simplifiees.fr\> 

On mettrait en place un répondeur automatique sur cette adresse, qui resterait consultable par nous (ca serait une vrai adresse, dispo sur HS a coté de contact@).

Sur le répondeur, on mettrait les infos de bases : 

"Bonjour,

Vous avez envoyé un email au service technique du site web demarches-simplifiees.fr. 
Celui-ci ne sera pas consulté par l'administration.

- Aide ou en est mon dossier ? 
- Aide  je veux faire une démarche
- Aide 3 etc

" 

Vous en pensez quoi ? (cc @benjaminhenkel @kemenaran )

Cette solution serait temporaire. Le but ultime est d'implémenter cette solution : #1783

**Comment by kemenaran** [comment]
Ça me semble raisonnable.

Sur le principe, si je suis attaché à la vraie-adresse-de-réponse, c'est parce que j'aimerais bien qu'on puisse répondre aux gens – ou à défaut au moins savoir quel sont leurs problèmes (ne pas trop cacher la douleur, quoi)

Mais en même temps j'ai l'impression qu'on n'a pas les moyens de faire ça – et que les messages qu'on reçoit en réponse à des mails transactionnels sont peu actionnables. Et si on peut consulter nous-même la boîte de réponse, c'est bien, on peut savoir ce qui s'écrit.

Du coup allons-y.

---

Après un truc qui me chagrine, c'est qu'en théorie le mail de réponse automatique pourrait dire :

> Vous cherchez à contacter l'administration de votre dossier ? Cliquez ici pour la messagerie.
>
> Sinon vous pouvez aussi contacter l'administration à contact@ville-de-tourloge.fr, ou au 01 02 03 04 05.

Mais si la réponse est générée par HelpScout, on ne va sans doute pas pouvoir personnaliser l'email automatique à ce point.

Bah, j'imagine que ça attendra que les réponses aillent automatiquement dans la messagerie (#1783) :)
