### ISSUE TITLE
ETQ Admin, je souhaiterais pouvoir fermer une démarche tout en permettant le dépôt des brouillons

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4241]
Pb auj : lorsqu'un administrateur met à jour sa démarche, les personnes ne peuvent plus déposer leur dossier qui sont en brouillon et n'ont aucun moyen de savoir comment créer un nouveau dossier sur la nouvelle démarche.  Pour pallier cela, il faudrait une étape intermédiaire où les personnes peuvent terminer leur brouillon et le déposer. 

>  archiver actuellement (pas de dépot de dossier)= clôturer la démarche 
> pas de création de nouveau brouillon mais dépôt des brouillons existants  =  nom à trouver

**Comment by kemenaran** [comment]
@tchak tu as travaillé là dessus récemment, non ? Ça en serait où ?

**Comment by tchak** [comment]
Côté modèle des données, c'est fait. Il manque un bouton dans l'interface.

**Comment by kemenaran** [comment]
Pour l'instant ça fonctionne dans le cas où on republie une démarche par dessus une démarche existante.

Il n'y a en revanche pas de bouton pour activer ce comportement explicitement. On pourra rouvrir cette issue si c'est très demandé.
