### ISSUE TITLE
ETQ Admin, je ne peux pas enlever la date de cloture automatique 

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4250]
Un admin a mis une date de clôture automatique le 20/01/0001, ce qui fait que dès qu'il la publie, elle s'archive automatiquement. Cela fait une erreur quand j'essaie de l'enlever 

Procédure n° 20 786

**Comment by benjaminhenkel** [comment]
# 21406

**Comment by LeSim** [comment]
Résolu
