### ISSUE TITLE
ETQ usager, je veux pouvoir imprimer un dossier

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#4259]
Remontée de l'ARS IDF, VIP
L'usager n'a pas de menu direct lui permettant d'imprimer. Il faut faire un clic droit pour imprimer mais qui en fait n'imprime que ce qui est affiché à l'écran. Et donc pas d'impression de tout le document ni de ce qui est caché dans les cellules textes ce qui provoque beaucoup d'appels pour cette simple manipulation chez nous. Nos services sont débordés pour répondre à ce genre de demande.

**Comment by kemenaran** [comment]
On pourrait le faire relativement facilement en ajoutant un bouton "Imprimer" qui affiche la page "Demande" (qui normalement est déjà print-friendly).

**Comment by jchourdeaux** [comment]
Bonjour, je me permet de rebondir sur cette demande qui m'a été demandé plusieurs fois déjà..
Peut-on intégrer le bouton existant pour les instructeurs dans la vue usager ?

**Comment by kemenaran** [comment]
On a maintenant un bouton "Imprimer" pour les Usagers, qui génère un export PDF du dossier.
