### ISSUE TITLE
ETQ instructeur, je souhaite avoir accès à plus d'informations sur les personnes morales. Rajouter un lien vers "entreprise.data.gouv.fr"

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#4267]
Très bonne proposition, qui ne coute rien, que d'automatiser l'interrogation vers "entreprise.data.gouv.fr" afin d'avoir la fiche d'information d'une personne morale, avec toutes les informations légales ....

https://secure.helpscout.net/conversation/940728877/21359?folderId=1653804

Cela nous règle le sujet du Dite le nous une fois... et pas la peine de faire remonter plus d'informations dans DS. En plus, quand les équipes auront remonter les documents, pas la peine non plus de les intégrer... 

VICTOIRE TRES RAPIDE...

**Comment by emsnytech** [comment]
[evoilution lien entreprises.data.pdf](https://github.com/betagouv/demarches-simplifiees.fr/files/3565431/evoilution.lien.entreprises.data.pdf)

**Comment by LeSim** [comment]
Tu proposes que l'on mette un lien vers entreprises.data.gouv.fr ?

**Comment by emsnytech** [comment]
yes, je viens de faire une simulation
