### ISSUE TITLE
ETQ admin, je peux gérer les groupes instructeur

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4288]
**Objectif**: spécifier le/les écrans de création de groupes instructeurs.

 - il faut savoir quel est le groupe par défaut. 
 - Un admin peut changer le groupe par défaut ?
 - les groupes instructeurs sont gérés au niveau de la procédure: un groupe instructeur ne peut PAS être partagé entre plusieurs procédures.
 - un administrateur peut créer un groupe avec un label + un instructeur
 - un instructeur peut-être dans plusieurs groupes instructeurs
 - un instructeur peut être super instructeur du groupe. Il peut alors ajouter des instructeurs dans son (ou ses) groupes
 - un super-instructeur peut supprimer des instructeurs, mais il doit rester minimum un instructeur dans le groupe
 - dans un premier temps, on ne gère pas la suppression de groupes instructeurs (ça pose des questions pénibles, comme "comment on fait quoi des dossiers et instructeurs associés lors de cette suppression ?")

# Vision instructeur

on commence par un piège : il n'y a pas d'écran, car l'instructeur n'y a pas accès.

# Vision super instructeur
on peut modifier les groupes d'instructeurs dont on est super-instructeur
https://wireframe.cc/U2uyp5

![image](https://user-images.githubusercontent.com/1223316/64539284-84ae3600-d31e-11e9-9f6d-9aab787b04eb.png)

# Vision admin
C'est le chaos : on peut tout faire ou presque.
https://wireframe.cc/X2My2T

![image](https://user-images.githubusercontent.com/1223316/64539087-1ec1ae80-d31e-11e9-939c-f32d5fdcde12.png)

On peut sans doute simplifier (visuellement) l'écran admin en découpant cette création en deux parties:
 - la vision admin, où on peut uniqumenet créer des groupes
 - la vision super instructeur, où on peut uniquement gérer les instructeurs de ses groupes

Qu'est ce que vous en pensez ?

**Comment by kemenaran** [comment]
Yay, chouettes mockups ! Ça permet de se projeter, du coup.

Ça m'inspire quelques bricoles :

- Comment est-ce qu'un instructeur qui a des droits de superinstructeur sur certains groupes accède à sa page de gestion ?

- J'imagine que certaines démarches auront beaucoup de groupes instructeurs et d'instructeurs (je viens de traiter une démarche à 350 instructeurs !).
  Dans ce cas :
    - Il faudra paginer la liste des instructeurs de chaque groupe
    - Même en paginant, avoir tous les groupes avec les instructeurs sur une même page risque de faire beaucoup (en bruit visuel et en charge DB).
  
  Du coup est-ce qu'on ne voudrait pas avoir d'un côté une page qui liste les groupes, et ensuite une page indépendante par groupe ?

- "Superinstructeur", je ne sais pas si c'est très clair. Un "Gestionnaire du groupe", ou "Gérant du groupe" pourrait être bien ?

- On va sans doute devoir permettre de promouvoir un instructeur existant comme superinstructeur. Ce qui voudra sans doute dire un bouton d'action à côté du nom de l'instructeur : "[ Promouvoir comme superinstructeur ]" ou "[ Retirer les droits de superinstructeur ]"

  Puisqu'on devra faire ça de toute façon, on peut carrément supprimer la case à cocher "Superinstructeur oui/non". Dans ce cas le workflow serait juste :
  1. Ajouter un instructeur (en renseignant seulement son email)
  2. Éventuellement le promouvoir comme superinstructeur

  Ça simplifie le formulaire d'ajout, ce qui n'est sans doute pas plus mal.

- D'une manière générale, si les listes deviennent trop longues, on voudra sans doute bouger les boutons "Ajouter" en haut de la liste (plutôt qu'en dessous, où ils deviendraient peu visibles).

  Mais ça dépendra sans doute de la taille de pagination qu'on choisira.

**Comment by Keirua** [comment]
Tous les points sont intéressants. Je prends en compte tes remarques:
 - super instructeur n'est pas terrible. `Gestionnaire de groupe` me parait plus inclusif (moins genré ?) que `Gérant`
 - découper sur 2 écrans:
   - un pour le listing des groupes et la création d'un groupe, avec pagination des groupes
   - un pour sa gestion (ajout d'instructeurs, promotion d'un instructeur)
 - ces écrans doivent être accessibles aux instructeurs, le filtrage se fait au niveau des droits:
   - un admin voit/édite tous les groupes
   - un instructeur voit tous ceux dont il appartient.
   - un instructeur avec les droits de gestion d'un groupe peut en plus ajouter des instructeurs dont il est gestionnaire
   - il faut que je trouve où caler ces liens côté instructeur, et enlever cette gestion de `new_administration`
 - on ajoute un instructeur par email, on le promeut ensuite si on le souhaite
 - l'ajout en haut de liste parait une bonne pratique sur les différents écrans

**Comment by Keirua** [comment]
La mise à jour des mockups du coup :

 - Admin: lister les groupes, en ajouter un
https://wireframe.cc/X2My2T
![image](https://user-images.githubusercontent.com/1223316/64704555-c66de680-d4ae-11e9-8b80-f4f3efb446f7.png)
 - instructeur: lister les groupes dans lesquels on se trouve, mais pas d'ajout. La possibilité de voir les autres instructeurs du groupe est discutable
https://wireframe.cc/sMu4uN
![image](https://user-images.githubusercontent.com/1223316/64705372-244efe00-d4b0-11e9-9224-4a80e1c31ecb.png)
 - gestionnaire de groupe et admin: on peut ajouter des instructeurs à un groupe, et promouvoir un instructeur en gestionnaire de groupe
https://wireframe.cc/f4rvJM
![image](https://user-images.githubusercontent.com/1223316/64705289-071a2f80-d4b0-11e9-8ae5-fd1314748567.png)

**Comment by ErwanLHH** [comment]
Je m'associe au thème sur l'intérêt de pouvoir regrouper les instructeurs dans des ensembles afin de faire des affectations groupées.
Par ailleurs, j'ajoute le confort de pouvoir faire le ménage dans les instructeurs pour nettoyer l'affichage de l'écran admin qui tend rapidement à devenir illisible en raison du grand nombre de personnes.

**Comment by LeSim** [comment]
Closed by #4317
