### ISSUE TITLE
ETQ Administration, je ne veux plus de notion de groupe par défaut

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#4307]
Aujourd'hui ce n'est pas possible car la notion de défaut est porté par le label.

début de la conversation dans #4301 

@Keirua 
> j'ai le même problème sur #4288 et je suis pas fan d'utiliser le label pour savoir qu'on est dans un groupe par défaut : ça fait du code pas élégant et ça oblige une procédure à se trimballer un groupe "défaut" qu'elle ne pourra pas renommer (et ça s'internationalise mal, même si on en est pas là). Je pensais ajouter une entrée dans la procédure pour définir le groupe par défaut pour clarifier ça, et permettre à un admin de changer ce groupe.

@LeSim 
> @Keirua je partage ton avis que le label pour définir un groupe par défaut atteint ces limites. Pourquoi pas un boolean groupe_par_defaut sur la table groupe_instructeur ?

@Keirua 
> Pour éviter de modifier la table procedure ? Vu qu'on ne peut avoir qu'un groupe par défaut, ça me parait un peu casse figure : il faut pas se planter quand on change le booléen (mettre un groupe sur true, l'autre à false et espérer éviter qu'il n'y ait pas de problèmes de concurrence. Et si on remplace la clé étrangère groupe par défaut par une table de jointure procedure_groupe_par_defaut, avec une procédure et un groupe ?

@Keirua tu nous prototypes une implémentation ?

**Comment by kemenaran** [comment]
@Keirua si tu as des souvenirs de ça, j'ai l'impression que c'est fait et qu'on peut fermer, non ?
