### ISSUE TITLE
ETQ Admin, je dois personnaliser le lien de ma démarche

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4309]
Afin d'améliorer la clarté de l'url de nos démarches, il est préférable que l'administrateur personnalise son lien. 

Pour cela, je propose que l'on supprime l'url automatiquement générée lorsque l'admin clique sur publier (cf. image ci-dessous) et que l'on mette du vide à la place !

![Screenshot 2019-09-12 at 14 32 21](https://user-images.githubusercontent.com/28590367/64784500-8e2bde00-d56a-11e9-9adc-39276609d82b.png)

Cela obligera ainsi les administrateurs à personnaliser les liens et cela rendra même cette personnalisation plus facile (plus besoin de supprimer ce qu'il y a après "/commencer/")

**Comment by ErwanLHH** [comment]
J'adhère et complète un peu avec une demande de bien alerter sur la syntaxe autorisée (notamment les majuscules qui sont interdites.. ;-)

**Comment by benjaminhenkel** [comment]
@n-b  travaille dessus 

#4048
