### ISSUE TITLE
ETQ Adm / Instructeur / Usager

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4314]
Situation : j'ai un compte DS comme instructeur et éventuellement admin
Lorsque je me connecte via un lien de procédure pour faire un test ou utiliser un formulaire, **si je ne me suis pas connecté avant à DS**, je suis dirigé vers l'interface admin/instructeur sans possibilité d'accéder au formulaire voulu
Il semblerait que cela soit lié au cookie du jeton de connexion.
Est-il possible ou d'avertir via un message ou de résoudre la question ?

**Comment by chaibax** [comment]
doublon avec #3366
