### ISSUE TITLE
ETQ admin je veux mettre un champ "lien vers un autre dossier" dans un champ répétable

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#4315]
Actuellement, cela ne semble pas possible

**Comment by benjaminhenkel** [comment]
Besoin pour  une procédure 

Cas d'usage ==> Procédure ID : 22257

publication prévu pour le 1er janvier 2020

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/77364/administrateur-creer-un-champ-lien-vers-un-autre-dossier-dans-un-bloc-repetable
