### ISSUE TITLE
ETQ instructeur je veux affecter un dossier à un autre instructeur

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4316]
Suite à des échanges avec des instructeurs, il est apparu que la fonctionnalité d'envoyer le dossier à un autre instructeur ne se comporte pas comme les gens le pensent.
On s'attend à ce que le dossier soit attribué ce qui n'est pas le cas.
Par ailleurs,  le mail ne mentionne pas le fait qu'il faille s'attribuer le suivi du dossier il invite juste à se connecter au dossier.
Solution rapide : modifier le texte du mail et ajouter un avertissement dans l'onglet qui permet d'envoyer le dossier
Solution plus longue : affecter le suivi du dossier lorsque l'instructeur le fait, ce qui recoupe la question du routage et les débats sur le "super instructeur" à qui on pourrait réserver cette fonction d'affectation dirigée

**Comment by benjaminhenkel** [comment]
Il me semble que notre dernière nouveauté pour les instructeurs (https://doc.demarches-simplifiees.fr/nouveautes/pour-les-instructeurs ) répond à cette problématique.

@ErwanLHH, si ce n'est pas le cas, je te laisse ouvrir en précisant le pb !
