### ISSUE TITLE
ETQ admin, je veux pouvoir supprimer des formulaires en test

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4322]
impossible de supprimer les démarches n°14573 & n°15666
La page "Une erreur est survenue" apparaît

**Comment by benjaminhenkel** [comment]
PB côte d'or

**Comment by kemenaran** [comment]
Pas eu de retour depuis longtemps, et on a fait pas mal de boulot depuis sur la suppression des démarches. Je ferme.
