### ISSUE TITLE
ETQ Instructeur, je ne peux pas utiliser le bloc répétable dans les annotations privées

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4323]
J'ai fait le test et effectivement quand on clique sur le bouton "ajouter une ligne", rien ne se passe 

dossier n° 837 957 

![Screenshot 2019-09-16 at 16 14 42](https://user-images.githubusercontent.com/28590367/64966807-c0597a80-d89f-11e9-81c5-4c3ec426629e.png)

**Comment by benjaminhenkel** [comment]
Cote d'Or PB

**Comment by ErwanLHH** [comment]
#4282 ?
J'ai été confronté à ce pb mais maintenant cela fonctionne pour mon compte admin

**Comment by benjaminhenkel** [comment]
Là c'est plutôt en tant qu'instructeur, et j'ai toujours ce problème de mon côté !

**Comment by ErwanLHH** [comment]
Je précise, c'est avec mon compte admin/instructeur/usager que j'ai fait le test et comme instructeur cela fonctionnait, dsl pour le raccourci

**Comment by kemenaran** [comment]
Maintenant ça fonctionne correctement.
