### ISSUE TITLE
ETQ instructeur, je veux pouvoir modifier plusieurs annotations privées d'un coup

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4337]
Actuellement, il faut sauvegarder à chaque champ quand on modifie les annotations privées, ce serait top de pouvoir le faire en une fois

à communiquer Aude Robin DIE

**Comment by ErwanLHH** [comment]
Je ne comprends pas, j'ai fait un test et j'arrive à sauvegarder plusieurs annotations privées en une fois

**Comment by kemenaran** [comment]
Pareil, ça me semble curieux qu'il faille sauvegarder à chaque fois.

Je ferme pour cause d'inactivité.
