### ISSUE TITLE
ETQ administrateur, je veux pouvoir traduire les noms des statuts

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4338]
La terminologie choisie ne convient pas à tout le monde. Une suggestion demandée, c'est la possibilité d'avoir une interface pour traduire les noms des statuts, genre`accepté` -> `validé`, et utiliser cette traduction dans les différents écrans.

**Comment by Keirua** [comment]
à communiquer aude robin DIE

**Comment by benjaminhenkel** [comment]
J'ai l'impression que c'est mettre le doigt dans un engrenage sans fin ==> On nous demandera ensuite de traduire  "passage en instruction", "passage en construction"... 
Ce n'est vraiment pas bloquant je pense

**Comment by emsnytech** [comment]
Oui, il faut que nous regardions cela... trop de pb, sauf si paramétrage, et encore !

**Comment by kemenaran** [comment]
Déplacé sur Feature Upvote : https://demarches-simplifiees.featureupvote.com/suggestions/78065/administrateur-configurer-les-noms-des-etats-du-dossier
