### ISSUE TITLE
ETQ instructeur, je veux voir les dossiers supprimés

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4339]
alors, je ne parle pas de les consulter, mais un scénario apparement fréquent c'est ça :
 - dépot du dossier par l'utilisateur
 - l'instructeur commence à le consulter, par ex pour regarder les pj ou autre
 - l'utilisateur supprime son dossier
 - l'instructeur est alors perdu: il ne retrouve plus le dossier dans le listing

⇒ ce serait pas mal d'afficher dans le listing que des dossiers ont été supprimé par l'utilisateur, qu'il est donc normal que l'instructeur ne puisse pas le consulter et que ce n'est pas un bug

Nous aurons par la suite des problèmes similaires avec la gestion des groupes instructeurs, lorsqu'on aura mis en place la possibilité de transférer un dossier d'un groupe à un autre pour réparer les accidents de routage utilisateur.

À communiquer Aude Robin DIE

**Comment by emsnytech** [comment]
Il me semble que nous pourrions mettre cette approche en lien avec ce que nous allons développer lors de la suppression d'un dossier.
Nous pourrions, comme lors de la suppression à la fin, garder systématiquement les élément de trace quand un usager prend l'initiative de supprimer
date de création, / date de suppression, nature de la démarche, l'état ou il était lors de la suppression.

**Comment by tchak** [comment]
done
