### ISSUE TITLE
Migration à Rails 6

### ISSUE THREAD

**Issue by n-b** [betagouv/demarches-simplifiees.fr#4354]
- [x] Attendre que les gems GraphQL soient compatible Rails 6
- [x] Utiliser des versions upstream des gems (plutôt que nos forks)
- [x] Mettre à jour Capybara (#4536)
- [x] Mettre à jour les gems
- [x] Faire passer les tests avec Rails 6
- [x] Tester l'application manuellement
- [x] Déployer le passage à Rails 6

## Après la migration

- [x] Passer de la config par défaut Rails 5 à Rails 6
- [x] Activer les belongs_to requis par défaut
- [x] Refactorer le chargement de `BlobVirusScannerConcern` (cf. initializers/active_storage.rb)
- [ ] Ré-activer le linter `Rails/UniqueValidationWithoutIndex`, et rajouter des index aux colonnes concernées (#5535)
- [ ] ~~Activer zeitwerk~~

**Comment by kemenaran** [comment]
Pour l'instant je crois qu'on a quelques points bloquants :

- La compatibilité des gems GraphQL avec Rails 6
- Un peu de code dans une gem forkée à nous, qu'il faudrait qu'on nettoie.

@tchak a déjà pas mal travaillé dessus ; je pense que c'est bien s'il termine le sujet lui-même. (/cc @pengfeidong)

**Comment by kemenaran** [comment]
@tchak j'ai essayé de bumper les gems (hors passage à Rails 6). Mais je tombe sur la mise à jour de Sprockets qui nous demande de créer un fichier `app/assets/config/manifest.js`. C'est pas quelque chose que tu aurais déjà fait dans une branche, par hasard ?

**Comment by tchak** [comment]
@kemenaran j'ai bloqué la version de sprockets – migrer pose des problèmes, ce n’est pas nécessaire pour rails 6 et on s'en sert de moins en moi de sprockets. J'ai bien espoir qu'on vire sprockets entièrement un de ces jours.

**Comment by n-b** [comment]
Le manifest.js remplace simplement la ligne `Rails.application.config.assets.precompile += ...` dans `initializers/assets.rb`. [La doc est plutôt bien fichue.](https://github.com/rails/sprockets/blob/master/UPGRADING.md#manifestjs) On a eu un souci sur PdE, parce qu’on avait pas retiré la ligne dans assets.rb, que certains fichiers étaient compilés plusieurs fois, que ça se terminait en race condition qui faisait crasher sassc.

**Comment by kemenaran** [comment]
État des lieux : y'a une branche, qui marche, mais sur laquelle il faut corriger des tests liés aux PJ

**Comment by kemenaran** [comment]
On est maintenant sur Rails 6 !

Maintenant, reste le nettoyage post-migration. (Voir la liste ci-dessus.)

**Comment by kemenaran** [comment]
Pour zeitwerk, ça peut s'activer en 1/4h de travail à peine : y'a une juste tâche rake `zeitwerk:check` qui dit de renommer quelques constantes, on fait ça, et hop.

Le seul souci, c'est que le debugger qu'on utilise, `byebug`, n'est pas compatible avec zeitwerk (https://github.com/deivid-rodriguez/byebug/issues/564). On peut donc soit:
- Changer de débogueur (y'en a des compatibles)
- Attendre un moment
- Contribuer une compat avec zeitwerk

Dans tous les cas, y'a pas d'urgence. On peut remettre ça à plus tard.

**Comment by kemenaran** [comment]
J'ai l'impression que globalement la migration est faite.

Je crée une issue pour le seul truc qui restait, et hop.
