### ISSUE TITLE
ETQ Usager avec un handicap, je souhaite réaliser une démarche

### ISSUE THREAD

**Issue by chaibax** [betagouv/demarches-simplifiees.fr#4359]
Il est important que nos usagers ayants un handicap puissent utiliser normalement demarches-simplifiees.fr .

**Comment by chaibax** [comment]
Voici 2 exemple d'erreurs, pris sur une page : https://www.demarches-simplifiees.fr/commencer/mhtravail 

1. Absence de balise Alt pour le logo

2. Balise H2 présente _avant_ la balise H1 dans le source

**Comment by chaibax** [comment]
Je propose de 

1 - tester https://github.com/Asqatasun/Asqatasun pour monitorer nos problèmes technique d'accessibilité . Il est listé sur le site du W3C pour le RGAA par https://www.w3.org/WAI/ER/tools/?q=rgaa-french-government-standard

2 - faire un vrai essai avec un mal voyant

**Comment by kemenaran** [comment]
On a remplacé cette issue par des issues d'accessibilité plus ciblées (par exemple #5162)
