### ISSUE TITLE
ETQ Instructeur, je veux que les pièces jointes de la messagerie soient incluses dans le zip des PJs

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4378]
Actuellement, on génère un fichier zip avec les PJs du dossier.
Il faudrait sans doute inclure également les PJs issues de la messagerie.

yannick dufour pref33

**Comment by benjaminhenkel** [comment]
+ Helene

**Comment by benjaminhenkel** [comment]
# 24071

**Comment by benjaminhenkel** [comment]
En lien avec avec la procédure pour les étrangers, qui seraient intéressants de répliquer

**Comment by kemenaran** [comment]
C'est en prod.
