### ISSUE TITLE
ETQ instructeur, je veux pouvoir me désabonner du récap hebdomadaire

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4379]
Les instructeurs se plaignent de recevoir trop de mails. Ils deviennent inutiles lorsque leur démarche est bornée dans le temps, mais on continue à envoyer un récap hebdomadaire.

On peut sans doute inclure une case à cocher "Recevoir le compte rendu hebdo" dans les préférences ?

HS 22789

**Comment by chaibax** [comment]
Le problème n'est-il pas la reception de message alors que la démarche n'est plus active, dans le sens : plus ne nouveau dossier  ?

Je ne sais pas si c'est le cas, mais peut être envoyons nous des recap "vide", c'est a dire alors qu'il n'y a pas eu "de mouvement" sur aucune démarche.

**Comment by benjaminhenkel** [comment]
@Keirua  Le choix apparaît dans la partie "Notifications par email", mais il n'est en réalité pas désactivable 

![Screenshot 2019-11-27 at 14 46 11](https://user-images.githubusercontent.com/28590367/69728500-d2b82600-1124-11ea-8f66-6f34621601f7.png)

Je pense au contraire qu'on devrait permettre de le désactiver : si les gens n'ont pas envie de recevoir le mail, ils ne le liront pas, donc autant permettre la désactivation de l'envoi.

**Comment by LeSim** [comment]
Et ça serait sympa de pouvoir le désactiver directement depuis le mail
