### ISSUE TITLE
ETQ admin/instructeur, j'aimerai envoyer un message à tous les usagers d'un coup

### ISSUE THREAD

**Issue by red1bush** [betagouv/demarches-simplifiees.fr#4386]
Une sorte de messagerie collective

**Comment by kemenaran** [comment]
Cas d'usage répertorié dans #3690 :

Cela permettrait ainsi à l'administrateur de les contacter directement par exemple pour un rappel sur un appel à projet qui termine bientôt afin que les dossiers soient effectivement déposés.

@red1bush pour toi quel est le besoin concret ?

**Comment by kemenaran** [comment]
On continue à avoir des admins qui nous demandent régulièrement la liste des gens en brouillon. Pour l'instant :

- on extrait la liste à la main,
- on demande à la démarche de mettre un texte comme quoi commencer un dossier autorise l'administration à les contacter

## Pistes futures

- @Keirua se demande si un bouton dans le Manager pour exporter la liste serait une bonne idée (#5167)
- Sinon on pourrait avoir une fonctionnalité dans la partie Admin "Envoyer un email à tous les gens en brouillon". Avantages :
  - Confidentialité : les adresses email des usagers ne sont jamais visibles pour l'administration
  - Contrôle : on peut mettre en place des restrictions antispam : genre une démarche ne peut pas spammer un usager plus d'une fois, ou pas plus d'une fois par semaine, etc.

**Comment by krichtof** [comment]
Je me pose la question à qui on souhaite envoyer le mail collectif, c'est pas clair pour moi.

- A tous les usagers ?
- Uniquement aux usagers en brouillon ?
- A tous les usagers sauf ceux dont le dossier est terminé ?

**Comment by krichtof** [comment]
Proposer comme option d'envoyer aux dossiers suivants
- en brouillon
- en cours d'instruction
- classé sans suite
- refusé
- accepté

(de manière exclusive)

**Comment by krichtof** [comment]
- Si la procédure a plusieurs groupes instructeurs, alors on envoie uniquementx aux dossiers où le groupe instructeur est déjà choisi.

Si la procédure n'a qu'un seu groupe instructeur, on envoie à tout le monde.

- ajouter le message dans la messagerie de l'utilisateur

- etq instructeur, je peux accéder à la liste des messages envoyés en masse par chacun des instructeurs dans les mêmes groupes que moi pour une procédure donnée

**Comment by kemenaran** [comment]
Après discussion avec @kara22 , @tchak, @LeSim et @lydiasan , on peut découper cette issue en trois parties, développée l'une après l'autre.

## 1. ETQ Instructeur je peux envoyer un message à tous les usagers qui ont un dossier en brouillon

  - Pas de balises pour l'instant
  - Le message n'est envoyé qu'aux dossiers qui ont choisi un groupe instructeur dont fait partie l'instructeur. (Si le brouillon n'a pas encore de groupe instructeur, on n'envoie pas le message. Si l'instructeur appartient à plusieurs groupes instructeurs, tous les brouillons dans ses groupes instructeurs reçoivent le message).
  - Dans l'interface instructeur, un texte explique à qui le message sera envoyé (par exemple "Vous allez envoyer un message à 15 453 personnes, dans les groupe d'instructions X, Y et Z")
  - Le message est associé à la messagerie du dossier (même si dans un 1er temps l'usager ne peut le lire que dans l'email, et pas encore dans la messagerie : comme ça au moment où le dossier passe en "déposé", on a une trace du message envoyé).

## 2. ETQ Usager, je peux répondre à un message envoyé par un instructeur sur un brouillon
  - Pour un brouillon qui a reçu un message automatisé, la messagerie devient disponible (mais pas avant, pour l'instant).
  - L'usager peut utiliser la messagerie pour répondre au message
  - L'instructeur qui a envoyé le message peut voir la réponse dans son interface d'instruction (mais il ne peut pas voir les champs du dossier en brouillon).

## 3. ETQ Instructeur, je peux envoyer un message à tous les usagers **par statut du dossier**

  - Par exemple envoyer un message à tous les dossiers "En instruction"
  - Bonus : on peut utiliser les balises dans le message

**Comment by kara22** [comment]
### 1. ETQ Instructeur je peux envoyer un message à tous les usagers qui ont un dossier en brouillon


État d'avancement :

- Il y a une validation sur la disponibilité de la messagerie pour les dossiers en brouillon que je vais faire sauter
- Pour des questions RGPD, on avait fait une modification sur les mails : le contenu des messages n'est plus à l'intérieur du mail mais l'usager doit se rendre sur la plateforme pour le consulter (voir capture plus bas)
- Lorsque l'usager qui a un dossier brouillon clique sur le lien reçu par mail, il accède bien à la messagerie. Cependant, lorsqu'il retourne sur son dossier via l'interface classique, il ne peut plus y accéder car les dossiers en brouillon n'y ont normalement pas accès.

Questions :

- Est-ce que l'usager en brouillon après avoir reçu un message de l'instructeur, doit avoir en permanence accès à sa messagerie sur le dossier en question ou il doit juste y accéder via l'e-mail reçu et le lien de redirection ?
- Est-ce qu'on fait sauter cette validation : https://github.com/betagouv/demarches-simplifiees.fr/blob/5000a094514172503cb81251b9ff75c958cc701d/app/models/commentaire.rb#L21 ?

![image](https://user-images.githubusercontent.com/21340608/124785757-6a0f6d00-df47-11eb-821d-f1e383823097.png)

cc @kemenaran @tchak @LeSim @lydiasan

**Comment by tchak** [comment]
J'ai l'impression que si l’on veut respecter la découpe en plusieurs étapes, il faut accepter que l'usager n'ait pas axés depuis l'UI au message dans un premier temps. Sinon, il faut merger l’étape 1 et l’étape 2.

**Comment by kemenaran** [comment]
Je dirais pareil : on accepte que la messagerie n'est pas accessible aux brouillons pour l'instant.

Et dans ce cas :

- Je dirais que si la messagerie n'est pas disponible, on met tout le contenu du message directement dans le corps du mail. C'est le plus simple (et ça reviendra automatiquement en "Cliquez pour lire le message" au moment où on rendra la messagerie dispo aux brouillons).
- On peut garder la validation, mais en rajoutant un `unless: -> { dossier.brouillon? }`

**Comment by tchak** [comment]
Ajouter une table d'historisation des envois

```ruby
#  id           :integer          not null, primary key
#  body         :text
#  dossier_count :integer
#  dossier_state :string
#  sent_at    :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null

class BulkMessageMail
  has_one_attached :piece_jointe
  has_and_belongs_to_many :groupe_instructeurs
end
```

**Comment by emsnytech** [comment]
Je me pose la question sur le niveau 2.... veux t'on vraiment ouvrir la messagerie alors que le dossier reste fermé ?
Pourquoi ne pas orienter vers la boite aux lettre fournie par le service ?
Cela afin de ne garder aucune interactions avec le porteur.

Que se passe t'il si l'instructeur veut répondre à celui qui a répondu ? 

n'allons nous pas créer une boite mail d'échanges  ?

Sauront'il quand le dossier sera déposé que tous les échanges avant seront visibles de tous les instructeurs ?

**Comment by kara22** [comment]
C’est vrai que s’il y a pas mal d'échanges et que les usagers ne déposent jamais leurs dossiers... Car si les instructeurs les contactent c'est pour par exemple les prévenir de la fin d'appels à projets etc non ?

@tchak @kemenaran @krichtof @LeSim

**Comment by tchak** [comment]
L'idée c'est de ne pas exacerber le déséquilibre entre l'administration et les usagers. L'usager se sent déjà assez impuissant. On s'était dit que si en plus l'usager reçoit des messages sans pouvoir répondre ça va délier les mains des instructeurs et peut mener à de l'abus de cette fonctionnalité (le mot "spammer" utilisé plusieurs fois lors du cadrage). Les messages en réponse seront visibles de tous les instructeurs dans le groupe instructeur.

**Comment by emsnytech** [comment]
HUm.... je reste en effet assez ... plus que septique.
On incite depuis les début à ce que tout ce qui ne sera pas lié à un dossier ne passe pas trop par la messagerie du dossier.
Quand on m'envoie un message général, cela va porter sur des généralités pour tous.
Si on commence en plus à donner à l'usager la possibilité de passer par sa messagerie du dossier pour discuter avec les services en dehors du dépôt, on crée un canal asymétrique, et potentiellement délicat, avec des débuts d'changes de données, qu'il va falloir stosker et tracer ( "mais j'avais dit cela dans la messagerie, mais le dossier a été supprimé ! je veux que l'on retrouve ce que j'avais répondu !)
Je crains  pour l'instant... ne pas vous suivre...
Pour l'instant,... donc je souhaite que l'on suspende cette deuxième étape...., surtout que l'on apporte la solution; la réponse est effectuée par la messagerie en bas du formulaire.

**Comment by tchak** [comment]
> surtout que l'on apporte la solution; la réponse est effectuée par la messagerie en bas du formulaire.
Je ne comprends pas ce que ça veut dire.

J’entends tes craintes et je laisse @kemenaran argumenter, car c'est lui qui avait le plus d'objections lors du cadrage.

**Comment by kara22** [comment]
Je pense qu'il veut dire que l'usager peut contacter directement par email l'instructeur pour lui répondre et que ça soit géré hors DS tant que l'usager n'a pas déposé son dossier

**Comment by emsnytech** [comment]
Oui, c'est cela.
Vraiment je pense que nous allons au delà du besoin.
Celui exprimé est d'envoyer un message à tous ceux qui ont un dossier en brouillon, pour prévenir d'une date etc, des informations générales.
Il ne faut pas mettre les mains dans l'utilisation ensuite de DS pour des échanges entre agents et usagers sur un dossier en brouillon, pour un dossier.
Cela brouille notre approche qui distingue bien les étapes aujourd'hui d'un dossier. On a eu le même pb en fin de démarche, on ferme la messagerie quand le dossier est archivé. En brouillon, le principe est le même.
Quand un dossier est en brouillon, il n'existe pas du point de vue de l'administration. Si on commence a avoir des échanges via ce dispositif par dossier, alors le statut de ces messages sont, du point de vue de la vie du dossier, indéfinissable sous l'angle "administratif".
Il faut alors systématiquement renvoyer vers la messagerie du service, comme on le fait pour le reste. Cela invitera d'ailleurs les services à bien remplir ce champ.
Aussi, je proposerai bien d'arrêter là ce developpement, en attendant d'avoir des retours de cette première évolution, qui était en effet attendue. 
Il y a d'autres aspects que nous pouvons traiter pour améliorer la relation usagers/agents, comme les aider à trouver une maison france service...

**Comment by emsnytech** [comment]
Premier retours. peut etre n'ai je pas tout compris.
[retour feature.pptx](https://github.com/betagouv/demarches-simplifiees.fr/files/6896066/retour.feature.pptx)

**Comment by kara22** [comment]
Vu avec Philippe : suite au merge et à l'amélioration de l'envoi des messages aux usagers en brouillon, on attend de communiquer et d'avoir les premiers retours avant d'avancer sur le développement.
