### ISSUE TITLE
ETQ instructeur, les parcelles cadastrales de mon champ carte dans les annotations privées n'apparaissent pas

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4388]
![Screenshot 2019-10-07 at 15 03 17](https://user-images.githubusercontent.com/28590367/66314072-be6d5f00-e913-11e9-972a-484c48447592.png)

Les instructeurs sont supposés sélectionner des zones pour faire apparaître les parcelles cadastrales; cela marche en test, mais pas dans cette démarche (j'ai testé moi-même)

Il s'agit de la démarche n°17 951

**Comment by benjaminhenkel** [comment]
Pourtant il semble bien que l'option cadastre ait été cochée (elle apparaît quand on clone la démarche)

**Comment by benjaminhenkel** [comment]
BD dév durable

**Comment by kemenaran** [comment]
Effectivement l'Instructeur prend une 404 quand il demande les zones cadastrales.

Je reproduis en local. Il faut que le champ :

- Soit une carte ou un champ répétable ;
- Soit dans les annotations privées ;
- Soit édité par un Instructeur qui n'a **pas** créé le dossier lui même.

L'accès aux champs Carte ou Champs répétables est géré depuis peu par Pundit :

```ruby
# app/controllers/champs/carte_controller.rb
policy_scope(Champ).find(params[:champ_id])
```

Mais le `ChampPolicy` en question ne fonctionne que si on est le propriétaire du dossier :

```ruby
# app/policies/champ_policy.rb
class ChampPolicy < ApplicationPolicy
  class Scope < Scope
    def resolve
      if user.present?
        scope
          .joins(:dossier)
          .where({ dossiers: { user_id: user.id } })
      else
        scope.none
      end
    end
  end
end
```

On ne gère donc que le cas où l'utilisateur courant est le propriétaire du dossier – et donc pas les annotations privées.

**Comment by kemenaran** [comment]
@benjaminhenkel c'est corrigé en production ; tu peux prévenir les gens du dev durable
