### ISSUE TITLE
ETQ Admin, je veux facilement renseigner l'adresse d'un service

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4395]
Lorsque je saisis l'adresse d'un service de ma structure pouvoir avoir accès à la base adresse comme le champ du formulaire plutôt qu'un champ texte

**Comment by ErwanLHH** [comment]
En complément on pourrait également copier un service afin d'ajuster le contenu

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/78063/admin-autocompletion-pour-renseigner-ladresse-dun-service
