### ISSUE TITLE
ETQ instructeur je voudrais signaler un mail hors mails automatiques via une notification

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4399]
Dans les échanges avec les utilisateurs il serait utile dans la phase de coconstruction de pouvoir pousser une notification vers l'usager lors d'un message rédigé dans la messagerie afin d'attirer son attention et de l'inciter fortement à consulter son espace usager.

Pour cela un témoin à cocher à côté du bouton envoi "notifier spécialement ce message" ou un bouton avec la double fonctions intégrée.

**Comment by kemenaran** [comment]
Quel est le besoin concret, exactement ?

(Pour mémoire aujourd'hui les usagers sont déjà notifiés de tous les messages. Le bouton rajouterait un titre "[Important]" au message, ou quelque chose comme ça ?)

**Comment by emsnytech** [comment]
Cela ne me semble pas essentiel....

**Comment by ErwanLHH** [comment]
Ce n'est pas stratégique j'en conviens mais cela permet de conserver le canal d'échanges avec l'usager dans DS en attirant son attention qu'il se passe quelque chose pour le dossier qu'il a déposé et pour lequel la phase de coconstruction est importante puisqu'elle permet de s'assurer de la complétude du dossier déposé.
Dans mon idée la fonctionnalité est simple et pousse un mail type "il se passe qqch sur votre dossier allez voir ici"

**Comment by kemenaran** [comment]
Comme expérience pour l'usager, c'est pas top : il ou elle reçoit donc un message "Il s'est passé quelque chose" – mais ensuite iel doit se débrouiller pour trouver ce qui a changé, sans aucune autre info.

@ErwanLHH tu as une description d'un cas d'usage **concret** de ça ?

**Comment by ErwanLHH** [comment]
J'ai 12 formulaires déclinés sur un thème (demande d'utilisation du compte formation) avec un potentiel théorique de 60 000 000 personnes en périmètre ( beaucoup moins pour les dossiers attendus, je vous rassure). Je vois en fonction de l'utilisation et vous fais le retour.

**Comment by kemenaran** [comment]
Cette issue est inactive depuis 4 mois : je la ferme pour l'instant. On pourra ré-ouvrir au besoin.
