### ISSUE TITLE
ETQ instructeur, je n'ai plus acces aux attestations des dossiers terminés

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#4400]
**Décrivez le bug**
ETQ instructeur, je n'ai plus acces aux attestations des dossiers terminés

**Reproduction**
1. Sur une procédure avec attestation, accepter un dossier
2. Cliquer sur le bouton de changement d'état pour voir l'attestation générée
3. Constater qu'il n'y a plus de lien pour voir l'attestation

**Comportement attendu**
On doit voir le lien pour télécharger l'attestation

**Image**
![Screenshot_2019-10-14 Demande · Dossier nº 768235) · demarches-simplifiees fr](https://user-images.githubusercontent.com/907405/66738865-be1f1780-ee6f-11e9-8ee2-cb5021cb90cf.png)

**Appareil et navigateur utilisé**
 - Tous les navigateurs

**Comment by kemenaran** [comment]
(wow, issue super-bien rédigée, top 👌)

**Comment by benjaminhenkel** [comment]
24018
