### ISSUE TITLE
ETQ Admin, je ne peux pas ajouter un instructeur

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4402]
Lorsque je tente d'ajouter une adresse email en tant qu'instructeur sur la démarche n°3723, la page d'erreur suivante s'affiche
![Screenshot 2019-10-14 at 15 00 25](https://user-images.githubusercontent.com/28590367/66753172-7f9b5400-ee93-11e9-9061-0dd3aa82d70d.png)

**Comment by benjaminhenkel** [comment]
# 23929

**Comment by kemenaran** [comment]
Je pense que c'est https://sentry.io/organizations/demarches-simplifiees/issues/1265671615/?project=1429550 – mais je ne reproduis pas systématiquement en prod.

> PG::UniqueViolation
>
> ERROR:  duplicate key value violates unique constraint "unique_couple_administrateur_instructeur"
> DETAIL:  Key (instructeur_id, administrateur_id)=(14125, 4908) already exists.

https://github.com/betagouv/demarches-simplifiees.fr/blame/e0571a8ae32ced85d9dce06ef2a18a0cc33d6018/app/models/user.rb#L76

**Comment by kemenaran** [comment]
## Investigation

C'est parce qu'on a un User qui a une adresse email, associé à un Instructeur qui a une autre adresse email.

```
> User.find(131489).email
fa@bas-rhin.gouv.fr
> User.find(131489).instructeur.email
fa@haute-marne.gouv.fr
```

Donc dans le `create_or_promote_to_instructeur`, on se vautre forcément :

https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/app/models/user.rb#L66-L80

1. Est-ce qu'il y a un Instructeur avec cet email ? Non => `create_or_promote_to_instructeur`
1. Est-ce qu'il y a un user existant ? Oui.
2. Est-ce qu'il faut créer un instructeur ? Non, il y  en a déjà un
4. Là on essaie d'assigner l'instructeur aux admins – et ça plante, parce qu'il existe déjà.

## Questions

- Est-ce qu'on ne devrait pas avoir de différence entre `User.email` et `User.instructeur.email` – et donc c'est de la Bad Data à corriger ?
- Ou est-ce que c'est légitime, et on doit corriger le code ?

**Comment by kemenaran** [comment]
## Réponses

Depuis les migrations récentes, l'email et le mot de passe sont portés uniquement par le modèle `User`.

Les colonnes `Instructeur.email` et `Admin.email` devraient donc être supprimées. Ça permettra de résoudre ce bug.

**Comment by kemenaran** [comment]
@benjaminhenkel en attendant j'ai corrigé les adresses incohérentes en production. L'ajout d'instructeurs devrait à nouveau fonctionner.

**Comment by kemenaran** [comment]
Corrigé par #4411
