### ISSUE TITLE
Supprimer les colonnes "emails" des tables Instructeur et Administrateur

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4410]
Depuis la migration des comptes, les infos email/password sont portées par le User.

Les colonnes `Instructeur.email` et `Administrateur.email` sont donc inutiles – et surtout trompeuses, vu qu'elles ne sont plus mises à jour.

1. [x] Migrer le code Instructeur (#4411)
2. [x] Ignorer la colonne Instructeur (#4411)
1. [ ] Migrer le code Administrateur
2. [ ] Ignorer la colonne Administrateur
3. [x] Supprimer les colonnes de la base
4. [ ] Retirer les colonnes ignorées

**Comment by kemenaran** [comment]
Je vais être sur les questions de pièces-jointes pendant les prochaines semaines – ce qui va me donner moins de temps pour m'occuper de ce sujet.

Si quelqu'un se sent de reprendre ce cleanup, je ne dis pas non :)

**Comment by kemenaran** [comment]
C'est fait côté Instructeur.

**Comment by kemenaran** [comment]
Wouhou, fin définitive de ce nettoyage, merci @krichtof !

**Comment by krichtof** [comment]
Yep @kemenaran , fin définitive de la colonne email pour Administrateur et Instructeur :)
Mais je continue le nettoyage en essayant de supprimer toutes les `ignored_columns` pour `Administrateur` et `Instructeur`
