### ISSUE TITLE
ETQ Instructeur, je veux une aide à la rédaction des décisions (et/ou motivations)

### ISSUE THREAD

**Issue by DanielBMY** [betagouv/demarches-simplifiees.fr#4421]
Sur demarches-simplifiees.fr, je suis agacé en tant qu'administrateur quand j'observe une différence de qualité dans la rédaction des motivations des différents agents instructeurs.

Les agents traitent des cas qui tournent essentiellement autour des mêmes textes de loi. Pour autant, à l'usage, ils refont presque à chaque dossier le travail de réflexion et de rédaction de leurs réponses. Selon la charge mentale et la charge de travail, la qualité des réponses varie. Cela nous génère du support lorsque que les usagers se sentent que leur demande n'a pas été bien prise en compte (motivations en mode post-it :( )

Nous avons partagé un document co-construit avec les Direccte des meilleurs rédactionnels pour motiver leurs décisions. Cependant, n'étant pas inclus dans l'outil DS, les agents oublient parfois de l'utiliser.

## Proposition de solution

Un nouvel onglet "aide à la décision" toujours re-configurable par l'administrateur au gré des améliorations de redaction des motivations et/ou changements des textes de loi.

Ou un outil inspiré de ce qui existe sur helpscout (où les templates apparaissent à l'endroit le plus pertinent selon par ex classement sans suite / refus etc.)

Sur Workinfrance, nous avons par ailleurs pour mission l'harmonisation des pratiques des Direccte. 
Une telle fonctionnalité interne à l'outil DS aiderait grandement à cela :)

**Comment by kemenaran** [comment]
Effectivement, ça a l'air légitime.

Côté DS on pourrait imaginer une fonctionnalité "Proposition de réponse" qui permette de définir des templates de réponse au niveau de la démarche – un peu comme HelpScout ou Github, yep.

**Comment by ErwanLHH** [comment]
Je rebondis sur le sujet, effectivement la motivation des décisions de refus (les décisions acceptées sont rarement motivées) est importante.
En attendant mieux serait-il possible d'avoir accès en admin à un champ déroulant/à choix multiple/combiné pour préparer la motivation de refus ? et cerise sur le gâteau pouvoir compléter ce motif de refus pré cadré par un autre champ libre en cas de besoin ?
Je suis en préparation d'une famille de procédures pour lesquelles je bricole un truc à base de préparation de templates de réponses dans un champ explication à copier coller par les instructeurs mais le risque d'erreur est là.

**Comment by kemenaran** [comment]
Effectivement ça me semble pertinent. J'ai déplacé la suggestion sur notre nouveau tableau de suivi des propositions : https://demarches-simplifiees.featureupvote.com/suggestions/78062/instructeur-proposer-une-aide-a-la-redaction-des-decisions-etou-motivations
