### ISSUE TITLE
ETQ Instructeur, lorsque je fais l'export excel, j'aimerais avoir le nom de la personne morale qui dépose dans la première feuille

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4422]
Si la démarche est faite pour les personnes morales, lorsque l'instructeur fait l'export excel, il est obligé d'aller dans la feuille "Etablissements" de l'excel pour savoir à quelle entreprise ou commune correspond le dossier. 

Proposition : Il faudrait que la colonne U de la feuille "Etablissements", nommée "Entreprise raison sociale", apparaisse aussi dans la feuille "Dossiers" par exemple au niveau de la colonne B

**Comment by benjaminhenkel** [comment]
Piccoz Pref 29

**Comment by kemenaran** [comment]
Ça m'a l'air pertinent. À la fois on n'a pas envie de recopier toute la table des infos SIRET directement dans le dossier – mais si on ne met que la clef de jointure, la personne qui consulte l'Excel ne voit pas du tout à qui correspond le dossier.
