### ISSUE TITLE
Éditeur de champ : les menus déroulants clignotent sur Firefox 52.5.3 Windows/Linux

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4428]
**Décrivez le bug**

Un clignottement des select dans firefox 52.5.3 rend pénible l'édition de formulaires

**Reproduction**

Le ministère des armées a remonté à plusieurs reprises un bug sur la version 52.5.3 de firefox:

```
Il suffit de télécharger la version identique de FFX que celle du poste de travail intradef  (PC)  à l’emplacement suivant :

https://ftp.mozilla.org/pub/firefox/releases/52.5.3esr/win64/fr/

Ensuite aller sur une démarche en tant qu’administrateur et jouer avec le menu de sélection de la nature des champs, ça saute tous le temps.

Je note que les 2 applications Intradef et Internet DINSIC sont réalisées avec une version react v16.8.6. ( si je comprends bien c’est un menu déroulant en REACT )

Paradoxalement, la même version sur Mac ne pose pas de problème.

IE11 ne pose pas de pb, sauf qu’un message indique que le navigateur est obsolète.

La version suivante FFX sur PC  https://ftp.mozilla.org/pub/firefox/releases/52.6.0esr/win64/fr/ ne pose pas de problème non plus.
```

J'ai reproduit le bug sous la version correspondante (linux ubuntu). Depuis l'édition de démarche, après avoir cliqué sur le menu, déplacer la souris de seulement quelques pixels fait sauter la sélection quelques lignes plus haut. C'est probablement pénible sur toute une démarche, mais on peut arriver à sélectionner les items qu'on veut.

Nous n'avons pas le problème en général, car il semble corrigé dans la version suivante de firefox. Je n'ai rien trouvé dans les release notes de Firefox qui en parle (malheureusement, ils ne publient des release notes que pour les versions majeures)

    https://www.mozilla.org/en-US/firefox/53.0/releasenotes/
    https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/53

Firefox 52 date de fin 2017. Le problème touche donc une population mineure (des administrations qui utilise une version obsolète du navigateur, le problème a seulement été remonté par les armées). Il peut être corrigé en montant de version de Firefox. Les contributions sont bienvenues pour investiguer plus en avant ce problème.
![bug-menu-déroulant](https://user-images.githubusercontent.com/1223316/67371827-45117580-f57d-11e9-8b47-d4c674c7446a.gif)

**Comportement attendu**

Pas de clignottement

**Appareil et navigateur utilisé**
 - Appareil : PC windows/linux (mais pas mac)
 - Navigateur : Firefox firefox 52.5.3esr

**Comment by Keirua** [comment]
Suite à de nouveaux échanges avec le MinArm, le problème viendrait (je les laisse détailler et clarifier) du mécanisme de rafraichissement de la page via react.

React détruit puis reconstruit la page en continu à chaque modification, ce qui est la source de ce problème lorsqu'il y a des pertes sur l'état interne des composants. Ça n'est pas visible en général:
 - la plupart du temps, l'état interne des champs est bien conservé, et donc malgré le rafraichissement on retombe bien sur nos pates avec les champs bien affichés
 - c'est visible chez eux car ils ont une vieille version, mais le «problème» affecte tout le monde (et c'est sans doute la cause de problèmes de performances)

La solution serait de modifier la manière dont on consomme l'information de changement d'état au niveau de react pour mieux gérer ces rafraichissements

**Comment by kemenaran** [comment]
De fait, vu à l'instant dans mon navigateur : c'est vrai qu'on re-rend l'éditeur de champ en permanence…

(Aucune interaction utilisateur pendant ce gif.)

![editeur-de-champs](https://user-images.githubusercontent.com/179923/67473150-79a33100-f652-11e9-8d47-6137a0068048.gif)

**Comment by tchak** [comment]
je vais regarder
