### ISSUE TITLE
ETQ Usager, je veux un n° de téléphone de contact valide pour joindre l'administration

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4433]
**Votre amélioration est liée à un problème spécifique ?**
Aujourd'hui sur DS, on a :

- 3500 services avec un n° de téléphone renseigné
- dont 93 services où le n° de téléphone est manifestement bidon.

```
> Service.where.not(telephone: nil).where('LENGTH(telephone) < 10').pluck(:telephone); nil
["02020202",
 "00000000",
 "--",
 "xxx",
 "xxx",
 "hgfd",
 "xxxxxxxxx",
 "01",
 "xxx",
 "020222",
 "121234566",
 "fZEFzf",
 "012456789",
 "012356789",
 "-",
 "-",
 "-",
 "000000000",
 "0",
 "3646",
 "-",
 "02020202",
 "3646",
 "01",
 "40468943",
 "007",
 "3430",
 "3646",
 ".",
 ".",
 "0",
 ".",
 ".",
 "UOUIUOI",
 "0000000",
 "36 46",
 ".",
 "UOUIUOI",
 "01",
 ".",
 ".",
 "00000000",
 "-",
 "27 31 15 ",
 "Néant",
 "-",
 "015599558",
 "3646",
 "O5656",
 "00000000",
 "016991",
 "40803964",
 "02",
 "2343",
 "038888888",
 "59623",
 "-",
 "ersgt",
 "NC",
 "hhh",
 "3646",
 "016991911",
 "01010101",
 "090909009",
 " /",
 "0",
 ".",
 "xxx",
 "3430",
 "-",
 "40124578",
 "40803865",
 "40803865",
 "-",
 "40478400",
 "5111",
 "000000000",
 "000000",
 "000000",
 "012010201",
 "3646",
 "40478400",
 "/",
 "038888888",
 "02",
 ".",
 "00000000",
 "3400",
 "012345678",
 "01",
 "xxxxx",
 "012345678",
 "*********"]
```

Concrètement, ça fait que les Usagers d'une démarche ne peuvent pas joindre l'administration par téléphone.

**Décrivez la solution proposée**

On devrait :

- Mieux expliquer pourquoi c'est important que les usagers puissent joindre l'administration
- Mettre un validateur sur le n° de tel, pour rendre plus difficile de mettre un n° bidon

**Comment by Keirua** [comment]
On se dit qu'il faut aussi contacter également les administrations des démarches actives publiés (soit en tant qu'équipe, soit etq dinsic) pour demander aux demarches concernées de corriger leur numéro incorrect.

**Comment by krichtof** [comment]
Les numéros de téléphone à 4 chiffres ne sont pas forcément bidons.
Par exemple, 3646, c'est le centre de contact de l'assurance maladie : https://lannuaire.service-public.fr/centres-contact/R19040

**Comment by krichtof** [comment]
Et là, je viens de découvrir une palanquée de numéros de centres de contact : https://lannuaire.service-public.fr/centres-contact

**Comment by krichtof** [comment]
Le numéro 273115 est également correct : https://www.horaire-ouverture.fr/mairie-noumea.html

**Comment by krichtof** [comment]
Du coup, comme règle de validation, je propose : 
- invalide quand il y a des lettres
- invalide quand il y a moins de 4 chiffres

Vous en voyez d'autres ?

**Comment by tchak** [comment]
Tu veux pas essayer un truc comme https://github.com/daddyz/phonelib ?

**Comment by krichtof** [comment]
J'utilise habituellement https://github.com/floere/phony
@tchak Une raison particulière de me conseiller phonelib par rapport à d'autres gem ?

**Comment by tchak** [comment]
Absolument pas. Je voulais juste dire que je commencerai par tester avec une bonne lib bien complète et j'ajouterai des contraintes à partir des résultats.

**Comment by krichtof** [comment]
:+1: Alors nous sommes complètement d'accord @tchak !

**Comment by benjaminhenkel** [comment]
Je suis totalement d’accord sur le fait qu’il soit important que les administrations proposent un support efficace pour les usagers. 

En revanche, je ne vois pas pourquoi on imposerait un support téléphonique plutôt qu’un support par mail par exemple. C’est extrêmement lourd à faire fonctionner et très chronophage pour les agents avec des tâches qui sont souvent à faible valeur ajoutée. En effet, il s’agit souvent de répéter les mêmes éléments de réponse et l’automatisation est impossible par téléphone ( contrairement au mail ). Les agents n'ont souvent pas le temps de faire cela. 

Et je parle en connaissance de cause, puisqu’on avait une hotline il n’y a pas si longtemps sur DS !

De plus, si on l’impose aux administrations contre leur gré, soit elles vont mettre un faux numéro, soit elles mettront un numéro auquel personne ne répondra... et ça ne fera pas avancer la cause de l’usager !

**Comment by krichtof** [comment]
PR mergée le 4/12/2019
https://github.com/betagouv/demarches-simplifiees.fr/pull/4521
