### ISSUE TITLE
Erreur 500 lors de l'export de données tableur

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4434]
J'ai testé l'export de données d'une procédure en test et j'ai constaté que l'export nouvelle formule était maintenant généré avec un lien de téléchargement dans un mail.
Lorsque j'ai suivi le lien de téléchargement : erreur 500
![image](https://user-images.githubusercontent.com/49941223/67459650-6172e800-f639-11e9-8030-165ca6fcb30b.png)

PC HP, Mozilla 
69.0.3
Firefox Release

October 10, 2019

**Comment by Keirua** [comment]
Salut @ErwanLHH , un correctif est en ligne, tu vas pouvoir télécharger à nouveau les exports.

**Comment by ErwanLHH** [comment]
Merci !!! Top efficacité !

**Comment by Keirua** [comment]
Super !
