### ISSUE TITLE
Fusionner certains types de champs ?

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#444]
Checkbox et engagement sont quasi-identiques
Checkbox et oui / non sont différents mais le principe est le meme

![screen shot 2017-06-15 at 15 42 06](https://user-images.githubusercontent.com/1333173/27184079-3529ce2a-51e1-11e7-9c93-5bdb18dac7c2.png)

**Comment by kemenaran** [comment]
ÀMHA on veut vraiment exposer des usages, pas des types de champs. Ça permet d'exposer quelque chose de sémantique, quelque soit l'implémentation.

Du coup ça me va bien d'avoir checkbox, oui/non (et éventuellement Engagement).

**Comment by gregoirenovel** [comment]
J'aimerais bien qu'on ait cette discution, et engamement / checkbox c'est quand meme exactement la meme chose, donc je rouvre

**Comment by benjaminhenkel** [comment]
Je plussoie donc Grégoire sur la partie engagement/checkbox qui est effectivement la même chose et qui est donc plus de nature à porter à confusion qu'autre chose. 
Surtout qu'on est plutôt amené à multiplier les champs, donc une simplification serait bienvenue !
