### ISSUE TITLE
ETQ Super Admin, je veux avoir accès aux rapports Metabase

### ISSUE THREAD

**Issue by chaibax** [betagouv/demarches-simplifiees.fr#4453]
Beaucoup de requêtes existantes dans Metabase ne sont plus correctes. 

Certainement dû au changement de nom de la table "gestionnaire", mais peut-être aussi à cause d'un changement sur le champ d'activation d'un admin. 

Bref, pas mal de questions sont cassées :(

**Comment by kemenaran** [comment]
Remplacé par #4894
