### ISSUE TITLE
Échec d'initialisation de l'environnement de dev

### ISSUE THREAD

**Issue by afriqs** [betagouv/demarches-simplifiees.fr#4482]
**Description du bug**

L'[initialisation de l'environnement de dev](https://github.com/betagouv/demarches-simplifiees.fr#initialisation-de-lenvironnement-de-d%C3%A9veloppement) ne va pas au bout du processus car la base de données n'existe pas encore.

**Reproduction**

Comment reproduire le problème :
1. Supprimer les bases de données **tps_development** et **tps_test**
1. Lancer `bin/setup` ou `bundle exec rake db:create`

Erreur : 
```
== Preparing database ==                                                                                                                                                
rails aborted!                                                                                                                                                                        
PG::ConnectionBad: FATAL:  la base de données « tps_development » n'existe pas
```
**Comportement attendu**

Installation et initialisation complètes.

**Comment by kemenaran** [comment]
C'est à cause de Flipper qui essaie de se connecter dans la tâche Rake.

@tchak tu ne parlais pas d'avoir corrigé un truc dans le genre à un moment ?

**Comment by tchak** [comment]
Je pense que le problème avec Flipper est corrigé. Si vous me confirmez que c'est encore ça le problème je veux bien regarder.

**Comment by tchak** [comment]
Je ne reproduit pas chez moi. @afriqs ping moi sur slack si besoin.

**Comment by afriqs** [comment]
Le problème vient du fait que je ne reçois pas l'exception `ActiveRecord::NoDatabaseError` mais `PG::ConnectionBad`.

Si je rajoute `PG::ConnectionBad` ça passe sans problème mais je ne comprends pas pourquoi nous n'avons pas le même comportement :thinking: 

Est-ce que je rajoute `PG::ConnectionBad` et on n'en parle plus (ça n'arrive qu'à la mise ne place de l'appli et PostgreSQL est obligatoire) ou est-ce qu'on creuse un peu plus ?

Note : une piste de réflexion : https://github.com/rails/rails/issues/32994

**Comment by LeSim** [comment]
Perso je serais pour rajouter le `PG::ConnectionBad`
