### ISSUE TITLE
ETQ Admin dans le nouvel écran de description d'un formulaire il y a des informations qui proviennent d'autres champs

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4494]
**Décrivez le bug**
Une description claire et concise du problème, en une phrase ou deux.

**Reproduction**
Comment reproduire le problème :
1. Aller sur la page '...'
2. Cliquez sur '...'
3. Une erreur '.....' apparaît

**Comportement attendu**
Comment le site aurait-il dû se comporter ?

**Capture d'écran**
Si besoin, ajoutez une capture d'écran de votre problème. Cela nous aide à identifier plus rapidement le souci.

**Appareil et navigateur utilisé**
 - Appareil : [par exemple PC, Mac, iPhone, Android]
 - Navigateur : [par exemple Firefox, Chrome, Safari]

**Comment by ErwanLHH** [comment]
Lorsque j'utilise l'écran de description d'un formulaire j'ai constaté à plusieurs reprises que le contenu de l'écran de saisie était prérempli avec des informations manipulée dans d'autres champs.
![image](https://user-images.githubusercontent.com/49941223/68381196-7e3b0f80-0151-11ea-9553-642f1139c239.png)
en jaune ce qui ne va pas et en vert les valeurs qui ont été saisies initialement et qui sont correctes

**Comment by ErwanLHH** [comment]
J'ai réussi à revenir à un comportement normal en me déconnectant/reconnectant.

**Comment by ErwanLHH** [comment]
Mozilla 70.0.1 (32 bits)

**Comment by kemenaran** [comment]
@ErwanLHH merci pour le signalement.
Tu peux nous dire si tu rencontre le problème à nouveau ?

**Comment by ErwanLHH** [comment]
je l'ai rencontré hier mais je pensais avoir mal joué du clavier et aujourd'hui par contre je suis sûr de n'avoir rien fait de pas catholique, d'où mon signalement.
Pour le moment cela a l'air plutôt stable....

**Comment by kemenaran** [comment]
@ErwanLHH ça marche. Je ferme cette issue pour l'instant – mais si tu as à nouveau le problème n'hésite pas à la ré-ouvrir.
