### ISSUE TITLE
ETQ Instructeur, je souhaiterais lire facilement les grands nombres grâce à des séparateurs de milliers

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4501]
Peu de visibilités actuellement quand on lit des nombres 

![Screenshot 2019-11-07 at 17 06 06](https://user-images.githubusercontent.com/28590367/68405864-21574d80-0181-11ea-90f6-95f23cc456f0.png)

Mettre des séparateurs de milliers pourrait rendre simplifier la lecture des dossiers

**Comment by benjaminhenkel** [comment]
A communiquer 
# 25292

**Comment by ErwanLHH** [comment]
Je m'associe pleinement à la demande  !

**Comment by emsnytech** [comment]
idem

**Comment by benjaminhenkel** [comment]
27264

**Comment by benjaminhenkel** [comment]
Gaudin PREF52

**Comment by kemenaran** [comment]
Les gens qui gèrent une démarche avec un n° de pass navigo nous signalent qu'avec les séparateurs de milliers, il leur est maintenant difficile de copier/coller le n° de pass sans avoir des espaces en rab qui apparaissent.

J'ai l'impression qu'il y a plusieurs solutions possibles à ça :

## 1. Reverter les changements

**Pour** :

- On ne casse rien

**Contre :**

- On pert le bénéfice de la fonctionnalité pour tout le monde, à cause d'un seul cas spécifique.

## 2. Mettre des espaces qui n'apparaissent pas au copier-coller

**Pour :**

- C'est une solution élégante et simple

**Contre :**

- De tels caractères n'ont pas l'air d'exister en web ou en Unicode :'(

## 3. Modifier les démarches qui posent problème 

On change le type de champ utilisé par le pass Navigo de "number" à "string".

**Pour :**

- Ça résout pile le problème de la démarche qui coince, et rien de plus.
- Pour les démarches futures, elles pourront, en phase de test, voir si elles préfèrent avoir des champs nombre ou texte.

**Contre :**

- Faudrait vérifier les effets de bord de cette modification sur cette démarche.

## 4. Formater les nombres avec du HTML plutôt que des espaces

Dans les pages web, au lieu d'utiliser `number_with_delimiter`, on écrit un petit helper à nous `number_with_html_delimiter`, qui émet par exemple `198<span class="thousands-delimiter"></span>876`. 

**Pour :**

- C'est clair et simple

**Contre :**

- Ça oblige à avoir deux helpers différents : un quand on veut du HTML, et un quand on veut du texte.

## 5. Utiliser du Javascript pour supprimer les espaces

Au moment où on détecte que l'utilisateur copie du texte, on peut modifier le presse-papier pour enlever les espaces (s'il n'y a que des chiffres dedans).

**Pour :**

- Ça couvre tous les cas d'usage d'un coup

**Contre :**

- C'est du Javascript tricky, et pas géré dans tous les navigateurs
- C'est difficile de comprendre pourquoi les espaces ne sont pas copiés quand on en a besoin
- Ça n'a pas l'air évident de lire le presse-papier dans tous les cas (par exemple quand on copie le contenu d'un champ).

---

À vue de nez, les solutions 3. (modifier la démarche) ou 4. (formatter en HTML) me semblent les meilleures. @kara22 tu en penses quoi ?

**Comment by kara22** [comment]
@kemenaran La solution 3 me semble bien, je me demande juste si le Navigo est le seul cas spécifique pour cette feature ? 

Si ce n'est pas le seul cas la solution 4 serait mieux sur le long terme ?

**Comment by kara22** [comment]
Sinon nous pouvons aussi rajouter un champ "monétaire" qui aurait les séparateurs de milliers.

Et sur le champ "nombre" on reviens comme c'était avant.

Le souci c'est que les séparateurs de milliers seront uniquement dispo pour les nouvelles démarches, ou le champ "monnétaire" à été choisi

**Comment by kemenaran** [comment]
Une fois avoir dormi dessus, je me suis dit que la solution 3 (modifier le type du champ) n'était pas la meilleure solution – parce que ça ne marche que pour la démarche qui nous a signalé le problème, en ignorant les autres qui peuvent avoir le souci, mais ne nous le disent pas.

Et pour la devise pourquoi pas – mais en même temps on a déjà mille champs "Nombre" différents. Et si on fait un champ "Monétaire" on va devoir gérer la devise (€, $…)

Je crois que j'en suis au point où la solution 4. (Mettre les séparateurs de milliers avec du HTML qui n'affecte pas le copier/coller) me semble la meilleure solution. Ça a le mérite de marcher partout, et d'être tout bête à implémenter (et à comprendre).

J'imagine que ça donnerait un truc du genre :

```ruby
def number_with_html_delimiter(number)
  number_with_delimiter(number)
    .replace(' ', '<span class="numbers-delimiter"></span>'.html_safe)
end
```
