### ISSUE TITLE
ETQ usager, je souhaite modifier le SIRET ou le nom/prénom de mon dossier en construction

### ISSUE THREAD

**Issue by red1bush** [betagouv/demarches-simplifiees.fr#4506]
ETQ usager je veux modifier mon dossier, je peux changer le contenu du dossier mais je ne peux agir sur le premier ecran (SIRET/Nom-prénom)

**Comment by kemenaran** [comment]
Je viens de tester : on peut bien modifier le nom, prénom et le SIRET d'un dossier en construction.

<img width="770" alt="Capture d’écran 2020-02-10 à 12 42 32" src="https://user-images.githubusercontent.com/179923/74147108-de36cb80-4c02-11ea-9d79-41915fdb2b91.png">
