### ISSUE TITLE
ETQ Instructeur je souhaite savoir quel instructeur assure le suivi d'un dossier donné depuis l'onglet suivi

### ISSUE THREAD

**Issue by ndrianab** [betagouv/demarches-simplifiees.fr#4512]
Proposition d'un administrateur : l'ajout d'une colonne "Suivi assuré par", dans l'onglet "Suivis", pourrait être d'une grande aide aux instructeurs des dossiers pour peu qu'il y ait beaucoup de dossiers à suivre et beaucoup d'instructeurs différents.

Référence : helpscout #25101

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/77374/instructeur-savoir-depuis-le-tableau-de-bord-quel-instructeur-assure-le-suivi-du
