### ISSUE TITLE
ETQ Instructeur, j'aimerais savoir si l'usager s'est connecté avec FranceConnect

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4516]
Aujourd'hui impossible de savoir comment s'est connecté l'usager (avec FranceConnect ou un compte DS). C'est problématique dans la mesure où on explique aux administrations que si l'usager se connecte avec FranceConnect alors celui-ci n'a pas besoin de prouver son identité. 
Comme c'est impossible à savoir, l'administration est obligé de demander à l'usager de prouver son identité dans tous les cas, limitant par là l'intérêt de FranceConnect.

**Comment by emsnytech** [comment]
Très important en effet de pouvoir distinguer en back office si la personne s'est connecté avec DS ?
Cela ne donne pas la même valeur au dossier.

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/77371/instructeur-savoir-si-lusager-sest-connecte-avec-france-connect
