### ISSUE TITLE
ETQ utilisateur, je veux pouvoir accéder à mes dossiers via l'API

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4526]
**Le problème**
L'API est accessible uniquement aux administrations qui exposent leurs procédures.
Cependant, des utilisateurs (ex: CAF, aidants…) peuvent avoir beaucoup de dossiers, parfois à faire correspondre avec une BDD interne

**Solution proposée**

Permettre aux utilisateurs d'avoir un jeton API pour leur permettre d'accéder à leurs dossiers via l'API.
Sans doute faisable facilement dans l'API graphql qui se profile?

**Plus de contexte**

HS 25468

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/77369/utilisateur-acceder-a-mes-dossiers-via-lapi
