### ISSUE TITLE
Finir de décommissionner CarrierWave

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4533]
Donc à priori on n'a plus qu'à décommissionner CarrierWave :

- [x] Supprimer le code lié à CarrierWave
- [ ] Supprimer les fichiers sur le bucket
- [ ] Supprimer la facturation CarrierWave

**Comment by Keirua** [comment]
@LeSim on a l'impression que c'est bon, tu rouvres si c'est pas le cas?
