### ISSUE TITLE
Déprécier IE11

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#4534]
Le mettre dans la liste des navigateurs dépréciées (bandeau etc)

Dans 6 mois retirer les regles de transpilation spécifiques

**Comment by kemenaran** [comment]
Le bandeau a été mis en prod – puis désactivé, pour ne pas faire double-bandeau avec la grève.

On attend que la grève se tasse pour remettre le bandeau IE11.
