### ISSUE TITLE
Bumper Capybara

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4536]
Pour passer à Rails 6, on doit bumper les gems.

Le bump de Capybara n'est pas évident :

- Ça lève des problèmes de timing dans les tests de l'éditeur de champ
- Les nouvelles versions de Capybara échouent maintenant quand une exception JS est levée

Il mettre à jour les feature-tests pour qu'ils passent avec la dernière version de Capybara.

**Comment by Keirua** [comment]
`Ça lève des problèmes de timing` = ça les résoud, ou bien ça en introduit de nouveaux ?

**Comment by kemenaran** [comment]
Oups, pardon ; je voulais dire que ça en introduit de nouveaux – ou en tout cas ça exacerbe ceux qui étaient déjà là :)
