### ISSUE TITLE
Description des entrées du env.example

### ISSUE THREAD

**Issue by mfaure** [betagouv/demarches-simplifiees.fr#4537]
**Votre amélioration est liée à un problème spécifique ?**

Les entrées du fichier `config/env.example` ne sont pas décrites

**Décrivez la solution proposée**

Ajouter un peu de doc :)

**Plus de contexte**

L'idée est d'initier le mouvement, pas forcément de tout faire du premier coup

**Comment by kemenaran** [comment]
On a maintenant quelques commentaires dans le .env.example. Je ferme.

**Comment by mfaure** [comment]
merci @kemenaran !

Effectivement : https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/config/env.example

 /cc @Haradwaith
