### ISSUE TITLE
ETQ Administrateur/instructeur je n'arrive pas à me connecter facilement à un formulaire comme usager

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4541]
J'ai voulu me connecter à votre formulaire de retour d'expérience avec DS.
ICI
![image](https://user-images.githubusercontent.com/49941223/69221201-01f3f380-0b77-11ea-80d8-3f1a37000f5d.png)
 
J'ai eu la fenêtre d'authentification sur la procédure et choisi "j'ai déjà un compte".
Id + mdp, mail de confirmation => normal

lorsque je clique sur le jeton d'authentification j'accède à DS en tant qu'Administrateur/instructeur mais je ne peux pas accéder au formulaire sauf à revenir sur le lien ou à me déconnecter/reconnecter puis aller sur le lien.

J'ai déjà plusieurs fois été interrogé par des utilisateurs qui rencontraient ce pb et la solution de se connecter à DS PUIS d'aller sur le lien fonctionne mais elle n'est pas vraiment agréable pour l'usager et suscite une irritation ou un soupçon de bug.
Pour les utilisateurs rompus ce n'est pas un souci mais avec le succès grandissant de DS les instructeurs ne seront pas toutes et tous aussi résilient et astucieux, et pourront utiliser cela pour freiner l'utilisation et ternir l'image du service rendu.
Bref, je profite du thème d'ouverture de l'infolettre pour relancer le sujet.

**Comment by kemenaran** [comment]
Exact, c'est un cas répertorié de cette issue : #3366.

L'issue #3366 est d'ailleurs un peu vague, alors que ce cas est très précis et assez pénible. Je rajoute ça dans notre backlog, on va essayer de prioriser ça à un moment.

@ErwanLHH merci pour le retour là dessus.

**Comment by kemenaran** [comment]
Je ferme au profit de #3366, pour ne pas dupliquer les issues – mais on va regarder ça.
