### ISSUE TITLE
[Routage] ETQ usager, je ne dois pas pouvoir choisir le groupe "Défaut"

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4542]
Il ne faudrait pas que le groupe défaut apparaisse dans les choix proposés à l'usager. 

![image001 (1)](https://user-images.githubusercontent.com/28590367/69225586-e987d700-0b7e-11ea-8c35-c0cf0b823ec8.png)

**Comment by LeSim** [comment]
Salut Benjamin.

J'ai l'impression qu'il y a un problème de sémantique. Le groupe `défaut` est un groupe comme un autre, l'administrateur peut le renommer.

**Comment by benjaminhenkel** [comment]
Ah ok, je vois, merci ! 

Je pensais que cela répondait à un besoin, à savoir : avoir un groupe d'instructeurs qui ait accès à tous les dossiers, sans distinction ! Je ne sais pas si c'est prévu/envisageable ? Des discussions que j'ai pu avoir, cela me semblerait utile !
