### ISSUE TITLE
ETQ Administrateur je veux pouvoir configurer les noms des états du dossier

### ISSUE THREAD

**Issue by tchak** [betagouv/demarches-simplifiees.fr#4543]
Certaines administrations (ex DIE) ont un langage métier spécifique et souhaitent pouvoir adapter le vocabulaire dans DS à leur métier.

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/78065/administrateur-configurer-les-noms-des-etats-du-dossier
