### ISSUE TITLE
ETQ Administrateur je souhaite valider les instructeurs lors d'un changement d'adresse mail d'un compte

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4557]
J'ai testé la fonctionnalité de changement d'adresse mail dans DS.
Simple, fluide, top ! 👍 
Pour une utilisation par les usagers je ne vois pas vraiment d'irritant pour les instructeurs, si ce n'est que le contrôle que l'on peut faire sur la syntaxe de l'adresse mail et du dossier associé peut être un peu amoindri si l'usager a déposé une demande avec une demande en prenom.nom@truc.com + prenom nom et qu'il modifie son mail qui ne sera plus raccord avec le nom dans le dossier. Peut-être que figer les adresses mails du compte d'un dossier après le passage en instruction serait une bonne chose.

**Par contre pour les administrateur, je suis beaucoup plus réservé**. L'administrateur choisit les instructeurs et le changement d'adresse mail étant automatique, l'administrateur n'a pas d'alerte sur cette évolution de son périmètre d'instructeurs désignés ; alors qu'il s'agit de sa responsabilité (au sens administratif et juridique) de délimiter qui a accès au formulaire et aux données.

La solution serait que le nouveau compte d'adresse mail de l'instructeur soit sorti du périmètre des instructeurs autorisés en attendant que l'administrateur valide ce nouveau compte (ou pas).
Pas besoin de mécanisme d'alerte, si l'instructeur qui a changé son adresse le souhaite, il recontactera l'administrateur pour ouvrir les droits au nouveau compte.

**Comment by ErwanLHH** [comment]
J'ajoute cette capture d'écran des CGU de DS qui précise bien que l'administrateur est responsable de l'habilitation des comptes instructeurs
![image](https://user-images.githubusercontent.com/49941223/69859036-9b1bbc00-1293-11ea-97a3-0e3f7ae5744c.png)

**Comment by kemenaran** [comment]
Aujourd'hui on ne permet plus aux Instructeurs de changer d'adresse email. Ça résout la problématique de la validation :)
