### ISSUE TITLE
ETQ Usager je ne peux pas utiliser un calendrier dans un champ date sous Firefox 52

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/demarches-simplifiees.fr#4560]
**Décrivez le bug**
Sur le Firefox 52.5.3, le champ date n'affiche pas l'agenda,  je dois saisir la date au format JJ/MM/AAAA avec le clavier.

**Reproduction**
Comment reproduire le problème :
1. Aller sur la page de remplier d'un dossier avec un champs type "date"

**Capture d'écran**
Firefox 52:
![image](https://user-images.githubusercontent.com/9320719/69353472-d3614000-0c7e-11ea-92c7-273abd75b3b5.png)
Firefox 70:
![image](https://user-images.githubusercontent.com/9320719/69353283-8e3d0e00-0c7e-11ea-8419-e0c294be2673.png)

**Appareil et navigateur utilisé**
 - Appareil : [PC, Windows 10]
 - Navigateur : [Firefox 52]

**Comment by kemenaran** [comment]
Intéressant. Je pense que pour nous les bugs de Firefox 52 (sorti en septembre 2016) ne sont pas les plus prioritaires – mais si vous trouvez un correctif on est preneur.

**Comment by Keirua** [comment]
Je clos car ce n'est pas un bug de DS et qu'il n'y a par ailleurs pas eu d'activité à ce sujet.
