### ISSUE TITLE
ETQ Administrateur Instructeur je souhaiterais un écran récapitulatif et de pilotage d'une procédure

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4562]
Pour les administrateurs et instructeurs ce serait top d'avoir un écran récapitulatif et de pilotage d'une procédure afin de pouvoir centraliser les informations à un seul endroit.
Cet **écran serait uniquement récapitulatif** des informations qui sont présentes dans DS, éventuellement il y aurait un lien vers la partie concernée pour maj/écriture
Voici une idée/proposition d'organisation de cet écran
![image](https://user-images.githubusercontent.com/49941223/69355960-faba0c00-0c82-11ea-920c-27d1d34eed23.png)

Gain pour les administrateur de pouvoir contrôler une procédure en un coup d'oeil sans changer de rôle
Gain faciliter le respect des obligation de déclaration au registre de traitement des données, notamment si on peut avoir un export des données présentées sur cet écran (reste la question du format de cet export)
Gain pour les instructeurs qui pourraient ainsi mieux comprendre le tableau d'ensemble d'une procédure et éventuellement mieux renseigner l'usager en cas de question

C'est bientôt Noël alors je demande ;-) :-)

**Comment by ErwanLHH** [comment]
J'ajoute également la liste des instructeurs ayant demandé une extraction des données, cela permet de voir qui l'a fait et le rythme avec la date

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/77353/administrateur-avoir-un-ecran-recapitulatif-et-de-pilotage-dune-demarche
