### ISSUE TITLE
ETQ Usager, je veux que l'on contrôle si je rentre bien mon numéro sous un format correct

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4566]
Actuellement le champ téléphone est assez souple : il accepte par exemple "34324.32432" ou un numéro à 20 chiffres par ex.

**Comment by benjaminhenkel** [comment]
@krichtof  est-ce que ce ne serait pas plus ou moins la même chose que ce que tu as fait pour le contrôle du numéro de service ? (et donc potentiellement simple à reproduire ?)

**Comment by benjaminhenkel** [comment]
HS 25255

**Comment by kemenaran** [comment]
Oui, c'est voulu. En fait un numéro de téléphone peut avoir [plein de formats différents](https://fr.wikipedia.org/wiki/Num%C3%A9ro_de_t%C3%A9l%C3%A9phone) :

- 10 chiffres (`01 02 02 43 77`)
- Préfixe international (`+33 6 01 02 03 04`, ou `0033 6 01 02 03 04`)
- Numéro court (`17`, `1033`)
- Numéro avec des lettres (`1-800-taxicab`)
- Numéro international (là ça peut être ce qu'on veut)

Du coup c'est difficile d'avoir une validation stricte : y'a plein de numéros valides qui ne sont pas des numéros auxquels on penserait spontanément.

Sur DS on utilise une validation [entre souple et stricte](https://github.com/betagouv/demarches-simplifiees.fr/blame/1de4ef8a9af0e8a9ac8b8397dc51ef8cecf56b5f/app/views/shared/dossiers/editable_champs/_phone.html.haml) :

```haml
-# Allowed formats:
-# 0123456789
-# 01 23 45 67 89
-# 01.23.45.67.89
-# 0123 45.67.89
-# 0033 123-456-789
-# 0035 123-456-789
-# 0033 123-456-789
-# 0033(0)123456789
-# +33-1.23.45.67.89
-# +33 - 123 456 789
-# +33(0) 123 456 789
-# +33 (0)123 45 67 89
-# +33 (0)1 2345-6789
-# +33(0) - 123456789
-# +1(0) - 123456789
-# +2 123456789
-# 012345678
-# 01234567890
= form.phone_field :value,
  placeholder: champ.libelle,
  required: champ.mandatory?,
  pattern: "([\\+\\d\\(][\\(\\)\\s\\.\\-\\d]{4,}\\d)"
```

Le mieux serait sans doute d'écrire **un article dans la FAQ Admin** pour expliquer qu'il y aura toujours une marge d'incertitude sur les numéros de téléphone, et que c'est la vie :)

**Comment by benjaminhenkel** [comment]
Merci !
