### ISSUE TITLE
ETQ usager, je dois entrer une adresse email valid pour m'inscrire

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4575]
**Votre amélioration est liée à un problème spécifique ?**

Les usagers peuvent entrer des emails incorrects lors de l'inscription

**Décrivez la solution proposée**
Ajouter un champ de ce genre. 2 options:
 - vérifier à partir d'une liste de domaines (yahoo.fr/.com, gmail.com, hotmail…) que l'adresse entrée est proche (distance de levenstein <= 1), et proposer la correction en conséquences lorsque l'usager quitte le champ "email".
 - vérifier que l'adresse existe au niveau smtp (est-ce possible?)

<img width="346" alt="force-correct-domain" src="https://user-images.githubusercontent.com/1223316/69636197-5a832f00-1056-11ea-88ac-5a950c6adf0e.png">

**Plus de contexte**
Suite spirituelle de https://github.com/betagouv/demarches-simplifiees.fr/issues/4419

**Comment by kemenaran** [comment]
@Keirua pour info je crois qu'il y a des libs Javascript pour fournir le message en question (et à charge ensuite pour nous d'intégrer le message fourni dans l'UI)

**Comment by Keirua** [comment]
J'ai pas vu bcp de librairies chouettes (la suggestion d'email, ça ne secoue pas les foules manifestement), mais j'ai l'impression que https://www.npmjs.com/package/email-butler peut le faire:
 - c'est raisonnablement bien écrit (et en typescript)
 - c'est récent (dernier commit il y a 3 mois)
 - bonus: c'est performant, car basé sur [sift4](https://web.archive.org/web/20190613223908/http://siderite.blogspot.com/2014/11/super-fast-and-accurate-string-distance.html), apparement plus rapide que la distance de levenshtein, en particulier sur des batches de vérification.

Quand on a un moment cette semaine on aimerait pairer avec Christophe là dessus
