### ISSUE TITLE
ETQ Admin je souhaiterais intégrer des pictogrammes dans le formulaire

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4576]
Une demande formulée par une des stagiaires de la formation que l'on donne à DS.
Est-il possible de disposer d'un champ qui intégrerait un pictogramme dans le cours du formulaire ?
Solution 1 : bibliothèque de pictogrammes
Solution 2 : pouvoir déposer une image librement

Cela permettrait d'améliorer la lisibilité du formulaire .

**Comment by kemenaran** [comment]
Une bibliothèque de pictogrammes ça pourrait être une idée.

Ça serait pour l'intégrer à quel genre d'endroits dans les formulaires ?

**Comment by ErwanLHH** [comment]
Les pictogrammes viendraient en renfort des sections et explications et également pour structurer les annotations privées

**Comment by fle-roy** [comment]
Super idée!!

**Comment by fle-roy** [comment]
le picto "point d'exclamation"

**Comment by kemenaran** [comment]
Déplacée vers https://demarches-simplifiees.featureupvote.com/suggestions/77356/administrateur-inserer-des-pictogrammes-dans-le-formulaire
