### ISSUE TITLE
ETQ Instructeur, je veux que "télécharger toutes les pjs" incluent aussi les pjs des annotations privées + des avis externes

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4584]
Actuellement, le bouton télécharger tous les pjs incluent seulement les pjs des dossiers et de la messagerie

**Comment by benjaminhenkel** [comment]
# 26282

**Comment by benjaminhenkel** [comment]
Ca me paraît en effet plus logique (et je n'y avais pas pensé plus tôt ) 
@Keirua qu'est ce que tu en penses ?

**Comment by Keirua** [comment]
Hum, moi non plus :cry: !
Ça parait une bonne idée, j'ai l'impression que vu que c'est uniquement pour les instructeurs, les pjs des avis externes ne posent pas problèmes.

**Comment by benjaminhenkel** [comment]
C'était dans le retour que j'ai eu, mais je vais creuser avec lui pour voir à quel point c'est nécessaire !

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/78058/instructeur-telecharger-en-une-seule-fois-les-pjs-des-annotations-privees-des-av
