### ISSUE TITLE
ETQ Instructeur, j'aimerais recevoir un mail de notification chaque fois qu'un dossier est déposé

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4587]
Cas d'usage précis : les démarches pour obtenir un passeport d'urgence. Démarche relativement peu utilisée (donc pas de connexion quotidienne) mais qui nécessite une réaction rapide de l'administration (sous 24h) lorsque quelqu'un dépose un dossier.

Plus globalement c'est un retour que j'ai souvent, mais contrairement à ici, ce n'est pas bloquant et la notification quotidienne fait l'affaire.

Est-ce que c'est une évolution qui est techniquement envisageable ?

**Comment by benjaminhenkel** [comment]
#26231

**Comment by ErwanLHH** [comment]
Cela peut rassurer mais je ne suis pas sûr que cela soit une bonne idée... à tout le moins la fonction est par défaut quotidien et l'instructeur doit choisir ou bien c'est une option activée par l'administrateur. Pas sûr que cela  réponde à beaucoup de cas.

**Comment by benjaminhenkel** [comment]
Je voyais effectivement cela comme une option désactivée par défaut et proposée aux instructeurs dans le menu "Gestion des notifications"

![Screenshot 2019-11-27 at 18 05 15](https://user-images.githubusercontent.com/28590367/69744476-8a0e6600-1140-11ea-8ca9-917d7fe79e3c.png)

**Comment by ErwanLHH** [comment]
Cette question de la réactivité de la relation à l'usager recoupe en partie le #4399 et la possibilité de signaler un mail non automatique à l'usager.

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/77367/instructeur-recevoir-un-email-de-notification-immediatement-des-quun-dossier-est
