### ISSUE TITLE
Unifier l'ux groupe instructeur / instructeur

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4602]
Avec le routage on a fait une jolie UI moderne pour gérer les instructeurs. Mais la gestion des instructeurs quand le routage est désactivé utilise toujours l'ancienne UI.

Ça serait bien de refondre l'UI des instructeurs pour que même sans le routage les Admins bénéficient de l'UI moderne.

**Comment by emsnytech** [comment]
On a un pb d'UI dans la nouvelle interface quand on veut se passer du routage.
L'approche par défaut reste assez difficile à comprendre.
Et quand on veut faire un formulaire sans routage donc, il faut peut être expliquer.
