### ISSUE TITLE
ETQ instructeur, je veux m'y retrouver dans la liste des démarches

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4605]
**Votre amélioration est liée à un problème spécifique ?**

Les démarches archivées remontent dans la liste des démarches et rapidement, on ne s'y retrouve plus. 

**Décrivez la solution proposée**

 - ne pas afficher les démarches archivées dans la liste des démarches
 - afficher toutes les démarches, sans filtres, sur un écran dédié

**Plus de contexte**

Comportement présent par ex lorsqu'on teste une démarche, l'archive puis la clone plusieurs fois.

**Comment by ErwanLHH** [comment]
Il me semble que l'on peut fusionner avec #4559

**Comment by Keirua** [comment]
Bien vu, j'avais cherché des duplicata mais pas trouvé (malgré la date récente!).
Ta suggestion 1 est identique, je ferme cette issue
