### ISSUE TITLE
ETQ instructeur, je souhaite retrouver le contenu des champs que j'ai rentré sur le formulaire privé

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#4615]
Retour Agglomération de LILLE politique de la ville.
Depuis hier, les champs qui avaient été complétés dans les formulaires privés
<img width="1088" alt="remontées" src="https://user-images.githubusercontent.com/27733126/70152754-13c4b300-16ae-11ea-8983-e3df61fd087c.png">
 ne font plus apparaître le contenu qui avait été saisi.
Plusieurs semaines de travail qui n'apparaissent plus, de ce qu'ils disent.

Voir dans la copie écran le dernier paragraphe. L'agglomération fait un mail pour préciser les démarches susceptibles d'être concernées.

**Comment by kemenaran** [comment]
On a investigué, j'ai l'impression qu'on a rien trouvé.

Je ferme, à réouvrir au besoin.
