### ISSUE TITLE
ETQ invité, je souhaite pouvoir télécharger le zip des pièces

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4629]
**Votre amélioration est liée à un problème spécifique ?**

L'export est disponible uniquement pour les instructeurs, alors que les invités doivent également pouvoir consulter les dossiers facilement.

**Décrivez la solution proposée**

Fournir aux invités le même bouton que pour les instructeurs

**Plus de contexte**

HS26781

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/77360/expert-telecharger-une-achive-de-toutes-les-pieces-jointes
