### ISSUE TITLE
ETQ Usager, je voudrais avoir une affichage plus dense des informations de mon dossiers

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4630]
Exemple mtn : 

![Avant](https://user-images.githubusercontent.com/28590367/70636557-08393500-1c36-11ea-9d3f-cf0707a76ea3.jpg)

Exemple après 

![Après](https://user-images.githubusercontent.com/28590367/70636568-0ec7ac80-1c36-11ea-84ca-983828a08d94.jpg)

**Comment by benjaminhenkel** [comment]
HS 26648

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/77359/usager-afficher-les-champs-de-facon-plus-dense
