### ISSUE TITLE
ETQ Administrateur j'aimerais récuperer les informations politique de la ville

### ISSUE THREAD

**Issue by fle-roy** [betagouv/demarches-simplifiees.fr#4635]
*En quelques mots...dans le cadre d'un projet mené par le ministère du travail et de la CDC "prépa apprentissage", j'ai besoin de créer un formulaire ou seraient indiqués les coordonnées du jeunes, ses niveaux de certification ET son origine : issus ou non d'un ### quartier prioritaire de la politique de la ville. La consigne donnée par le donneur d'ordre est d'aller vérifier d'après l'adresse si celle ci appartient à un quartier prioritaire de la ville via l'outil []([](https://sig.ville.gouv.fr/adresses/recherche)). N'y a t'il pas moyen d'intégrer un type de champ ou une option de type de champ, lié à l'adresse et allant chercher les infos sur la base data?
![image](https://user-images.githubusercontent.com/58854462/70809278-bcb39200-1dc1-11ea-9d96-32895265bff7.png)

Merci! F.

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/77358/administrateur-recuperer-les-informations-politique-de-la-ville
