### ISSUE TITLE
ETQ Instructeur je souhaite voir dans la liste des dossiers si une pièce-jointe a été déposée

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4637]
Lorsque je choisis d'afficher le champ PJ dans l'écran instructeur il n'y a rien d'affiché (cadre jaune)
![image](https://user-images.githubusercontent.com/49941223/70898135-5cf0fd00-1ff4-11ea-8b9e-cb7261307c07.png)

Serait-il possible d'afficher une information de type oui/non pour savoir tout de suite si une pj est présente ?

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/77355/instructeur-voir-dans-la-liste-des-dossiers-si-une-piecejointe-a-ete-deposee
