### ISSUE TITLE
ETQ Administrateur je n'arrive pas à saisir un numéro de téléphone

### ISSUE THREAD

**Issue by ErwanLHH** [betagouv/demarches-simplifiees.fr#4640]
Lorsque je saisis un numéro de téléphone pour un service du rectorat j'ai une erreur alors que ce numéro est opérationnel
![image](https://user-images.githubusercontent.com/49941223/70915551-54132200-201a-11ea-9dbf-5c4094a9e1ca.png)
![image](https://user-images.githubusercontent.com/49941223/70915634-79a02b80-201a-11ea-8d48-3b9651852beb.png)
![image](https://user-images.githubusercontent.com/49941223/70915723-a7857000-201a-11ea-91db-5f98a38f340c.png)

Par contre 0102030405 passe sans problème ;-)

**Comment by Keirua** [comment]
Ça pourrait être lié au fait qu'il y a 12 chiffres dans ce numéro et que ce type de format n'est pas géré en l'état.

**Comment by Keirua** [comment]
Par contre, on peut vérifier le format (est-ce que ça a l'air valide?) mais vérifier s'il est valide (est-ce que ça répond derrière?) est plus compliqué.
Ça nécessite de passer par des opérateurs tiers (je connais Twilio, l'acteur majeur, aux US, je ne sais pas s'il y a un équivalent français), mais 1) c'est plus compliqué 2) étant hébergés aux US je ne suis pas sûr qu'on puisse les intégrer pour cause de données personnelles (il y a aussi des champs de formulaire avec des numéros de téléphone usager). De plus ce type d'acteur a la réputation de faire des trucs un peu tangents niveau partage de leurs données donc il faudra qu'on soit super prudent.

**Comment by ErwanLHH** [comment]
Ok je vais voir si je peux faire avec un autre numéro

**Comment by ErwanLHH** [comment]
pour moi on peut fermer
