### ISSUE TITLE
ETQ administrateur, je veux pouvoir configurer le lieu par défaut d'une carte

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4642]
**Votre amélioration est liée à un problème spécifique ?**

La carte se trouve, par défaut, à un endroit qui n'a probablement rien à voir avec la démarche en question

**Décrivez la solution proposée**
Lors de la configuration des champs, permettre aux admin de configurer le lieu par défaut où se trouve la carte.

**Plus de contexte**
HS 27216

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/77354/administrateur-configurer-le-lieu-par-defaut-dune-carte
