### ISSUE TITLE
ETQ Invité je souhaite pouvoir visualiser l'attestation

### ISSUE THREAD

**Issue by ndrianab** [betagouv/demarches-simplifiees.fr#4653]
**Votre amélioration est liée à un problème spécifique ?**
L'expert invité ne peut pas visualiser l'attestation depuis le lien dans la messagerie.

**Décrivez la solution proposée**
Accorder un droit de lecture/ visualisation de l'attestation aux experts invités.

**Plus de contexte**
Il s'agit d'une demande faite par un administrateur, pour permettre aux experts d'avoir une visibilité exhaustive

**Comment by ErwanLHH** [comment]
Je comprends la demande mais pour le moment, une fois qu'un dossier est accepté, ce qui génère l'attestation, il n'est pas possible d'inviter un expert.
J'ajoute que l'expert n'a accès qu'au dossier et pas aux annotations privées ce qui pourrait être également très pratique.
Solution possible : lors de l'invitation d'un expert autoriser l'accès à tout ou partie du dossier avec 3 boutons radios  (dossier, dossier + annotations privées, dossier+ AP+ attestation, dossier +attestation)

**Comment by kemenaran** [comment]
Déplacé dans https://demarches-simplifiees.featureupvote.com/suggestions/78055/expert-pouvoir-visualiser-lattestation
