### ISSUE TITLE
ETQ usager et instructeur, je ne veux pas perdre le texte d'un message ou d'un avis

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4659]
**Votre amélioration est liée à un problème spécifique ?**

Un instructeur me fait remarquer qu'il a perdu le texte du mail qu'il avait commencé à rédiger, et ce après être retourné sur le dossier d'un usager pour vérifier quelque chose.
Et il a dû tout retaper... :-[

**Décrivez la solution proposée**

 - soit la possibilité que le texte reste dans l'onglet messagerie sans qu'on n'ai rien à faire de particulier
 - soit la possibilité "d'enregistrer en tant que brouillon" (via un bouton dédié)
 - soit un message avertissant de la perte du texte tapé si on persiste à vouloir changer d'onglet.

**Plus de contexte**

HS 27477

**Comment by kemenaran** [comment]
Le message avertissant de la perte du texte tapé, ça doit être simple à coder.

Après la cerise sur le gâteau ça serait d'enregistrer le texte toutes les 10s dans du localStorage, et de le restaurer au besoin 👌

**Comment by kemenaran** [comment]
Déplacé dans https://demarches-simplifiees.featureupvote.com/suggestions/78054/instructeur-enregistrer-des-brouillons-de-message

**Comment by kemenaran** [comment]
On peut sans doute stocker ça dans localStorage - peut-être même avec un pattern d'unostrusive-JS du genre `data-save-to-local: true`.
