### ISSUE TITLE
ETQ Instructeur, je souhaiterais pouvoir préenregistrer le texte de demande d'avis. 

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4661]
Contexte : procédure de l'ARS où il demande des avis externes avec nécessité de mentionner le délai légal dans la demande d'avis externe car la procédure est assez risquée juridiquement (gérée par des avocats)
Pb : procédure gérée sur 12 sites différents avec un grand nombre d'instructeurs

Solution qui pourrait faire gagner un peu de temps à tous les instructeurs : proposer comme modèle préenregistré dans l'avis externe, le dernier message écrit pour l'instructeur lors de sa demande d'avis externe

**Comment by benjaminhenkel** [comment]
27495

**Comment by kemenaran** [comment]
Déplacé dans https://demarches-simplifiees.featureupvote.com/suggestions/78057/instructeur-preenregistrer-le-texte-de-demande-davis
