### ISSUE TITLE
ETQ Expert invité, j'aimerais avoir le bouton "télécharger toutes les pjs" comme pour les instructeurs 

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4663]
Le bouton télécharger les pjs n'est pas disponible pour l'expert invité 

HS 28430

**Comment by kemenaran** [comment]
Déplacé dans https://demarches-simplifiees.featureupvote.com/suggestions/77360/expert-telecharger-une-achive-de-toutes-les-pieces-jointes
