### ISSUE TITLE
ETQ Expert invité, je souhaiterais que les pjs ne changent pas nom lorsque je les télécharge

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4664]
Il semblerait que le nom des pjs changent pour une série de caractères incompréhensible. 

HS 28430

**Comment by kemenaran** [comment]
@tchak ça serait un effet des URLs Active Storage, tu crois ?

**Comment by tchak** [comment]
normalement le filename est passé à la création de l'url

**Comment by kemenaran** [comment]
J'ai l'impression qu'on n'a pas reproduit le problème. On ferme ?

**Comment by tchak** [comment]
ouai
