### ISSUE TITLE
ETQ Instructeur, je souhaite recevoir une notification mail lors d'un nouveau message

### ISSUE THREAD

**Issue by jchourdeaux** [betagouv/demarches-simplifiees.fr#4669]
Actuellement, les nouveaux messages sont uniquement notifiés via la pastille orange sur la plateforme (mais pas dans le mail quotidien ou hebdo).
Nos instructeur n'étant pas en permanence sur DS, et ayant des échanges assez fréquents avec les usagers, il serait vraiment important pour eux de pouvoir être notifié par mail lorsqu'un message est envoyé sur un dossier qu'ils suivent.
A minima (ou en plus  ;) ), on pourrait également ajouter la notif de nouveau(x) message(s) dans le mail quotidien ou hebdo.
bien cdt

**Comment by kemenaran** [comment]
Effectivement ça serait une bonne idée.

J'ai déplacé cette proposition dans notre nouveau tableau de vote et de suivi des fonctionnalités : https://demarches-simplifiees.featureupvote.com/suggestions/78056/instructeur-recevoir-immediatement-une-notification-par-email-lors-dun-nouveau-m
