### ISSUE TITLE
ETQ Instructeur/Usager, le texte de certains champs sort du cadre

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4676]
Exemple : 

![2020-01-08-14_41_50-microsoft-_dmvyf5](https://user-images.githubusercontent.com/28590367/71982906-e677a180-3225-11ea-864a-b3044743cec2.png)

ce qui complexifie la lecture

**Comment by kemenaran** [comment]
Hmm, chez moi ça fonctionne (Firefox 72).

La personne utilise quel navigateur ?

<img width="1487" alt="Capture d’écran 2020-01-08 à 15 51 18" src="https://user-images.githubusercontent.com/179923/71987564-c3052480-322e-11ea-97d7-a83ec760f6a0.png">

**Comment by kemenaran** [comment]
Pas réussir à reproduire. Je ferme.
