### ISSUE TITLE
ETQ administrateur, je veux voir le contenu d'un groupe d'instructeur

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/demarches-simplifiees.fr#4683]
**Décrivez le bug**
Une erreur quand je veux voir le contenu d'un groupe d'instructeur.

**Reproduction**
Comment reproduire le problème :
1. Aller sur la page 'Groupes d’instructeurs'
2. Cliquez sur 'voir' d'un groupe instructeurs
3. Une erreur 'Une erreur est survenue' apparaît
4. Dans les logs: PG::UndefinedColumn: ERREUR:  la colonne instructeurs.email n'existe pas
LINE 1: ...assign_tos"."groupe_instructeur_id" = $1 ORDER BY "instructe...

**Appareil et navigateur utilisé**
 - Appareil :  PC
 - Navigateur : [Chrome,]

Dans le GroupeInstructeursController => paginated_instructeurs, il y a un "order by" email de instructeur.

**Comment by LeSim** [comment]
Je reproduis pas, vous êtes sur quelle version ? Ca semble passer chez moi car `user` est eager loadé et donc on a bien un `email` dans la requete sql de `paginated_instructeurs`

**Comment by pengfeidong** [comment]
> Je reproduis pas, vous êtes sur quelle version ? Ca semble passer chez moi car `user` est eager loadé et donc on a bien un `email` dans la requete sql de `paginated_instructeurs`

@LeSim On est sur 2019-12-18-01.

**Comment by kemenaran** [comment]
@pengfeidong vous avez toujours le problème ?

**Comment by pengfeidong** [comment]
@LeSim @kemenaran 
C'est un problème de Rails: https://github.com/rails/rails/issues/33239
On est sur rails : 5.2.1.
Pour la version Rails : 5.2.3, il n'y a pas de problème.
Ou changer dans le code avec :`order("users.email ASC")`

**Comment by pengfeidong** [comment]
C'est le gem "copy_carrierwave_file" nous oblige sur le Rails 5.2.1, il n'est pas été supprimé chez nous.  en supprimer le gem, on est en Rails 5.2.3 aussi. je close le ticket.
