### ISSUE TITLE
ETQ Superadmin, je voudrais pouvoir modifier les modèles des pj contenus dans un bloc répétable

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4685]
Depuis l'espace manager, un unique champ "bloc répétable", ne permettant pas de voir ce qu'il y a à l'intérieur et donc de changer les modèles de pj

**Comment by tchak** [comment]
c'est pas trop compliqué à corriger, je vais le faire
