### ISSUE TITLE
ETQ instructeur, je ne peux pas télécharger l'export tableur à jour de mes dossiers 

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4700]
L'export semble bien fonctionner une première fois, mais après impossible de générer un nouvel export excel des dossiers : 

![Screenshot 2020-01-24 at 10 55 36](https://user-images.githubusercontent.com/28590367/73060910-2f239180-3e99-11ea-9c7c-545e25540d30.png)

les boutons restent bloqués en "Télécharger l'export au format ..." (même pour les nouveaux instructeurs)

**Comment by benjaminhenkel** [comment]
HS  30262

**Comment by benjaminhenkel** [comment]
NOLOT

**Comment by benjaminhenkel** [comment]
HS 30453

**Comment by benjaminhenkel** [comment]
# 29422

**Comment by Keirua** [comment]
J'ai exploré pas mal de trucs et je tourne en rond là.

Le problème: des exports sont bien générés, ne sont pas supprimés, et cela semble empêche la ré-génération d'un export.

J'ai lancé `PurgeStaleExport` à la main, qui a supprimé tous les exports :(

Là où j'en suis:
 - on a toujours un job `CleanupStaleExportsJob` qui n'a plus lieu d'exister et que ca vaudra le coup de supprimer
 - `PurgeStaleExportsJob` tourne bien, une fois par jour, à 8h du matin. On supprime une fois par jour des exports trop vieux (et du coup, on ne fait cette suppression qu'une fois par jours).
 - Le code du bouton de téléchargement ne semble pas en cause: il affiche bien les 3 boutons dans les 3 états ; les 3 cas sont cohérents, et en fonction de ce sur quoi on clique on a bien le bon affichage
```ruby
- if export.nil?
= link_to "Demander un export au format .#{format}", download_export_instructeur_procedure_path(procedure, export_format: format), remote: true
- elsif export.ready?
= link_to "Télécharger l'export au format .#{format}", url_for(export.file), target: "_blank", rel: "noopener"
- else
L'export au format .#{format} est en cours de préparation 
```
 - j'ai l'impression que le problème vient plutôt de la mécanique du cycle de vie d'un export
 - on a des problèmes en particulier depuis le 21, mais je ne vois pas le rapport avec ce qui a été MEP à cette période
 - on a des jobs `ExportJob` en échec à cause de la serialization d'exports inexistants (cf manager/delayed jobs)

Une solution partielle serait de remplacer le `- if export.nil?` par `- if export.nil? || export.stale?`, mais ca ne résoud pas complètement le problème.

**Comment by Keirua** [comment]
J'ai surveillé les exports cet après-midi ; le nettoyage se fait bien correctement : les exports trop vieux sont bien supprimés, il y a en général seul 4-5 exports disponibles à un instant T.
Pas trouvé la cause du problème (de vieux exports non supprimés empêchent la création de nouveaux exports : `export = Export.find_or_create_export(format, groupe_instructeurs)` renvoit un export dans `ProceduresController#download_export`).
Je n'ai pas non plus réussi à reproduire le problème chez moi.
La solution (la rustine, hein) a été:
 - de vider la file des exports (`PurgeStaleExportsJob.perform_now`).
 - éventuellement de générer les exports à la main pour certains instructeurs.

Une alternative à la solution de mon message précédent serait de plutôt modifier `export#ready` pour tenir compte du TTL, mais cette approche est trompeuse (le nom de méthode ne reflète pas ce qui se passe).

**Comment by Keirua** [comment]
Ok, on a plusieurs problèmes en l'état actuel. Contrairement à ce que je pensais, la mécanique de nettoyage fonctionne bien. C'est la mécanique de génération qui est erronnée.

On a fait des changements dans la sérialization qui font que lors que la génération échoue (caractère invalide dans les noms de worksheet) et l'export n'aboutit jamais.

Par ailleurs, et c'est le problème principal, assez souvent (~5-10 cas depuis hier après midi), on lance un `ExportJob` alors que l'`Export` est invalide/n'existe pas. Du coup `ExportJob` échoue, réessaie en boucle et il n'est jamais possible de le supprimer dans le job de nettoyage car il n'a jamais abouti. On a donc ce genre de retry :
```
    --- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper
    job_data:
      job_class: ExportJob
      job_id: 1d513e96-9cfd-43b2-abd6-2c8189e501d0
      provider_job_id: 
      queue_name: default
      priority: 
      arguments:
      - _aj_globalid: gid://tps/Export/2510
      executions: 0
      locale: fr

Last Error
    Toggle full message

    Error while trying to deserialize arguments: Couldn't find Export with 'id'=2510
```

**Comment by kemenaran** [comment]
Résumé de la discussion avec @Keirua :

## Problèmes immédiats

Au sujet des **jobs d'antivirus qui échouent** quand l'export échoue : on n'a pas vraiment besoin de l'antivirus sur des fichiers qu'on génère nous même. => **on va marquer les exports comme antivirus-safe**.

Au sujet des **jobs d'export qui restent en attente** : on n'a pas vraiment besoin de retry les jobs d'export indéfiniment. Soit ça passe, soit ça ne passera sans doute pas du tout. => **configurer les ExportJob pour ré-essayer seulement 1 fois**.

Au sujet du **comportement en cas d'échec de l'export** : on devrait quand même vaguement retomber sur nos pattes, et informer l'utilisateur. => ajouter une méthode `Export#failed?`, **informer l'utilisateur par un petit texte rouge dans l'UI**, et le laisser ré-essayer.

## Questions de fond

Le cycle de vie actuel d'un export pourrait être plus simple. Notamment :

- On supprime les fichiers au bout de 15mn. Si un utilisateur rate la fenêtre de 15mn pour télécharger son export, il doit le re-télécharger.
- On ne peut pas re-générer un export immédiatement même pour les toutes petites  démarches
- Des démarches ont quand même besoin de (relatif) temps-réel

Pierre suggère de séparer conceptuellement la **durée de disponibilité** du fichier du **rate-limiting** :

- Disponibilité : On supprime le fichier au bout de N jours (c'est un paramètre du job de purge) 
- Rate-limiting : On ne peut pas re-générer de fichier avant X minutes (c'est un paramètre essentiellement d'UI)

Mais ça sera pour plus tard, ou si jamais on se sent le besoin de simplifier ce workflow.

**Comment by Keirua** [comment]
Marquer les exports comme "antivirus-safe" a suffi à corriger les problèmes depuis plusieurs semaines, je clos ce ticket
