### ISSUE TITLE
ETQ Administrateur, je souhaiterais mettre le groupe d'instructeur en balise

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4701]
sauf erreur de ma part, pas encore de balise groupe d'instructeurs, qui peut être  utile pour personnaliser les emails et permettre l'usager de se rendre compte s'il s'est trompé dans le routage.

**Comment by kemenaran** [comment]
Déplacé sur https://demarches-simplifiees.featureupvote.com/
