### ISSUE TITLE
ETQ Usager, lors de la création de mon compte, je voudrais pouvoir voir le mdp que je mets

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4702]
Remarque que l'on m'a faite au tel : il est actuellement impossible de voir le mdp que l'on met lors de la création du compte : 

![Screenshot 2020-01-24 at 16 01 55](https://user-images.githubusercontent.com/28590367/73078698-00baac00-3ec3-11ea-862d-9e18e5035f45.png)

+ on ne demande pas de confirmation du mdp, donc facile de se tromper je pense 

Piste : un petit "oeil" à droite du champ qui permettrait en cliquant de rendre visible le mdp ?

**Comment by kemenaran** [comment]
Déplacé sur https://demarches-simplifiees.featureupvote.com/
