### ISSUE TITLE
ETQ Usager, je ne peux pas déposer un dossier avec un champ  obligatoire " Menu déroulant lié "

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4703]
Si j'ai un champ construit comme suit : 
![Screenshot 2020-01-24 at 16 14 17](https://user-images.githubusercontent.com/28590367/73079498-a02c6e80-3ec4-11ea-84b7-46af9de52126.png)

et que je veux sélectionner Martin comme ceci : 
![Screenshot 2020-01-24 at 16 15 13](https://user-images.githubusercontent.com/28590367/73079573-bf2b0080-3ec4-11ea-8cdf-3cc7f7ccff58.png)

Alors le dépot de dossier n'est pas possible

![Screenshot 2020-01-24 at 16 15 44](https://user-images.githubusercontent.com/28590367/73079614-d10ca380-3ec4-11ea-8221-d00d0cea3e7e.png)

**Comment by benjaminhenkel** [comment]
# 30165

**Comment by kemenaran** [comment]
Normalement c'est corrigé.
