### ISSUE TITLE
ETQ instructeur, je voudrais disposer de l'adresse url des dossiers dans l'export excel 

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4704]
Pour pouvoir accéder rapidement au dossier sur demarches-simplifiees.fr

**Comment by benjaminhenkel** [comment]
# 30262

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/78053/instructeur-exposer-lurl-des-dossiers-dans-lexport-tableur#comment169066
