### ISSUE TITLE
ETQ Administrateur, je veux changer mon mot de passe

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#471]

**Comment by kemenaran** [comment]
@mmagn j'ai l'impression qu'on peut faire ça par le lien "J'ai oublié mon mot de passe" sur la page /users/sign_in ?

**Comment by mmagn** [comment]
Oui. Mais je sais pas si la page est accessible si tu es loggé. Et il
faudrait peut-être ajouter un lien depuis l'espace connecté.

Mathieu MAGNIN
+33 6 58 05 20 91

**Comment by kemenaran** [comment]
On a régulièrement des erreurs Sentry là dessus depuis quelques jours. Je regarde.

**Comment by kemenaran** [comment]
J'ai investigué les erreurs : ça s'est produit une fois, pour un Admin sans User associé. J'ai créé le user, et vérifié en prod : c'était le seul Admin sans User.

Bref, c'était un cas particulier, ça devrait fonctionner pour tout le monde maintenant.

L'issue "ETQ Admin, je peux réinitialiser mon mot de passe" est donc résolue : ça fonctionne. En revanche je pense qu'il s'agit plus de pouvoir changer son mot de passe (sans passer par la procédure de ré-initialisation). Je change le titre de l'issue pour corresponde.

**Comment by kemenaran** [comment]
C'est le pendant Admin de #1708.
