### ISSUE TITLE
ETQ Usager, je n'arrive pas à rentrer mon adresse dans un champ adresse

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#4730]
Le champ reste bloqué sur "recherche en cours"

![Screenshot 2020-01-30 at 10 53 03](https://user-images.githubusercontent.com/28590367/73438921-1ca0d080-434f-11ea-8438-bb8fcb324ed4.png)

J'ai retesté avec lui ce matin au tel, avec Firefox, Chrome, IE, rien n'y fait ! 

Je n'ai cependant pas pu reproduire le problème moi-même et c'est le seul cas dont nous ayons connaissance 

Peut être faudrait-il permettre à l'usager de rentrer sa propre adresse même lorsqu'une recherche est en cours ? (actuellement il faut que la recherche soit finie pour que l'usager ait cette possibilité)

**Comment by benjaminhenkel** [comment]
30302

**Comment by tchak** [comment]
Je viens de tester :

- en situation "normal" il est possible de saisir une adresse qui n'existe pas dans ban
- il y a un timeout sur la recherche

Je ferme et on rouvrira si d'autres problèmes sont remontés
