### ISSUE TITLE
ETQ Usager je souhaite être redirigé sur ma démarche depuis le lien de connexion sur mobile

### ISSUE THREAD

**Issue by ndrianab** [betagouv/demarches-simplifiees.fr#4738]
**Votre amélioration est liée à un problème spécifique ?**
Test effectués sur le Pass Culture sur mobile : on passe sur le site du pass culture, on clique sur la démarche.
Une fois sur DS on renseigne le mot de passe et l'adresse e-mail.
On reçoit le mail et en cliquant sur le lien, on arrive dans la liste des dossiers mais pas sur la démarche

**Décrivez la solution proposée**
Être redirigé sur la démarche, comme c'est fait sur desktop

**Plus de contexte**
Demande remontée par HS 29422

**Comment by kemenaran** [comment]
@ndrianab j'ai testé sur mon téléphone, ça fonctionne.

Tu as testé sur quel téléphone, toi ? Est-ce que tu avais utilisé le même navigateur pour créer le compte et pour cliquer sur le lien ?

**Comment by kemenaran** [comment]
En fait le ticket HS parle sans doute de deux cas différents où ça ne fonctionne pas :

1. **La redirection après avoir créé un compte** : ça ne marche que si on a créé le compte **avec le même navigateur** que celui avec lequel on valide le lien.
    On pourrait arranger ça à l'avenir (pour faire en sorte que ça fonctionne depuis n'importe quel navigateur), mais c'est pas ééévident.
2. **La redirection en cas de "Le compte existe déjà"** : c'est vrai que c'est pas fou. L'usager clique sur le lien, reçoit un "Vous êtes déjà connecté", c'est pas incroyable.
    Dans l'email qui dit "Votre compte existe déjà", on pourrait proposer de remplir la démarche directement.
