### ISSUE TITLE
Statistiques par instructeurs

### ISSUE THREAD

**Issue by Thyami** [betagouv/demarches-simplifiees.fr#4741]
**Votre amélioration est liée à un problème spécifique ?**
Pouvoir disposer sur son compte instructeur de ses propres statistiques d'utilisation du service

**Décrivez la solution proposée**
Disposer : 
- du délai moyen de gestion de SES dossiers,
- du nombre de dossiers traités,
- du nombre de dossier instruits (y compris les dossiers passés en instruction puis repassés en construction avant de repasser en instruction  ...)
- du nombre de messages échangés via ma messagerie pour obtenir les dossiers complets....

**Plus de contexte**
Cela pourrait permettre aux agents qui le souhaitent de valoriser leur travail auprès de leur hiérarchie qui ne voit peut être pas l'ensemble du travail réalisé.

**Comment by kemenaran** [comment]
Effectivement, ça pourrait être une idée.

Après historiquement on a effectivement privilégié les statistiques d'équipe plutôt que les statistiques individuelles. Essentiellement, on craint que des statistiques individuelles ne soient détournées par la hiérarchie pour surveiller le travail des instructeurs.

Est-ce que vous pensez que des statistiques de ce genre seraient plus un outil qui permet de valoriser le travail, ou en tout cas plus que ça ne permettrait de la surveillance ?

**Comment by kemenaran** [comment]
Déplacée sur https://demarches-simplifiees.featureupvote.com/
