### ISSUE TITLE
ETQ utilisateur d'API, je souhaite être informé des évolutions

### ISSUE THREAD

**Issue by krichtof** [betagouv/demarches-simplifiees.fr#4756]
En tant qu'utilisateur d'API, je découvre parfois trop tard une évolution de l'API, ce qui dégrade la qualité du service que j'opère.

Solution : Une liste de diffusion va être créée sur le thème des évolutions d'API impactantes.
L'inscription à cette liste se fera depuis un lien sur la page d'accueil de DS

**Comment by LeSim** [comment]
Informer les médailles

**Comment by krichtof** [comment]
Done. J'attends que la newsletter soit envoyée pour clore le ticket

**Comment by Keirua** [comment]
on a ajouté une mailing list dont le lien est dans la doc, je ferme
