### ISSUE TITLE
Email - Erreurs d'envoi pour les comptes avec des accents

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4768]
**Décrivez le bug**

On peut créer un compte avec un email qui contient des accents. Du coup, on a des erreurs d'envoi d'email `Net::SMTPSyntaxError` lorsque l'on essaie de notifier les personnes en question. Cela arrive occasionnellement (~1/semaine).

Cela touche surtout usager et instructeur, sans doute car on valide manuellement les comptes administrateurs.

**Solution proposée**

Utiliser le mécanisme de suggestion pour proposer une adresse email sans accents lors de la création de comptes.

![image](https://user-images.githubusercontent.com/1223316/74318672-fbdc7000-4d7d-11ea-8157-4a695b9619b7.png)

**Comment by Keirua** [comment]
Pour info voici quelques typologies d'emails en erreur ces derniers temps

## Domaine invalide
```
prenomnom@.fr
nomprenom@gmail.coù
```
## Domaine avec accent
```
nom.prenom@xy.intérieur.gouv.fr 
xy@collectivitémachin.mq
```

**Comment by tchak** [comment]
mais les emails avec des accents c'est valide en vrai... je ne comprends pas pourquoi la lib smtp se vautre

**Comment by kemenaran** [comment]
Je crois que c'est pas la lib SMTP qui se vautre, c'est Mailjet/SIB – et que la lib SMTP convertit la valeur de retour du service d'envoi en une erreur `Net::SMTP`.

**Comment by kemenaran** [comment]
Du coup si je comprends bien, le problème c'est pas l'accent en tant que tel, c'est que Mailjet/SIB nous dit que l'email est invalide – parce que le domaine n'existe pas.

**Comment by tchak** [comment]
ça pourrai être que Mailjet/SIB ne savent pas gérer les domaines en Unicode... Si ils envoi "Bad recipient address syntax" pour une adresse qui n'existe pas c'est moche :)

**Comment by Keirua** [comment]
Concrètement on a pas de moyen d'action car l'erreur n'est pas de notre fait et les emails sont légitimes. Ça arrive assez peu (pas arrivé cette semaine).
Je clos donc ce ticket
