### ISSUE TITLE
API V2: ajouter la possibilité de changer le groupe de routage pour le dossier

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/demarches-simplifiees.fr#4780]
**Ajouter dans API V2 de changer le groupe de routage pour le dossier**
Dans le cas d'affectation de groupe de routage, ajouter la possibilité de changer le groupe de routage de dossiers via l'API V2.
Les status de dossier possible:  
- en construction
- en instruction.

**Comment by kemenaran** [comment]
Concrètement, ça prendrait sans doute la forme d'une mutation supplémentaire sur l'API v2 (GraphQL). Cette mutation permettrait de changer le groupe de routage d'un dossier spécifique.

**Comment by kemenaran** [comment]
Feature-Upvote associé : https://demarches-simplifiees.featureupvote.com/suggestions/79085/administrateur-affecter-les-dossiers-routes-selon-une-logique-externe-via-une-ap

**Comment by tchak** [comment]
ça ressemblerai à ça :

```ruby
module Mutations
  class DossierChangerGroupeInstructeur < Mutations::BaseMutation
    description "Changer le grope instructeur du dossier."

    argument :dossier_id, ID, "Dossier ID", required: true, loads: Types::DossierType
    argument :groupe_instructeur_id, ID, "Group instructeur a affecter", required: true, loads: Types::GroupeInstructeurType

    field :dossier, Types::DossierType, null: true
    field :errors, [Types::ValidationErrorType], null: true

    def resolve(dossier:, groupe_instructeur:)
      dossier.update!(groupe_instructeur: groupe_instructeur)

      { dossier: dossier }
    end

    def authorized?(dossier:, groupe_instructeur:)
      dossier.groupe_instructeur.procedure == groupe_instructeur.procedure
    end
  end
end

```

**Comment by pengfeidong** [comment]
Pour le dumping de schema: https://graphql-ruby.org/api-doc/1.9.12/GraphQL/RakeTask
Il y a une erreur (`NameError: uninitialized constant Api`) en utilise de le rails pour lancer le task: `rails graphql:schema:idl`.
Mais avec rake ça fonctionne: `bin/rake graphql:schema:idl`

**Comment by tchak** [comment]
implemented in #4815
