### ISSUE TITLE
Augmentation du nombre de colonnes personnalisées possibles dans un dossier à 8-10. (limité à 5 aujourd'hui)

### ISSUE THREAD

**Issue by etiquet** [betagouv/demarches-simplifiees.fr#4782]
**Votre amélioration est liée à un problème spécifique ?**
 le nombre de filtre n'est pas suffisant. ( limité à 5 )

**Décrivez la solution proposée**
Augmenter à 8-10 le nombre de colonnes personnalisées.
![Capture d’écran 2020-02-16 à 06 53 31](https://user-images.githubusercontent.com/18629332/74599860-19b11a00-5089-11ea-81f2-c71dafead3c7.png)

**Comment by kemenaran** [comment]
Déplacé vers https://demarches-simplifiees.featureupvote.com/suggestions/79087/instructeur-filtrer-les-dossiers-sur-plus-de-5-criteres#comment169913
