### ISSUE TITLE
Outillage pour "populer"  synchroniser les groupes de routage à partir de source de données 

### ISSUE THREAD

**Issue by etiquet** [betagouv/demarches-simplifiees.fr#4783]
**Votre amélioration est liée à un problème spécifique ?**
Dans le cadre de la mise en place de la fonction routage à grande échelle ( cibles des centaines de procédures, des centaines de traitant répartis par régions avec des compétences dédiées ) Il est indispensable d'outiller les administrateurs sur la gestion des groupes.

**Décrivez la solution proposée**
En priorité 1 : capacité d'importer une liste d'instructeurs en masse dans les procédures / groupe de traitement associés au routage. ( bouton : "importer" un CSV ou autre avec des emails 2 colonnes, email et nom du groupe de routage )
En P2: fonction de synchronisation via API avec des données d'organisation ;
En P3 : mettre en place routage via un appel via WebHook sur un référentiel d'organisation.

**Plus de contexte**
A investiguer sur besoin à l'initialisation puis ensuite de synchronisation avec référentiels.

**Comment by kemenaran** [comment]
Merci pour la suggestion ; effectivement ce sont des outils à considérer.

Nous sommes en ce moment en train de déplacer les fonctionnalités demandées vers un espace spécifique, qui permet notamment aux utilisateurs de demarches-simplifiees.fr de voter pour les améliorations qui leur seraient le plus utile. J'ai donc déplacé votre suggestion à cet endroit : https://demarches-simplifiees.featureupvote.com/suggestions/79084/administrateur-synchroniser-les-groupes-de-routage-avec-une-source-de-donnees-ex
