### ISSUE TITLE
Erreur lors de la suppression d'une démarche (groupe instructeur)

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4795]
**Décrivez le bug**

On a beaucoup d'erreurs dans Sentry qui arrivent lors de la suppression d'une démarche.

https://sentry.io/organizations/demarches-simplifiees/issues/1220091646/?project=1429550

```ruby
# app/controllers/admin/procedures_controller.rb in destroy at line 60
        procedure.destroy
```

>ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "groupe_instructeurs" violates foreign key constraint "fk_rails_42900e2578" on table "dossiers"
DETAIL:  Key (id)=(19590) is still referenced from table "dossiers".
: DELETE FROM "groupe_instructeurs" WHERE "groupe_instructeurs"."id" = $1

Ça a l'air de dire que supprimer une démarche entraine la suppression du groupe instructeur, mais que ça pète pour une raison ou une autre.

**Comment by kemenaran** [comment]
@tchak j'ai l'impression que c'est corrigé ; et toi ?

**Comment by tchak** [comment]
oui, c'est corrigé
