### ISSUE TITLE
ETQ instructeur, je crois qu'il manque des données dans l'export CSV

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4806]
**Constat**
Les usagers remontent régulièrement qu'il manque des infos dans les exports CSV. Ce format ne peut contenir qu'un seul onglet

**Amélioration**
On peut envisager 2 manières de préciser ce qui est disponible:
 - ajouter un label pour préciser qu'un seul onglet est disponible dans le CSV
 - ajouter une liste de ce qui est disponible pour chaque type d'export

Problème du 1: les champs répétables ne sont pas disponible dans l'export CSV, donc la liste des dossiers est incomplète
Problème du 2: longue liste à afficher dans un espace réduit ([:dossiers, :etablissements, :avis] + champs_repetables_options)

**Comment by tchak** [comment]
Je pense qu'il faut inclure ce retour dans la discussion sur l'export des dossiers avec les revisions

**Comment by tchak** [comment]
je ne suis pas sur que ça soit un "bug"

**Comment by kemenaran** [comment]
Dans l'immédiat, ça me semble top de préciser dans l'UI que le CSV ne contient pas toutes les infos.

Après, si on voulait résoudre le problème, j'imagine qu'on ferait un zip de plusieurs CSV (un par table), non ?

**Comment by kemenaran** [comment]
On a précisé ça dans l'UI.
