### ISSUE TITLE
ETQ Usager, je souhaiterai être alerté 48h avant la cloture, que mon dossier n'est pas déposé

### ISSUE THREAD

**Issue by maatinito** [betagouv/demarches-simplifiees.fr#4807]
Beaucoup de personnes ne saisissent pas la différence entre brouillon et déposer. En fait ils pensent que enregistrer en mode brouillon c'est enregistrer donc c'est déposer le dossier. Du coup avec le démarches avec date de clôture, des usagers se sont fait avoir et leur dossier n'a pas été pris en compte.
J'ai ajouté une notification 48h avant la date de clôture d'une démarche qui a cette forme :

![image](https://user-images.githubusercontent.com/15379878/74892808-bfd17e00-532e-11ea-8caf-f59575c49ad5.png)

Je peux proposer la PR correspondante. Qu'en pensez vous ? 

Si vous êtes pour le principe, pensez vous que le nb de jours avant cloture doit être paramétré ? 
D'autres suggestions de formulations ? (nous avons essayé de simplifier le message au maximum tout en restant complet mais peut etre avez vous mieux ?)

**Comment by Keirua** [comment]
Ca me parait très cool !
Dans un premier temps je me dis qu'il n'est pas nécessaire de configurer le nombre de jours qui va déclencher la notification.
On peut faire sans pour commencer, et voir s'il y a des demandes dans ce sens qui nécessiteraient de développer la fonctionnalité.
La formulation me parait claire également.

**Comment by kemenaran** [comment]
Pareil que Keirua !

Et comme on se disait par email, ça me semble intéressant de n'envoyer cet email que si l'usager n'a pas de dossier déposé sur la démarche (ce qui tendrait à indiquer que ça serait un brouillon dupliqué).

**Comment by maatinito** [comment]
Bon point le coup du brouillon en doublon.
Meme si je sens que je vais m'amuser pour la requête ;-)
