### ISSUE TITLE
ETQ Admin, je souhaite indiquer une date de cloture à 23h59

### ISSUE THREAD

**Issue by maatinito** [betagouv/demarches-simplifiees.fr#4808]
Les créateurs de formulaires se plantent systématiquement pour positionner la date de clôture d'une démarche: fermer une démarche le 7/02 à 00h00 (ou 00h01), humainement c'est fermer la démarche le 7 à minuit et techniquement  la plateforme ferme la démarche le 7 à 00h01 donc le matin. (ce qui fait en fait une fermeture le 6 à minuit)
==> Pour améliorer la compréhension, j'ai changé la signification et je propose une date de cloture à 23h59
![image](https://user-images.githubusercontent.com/15379878/74893084-906f4100-532f-11ea-9799-be783df6eb25.png)

Du coup, humainement il n'y a plus d'ambiguïté.
On peut comme le suggère Pierre, mettre un horaire à 23h59m59s

Pour l'implémentation, pour assurer la compatibilité avec les données en base, j'ai pour le moment fait la distinction dans l'interface. Ainsi en base on enregistre 1 jour de plus que ce que l'utilisateur a demandé. L’utilisateur spécifie la clôture au 20/02, on enregistre une clôture au 21/02.
Option 2: plus coûteuse/risquée, faire tourner un after party pour changer toutes les dates en base (enlever un jour) et modifier les routines pour prendre en compte cette modification. (Stocker en base ce que l'utilisateur a donné)
Je peux faire une PR pour l'option 1 mais je peux aussi regarder pour faire l'option 2 si vous pensez que c'est mieux.

**Comment by kemenaran** [comment]
Ça me semble une bonne idée d'améliorer cette interface 👍 

J'ai l'impression que le "23h59" serait plus clair, oui (et qu'on pourrait quand même garder les données actuelles en base, avec le jour de plus, sans faire de moulinette).

Après on peut p-ê faire encore mieux pour l'interface. Notamment le texte actuel parle beaucoup avec le jargon de DS (clôture, instruction, etc). Alors qu'on pourrait plutôt décrire les effets que ça a pour les usagers et les instructeurs.

Qu'est-ce que tu penserais d'un truc comme ça ?

<img width="519" alt="Capture d’écran 2020-02-24 à 11 27 35" src="https://user-images.githubusercontent.com/179923/75145197-c9753000-56f8-11ea-8d5c-48c8a315dcaf.png">

**Comment by maatinito** [comment]
J'aime bien la simplification de jargon :-)
Je met ca dans mon pipe pour la semaine prochaine en principe.

**Comment by emsnytech** [comment]
et dire que l'on se traine ce sujet depuis.... 2016... (une de mes très très vieilles issues...)
