### ISSUE TITLE
ETQ Usager, je ne souhaite pas être bloqué quand j'ai demandé la non-publication des données SIRET

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#4822]
On un un sujet sur les numéro de SIRET non diffusible, qui bloquent les entreprises qui ont fait opposition à l'INSEE

Hors, depuis le 1 décembre 2019, il semble que nous puissions contourne le sujet 
la doc dit cela 

"Entreprises non-diffusées

Vous pouvez accéder aux entreprises non diffusées en ajoutant le paramètre non_diffusables=true. Un champ supplémentaire apparaît alors diffusable_commercialement indiquant si l'entreprise est diffusée ou non.

Selon les articles A123-95 et A123-96 du code du commerce, peuvent être non diffusés :

certains établissements du ministère de la défense
certaines personnes morales pour des raisons de confidentialités
toute personne physique qui en fait la demande auprès de l'INSEE"

Proposition;
Quand on a un code 403, on est en mesure d'afficher co^té Front:
L'entreprise  "etablissement_siege": {
    "siege_social": true,
    "siret": "41816609600051",
 à demandé la nom publication de ses informations .

Ces dernière ne sont pas visibles.
Toutefois, elles ont été récupérées et seront visibles des agents chargés de l'instruction de votre dossier.

Les données consultables par les agents sont décrites dans la documentation" (lien vers la doc)

**Comment by Keirua** [comment]
«Vous pouvez accéder aux entreprises non diffusées en ajoutant le paramètre `non_diffusables=true`. Un champ supplémentaire apparaît alors `diffusable_commercialement` indiquant si l’entreprise est diffusée ou non.»

Pour info les textes en question:
 - [A 123-95](https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=A50D4E549BAC95B63FFE10B24F86D7A5.tplgfr21s_1?idArticle=LEGIARTI000020165032&cidTexte=LEGITEXT000005634379&dateTexte=20100702)
 - [A 123-96](https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=A50D4E549BAC95B63FFE10B24F86D7A5.tplgfr21s_1?idArticle=LEGIARTI000020165030&cidTexte=LEGITEXT000005634379&dateTexte=20100702)

Proposition de Philippe: Quand on a un code 403, on peut faire apparaître coté usager juste le nom de la boite et un texte ” les informations de l’entreprise ont fait l’objet d’une interdiction de diffusion, toutefois, les informations inscrite à l’insee seront visible des services instructeurs. ou qques chose comme cela...

**Comment by krichtof** [comment]
De ce que je comprends, c'est que lorsque les infos ne sont pas diffusables publiquement, on souhaite afficher pour l'usager uniquement le nom de l'établissement, mais pas le reste des infos. Et on affiche toutes les infos pour l'instructeur.

Je me pose la question du pourquoi cacher les infos à l'usager ? A priori, il les connait.

Hormi l'instructeur et l'usager, y a t-il un profil qui a accès au dossier et qui ne serait pas habilité à voir les infos non diffusables ?

**Comment by krichtof** [comment]
Réponse de @emsnytech :
> n’importe qui peut rentrer n’importe quel siret et donc tout voir ...

@krichtof 
> donc on cache l'info uniquement dans l'interface usager ?

@emsnytech 
> Exactly.... juste faut il rajouter peut être qque chose dans l’interface usager mais je vois avec nos juristes « l’entreprise à exercer son droit à la non publication des informations relatives à son identité. Les informations ne seront donc visibles que de la part des services instructeurs » ou qque chose comme cela
