### ISSUE TITLE
ETQ Administrateur, je souhaite accéder aux nouvelles fonctions de cartographie

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#4823]
Mise en place du plan d'amélioration de la CARTO pour la DGLNA

**Comment by Keirua** [comment]
Dans le HS32289 il est question de l'export de la zone sélectionnée dans un fichier SIG

**Comment by kemenaran** [comment]
- afficher une vue aérienne récente et cartes marines en fond de carte ;
- afficher la couche Natura2000 et réserves naturelles ;
- dessiner des zones, lignes et points ;
- afficher les surfaces ou longueurs des tracés dessinés ;
- ajouter une description pour chaque tracé ;
- exporter la cartographie au format accepté par QGIS (.shp, .tab, .kml, .geojson, etc.) ;
- augmenter le niveau de zoom.

**Comment by tchak** [comment]
superseded by #5917
