### ISSUE TITLE
Ne pas dupliquer les données liées à l'adresse sur Etablissement

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#483]
On a
- adresse
- numero_voie + type_voie + nom_voie + complement_adresse + code_postal + localite

Étudier la pertinence de cette duplication, et l'enlever si elle est inutile

**Comment by emsnytech** [comment]
Attention ! compatibilité avec les applications métiers . (format standard des données adresses sont à respecter par contre dans l'API)
