### ISSUE TITLE
Amélioration des performances des démarches avec beacoup de dossiers

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4832]
L'écran d'affichage des procédures instructeur est lent lorsque les démarches ont beaucoup de dossiers (`Instructeurs::ProceduresController#show`).
On a le cas pour certaines grosses démarches (ex: HS32764, 45000 dossiers traités, impossible d'ouvrir l'onglet traité) : la page timeout avant de s'afficher.
Au niveau de [skylight](https://www.skylight.io/app/applications/zAvWTaqO0mu1/recent/6h/endpoints/Instructeurs::ProceduresController%23show?responseType=html), on peut voir que l'on fait pas mal de requêtes, en particulier lors du rendu de la page.
Cela semble lié à plusieurs choses:
 - la gestion des notifications… Sujet compliqué avec pas mal de couplage, qui oblige à faire plein de jointures et avoir des requêtes compliquées.
 - les appels à `procedure_presentation.sorted_ids`, et parfois  `procedure_presentation.filtered_ids` lorsque des filtres sont sélectionnés, semblent faire beaucoup de choses
 - dans la [boucle de rendu des dossiers](https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/app/views/instructeurs/procedures/show.html.haml#L122-L143), on doit pouvoir alléger les choses:
   - mettre en cache les notifications (`current_instructeur.notifications_for_procedure`)
   - on recalcule `@procedure_presentation.displayed_fields(dossier)` alors que j'imagine que ce sont les mêmes champs à afficher partout, car les champs sont stockés dans le dossier

J'ai pas encore fait de benchmark de ces améliorations (je ne suis pas expert en performances), et je ne connais pas l'historique de cet écran, je me doute que si c'était simple de faire plus efficace on l'aurait fait.

Par ailleurs la situation ne va pas s'améliorer (avec l'arrivée des groupes instructeurs, les démarches vont avoir beaucoup de dossiers, et la démarche concernée ici prévoit pas mal de nouveaux dossiers) donc il va falloir trouver des axes d'améliorations

**Comment by Keirua** [comment]
(après bench, c'est bien `procedure_presentation.sorted_ids` qui met le bazar)

**Comment by Keirua** [comment]
Suite à discussion, on a 2 axes pour améliorer la situation:
 - limiter le nombre de dossiers par procédure, en purgeant régulièrement les dossiers pour éviter que trop de données s'accumule chez
 - améliorer les performances

Concernant les performances, c'est le bloc suivant qui pose problème. Avec 15000 dossiers, 75% du temps de la requête a lieu là dedans:
```ruby
# ProcedurePresentation#sorted_ids
dossiers_id_with_notification = dossiers.with_notifications.merge(instructeur.followed_dossiers).ids
if order == 'desc'
  return dossiers_id_with_notification +
    (dossiers.order('dossiers.updated_at desc').ids - dossiers_id_with_notification)
else
  return (dossiers.order('dossiers.updated_at asc').ids - dossiers_id_with_notification) +
    dossiers_id_with_notification
end
```
Le scope `:with_notifications` fait en particulier une jointure sur la table champs qui alourdit la requête

On se dit qu'on peut éviter cette jointure en ajoutant une propriété `champs_updated_at`, qui serait mise à jour lorsqu'un champ est modifiée, et qui permet d'obtenir les dossiers modifiés à moindre coût

**Comment by Keirua** [comment]
Après avoir joué un poil avec les scope, en fait c'est la précondition `dossiers.each { |dossier| assert_matching_procedure(dossier) }`
qui induit une N+1 sans valeur ajoutée, cf la discussion originelle (il faut faire un show conversation): https://github.com/betagouv/demarches-simplifiees.fr/pull/2770/commits/667deae5ccc5a4bf1d5386440bb4cd5f8086b305#diff-b6be6196cd739f8b31e0b195677e46d6R176

**Comment by Keirua** [comment]
Supprimer les préconditions permet de passer de 60s de rendu pour 45k dossiers à ~2s, donc ajouter du cache sur les champs mis à jour ne parait pas nécessaire

**Comment by emsnytech** [comment]
super !
