### ISSUE TITLE
Bug d'affichage dans la page de réaffactation des dossiers d'un groupe

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#4850]
![Screenshot_2020-03-02 demarches-simplifiees fr](https://user-images.githubusercontent.com/907405/75664131-43b23100-5c72-11ea-8a2e-3d18ac793f70.png)

**Comment by Keirua** [comment]
résolu par https://github.com/betagouv/demarches-simplifiees.fr/pull/4844
