### ISSUE TITLE
Bug lors de la suppression d'un groupe d'instructeur comportant des dossiers hidden

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#4851]
**Décrivez le bug**
Lorsqu'un groupe d'instructeur comporte des dossiers hidden, l'interface admin ne les réaffecte pas comme les dossiers non caché, du coup, elle propose de supprimer le groupe ce qui plante à cause d'une clé étrangère. 

**Reproduction**
Comment reproduire le problème :
1. Remplir un dossier dans un groupe d'instruction en brouillon
2. ETQ usager, supprimer le
3. ETQ admin, supprimer le groupe d'instruction en question => badaboum

**Comportement attendu**
Le groupe d'instruction aurait du être supprimé

**Comment by tchak** [comment]
je prend
