### ISSUE TITLE
Programmer un audit accessibilité

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#4852]

**Comment by kemenaran** [comment]
On attend que #4869 (amélioration d'accessibilités) soit mise en prod. Ensuite @emsnytech va demander à quelqu'un de la DINUM de faire un test, et de faire des retours.

**Comment by kemenaran** [comment]
@emsnytech va relancer l'audit au mois d'août.

**Comment by tchak** [comment]
l'audit est fait
