### ISSUE TITLE
ETQ Admin, je veux que les dossiers soient supprimés après traitement (RGPD)

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#4867]
Les CGU fixent la règle de la suppression des dossiers traités à la fin du délai de conservation du dossier fixé par l'administrateur; 

De fait, il convient de prévoir deux règles:
- La suppression sitôt le traitement effectué (le principe est qu'un dossier qui a fait l'objet d'une décision soit supprimé dans des délais très rapide après décision ( 30  jours ? sitôt assuré du téléchargement ?...). Cela va concerner les démarches qui traitent en particulier de données dont il convient de ne pas les garder au delà du temps nécessaire au traitement (normalement, c'est l'analyse de risque effectuée par le service qui défini le niveau de risque)
- la suppression à la date limite fixé par l'administrateur. Cette règle un peu plus souple va notamment concerner des démarches qui ne comportent pas de risques importants (on dit que les risques sont acceptables) s'agissant des données collectées (dossiers de personnes morales, demande de subvention...)

Le pb du point de vue usage est de s'assurer que les usagers et les administrations aient été en mesure de récupérer ces dossiers, avant suppression (c'est surtout vrai pour les administrations qui dans le cas où elle ne gardent aucune trace du dossier peuvent se retrouver juridiquement dans une situation compliquée).

Le mise en oeuvre de ce point est un élément essentiel qu'il convient d'automatiser, malgré le fait qu'aujourd'hui nous sommes en mesure d'effectuer une suppression semi automatique.

**Comment by kemenaran** [comment]
Doublon de #3796
