### ISSUE TITLE
Bug lors de changer le"bloc répétable" à un autre type, les sous champs ne sont pas supprimés dans BD

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/demarches-simplifiees.fr#4868]
**Décrivez le bug**
Lors de changer le type_de_champs "bloc répétable" à un autre type de champs, les champs dans le "bloc répétable" ne sont pas supprimés dans la BD.

**Reproduction**
Comment reproduire le problème :
1. Aller sur la page 'Configuration des champs'
2. Changez un champs de type  'bloc répétable' à un autre type
3. Le type champ 'bloc répétable' est bien update dans le BD, mais les sous champs de  'bloc répétable' ne sont pas supprimés.

**Capture d'écran**

1. Deux champs dans un "bloc répétable":
![image](https://user-images.githubusercontent.com/9320719/76074909-5e4f1780-5f9c-11ea-895d-c11de26be228.png)
![image](https://user-images.githubusercontent.com/9320719/76074984-82125d80-5f9c-11ea-82c8-e3264329a89d.png)

2. Changez le "bloc répétable" à "Date": 
![image](https://user-images.githubusercontent.com/9320719/76075177-d61d4200-5f9c-11ea-9a83-8595a9eb71a9.png)
![image](https://user-images.githubusercontent.com/9320719/76075213-e33a3100-5f9c-11ea-9cec-475652f2ca0c.png)

**Appareil et navigateur utilisé**
 - Appareil : PC
 - Navigateur : Chrome

**Comment by pengfeidong** [comment]
Pour supprmer les sous champs, on peut ajouter un `before_save `dans `TypeDeChamp`:
```
before_save :destroy_sub_champ

def destroy_sub_champ
  types_de_champ.delete_all if was_repetition?
end
```

**Comment by tchak** [comment]
PR welcome :)

**Comment by tchak** [comment]
c'est corrigé
