### ISSUE TITLE
ETQ Admin , je veux pouvoir ajouter ou retirer massivement des instructeurs sur des démarches 

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/demarches-simplifiees.fr#4877]
En tant qu’administrateur, je veux pouvoir ajouter ou retirer massivement des instructeurs sur des démarches en cochant la ligne ou avec un bouton qui sélectionne tous mes instructeurs.

**Comment by ndrianab** [comment]
https://demarches-simplifiees.featureupvote.com/suggestions/82896/etq-admin-je-veux-pouvoir-ajouter-ou-retirer-massivement-des-instructeurs-sur-de

**Comment by pengfeidong** [comment]
https://demarches-simplifiees.featureupvote.com/suggestions/82896/etq-admin-je-veux-pouvoir-ajouter-ou-retirer-massivement-des-instructeurs-sur-de

**Comment by kemenaran** [comment]
Du coup, vu que c'est dans FeatureUpvote, je ferme l'issue.

@pengfeidong On pourra la ré-ouvrir si vous pensez travailler dessus 👍
