### ISSUE TITLE
ETQ Admin, je dois pouvoir repasser ma démarche declarative en mode 'normal'

### ISSUE THREAD

**Issue by maatinito** [betagouv/demarches-simplifiees.fr#4892]
**Décrivez le bug**
@tchak  Une fois passée en mode déclaratif, l'option 'Non' disparait du menu de démarche déclarative et il n'est plus possible de revenir en mode normal. 
**Reproduction**
Comment reproduire le problème :
1. Créer une démarche 
2. La passer en mode déclarative (instruction ou acceptée) puis valider 
3. Revenir sur le champ ==> le menu n'a plus l'option 'Non'. 
![image](https://user-images.githubusercontent.com/15379878/76791557-424e3180-6765-11ea-98f7-c55a16fbd916.png)

Deux aspects: 
  1) j'ai l'impression que cela devrait être possible que ce soit en mode publiée ou en test : on devrait pouvoir la ramener en mode normal. Mais ça se discute peut-être pour le mode publié.
  2) je peux faire une PR pour la correction.

**Comment by kemenaran** [comment]
@tchak on est preneur d'une PR - à moins que ça soit voulu explicitement ?

**Comment by tchak** [comment]
Non, ce n'est pas voulu. Nous sommes preneur d'une PR.
