### ISSUE TITLE
Migrer le lecteur de carte sur mapboxGL

### ISSUE THREAD

**Issue by tchak** [betagouv/demarches-simplifiees.fr#4893]
- [x] se familiariser avec `mapbox-gl-js` https://docs.mapbox.com/mapbox-gl-js/api/
- [x] utiliser un component `react-loadable`
- [x] afficher les GeoJSON de la selection usager
- [x] afficher les GeoJSON des cadastres

docs :
https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/

**Comment by kara22** [comment]
Pour info on est parti sur ce package : https://github.com/alex3165/react-mapbox-gl
