### ISSUE TITLE
ETQ Usager, je veux pouvoir redéposer / prolonger un dossier qui traine en construction (avant qu'il soit supprimé)

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4896]
On va bientôt envoyer des emails aux usagers, pour prévenir que leurs vieux dossiers en construction vont être supprimés. Donc des dossiers qui ont été déposés, mais qui n'ont jamais été traités par l'administration.

Dans le cas où le dossier est obsolète, pas de souci. Mais si la demande est toujours valable, il serait bon que l'Usager puisse cliquer sur un bouton pour relancer le délai d'expiration, sans que son dossier soit supprimé.

On peut imaginer un bouton "Relancer" dans l'email et/ou dans l'interface. Ça ré-initialiserait le délai de suppression, et re-rendrait le dossier visible aux agents instructeurs d'une manière ou d'une autre.

**Comment by Keirua** [comment]
Ça marche sur les plates bandes de https://github.com/betagouv/demarches-simplifiees.fr/pull/4779

Si je comprends bien, une solution technique serait:
 - Ajout d'un interval `dossier_construction_extend_keep_duration`.
 - À chaque fois qu'on clique sur le bouton dans le mail on ajoute un mois de délai (durée à discuter) de conservation.
 - Modification du `scope :en_construction_close_to_expiration` pour tenir compte de cette durée
