### ISSUE TITLE
ETQ Instructeur, je veux savoir quel instructeur a pris la décision sur un dossier

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4897]
L'usage de DS est basé sur la transparence plutôt que le contrôle. Dans ce cadre, on devrait pouvoir afficher dans l'interface quel instructeur a pris la décision sur un dossier.

Ça serait sans doute de la même manière qu'on affiche déjà la liste des instructeurs qui sont intervenus sur un dossier.

**Comment by tchak** [comment]
Aujourd'hui, on perd de l'information. Il est possible de faire des allers-retours entre les différents stades de traitement et aujourd'hui on écrase le dernier état. Je propose d'introduire un nouveau model Traitement.

Il aurait 4 opérations possibles ('accepter', 'refuser', 'classer_sans_suite', 'repasser_en_instruction') et à terme on migrerait dessus tout les informations concernant le traitement aujourd'hui attaché directement au dossier (motivation, attestation, etc.). On continuerait de perdre de l'information en cas d’allez retours entre `en_construction` et `en_instruction` mais il me semble que l'impact de c'est opérations n'est pas aussi important.

**Comment by kemenaran** [comment]
Effectivement. Cela dit on stocke quand même dans le OperationLog le nom de chaque instructeur pour chaque validation effectuée sur un même dossier, non ?

Et aussi, est-ce que dans ce cas on pourrait faire par étapes ?

- v1 : on affiche juste l'instructeur ayant pris la dernière décision (en continuant à perdre de l'info en cas de rollback).
    _Et on met un "TODO: en cas de rollback on perd de l'info ; si un jour c'est un souci refactorer avec un modèle Traitrement"._
- v2 : si le besoin apparait, on introduit le modèle Traitement.

**Comment by tchak** [comment]
Je suis très hésitant à utiliser les opérations log pour des besoins métier/UI. De plus, les informations sont enregistré dans un json sérialisé sur le storage ovh. Donc pour chaque affichage on ferait une requête à ovh pour lire le json. Je ne pense pas que ce soit une bonne idée.

Ajout de Traitement en v1 avec juste les infos manquantes: (instructeur, date et type du traitement) ne me parai pas super complexe.

**Comment by krichtof** [comment]
J'arrive après la discussion.
L'idée du modèle Traitement si je comprends bien est de ne pas garder uniquement le dernier état d'une décision sur un dossier. De savoir par exemple qu'il a été refusé, puis accepté.

> Ajout de Traitement en v1 avec juste les infos manquantes: (instructeur, date et type du traitement) ne me parai pas super complexe.

Du coup, dans Traitement, ne faudrait-il pas également _motivation_ et _justificatif_movitation_ ?

**Comment by kemenaran** [comment]
La motivation ça me semble intéressant (c'est juste du texte) ; mais le justificatif, hmm… Ça fait un fichier à stocker même en cas de rollback ; je dirais qu'on s'en fiche, non ?

**Comment by krichtof** [comment]
ça me va bien de garder la motivation, mais pas le justificatif. Au pire, s'il y en a besoin, les utilisateurs nous le remontront.

**Comment by krichtof** [comment]
Pour éviter d'avoir du code hybride, je propose de ne pas se limiter aux states terminé mais également en_construction et en_instruction. Cela permettrait en plus pour l'instructeur de voir tout l'historique du dossier : quand il est passé en construction, en instruction, quand la décision a été rendue, par qui.
