### ISSUE TITLE
Permettre aux administrateurs de mettre en forme le "corps du document" de l'attestation

### ISSUE THREAD

**Issue by icollombet** [betagouv/demarches-simplifiees.fr#490]
Actuellement, les administrateurs ont un seul champ pour le corps du document de l'attestation qu'ils en peuvent pas mettre en forme (ex. mettre en gras, modifier l'alignement...) alors que ce serait utile pour que l'attestation soit parfaitement lisible claire. Demande de l'Agence nationale des fréquences.

**Comment by benjaminhenkel** [comment]
demande de la Mayenne

**Comment by benjaminhenkel** [comment]
Demande également de la DGAC

**Comment by benjaminhenkel** [comment]
A importation d'acier

**Comment by benjaminhenkel** [comment]
Prefecture du gard

**Comment by LeSim** [comment]
Déléguée au Permis de Conduire et à la sécurité Routière `hs #2440`

**Comment by chaibax** [comment]
Demandé par frederic.fournier@haute-loire.gouv.fr  / Préfecture de la Haute-Loire deal . Sans ca, il continuera a envoyer des attestations papier par courrier.

**Comment by LeSim** [comment]
`hs #8388`

**Comment by gregoirenovel** [comment]
HS 2288

**Comment by CamilleGarrigue** [comment]
- Patrice. A (DDTM Loire Atlantique)

**Comment by CamilleGarrigue** [comment]
- Agnès.R (pref Rhône)
