### ISSUE TITLE
Problème de report des balises dans les e-mails automatiques

### ISSUE THREAD

**Issue by ndrianab** [betagouv/demarches-simplifiees.fr#4904]
**HS #34602**

Depuis fort longtemps, il y a un mauvais 'remplacement' des champs dans les courriels envoyés aux usagers lors de leur création de dossier.

Par exemple, procédure NNNNN, demande de MHRDC en test, dossier fictif XXXXXXX :

Dans la première réponse automatique, l'accusé de réception, le champs "--G.03 - Nom de naissance--" ne se remplace pas.

Voici le résultat que l'on reçoit entant qu'usager (copie du courriel ==> "[INTERNET] Accusé de réception de votre démarche en ligne pour LYMA Christophe (Dossier n°XXXXXX).eml")

    ------------------------------------------------------------------------------------------------------------------
    Bonjour,

    L'équipe demarches-simplifiees.fr vous confirme la réception de votre dossier pour --G.03 - Nom de naissance-- Christophe (Dossier n°1521518).
    Votre demande va être dirigée vers le service instructeur du département de résidence du candidat.

    Vous recevrez alors un message avec les coordonnées de ce service.
    ------------------------------------------------------------------------------------------------------------------

Pour l'accusé de passage en instruction, c'est le numéro du dossier qui ne se remplace pas. (copie du courriel ==>"[INTERNET] Votre dossier demarches-simplifiees.fr pour LYMA Christophe (Dossier n°XXXXXXXX) va être instruit.eml")

    ------------------------------------------------------------------------------------------------------------------

    Bonjour,
    Votre administration vous confirme la bonne réception de votre dossier pour LYMA Christophe (Dossier n°--numéro du dossier--).Celui-ci sera instruit dans le délai légal déclaré par votre interlocuteur.
    ------------------------------------------------------------------------------------------------------------------

**Comment by kemenaran** [comment]
J'ai regardé les templates d'email : c'est parce qu'il y a un saut de ligne au milieu des balises.

À priori pas facile de prendre en compte les sauts de ligne de notre côté. La meilleure solution est donc de ne pas mettre de saut de ligne au milieu des balises.

Je réponds à la personne.

**Comment by ndrianab** [comment]
super !!! Merci

**Comment by tola42** [comment]
Bonjour,
Après vérification, il n'y a pas de saut de ligne dans nos balises quand nous les copions.
C'est lors de la 'mise en page' du texte que ces sauts se rajoutent, et nous n'avons aucune possibilité de changer cet ajout.
Merci pour votre analyse.

**Comment by kemenaran** [comment]
@tola42 mmm, c'est un peu curieux ; je crois que vous êtes les seuls à rencontrer ce souci. Est-ce que ça serait lié au fait que vous fassiez du copier-coller d'un texte dans le champ de composition ?

**Comment by tola42** [comment]
Je pense plutôt que c'est lié à logiciel qui met en forme le message aux usagers. En effet, j'ai remarqué qu'il 'coupait' le champs au milieu sur les 'preview' quand je suis dans l'éditeur de mail des DS. D'ailleurs, j'ai récupéré le texte de l'éditeur mise à notre disposition et je l'ao collé dans notepad++, je ne voit pas de CR/LF !

**Comment by tola42** [comment]
![image](https://user-images.githubusercontent.com/3890867/77449172-eed98480-6df1-11ea-864e-02b88567f735.png)
Voila même  une image du 'concepteur/éditeur' de courriel ou l'on voit la coupure qui, pour moi, semble poser problème.

**Comment by krichtof** [comment]
Merci pour cette copie écran @tola42 
Mais la coupure que vous mentionnez est celle effectuée par le navigateur et non le code de Démarches Simplifiées qui substitue la balise avec la valeur du champ.

J'ai importé une base anonymisée de la production en environnement local et j'ai réussi à reproduire votre problème. 
Il semble qu'un caractère "invisible" se soit glissé dans la balise (et pas uniquement pour le template de mail d'accusé réception, le problème est également pour l'accusé de passage en instruction).

Pour corriger le problème, voici comme j'ai procédé :

J'ai supprimé la partie du template --G.03 - Nom de naissance-- --G.04 - Prénom 1-- (Dossier n°--numéro du dossier-- puis l'ai resaisi en copiant-collant à partir des balises indiquées en bas de page.

Après avoir mis à jour le template, la substitution dans les mails envoyés à l'usager s'est effectuée correctement.

Si cette procédure ne fonctionne pas, avez-vous essayé une manière plus laborieuse qui est de taper à la main cette partie du template ?

**Comment by tola42** [comment]
Je vous avouerai que j'ai fait du copier/collé et pas de recopie à la main. Ce qui m'étonne, c'est que j'ai copié il y a de cela fort fort longtemps les balises du bas de page, dans le petit éditeur de courriel. 

Mais quand j'ai copié tout ceci dans Notepad++, je n'ai pas vu de caractère caché alors qu'habituellement, ils apparaissent dans Np++.

Je vais donc refaire mes courriels qui posent problème en copiant de nouveau les balises et je revérifierai tous les courriels en testant un faux dossier.

Merci.
