### ISSUE TITLE
Clarifier la suppression de dossiers

### ISSUE THREAD

**Issue by tchak** [betagouv/demarches-simplifiees.fr#4905]
Il existe plusieurs façons de supprimer un dossier :

- `dossier.delete_and_keep_track()`
  - appel `dossier.discard!`
  - crée un `DeletedDossier`
  - envoie un mail au usager
  - si en construction, envoie un email aux instructeurs
  - log operation pour horodatée
- `user.delete_and_keep_track_dossiers()`
  - appel `dossier.delete_and_keep_track()`
  - appel `dossiers.with_discarded.destroy_all`
- `destroy_brouillons_and_notify()`
  - crée un `DeletedDossier`
  - appel `dossier.destroy`
  - envoie un mail au usager (différent mail du cas `delete_and_keep_track`)
- `procedure.hide!`
  - appel `dossiers.discard_all`

Dans les 4 cas, le résultat est très différent. Les mails ne sont pas toujours envoyés et ce n’est pas les mêmes emails dans tous les cas. Le “operation log” est seulement créée dans certains cas. On crée des `DeletedDossier` pour des dossiers en brouillon – devrait-on le faire ?

Par ailleurs, lors de la suppression de brouillon (sur demande de l'usager) on envoie un email disant "Une trace anonyme de ce traitement sera conservée pour l’administration." Ce qui est faux – on ne montre jamais à l'administration l'existence de brouillons.

**Comment by kemenaran** [comment]
Je dirais qu'on ne devrait pas garder de trace des dossiers en brouillon (ni dans le Operation Log, ni dans dans les DeletedDossier)

**Comment by tchak** [comment]
Vous pensez qu'on devrait horodater la suppression automatique de dossiers "en_construction" ?

**Comment by tchak** [comment]
Je considère que c'est fait
