### ISSUE TITLE
Afficher les `DeletedDossier` dans l'UI

### ISSUE THREAD

**Issue by krichtof** [betagouv/demarches-simplifiees.fr#4907]
En tant qu'instructeur, je dois voir la liste des dossiers supprimés qui ne sont pas brouillon.

Pour chacun des dossiers supprimés, indiquer l'état, la procédure et la date de suppression

**Comment by krichtof** [comment]
Besoin d'avis sur la mise en forme. Où est-ce que je place le lien qui amène aux dossiers supprimés ?

Voici pour l'instant 2 propositions :

- par défaut, l'ajout du nouvel onglet "supprimés" crée une 2e ligne. J'ai l'impression que ça lui donne trop d'importance. Vous en pensez quoi ?

![supprimés-2l](https://user-images.githubusercontent.com/1111966/77300830-01b76080-6cef-11ea-919e-270d54b96f94.png)

- quand j'essaie de mettre l'onglet "supprimés" sur la même ligne, cela m'oblige à revoir la structure de `procedure-header` et pour l'instant, ça pose comme souci de ne pas mettre sur le h1 de la procédure et le `procedure.actions` (Télécharger tous les dossiers)
![supprimés-1l](https://user-images.githubusercontent.com/1111966/77300848-07ad4180-6cef-11ea-8753-b3e609ac6f2c.png)

Avant de creuser un peu cette 2e proposition, est-ce que vous trouvez que c'est une bonne idée de mettre le lien "supprimés" en tant qu'onglet ? Est-ce que vous préférez que je l'isole des autres parce que pas de même nature ? Et le mettre par exemple au même niveau que "Gestion des notifications | Statistiques" ? (mouais)

**Comment by krichtof** [comment]
J'avance sur la 2e option. Mais "Télécharger tous les dossiers" et le menu "Aide" devraient être alignés, ce qui n'est pas le cas...

![supprimés-1l-left](https://user-images.githubusercontent.com/1111966/77306509-15b39000-6cf8-11ea-9950-ab3cff315eda.png)

**Comment by kemenaran** [comment]
Je me demande si ça a sa place dans la barre d'onglets, qui est déjà assez chargée.

Est-ce que par exemple on ne pourrait pas en faire une option en haut de la liste "Archivés" ? Quelque chose comme un lien "Afficher les dossiers supprimés" en haut de la liste ?

<img width="1120" alt="Capture d’écran 2020-03-23 à 11 45 25" src="https://user-images.githubusercontent.com/179923/77308793-ccfdd600-6cfb-11ea-9a9a-acca03e1d708.png">

C'est pas _incroyable_ niveau UX – mais j'ai l'impression que :

- ça évite à minima de polluer les onglets de dossiers qui sont souvent utilisés
- ça évite d'avoir des éléments de différente nature dans les onglets (des dossiers et des dossiers supprimés, c'est pas la même présentation ; par exemple on ne peut pas mélanger l'affichage de dossiers normaux et supprimés dans la même liste)

Tu en penses quoi ?

**Comment by krichtof** [comment]
Je n'étais pas à l'aise à le mettre dans les onglets. J'aime bien ta proposition qui permet d'éviter de le mélanger avec des dossiers de nature différente. Je vais l'implémenter.
