### ISSUE TITLE
Mise à jour du logo "Marianne"

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#4935]
On utilise le logo Marianne à 3 endroits:

 - dans le header sur les pages déconnectées
![image](https://user-images.githubusercontent.com/1223316/77435754-f9405200-6de2-11ea-8294-d0d17eddabda.png)
 - lors du dépot d'un dossier en tant qu'usager
![image](https://user-images.githubusercontent.com/1223316/77436034-48868280-6de3-11ea-9c57-ae83f6f87ad1.png)
 - dans la barre de navigation en tant qu'admin
![image](https://user-images.githubusercontent.com/1223316/77436131-6653e780-6de3-11ea-8fe4-2cdbf5840828.png)

On a un nouveau logo via la marque France.
 - est-il pour ces 3 endroits ? @emsnytech 
 - il est plus gros donc le rendu est encore moins lisible que maintenant (sauf sur la page d'une procédure)

**Comment by kemenaran** [comment]
Je crois que

**Comment by kemenaran** [comment]
Avec le nouveau design system et la suppression de l'ancien design, je pense que cette issue n'est plus d'actualité.
