### ISSUE TITLE
Fusionner les 3 types de comptes

### ISSUE THREAD

**Issue by mmagn** [betagouv/demarches-simplifiees.fr#496]
Pour éviter la syncro des mots de passes et autres hacks.

Gestion de roles ?

**Comment by gregoirenovel** [comment]
Ça va peut etre bypasser devise et nous poser quelques problèmes (quoi que...) mais je propose :
- un unique objet `User`
- des colonne `is_X` où X in { superadmin, administrateur, gestionnaire, usager }
- une colonne `current_role` qui contient le role actuel d'un User donné
