### ISSUE TITLE
Clarifier la notion d’archivage dans DS

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4965]
On va commencer à avoir du "vrai" archivage. Du coup la formulation de l'onglet "Archivage" qui existe en ce moment est trompeuse.

~~Trouver un meilleur nom et le renommer.~~

On devrait ajouter plus d'informations sur la nature temporaire de l'archivage dans DS. L'information devrait apparaitre dans l'onglet "Archivage".

**Comment by kara22** [comment]
Ce n'est pas qu'un renommage front-end ? Car dans les contrôleurs et autres on appelle procedure.archived du coup si on change de nom il faudra changer le nom dans les contrôleurs, schema et tests ?

**Comment by tchak** [comment]
Il semble que pour l'instant le consensus est de garder "archivage”, mais d'ajouter un message qui mentionne la suppression après la durée de conservation.
