### ISSUE TITLE
Instructeur : exporter les démarches de moins d'1 Go

### ISSUE THREAD

**Issue by tchak** [betagouv/demarches-simplifiees.fr#4978]

**Comment by tchak** [comment]
Lors de la demande d'export de la totalité des dossiers pour archivage veut-on vraiment retélécharger tous les dossiers à chaque demande ? On ne veut pas faire des bundles par mois ou semaine ? Peut-être en fonction de la volumétrie ?

**Comment by tchak** [comment]
Je pense à un truc du genre en fin de semaine le job regarde le nombre de dossiers terminé et si > 100 alors création d'exports pour la semaine avec last_archived_dossier_id. En fin de mois création du bundle même si moins de 100 dossiers.

**Comment by Keirua** [comment]
Je me disais que ca vaut le coup de tout envoyer malgré les problèmes de bande passante chez nous: j'ai peur que les démarches concernées n'aient pas de gros SI, donc leur imposer une étape manuelle mensuelle ca m'embête un poil.
Par ailleurs pour les fichiers de moins d'un Go je me voyais bien les générer à la volée (plutôt que les générer dans un job et les stocker dans un bucket). Ca résoud des problèmes de sécu en évitant de stocker des fichiers trop longtemps, mais c'est peut-être pas fiable.

**Comment by tchak** [comment]
Mais de toute façon, ils vont devoir faire la manipe tous les mois ou toutes les semaines, non ? C'est juste qu'ils vont télécharger plein de doublons... Alors je sais que tu peux dire que c'est leur problème, mais je trouve ça horrible. On peut afficher la date du dernier dossier dans l'archive, j’imagine… Je pense que ce que je propose peut être fait à la volée. C'est juste une question d’afficher les bons liens avec de l'info sur le bundle que tu veux générer dedans.

**Comment by Keirua** [comment]
J'ai l'impression qu'il y a 2 cas d'usages:
 - des démarches qui vont avoir toute leur vie sur DS sans suppression, et qui un jour vont vouloir un dump pour archivage chez eux.
 - des démarches qui vont avoir une longue vie sur DS avec des suppressions à partir d'un certain seuil, et qui n'auront pas d'autre choix que de faire des exports à intervalles réguliers.

J'ai répondu sous l'angle du 1) et toi du 2) j'ai l'impression. 

Ceci dit, de ce que j'ai fait actuellement, on a quand même plusieurs problèmes à faire un export global, même pour les procédures légères:
 - procédures avec beaucoup de dossiers+pj = grosses requêtes SQL avec plusieurs dizaines de milliers de résultats -> pas forcément fun à faire en synchrone. 
 - pour chaque PJ, j'ai l'impression qu'on a pas l'URL permanente, donc il faut solliciter le backend pour récupérer une URL temporaire, ce qui pose plein de problèmes (nombre de requêtes, timeout si on utilise pas l'URL dans les temps…). Pour le zip d'un dossier qu'on a déja, ça marche par accident (:scream:): on a pas beaucoup de fichiers, donc on a le temps de récupérer toutes les URLs temporaires avant le timeout du serveur.

…du coup faut que je regarde encore un peu, mais je sens qu'on va sans doute pas avoir d'autre choix que de générer les archives de manière découpée pour  tout le monde

**Comment by Keirua** [comment]
On me souffle dans l'oreillette qu'une spécification sur un format d'échange au sein de l'état existe, le [SEDA](https://redirect.francearchives.fr/seda/documentation.html):
 - leur [pdf](https://redirect.francearchives.fr/seda/documentation/SEDA_description_standard_v2_1.pdf) de présentation fait un joli 67 pages, pratique si vous vous ennuyez pendant le confinement
 - « Le mieux pour naviguer dans le SEDA 2.1 c’est [cela](https://redirect.francearchives.fr/seda/api_v2-1/seda-2_1-descriptive_xsd.html#ArchiveUnitType_Content) »

**Comment by Keirua** [comment]
du coup, après une petite visio le conseil a conclu pour cette fois-ci:
 - on part sur un **découpage mensuel** pour gérer un maximum de cas d'usages.
 - on exporte les **dossiers terminés**, découpés par date de terminaison.
 - on inclue pour commencer:
   - les pièces jointes
   - l'export PDF du dossier
   - le `DossierOperationLog`
 - export généré de manière asynchrone, idéalement stocké dans un bucket dédié. Stockage limité dans le temps (ex: 1 semaine)
 - une fois l'export généré, on envoie un mail pour indiquer l'adresse de téléchargement
 - Création d'**un écran dédié coté instructeur** pour gérer la liste des archives à télécharger, avec le nombre de dossiers en face
 - on attend de voir ce qu'implique SEDA dans un point avec les acteurs en question. A priori pour nous, ce serait une API XML à fournir pour permettre à d'autres de télécharger les exports de manière authentifiée (cf [p.32-33](https://redirect.francearchives.fr/seda/documentation/SEDA_description_standard_v2_1.pdf) de la spec, 3.1.1 Transférer et 3.1.2 Communiquer). C'est un sujet tiers et on ouvrira sans doute une issue dédiée quand ça vaudra le coup.

**Comment by jpoulvel** [comment]
@LeSim : on attend d'avoir un trafic de retour à la normale (septembre) pour activer la fonctionnalité.
