### ISSUE TITLE
[Carto] - Lecteur de carte : migrer l'affichage des cadastres avec etalab

### ISSUE THREAD

**Issue by kara22** [betagouv/demarches-simplifiees.fr#4991]
- [ ] Afficher les cadastres non plus avec des polygones mais avec le fond de carte Etalab

**Comment by kemenaran** [comment]
État des lieux :

- L'ancienne API carto a une API cadastre, mais qui envoie des données périmées et qui va expirer.
- L'équipe API Geo n'est plus en train de travailler sur l'API "Cadastre" dont on aurait besoin (elle est presque finie, mais ils n'ont plus de budget).
- L'IGN n'a pas d'API "Cadastre".

On est donc bloqués.
