### ISSUE TITLE
[Carto] - clean Legacy

### ISSUE THREAD

**Issue by kara22** [betagouv/demarches-simplifiees.fr#4992]
- [x] supprimer les quartier prioritaires
- [x] supprimer parcelles agricoles
- [x] Supprimer le code de l'ancienne carte
- [x] Revoir la structure des geoJson (selection)

**Comment by kemenaran** [comment]
Les quartiers prioritaires ne fonctionnent plus ; on va supprimer ça (le code, pas la data, pour l'instant). Éventuellement notifier Lille de cette modification.

**Comment by tchak** [comment]
done
