### ISSUE TITLE
[Carto] - migrer l'éditeur de carte sur mapboxGL

### ISSUE THREAD

**Issue by kara22** [betagouv/demarches-simplifiees.fr#4995]
Sous feature flag : new_map_editor

**Comment by tchak** [comment]
Le fonctionnement de l'éditeur actuellement :
* l’usager dessine une sélection
* l’éditeur récupère les polygones et les sérialise en json et soumet au serveur via la valeur du champ
* le serveur fait appel à l'API carto avec les polygones de sélection pour récupérer les cadastres
* le serveur répond au frontend avec la liste des cadastres à dessiner sur la map
* l'éditeur supprime les layers de cadastres
* l'éditeur dessine la liste des cadastres reçue du serveur
