### ISSUE TITLE
ETQ INSTRUCTEUR et USAGER, je veux que l'information comme quoi le SIRET est aussi un SIRET SIEGE

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#5053]
Dans la présentation des données remontées quand on rentre par un SIRET, il faudrait ajouter les informations suivantes:

- le siret est un siret siège 
Si ce n'est pas un siret siège: indique le numéro du siret siège ( avec lien automatique sur la entreprise.data.gouv.fr

On peut faire apparaitre cela en front et en back.

**Comment by krichtof** [comment]
@emsnytech 

Aujourd'hui, nous avons déjà l'indication du siret siège social.

Lorsque l'établissement demandeur indique un siret qui n'est pas celui du siège social, voici ce qui est affiché :
![siret_siege_social](https://user-images.githubusercontent.com/1111966/80113866-223f3880-8583-11ea-8163-9df9d7ceefeb.png)

Lorsque l'établissement demandeur indique un siret qui est celui du siège social, voici ce qui est affiché : 
![siret](https://user-images.githubusercontent.com/1111966/80113951-397e2600-8583-11ea-9f90-083ed3e1d49e.png)

Souhaites-tu qu'on précise pour le 2e cas que c'est le siège social ?

**Comment by emsnytech** [comment]
Oui, mais donc on est déjà bon !!!
