### ISSUE TITLE
reformuler le texte : Tous les dossiers qui ont été déposés sur cette démarche, sans aucun filtre.

### ISSUE THREAD

**Issue by etiquet** [betagouv/demarches-simplifiees.fr#5056]
**Constat** 
Dans l'interface instructeur, lors que l'on sélectionne l'onglet "tous les dossiers"

La phrase suivante apparait:

"Tous les dossiers qui ont été déposés sur cette démarche, sans aucun filtre."
Sauf que ... l'on peut appliquer un filtre et que la liste affichée est bien filtrée...

**Suggestion**  
le plus simple :  reformuler la phrase... 
ex: "Tous les dossiers qui ont été déposés sur cette démarche quelque soit le statut et hors filtres appliqués localement. "

./ds/app/views/instructeurs/procedures/show.html.haml ( ligne 63 )

%p.explication-onglet Tous les dossiers qui ont été déposés sur cette démarche quelques soit le statut et hors filtres appliqués localement.

![Capture d’écran, le 2020-04-19 à 14 25 56](https://user-images.githubusercontent.com/18629332/79687748-bfc7fe80-8249-11ea-8265-a6accaf9393e.png)

**Comment by kemenaran** [comment]
C'est vrai, merci pour la remarque.

"Tous les dossiers qui ont été déposés sur cette démarche quelque soit le statut" me semble bien (et je propose d'arrêter la phrase là, pour ne pas faire trop de bruit cognitif).

**Comment by kemenaran** [comment]
C'est fait, ça sera disponible sur demarches-simplifiees.fr d'ici quelques heures.
