### ISSUE TITLE
Instructeur : afficher effectif entreprise année n-1

### ISSUE THREAD

**Issue by krichtof** [betagouv/demarches-simplifiees.fr#5068]
En tant qu'instructeur, je peux voir les effectifs d'une entreprise au 31/12 de l'année antérieure à celle en cours.

On en profitera également pour 
- préciser la source des données (URSSAF pour les effectifs mensuels, INSEE pour effectif de l'organisation)
- supprimer le code effectif qui n'apporte pas de valeur

**Comment by emsnytech** [comment]
super !
