### ISSUE TITLE
Passer la récupération des données API Entreprise en asynchrone

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#5113]
Chaque requête SIRET entraine de plus en plus de requêtes à l'API Entreprise, au fur et à mesure qu'on rajoute des infos.

Ça pose plusieurs problèmes :

- Pour l'usager, il voit que sa requête prend 10-15s avant que la page s'affiche. Pouvoir afficher la progression serait mieux.
- Pour nous, avoir une langue requête synchrone n'est pas idéal : y'a de bonnes chances que la connexion de l'utilisateur coupe au milieu, ou timeout, et on devra tout reprendre à zéro.
- Plus y'a de requêtes à API Entreprise, plus il faut qu'on voie ce qui se passe si _une_ de ces requêtes échoue. Est-ce qu'on marque tout comme échoué ? On ré-essaie automatiquement ? On affiche des données partielles ?

## Pistes

- Peut-être convertir la récupération des données API Entreprise en un Job asynchrone (y'a déjà un prototype de job existant, mais qui n'a jamais marché)
- Peut-être lancer des requêtes en parallèle ?

**Comment by krichtof** [comment]
Après discussion avec @tchak , je compte partir sur 
- vérification que le siret correspond bien à une entreprise existante, en synchrone
- un job par requête api entreprise
