### ISSUE TITLE
[ETQ Instructeur] Je veux pouvoir envoyer un message à l’attention d’un groupe de dossiers

### ISSUE THREAD

**Issue by tchak** [betagouv/demarches-simplifiees.fr#5124]
Il me semble qu’assez souvent au support il y a la demande d'envoyer un message a tous les usagers sur un dossier. Souvent pour les dossiers dans un état. Par exemple à tous les "en_construction". Il me semble même que le problème se pose aussi pour les dossiers pas encore déposés donc en brouillon. Je trouverai ça pas déconnant de pouvoir faire un communiqué à l'ensemble des dossiers en brouillon.

Peut-être que je me trompe et c'est une demande trop anecdotique.

cc @red1bush

**Comment by kemenaran** [comment]
Moi je serai pour.

On peut p-ê mettre ça dans feature-upvote, et voir si ça remonte ?

**Comment by emsnytech** [comment]
Entièrement d'accord !!!!!!

**Comment by kemenaran** [comment]
Déplacé dans https://demarches-simplifiees.featureupvote.com/suggestions/95098/instructeur-envoyer-un-message-a-tous-les-dossiers-en-construction-ou-en-instruc
