### ISSUE TITLE
Erreur 404 en cliquant sur le lien "Donner mon avis"

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#5125]
**Décrivez le bug**

Dès que l’on veut accéder à un dépôt d’avis... on a une erreur “contacter demarches simplifiees”. J’ai demandé à publier la démarche, même pb qu’en test.

Message sur Helpscout (`HS #88755`) :

> Nous recevons bien la demande réalisée par un instructeur à notre égard, mais nous ne pouvons pas aller sur la démarche pour déposer notre avis : page erreur qui s'affiche.

> J'ai essayé avec mes deux adresses email : finances et direccte.

**Contexte**

- Procédure 29742
- Cette fonction est devenue problématique quand ils ont ajouté le token spécifique de l’APIENTREPRISE... est ce que les droit d’accès à ces données à quelque chose à voir..., Je ne vois pas pourquoi, mais bon

**Comment by emsnytech** [comment]
Ils ont testé à nouveau sans le token (c'est OK) et avec (KO) la piste est peut être la bonne

**Comment by emsnytech** [comment]
J'ai proposé qu'il passent sans le token, si ils veulent commencer, et on ferait rejouer après.

**Comment by emsnytech** [comment]
yes !
