### ISSUE TITLE
Erreur lors du déplacement de champs quand le cadre juridique est manquant

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#5134]
**Décrivez le bug**

Quand le cadre juridique est manquant, déplacer un champ dans l'éditeur produit une erreur cryptique.

<img width="1137" alt="Capture d’écran 2020-05-11 à 18 37 01" src="https://user-images.githubusercontent.com/179923/81587116-dd0a6b80-93b6-11ea-8500-ddba149dae24.png">

**Reproduction**
Comment reproduire le problème :
1. Cloner une démarche avec comme cadre juridique un fichier de délibération
2. Supprimer le fichier de délibération
3. Cliquer sur "Démarches" dans le Header pour revenir à la liste des démarches.
    _La procédure est maintenant sans cadre juridique, donc invalide._
4. Aller dans l'éditeur de champs de la démarche
5. Essayer de déplacer un champ

**Pour résoudre**

C'est un peu embêtant qu'on puisse passer une démarche en "Invalide" comme ça. Mais si on permet de supprimer la délibération direct, on n'a pas trop le choix.

Une possibilité, ça serait d'à la place marquer la délibération comme "À détruire", mais de ne pas le faire tout de suite. 

Une autre, ça serait d'indiquer un message clair dans l'éditeur de champs.

**Comment by kemenaran** [comment]
Pour info, on a 7 démarches en prod invalides, parce qu'elles ont un 'juridique_required' true, mais pas de délibération ni de cadre juridique.

**Comment by Keirua** [comment]
J'ai corrigé certaines de ces erreurs et plus généralement, cette erreur arrive lorsque la démarche est invalide. Il reste des erreurs sur les délibérations (30 démarches), notice (18) et liens manquants (trop pour une correction manuelle de notre part).

Si le sujet intéresse, voici quelques questions à poser

```ruby
# on récupère les procédures invalides
invalid = Procedure.publiees.reject(&:valid?)

# Quels sont les différents types d'erreur ?
invalid.flat_map do |i| i.errors.messages.keys end.sort.uniq

# Combien on a d'erreurs de chaque type ?
y ([:cadre_juridique, :deliberation, :lien_site_web, :logo, :notice].map do |e|
    [e, invalid.count do |i| i.errors.messages.keys.include?(e) end]
end)
```

**Comment by krichtof** [comment]
Il n'y a plus de procédures invalides. Des modifications en base ont été faites, et quelques règles de validations modifiées pour s'appliquer à partir d'une certaine date, et ainsi rendre valides quelques procédures anciennes.

#5957  et #5962
