### ISSUE TITLE
ETQ Instructeur, je veux révoquer des experts invités

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#5138]
Dans la vue expert, je veux pouvoir révoquer ou réalerter un expert

**Comment by krichtof** [comment]
Je propose de séparer la révocation et réalerter un expert. Et de traiter dans ce ticker uniquement la révocation d'un expert.

Qu'entend-on par révoquer un expert ?

- si l'expert n'a pas encore donné d'avis, supprimer la demande d'avis
- si l'expert a déjà donné son avis, garder l'avis qu'il a donné mais l'empêcher de le modifier

Est-ce que c'est ce comportement qui est attendu ?

**Comment by krichtof** [comment]
Discuté IRL.

- on supprime la demande d'avis si l'expert n'a pas encore donné son avis
- on empêche l'expert de modifier son avis s'il l'a déjà donné

**Comment by tchak** [comment]
* on empêche l'expert de demander l'avis à d'autres experts

**Comment by tchak** [comment]
On empêche l'expert de voir le dossier, non ?

**Comment by krichtof** [comment]
oui, tout à fait. Et on laisse son avis déjà déposé visible aux instructeurs ayant accès au dossier

**Comment by krichtof** [comment]
Concernant la relance d'un expert, j'ai créé cette issue : #5395
