### ISSUE TITLE
Pérenniser les liens vers la doc

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#5172]
Je me pose la question de comment nous assurer d'avoir des liens valides de DS vers les pages externes de documentation, afin de ne pas rediriger les utilisateurs vers des pages qui n'existent pas (suppression accidentelle, modification du lien non reportée…)

L'idéal serait d'utiliser les liens déja présent dans le code. Peut-être une tache Rake qui s'occupe de vérifier le code de retours de ces URLs ?
En CI, c'est pas idéal (flaky, et pourrait empêcher de merger du code sans rapport), mais peut-être qu'on peut s'envoyer une notification lors de la désynchro ?

# Ancien lien invalide

```
curl -I https://faq.demarches-simplifiees.fr/collection/1-administrateur    
HTTP/1.1 303 See Other
…etc
```

# Nouveau lien valide

```
# curl -I https://faq.demarches-simplifiees.fr/collection/1-administrateur-creation-dun-formulaire
HTTP/1.1 200 OK
…etc
```

**Comment by kemenaran** [comment]
Moui, ça serait une idée ; genre une tâche rake ça a l'air pas mal.

Après, well, pour les soucis récents, le lien invalide vers la catégorie, c'est parce que je venais de modifier le nom de la catégorie en prod – et qu'en vérifiant je me suis rendu compte que ça modifiait le slug aussi ^^

Et pareil pour l'article en brouillon : c'est parce que ce n'était pas une fonctionnalité activée encore, donc c'était pas grave.

Du coup, à vue de nez, je me dis que tester les liens externes ne serait pas le meilleur retour sur investissement – mais si ça semble pertinent à des gens, pourquoi pas, allez.

**Comment by Keirua** [comment]
À la réflexion c'est vrai que c'est pas un problème pressant, et en cas de problèmes:
 - les usagers peuvent retrouver le bon lien via l'arborescence de la doc
 - on aura au pire des remontées support, mais vu le volume/fréquence ça vaut le coût d'accepter une résolution a posteriori.
