### ISSUE TITLE
Définir et annoncer une date de fin de support pour IE 11

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#5189]

**Comment by Keirua** [comment]
on se dit que la fin du support sera pour la fin d'année/début 2021

**Comment by kemenaran** [comment]
La date de fin de support d'Internet Explorer 11 a été fixée au 31 janvier 2021. Cette date est maintenant mentionnée dans la bannière de dépréciation.

On peut maintenant annoncer cette date dans la newsletter, et sans doute aussi par un mail personnalisé aux admins et instructeurs qui utilisent encore IE 11.
