### ISSUE TITLE
ETQ administrateur, je veux pouvoir informer mon DPO de la création d'une démarche

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#5281]
Aujourd'hui, les administrateurs peuvent informer leur DPO mais cela leur demande de créer un mail, et mettre le lien vers la procédure de test, par exemple. Pas optimal.

Il s'agit de faciliter cette saisine, et en profiter pour parfaire notre conformité avec le RGPD.

Proposition:

Rajouter obligatoirement dans le volet service, le mail du DPO et son numéro de téléphone

Faire en sorte de mettre un bouton lors du passage en test d'une procédure qui envoie un mail générique d'alerte du DPO, avec le lien vers le formulaire de test.

Ce mail n'est pas obligatoire, et reste à la main de l'administrateur.

**Comment by kemenaran** [comment]
Proposition re-discutée collectivement :

> Ajouter un bouton "Informer mon DPO" dans le tableau de bord admin (à côté du paragraphe qui parle déjà du DPO). Quand on clique sur ce bouton, un email automatisé standard est envoyé au DPO.
