### ISSUE TITLE
ETQ Admin, je veux voir les détails d'un démarche dans la nouvelle interface

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#5287]
Convertir la page de détails d'une démarche dans la partie Admin vers la nouvelle interface.

**Comment by kemenaran** [comment]
Les mockups sont sur Zeplin : https://app.zeplin.io/project/58d91c6f824616263cb8b508/dashboard?tag=Admin

Essentiellement ça ressemble à ça (sans tous les détails) :

<img width="768" alt="Capture d’écran 2020-06-23 à 11 54 58" src="https://user-images.githubusercontent.com/179923/85389988-76957300-b548-11ea-9ce5-d3a46d1c4620.png">

Chque pavé redirige ensuite vers les différentes pages qui existent déjà (ancienne ou nouvelle UI).

**Comment by kara22** [comment]
@kemenaran sais-tu ou je peux trouver les accès à Zeplin stp ? Il n'y a pas dans le keypass
