### ISSUE TITLE
Ajouter un tableau de synthese des dossiers en cours sur la page instructeur

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/demarches-simplifiees.fr#5300]
Ajouter un tableau de synthese des dossiers en cours sur la page instructeur. Dans le tableau de synthese, on s'afficher  le nb total de dossier "à suivre", "suivi","traité","dossier","archivé".

**Comment by myriamzbyt** [comment]
![image](https://user-images.githubusercontent.com/20207040/85835355-370f9680-b795-11ea-8282-afef4d30d0d2.png)

Maquette pour le tableau de synthèse des dossiers avec le nombre total de dossiers "à suivre", "suivi","traité","dossier","archivé".

**Comment by kemenaran** [comment]
Ça m'a l'air raisonnable.

Juste quelques remarques :

- Ça vous irait de n'afficher la synthèse que si l'instructeur a plusieurs démarches ?
- Si les items de la section "Synthèse des dossiers" ne sont pas cliquables pour l'instant (en tout cas dans un premier temps), ça serait intéressant d'utiliser un autre style que celui des éléments cliquables juste en dessous, pour ne pas perturber les utilisateurs. Par exemple un badge ?

<img width="977" alt="Capture d’écran 2020-06-26 à 11 43 06" src="https://user-images.githubusercontent.com/179923/85843905-38938b80-b7a2-11ea-9966-7ac5d352f53d.png">

**Comment by myriamzbyt** [comment]
Suite à vos remarques : 
- la synthèse s'affiche si l'instructeur a plusieurs démarches
- les items de la section "synthèse" sont de type badge, avec une autre couleur que la couleur des badges pour les démarches en test : 

![image](https://user-images.githubusercontent.com/20207040/85994759-8acdea00-b9f8-11ea-8d3f-2c61bb8369cc.png)
