### ISSUE TITLE
Type de champ : Trouver un libelle plus explicite pour 'Texte' et 'Zone de Texte'

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#533]

**Comment by gregoirenovel** [comment]
Y'a pas "texte court" et "texte long" dans les design de Marine ?

**Comment by LeSim** [comment]
Peut être, je n'arrive pas a accéder a invision pour l'instant.

**Comment by emsnytech** [comment]
Texte court et texte long est OK pour moi
