### ISSUE TITLE
ETQ Ops je souhaite changer l'URL de la Status Page

### ISSUE THREAD

**Issue by mfaure** [betagouv/demarches-simplifiees.fr#5379]
**Décrivez le bug**

[L'URL de la Status Page](https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/config/initializers/urls.rb#L29) est écrite en dur dans le code, et n'est pas configurable.

Lorsqu'on installe sa propre instance DS (par exemple celle de l'Adullact), l'utilisateur voit le statut de l'instance de la Dinum au lieu de celle de l'Adullact.

**Comportement attendu**

Rendre configurable l'URL de la Status Page

Note : une PR est dans les tuyaux :)

**Comment by dzc34** [comment]
> une PR est dans les tuyaux :)

fichier `config/initializers/urls.rb `
```diff
- STATUS_PAGE_URL = "https://status.demarches-simplifiees.fr"
+ STATUS_PAGE_URL = ENV.fetch("STATUS_PAGE_URL", "https://status.demarches-simplifiees.fr")
```
Fichier `config/env.example`
```diff
+ # Personnalisation d'instance - Page externe "Disponibilité" (status page)
+ # STATUS_PAGE_URL=""
```
