### ISSUE TITLE
ETQ usager, je ne souhaite pas pouvoir entrer un numéro de téléphone invalide

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#5416]
Aujourd'hui, la validation des numéros de téléphone se fait uniquement [au niveau du navigateur](https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/app/views/shared/dossiers/editable_champs/_phone.html.haml).

Nous pourrions peut-être avoir une validation au niveau du modèle (`app/models/champs/phone_champ.rb`), pour éviter de sauvegarder des numéros de téléphone incorrect, pour ceux qui ont des vieux navigateurs et peuvent passer outre. C'est utile par exemple pour les démarches qui sont intégrées avec des outils d'appel, et qui ont donc besoin d'avoir des numéros valides.

HS 51277

**Comment by krichtof** [comment]
Actuellement, la validation au niveau du navigateur a le comportement suivant.

- Elle autorise d'avoir 2 numéros de tel, par exemple : `0123456789 0123456789` ou encore `01.23.45.67.89 01.23.45.67.89` ce qui pose problème par les logiciels d'appels mentionnés par @Keirua 

- Elle interdit `3646` alors que c'est le tel du centre contact de l'assurance maladie

- Elle autorise les numéros `0035 123-456-789` `+2 123456789` ou encore `01234567890` qui ne sont pas des numéros de tel français valides.

La gem phonelib (déjà utilisée dans DS pour la validation du téléphone du service d'une démarche), utilisée côté serveur, pourrait interdire d'avoir 2 numéros de tel, accepter les numéros spéciaux à 4 chiffres et interdire les 3 numéros de tel mentionnés ci-dessus qui ne sont pas valides.

Il faudrait également par souci de cohérence modifier les règles de validation côté navigateur.

Vous êtes chaud pour passer à phonelib @kemenaran @LeSim @kara22 @jpoulvel ?

**Comment by kemenaran** [comment]
J'avoue, tu vends bien phonelib :) Si tu penses que c'est le mieux, moi ça me va 👍 

Juste, quand tu dis _"+2 123456789 ou encore 01234567890 qui ne sont pas des numéros de tel français valides"_ : on est d'accord qu'on ne requiert pas forcément des numéros de téléphone français ? Si quelqu'un veut donner un numéro allemand ou tunisien, ça marche aussi ? (Pour les démarches destinées aux étrangers, par exemple)

Et aussi, tu veux dire quoi par "modifier la validation côté client" ? On ne va pas vraiment pouvoir intégrer phonelib sur le client, non ?

**Comment by krichtof** [comment]
> Juste, quand tu dis "+2 123456789 ou encore 01234567890 qui ne sont pas des numéros de tel français valides" : on est d'accord qu'on ne requiert pas forcément des numéros de téléphone français ? Si quelqu'un veut donner un numéro allemand ou tunisien, ça marche aussi ? (Pour les démarches destinées aux étrangers, par exemple)

Je me suis mal exprimé. 
- `+2 123456789`est un numéro international non valide
- `01234567890` est un numéro local français non valide

On peut donner un numéro de tel allemand ou tunisien pour peu que l'utilisateur le préfixe avec l'indicatif adéquat, par exemple `+49 2109 87654321`est valide

> Et aussi, tu veux dire quoi par "modifier la validation côté client" ? On ne va pas vraiment pouvoir intégrer phonelib sur le client, non ?

Pour l'instant, je n'ai pas d'idée arrêtée sur le "comment". Actuellement, il y a uniquement une validation côté client. Et si on ajoute une validation côté serveur, le mieux, c'est que les règles de validation soient identiques côté serveur et côté client. Or, comme indiqué plus haut, certains numéros sont refusés avec la validation actuelle côté client, et acceptés avec phonelib côté serveur (exemple `3646`), et inversement.

Le premier pas le plus simple serait peut-être de virer la validation côté client ?

Ou sinon chercher une lib javascript qui fait le job (pour l'instant, je n'en connais pas)

**Comment by kemenaran** [comment]
Pour les libs en javascript, y'en a sûrement, mais ça va nous faire une grosse dépendance, et un poids non négligeable dans la page.

Je dirais bien "Sur le client on fait une validation aussi légère que possible (pas de lettres par exemple), et on laisse le serveur faire la validation complète", tu en penses quoi ?

(Ou alors un remote-form, éventuellement, pour valider côté serveur mais au fil de la saisie)

**Comment by krichtof** [comment]
> Je dirais bien "Sur le client on fait une validation aussi légère que possible (pas de lettres par exemple), et on laisse le serveur faire la validation complète", tu en penses quoi ?

J'aime bien cette option :) C'est celle que je vais implémenter
