### ISSUE TITLE
ETQ instructeur, je veux effectuer des contrôles externes sur les données saisies

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#5520]
Nous souhaitons pouvoir introduire des contrôles développés par nos soins sur certaines données saisies par l’usager ou l’instructeur. L’idéal serait que ces contrôles puissent se faire lors de la saisie du formulaire par l’usager et également dans le cadre de l’instruction. Ce peuvent être des contrôles sur une donnée (par exemple la vérification d’une clé de Lhun, la présence du n° RPPS dans le RPPS), à faire si possible à la saisie de la donnée, ou sur un ensemble de données avant l’enregistrement ou la soumission du dossier (contrôle de cohérence entre données saisies ou contrôle par rapport à des référentiels externes sur un groupe de données). En retour, nous souhaiterions pouvoir fournir un message d’erreur qui serait visualisé par l’usager (si le formulaire est en construction) ou par l’instructeur (si le formulaire est en instruction).
Avant que l’usager soumette son dossier, nous souhaitons procéder à ce contrôle d’ensemble qui pourrait être bloquant ou non. L’instructeur doit pouvoir aussi lancer un contrôle et récupérer les erreurs ; notamment lorsqu’il récupère un dossier, il doit avoir connaissance des erreurs (non bloquantes) ainsi qu’avant de finir son instruction.
Une solution a mimima serait de pouvoir, avant de clore l’instruction, lancer un ensemble de contrôles externes sur l’ensemble des données du dossier (récupération des données et traitement par une application externe). Attention il est important que le contrôle puisse être lancé unitairement par l’instructeur sur des dossiers qui ne sont pas encore clos.

**Comment by kemenaran** [comment]
J'ai l'impression qu'il y a deux issues :

1. Usager : valider le dossier au moment de la soumission (et afficher les erreurs à l'usager). 
2. Instructeur : valider le dossier au moment de clore le dossier (et afficher les erreurs à l'Instructeur).

L'essentiel est discuté dans #2239.
