### ISSUE TITLE
ETQ API, je veux pouvoir télécharger les dossiers au format PDF

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#5543]
Des usagers veulent pouvoir récuperer le récapitulatif de la demande par API, pour ne pas devoir faire moitié API moitié interface.

Une solution est de rendre le endpoint de rendu PDF des dossiers accessible aux tokens d'API, quelque chose du genre:

```bash
curl -L \
    --header "Authorization: Bearer some_token" \
    -XGET "http://localhost:3000/procedures/:id/dossiers/:dossier_id.pdf"
```

**Comment by tchak** [comment]
done
