### ISSUE TITLE
Rendre accessible le champ Pièce justificative

### ISSUE THREAD

**Issue by krichtof** [betagouv/demarches-simplifiees.fr#5608]
Le champ pièce justificative n'est pas accessible (gestion du focus, navigation pour suppression, barre de chargement)
depends #5162

**Comment by krichtof** [comment]
@tchak et moi, après test via Voiceover, n'avons pas rencontré de problème de gestion de focus, ni de navigation pour suppression.

Une idée plus précise de ce qui pêche côté accessibilité sur le champ PJ ? poke @Keirua

**Comment by Keirua** [comment]
Les détails supplémentaires sur ce qui posait problème sont dans le retour d'audit détaillé. En l'occurence, je t'ai fait suivre le mail en question.

**Comment by krichtof** [comment]
A propos de la barre de téléchargement, extrait de l'audit :

> Il n'y a aucune information de progression pour les utilisateurs aveugles notamment ;
>
> Corrections
>
> - Implémenter le modèle de conception "progressbar" :
>   - Implémenter sur l'élément
       - un role="progressbar" ;
       - un tabindex="-1" ;
       - une propriété aria-valuemin="0" ;
       - une propriété aria-valuemax="100" ;
       - Une propriété aria-valuenow="[valeur instantanée dynamique]".
     - Tant que le travail est en cours, modifier la valeur aria-valuenow avec JavaScript, par exemple toute les 0,3 seconde.
     - A l'affichage de la barre de progression donner le focus sur l'élément ayant l'attribut tabindex="-1" ;
     - Lorsque le travail est terminé, repositionner le focus sur le bouton permettant de supprimer le téléchargement.

**Comment by krichtof** [comment]
A propos de la gestion du focus : 

> Lorsqu'un utilisateur clique sur le bouton "remplacer" un champ de téléchargement est ajouté dans le contenu mais le focus est maintenu sur le bouton "remplacer".
>
> Correction
> 
> Repositionner le focus sur le bouton de téléchargement ajouté.

**Comment by krichtof** [comment]
A propos de la suppression : 

> Remplacer le lien "supprimer" associé au téléchargement par un bouton ou utiliser le modèle de conception ARIA "button" : https://www.w3.org/TR/wai-aria-practices-1.1/#button

> un bouton implémenté sous la forme d’un lien qui déclenche une action de la page risque de perturber l’utilisateur qui s’attendra au chargement d’une nouvelle page.
> De manière générale, les liens ( <a href="url.htm"> ) devraient être réservés à l’affichage d’une nouvelle page ou la création de liens d’accès rapide dans le contenu ( <a href="#contenu"> ). Dans tous les autres cas, l’emploi d’un bouton d’action ( <button> , <input type="button"> ) est plus pertinent.
