### ISSUE TITLE
ETQ developpeur, je veux pouvoir merger des PRs plus rapidement

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#5626]
Pour merger une PR actuellement, il faut:
 - ouvrir une PR vers `dev`
 - passer tous les tests CI
 - avoir une validation par un reviewer

Une fois que c'est bon, il faut rebaser sa branche sur `dev`, repasser la CI, puis merger.

Si quelqu'un d'autre merge une branche entretemps, il faut recommencer. On a de plus en plus souvent pas mal de PRs en cours, en particulier dès qu'il y a des bugfixes à faire passer devant le reste, et passer du temps à regarder la CI se dérouler est sous-optimal. Avec l'introduction de `dependabot` pour mettre plus souvent à jour les dépendances, si on conserve cet outil, le problème ne va pas s’améliorer.

**Comment by Keirua** [comment]
Première solution testée il y a quelques temps: `bors`, utilisé dans la communauté rust.

problème: pas de rebase, et [pas prévu d'en prévoir](https://forum.bors.tech/t/rebase-a-pull-request/290).

**Comment by Keirua** [comment]
J'ai testé 2 github-actions pour merger des PRs, sur un projet à moi:

 - [merge-bot](https://github.com/marketplace/actions/pr-merge-bot)
 - [autosquash](https://github.com/marketplace/actions/autosquash)

**autosquash** est cool (fonctionne direct). Par contre… il squash, donc on perd notre historique. Leur [raisonnement](https://github.com/marketplace/actions/autosquash#why-squash-and-merge) (github est orienté merge, et quand on revert,on revert toute une PR) me va.

Pas réussi à faire fonctionner **merge-bot** :( ça parait prometteur, mais la doc pas à jour, je pense avoir trouvé comment corriger mais le job qui indique qu'il a terminé mais qui merge pas. Dommage, car c'est le seul que j'ai trouvé qui permet de rebase. C'est peut-être un problème de droits de token, mais rien dans les issues à ce sujet.

Niveau sécu, dans tous les cas, on notifie un serveur tiers qui a des droits de merge sur le repo. Github action étant relativement récent, les actions ont peu de commits et d'issues, c'est pas forcément rassurant. Mais ! ce n'est pas forcément un problème non plus, on peut se dire que ces actions n'ont pas lieu de bouger beaucoup une fois mises en place.

**Comment by LeSim** [comment]
je comprends le besoin, on perd pas mal de temps la dessus.

J'aime bien avoir la branche non squashé, ca permet de relire plus facilement (on se donne déjà du mal pour faire des commits atomiques).

Pour ce qui est de donner des droits d'écriture au repo à un tiers, je trouve ca casse gueule. Je sais pas si on aurait moyen de prouver qu'il n'y a pas eu d'altération.

**Comment by Keirua** [comment]
Ça me va de continuer à garder les branches non-squashées, et je vois bien le problème des droits d'écriture.

Option à tester: rester sur du github natif, et [activer la possibilité de `rebase and merge`](https://github.com/betagouv/demarches-simplifiees.fr/settings)

![image](https://user-images.githubusercontent.com/1223316/94277417-d0dc1080-ff49-11ea-9d43-0b3db13f1908.png)

**Comment by kemenaran** [comment]
Maintenant on a une commande /rebase qui fonctionne bien, et un "Enable auto-merge" : j'ai l'impression que la douleur n'a pas disparu, mais devient acceptable.

Je ferme pour l'instant.
