### ISSUE TITLE
ETQ instructeur, je veux que mon tableau de bord s'affiche vraiment très vite.

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#5659]
Dans https://github.com/betagouv/demarches-simplifiees.fr/pull/5559, on a amélioré les performances en faisant moins de requêtes, et on avait remarqué que l'essentiel de temps de calcul de la page avait lieu dans les requêtes de count.

Il se trouve qu'on peut aller encore plus loin en [groupant les nombreux count en une unique requête SQL](https://www.depesz.com/2013/07/23/waiting-for-9-4-implement-the-filter-clause-for-aggregate-function-calls/). Chez nous, ça donnerait un truc du genre:

```sql
SELECT
      groupe_instructeurs.procedure_id,
      procedures.libelle,
      COUNT(*) FILTER ( WHERE "dossiers"."state" in ('en_construction', 'en_instruction') and "follows"."id" IS NULL and not "dossiers"."archived" ) AS a_suivre,
      COUNT(*) FILTER ( WHERE "dossiers"."state" in ('en_construction', 'en_instruction') and "follows"."instructeur_id" = 741 and not "dossiers"."archived" ) AS suivis,
      COUNT(*) FILTER ( WHERE "dossiers"."state" in ('accepte', 'refuse', 'sans_suite') and not "dossiers"."archived" ) AS termines,
      COUNT(*) FILTER ( WHERE "dossiers"."state" != 'brouillon' and not "dossiers"."archived" ) AS total,
      COUNT(*) FILTER ( WHERE "dossiers"."archived" ) AS archived
  FROM
      "dossiers" 
  INNER JOIN
      "groupe_instructeurs" 
          ON "dossiers"."groupe_instructeur_id" = "groupe_instructeurs"."id" 
  INNER JOIN
      "assign_tos" 
          ON "groupe_instructeurs"."id" = "assign_tos"."groupe_instructeur_id" 
  INNER JOIN
      "procedures" 
          ON "groupe_instructeurs"."procedure_id" = "procedures"."id" 
  LEFT OUTER JOIN
      "follows"
          ON "follows"."dossier_id" = "dossiers"."id"
  WHERE
      "dossiers"."hidden_at" IS NULL 
      AND "assign_tos"."instructeur_id" = 741 
  GROUP BY
      groupe_instructeurs.procedure_id, procedures.libelle
```

…je laisse ça dans un coin pour quand on aura le temps de creuser la question: hardcoder un monstre pareil c'est pas fou, et on est pas encore sûr de l'impact positif sur les performances.

**Comment by Keirua** [comment]
(chapeau à @sim pour l'investigation)

**Comment by kemenaran** [comment]
J'ai l'impression qu'on a codé ce qu'on a pu là dessus, et que le reste n'est pas actionnable directement. Je ferme pour l'instant.
