### ISSUE TITLE
Mieux expliquer le fonctionnement du suivi des dossiers dans l'UI

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#566]

**Comment by kemenaran** [comment]
Trop vague ; je ferme. À rouvrir si on a des retours usagers précis.

**Comment by gregoirenovel** [comment]
Je précise alors : on en comprend rien à suivi / pas suivi (ce que ça fait), des instructeurs trouvent des comptes de dossiers sur une démarche dont les totaux ne matchent pas (ce qui est normal étant donné ce qu'on leur affiche)

À minima :
- rajouter un onglet "dossiers suivis par d'autres"
- expliquer pour chaque onglet instructeur ce qu'il contient
- expliquer que quand on passe un dossier en instruction il est automatiquement suivi
