### ISSUE TITLE
ETQ Super Admin, je veux pouvoir diagnostiquer (et débloquer) des envois de mails ratés plus rapidement

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#5660]
inspecter directement depuis le manager l'état des derniers mails envoyés, ou rapidement aller dans le prestataire mail pour cet utilisateur et éventuellement le débloquer.

**Comment by kemenaran** [comment]
On a maintenant un beau tableau de bord pour ça dans le Manager, avec accès aux emails SendInBlue et Mailjet.
