### ISSUE TITLE
diminuer le bruit des mauvais retours api entreprise

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#5675]

**Comment by Keirua** [comment]
2 option à tester:
 - jouer sur la conf de [`retry_on`](https://edgeapi.rubyonrails.org/classes/ActiveJob/Exceptions/ClassMethods.html#method-i-retry_on) pour attendre plus longtemps avant le premier essai lors des erreurs HTTP
 - mettre une validation soft du format de token API entreprise : on peut rentrer ce qu'on veut, mais lorsque le token semble invalide afficher un gros message rouge coté administrateur sur l'écran de la démarche et l'inciter à corriger le tir

**Comment by Keirua** [comment]
Autre élément: on a parfois des 503

**Comment by Keirua** [comment]
Autre élément: on a parfois des 503 dans `ApiEntreprise::AttestationSocialeJob`, qui fait un appel sur `https://entreprise.api.gouv.fr/v2/attestations_sociales_acoss/:id`.

```
{"errors":["L'ACOSS ne peut répondre à votre requête, réessayez ultérieurement (erreur: La situation du compte ne permet pas de delivrer l'attestation demandee.)"]}
```
```
body: {"errors":["L'ACOSS ne peut répondre à votre requête, réessayez ultérieurement (erreur: Analyse de la situation du compte en cours.)"]}
```

Il faut peut-être voir:
 - si "réessayer plus tard" a une chance d'aboutir (indisponibilité temporaire de l'information), on peut sans doute éviter de déclencher une erreur immédiatement
 - si ça n'a aucune chance d'aboutir, on doit pouvoir virer le job et de ce fait, les notifications d'erreurs

**Comment by Keirua** [comment]
# Question (concernant le point au dessus)

La doc parle juste d'une indisponibilité temporaire, mais avec les messages (surtout le second), on ne comprend pas trop du coup si c'est:

 - une indisponibilité du service temporaire (le service tiers qui vous fournit l'info est KO un moment). -> vous conseillez quel timing ?
 - une indisponibilité temporaire de la réponse (le service tiers doit calculer un truc pas immédiat à obtenir)  -> vous conseillez quel timing ?
 - si ça n'a aucune chance d'aboutir (ex: siren pas concerné) -> on pourrait arrêter de vous solliciter pour le siren en question

# Réponse 
(philippe)
Le pb, si cela fonctionne toujours comme quand on l’a mis en place , c’est que ce n’est pas parce que la pj n’est pas disponible qu’elle ne peut pas l’être qques heures plus tard.
En effet une demande de pj, quand elle est ko génère chez eux une demande d’actualisation qui peut nécessite une intervention d’un agent. Aussi, la nièce est rendu disponible qques temps plus tard .
Je ne me rappelle plus comme on avait fait avec mps mais on refaisait plusieurs appels que 3 jours ....
(alexandre, d'api entreprise)
Malheureusement nous n’avons pas d’informations concernant le timing exact (en imaginant que l’ACOSS en ait un à fournir). Par contre il ne s’agit pas du cas numéro trois, si la société était inconnue du service tu aurais un autre message d’erreur explicite.

# ma conclusion
j'ai l'impression que concernant ces erreurs 503, il faut ne pas déclencher d'erreur chez sentry, mais augmenter le temps de relance avant d'aller chercher à nouveau l'info.

**Comment by LeSim** [comment]
Voici les erreurs ayant eu lieu ces dernières 24h

- dgfip
  - attestations_fiscales
    - { code: 0, body: vide, nb: 16 }
  - exercices
    - { code: 0, body: vide, nb: 19 }
    - { code: 503 indiponible. nb: 1 }
    
- acoss
  - attestations_sociales
    - { code: 502, body: ... réessayer ultérieurement ..., nb: 72 }

- rna
  - association
      - { code: 0, body: 0, nb: 39 }
      - { code 503, nb: 1 } 

- bdf 
  - bilan entreprise
    { code: 502, body: erreur interne, nb: 25 }

**Comment by kemenaran** [comment]
Je ferme l'issue pour l'instant ; on ré-ouvrira au besoin.
