### ISSUE TITLE
amélioration des performances de Instructeur::ProceduresController#show

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#5689]

**Comment by kemenaran** [comment]
Y'a eu des améliorations, mais une partie a été revertée à cause d'un bug mineur. Il faudrait regarder pourquoi ça coinçait, et relancer la PR.

**Comment by kemenaran** [comment]
Il y a des améliorations mises dans #6079.

@LeSim Est-ce qu'on garde cette issue ouverte, ou on peut fermer pour l'instant ?
