### ISSUE TITLE
ETQ INSTRUCTEUR, je veux pouvoir supprimer un dossier depuis mon interface

### ISSUE THREAD

**Issue by kara22** [betagouv/demarches-simplifiees.fr#5720]
- [ ] Logique coté instructeur

- [ ] Logique coté usager

**Comment by kara22** [comment]
Les instructeurs doivent pouvoir supprimer un dossier qui a reçu une décision finale, et ce, depuis leur interface.


Pourquoi cette feature ?  :  ❓

Qui l'a demandée ?  : ❓

Va  t-elle améliorer l'expérience utilisateur (instructeur OU usager OU administrateur) et pourquoi ? : ❓



**Conséquences sur l'instructeur :** 

- Le bouton "supprimer le dossier" ne doit être visible uniquement si le dossier à reçu une décision finale (accepté / refusé)
- Une alerte demande à l'instructeur si il est sur et certain de vouloir supprimer le dossier et que l'action est irréversible
- Le dossier se supprime de son interface ET de la DB 🤔  (ou alors juste un dossier.discard ) ?
- Un email envoyé pour lui confirmer qu'il a bien supprimé le dossier avec en PJ le dossier en question 🤔  ?


**Conséquences sur l'usager :** 

- Le dossier en question se supprime de son interface ET de la DB 
- Un email est envoyé pour lui indiquer que suite à la décision de l'instructeur, son dossier est supprimé. En PJ son dossier en PDF  🤔 ?

**Comment by LeSim** [comment]
Yes, excellent ce début.

> Pourquoi cette feature :
- légal : minimisation des données perso conservées sur ds
- sécu : minimisation des données hackable

> Qui l'a demandée ?
- légal & sécu

> va-t-elle améliorer l'exp
- compliqué :)

> **Conséquences sur l'instructeur**

> - décision final c.a.d (accepté / refusé / **sans suite**)
> - l'alerte propose le téléchargement du fichier avec pj sans cni et indique qui a téléchargé le dossier et quand
> - le dossier se supprime de son interface ET de la DB et des logs fonctionnels (DossierOperationLog).

et avant on enregistre un événement dossier_supprimé `DeletedDossier` avec qui a fait l'action / quand / dossier id / etat final du dossier / procedure (groupe_instructeur_id ou révision ?).

Il faut également :
- créer les relations : un usager a plusieurs dossiers supprimés et un groupe instructeur (révision ?) à des dossiers supprimés.
- afficher sur le tableau de bord du groupe instructeur le dossier supprimé

> - Un email envoyé pour lui confirmer qu'il a bien supprimé le dossier avec en PJ le dossier en question

On ne peut pas passer le dossier en PJ car le canal n'est pas confidentiel, on peut rajouter le lien du téléchargement dans l'alerte

> **Conséquences sur l'usager :**
> - Le dossier en question se supprime de son interface ET de la DB
- afficher sur le tableau de bord usager les dossiers supprimés

> - Un email est envoyé pour lui indiquer que suite à la décision de l'instructeur, son dossier est supprimé. En PJ son dossier en PDF thinking ?

L'email ok mais on ne peut pas envoyer le dossier en pj non plus.

**Question :**
Lors de la suppression, on peut garder une version pdf + pj du dossier pour le remettre plus tard à l'usager.

Pour :
- l'usager peut le télécharger pour garder une trace de son action.

Contre :
- Je ne connais pas la valeur juridique de ce document qui pourrait très bien être contrefait.
- Prolonge encore la conservation des données.
- Complexifie le workflow en ajoutant une donnée à supprimer dans x jours.
- Dans le monde physique, je ne suis pas sûr qu'on rende le dossier à l'usager

Pour l'instant, je suis défavorable à garder une version pdf à destination de l'usager.

**Comment by kara22** [comment]
Les instructeurs doivent pouvoir supprimer un dossier qui a reçu une décision finale, et ce, depuis leur interface.


Pourquoi cette feature ?  
- légal : minimisation des données perso conservées sur ds
- sécu : minimisation des données hackable

Qui l'a demandée ?  : légal & sécu

Va  t-elle améliorer l'expérience utilisateur (instructeur OU usager OU administrateur) et pourquoi ? : compliqué :)

**Conséquences sur les relations** 

 - un usager a plusieurs dossiers supprimés
 - un groupe instructeur (révision ?) a plusieurs dossiers supprimés


**Conséquences sur l'instructeur :** 

- Le bouton "supprimer le dossier" ne doit être visible uniquement si le dossier à reçu une décision finale (accepté / refusé / sans suite)
- Une alerte demande à l'instructeur si il est sur et certain de vouloir supprimer le dossier et que l'action est irréversible et propose le téléchargement du fichier avec pj sans cni et indique qui a téléchargé le dossier et quand
-  Enregistrer un événement dossier_supprimé DeletedDossier avec qui a fait l'action / quand / dossier id / etat final du dossier / procedure (groupe_instructeur_id ou révision ?).
- Le dossier se supprime de son interface ET de la DB et des logs fonctionnels (DossierOperationLog).


**Conséquences sur l'usager :** 

- Afficher dans son interface les dossiers supprimés
- Un email est envoyé pour lui indiquer que suite à la décision de l'instructeur, son dossier est supprimé.

**Comment by tchak** [comment]
Super. Je n’ai pas trop à redire sur le cadrage fonctionnel - j'ai l'impression que vous avez bien avancé.

Sur le plan plus technique : la suppression de dossiers terminés est déjà en grande partie implémentée dans `ExpiredDossiersDeletionService`. Il manque la suppression des `DossierOperationLog`, mais sinon il y a largement de quoi s’inspirer.

Il y a un soucie avec l'enregistrement des événements. Nous enregistrons déjà un événement `supprime` dans les `DossierOperationLog` et l’on peut ajouter les événements de téléchargement de dossier. Mais ça ne sert à rien si l’on supprime les `DossierOperationLog` d'un dossier. Ou alors l'idée c'est de remplacer la stack des événements du dossier par les événements de téléchargement et de suppression ? Ou alors on ne supprime pas les événements `supprime` et `telecharge` ? À réfléchir.

**Comment by LeSim** [comment]
Philippe suggère : 

- dans la donnée résiduelle que l'on présente à l'usager et à l'administration, on ne montre pas l'état final du dossier mais juste dossier traité et la date de traitement.

- interrogation pour savoir si on garde le pdf pour l'usager ou pas.

**Comment by kara22** [comment]
Suite à point avec l'équipe : 

- Supprimer tous les évènements dans DossierOperationLog et ajouter par la suite l'évènement supprimé avec le dossier_id
- Afficher l'état du dossier coté usager🔥
- Ne pas enregistrer le log de téléchargement (dans une autre story)
- relations : user_id et groupe_instructeur_id et revision_id dans la table "deleted_dossiers" pas de foreign key

**Comment by kara22** [comment]
Trois dates clés: date de dépôt, date de passage en instruction, date de décision....

Donc j'en conclut qu'il ne faut pas supprimer les dossier_operations_logs ET ajouter un lors du dépôt de dossier de l'usager

**Comment by tchak** [comment]
Ou alors il faut écrire ces trois dates dans le log de suppression
