### ISSUE TITLE
MinArm | En tant qu'instructeur, je veux pouvoir définir pour chaque personne impliquée, si elle doit être notifiée de la décision finale

### ISSUE THREAD

**Issue by R-Wann** [betagouv/demarches-simplifiees.fr#5731]
Ajout d'un checkbox en face de chaque mention d'un acteur du dossier, permettant à l'instructeur de définir si cet acteur doit être notifié par email ou pas de la décision finale.

Proposition de révision l'UI de l'onglet, tenant compte de la possibilité de certaines organisation d'intégrer de nouveaux rôles :
⇨ Listage des rôle par système accordéon, une section par rôle et grande action.
⇨ titre de section variable selon nb d'acteurs concernés 
![DS-Evol_Personnes_impliquées](https://user-images.githubusercontent.com/61140187/98695205-aa93f800-2372-11eb-8f77-998c69d8d48c.jpg)

**Comment by LeSim** [comment]
2ieme itération :

ETQ admin, je peux voir l'ensemble des experts nommés sur ma démarche
ETQ admin, je peux ajouter/supprimer des experts qui seront notifiés de la décision finale sur le dossier
ETQ instructeur, je peux sélectionner des experts choisit par l'admin dans mon dossier
ETQ instructeur, lorsque je termine un dossier, les experts notifiable recoivent un mail (batch journalier ?) leur indiquant qu'une nouveauté est présente.
ETQ expert notifiable, je vois l'état final du dossier sur mon interface

**Comment by kara22** [comment]
Merci @LeSim

Ca voudrait dire que pour tous les dossiers d'une démarche, les experts seront notifiés si l'instructeur ne fait pas le checking. 

Quelques questions supplémentaires : 

- Est-ce que la notification doit être désactivée par défaut et l'instructeur doit refaire une passe (par dossier) afin de choisir qui notifier dans la liste ? (ça rajoute du boulot)

- L'administrateur prépare une liste d'experts, mais l'instructeur peut supprimer quelques experts ou tous les experts de ces notifications de décision ? Mais il ne peut pas en ajouter.

- Si l'expert choisi par l'administrateur n'a finalement pas eu à donner son avis sur le dossier, est-ce qu'il doit quand même avoir une notification de décision ?

**Comment by R-Wann** [comment]
@kara22 : 
La liste des experts créées par l'admin doit être vue comme un référentiel, spécifique à la démarche, et dans lequel, un instructeur vient sélectionner l'expert qu'il veut solliciter. 
Seuls les experts qui seront intervenus sur le dossier seraient notifiés. 
@LeSim : ta première description peut laisser comprendre l'admin peut désigner dans la liste les experts à notifier, de ce qui n'ont pas à l'être. Le vois-tu comme ça ou tous les experts sollicités depuis la liste et étant intervenus sont systématqiuement notifiés ?

**Quelques idées fonctionnelles complémentaires (peut-être en itération ultérieure, et selon retours utilisateurs) :**
- La possibilité pour l'instructeur de sélectionner n experts dans sa liste, pour solliciter plrs experts en parallèle 
- La possibilité pour l'admin d'ajouter un libellé/description à l'adresse email de chaque expert dans sa liste, et qui servirait à l'instructeur comme une aide avant la sélection d'un expert (exemple : nom de l'entité d'appartenance de l'expert...)

@kara22 :
premier niveau de réponse à tes questions
_Question 1 :_ je dirais que c'est l'admin qui prédéfinit quels experts peuvent être notifiés lorsqu'il implémente la liste, si il peut faire ce paramétrage. Sinon par principe, un expert de la liste, s'il intervient sera notifier (cf. question ci-dessus à LeSim)
_Question 2 :_ si la liste d'experts est vue comme un référentiel, l'instructeur choisit un expert dans la liste (ou n experts ?). 
Le fait que l'instructeur puisse ajouter un expert à la liste me semble discutable si on décide que cela est du rôle de l'administrateur. Je verrai plutot le fait que chaque admin doive prévoir prévoir process/démarche de demande d'un ajout d'un expert...
_Par contre conserve-t-on en parallèle, au moins dans un premier temps, les modalités actuelles de sollicitation d'un expert par l'instructeur ? ⇨ sans ça on risque de bloquer le traitement de certains dossiers, tant que les admin n'auront pas créé et géré leur liste... Ces expert n'auraient pas à être notifiés, comme actuellement._
_Question 3 :_ pour moi : non, surtout si on part du principe que la liste d'expert est une forme de référentiel interne d'experts pour l'instructeur

NB : j'ai pu échanger avec quelques utilisateurs : Ok pour eux sur ce ppe, surtout vu du côté RGPD !

**Comment by kara22** [comment]
@R-Wann merci pour les précisions.

pour répondre à ta question : 

> _Par contre conserve-t-on en parallèle, au moins dans un premier temps, les modalités actuelles de sollicitation d'un expert par l'instructeur ? ⇨ sans ça on risque de bloquer le traitement de certains dossiers, tant que les admin n'auront pas créé et géré leur liste... Ces expert n'auraient pas à être notifiés, comme actuellement._

Je dirais que du coup pour cette feature on partirait sur un feature flag ? Car je ne sais pas si tous les administrateurs sont prêts à remplir un référentiel d'experts par démarche, cela ferait un très gros changement dans le process. Est-ce que vous supportez les features flag dans votre branche ?
Qu'en pensez-vous @emsnytech @LeSim @tchak @krichtof ?

**Comment by R-Wann** [comment]
Ok pour moi pour une feature flag

**Comment by R-Wann** [comment]
Suite au cadrage, le titre de la carte n'est plus exacte. Je propose de renommer la carte "Gestion d'une liste d'experts pouvant être notifiés de la décision finale";

**Comment by kara22** [comment]
Bonjour @R-Wann , 

On s'est rendu compte que la feature est assez complexe du coup on l'a découpé en plusieurs tickets avec le label minarm, tu peux les voir dans la partie priorisé de notre board.

Les voici : 

- ETQ admin, je peux voir l'ensemble des experts nommés sur ma démarche
- ETQ admin, je peux choisir qui sera notifié de la décision finale sur le dossier
- ETQ Admin, je peux ajouter/supprimer des experts notifiables
- ETQ instructeur, je peux sélectionner des experts choisis par l'admin dans mon dossier
- ETQ instructeur, lorsque je termine un dossier, les experts notifiable recoivent un mail leur indiquant qu'une nouveauté est présente.
- ETQ expert notifiable, je vois l'état final du dossier sur mon interface

Je suis en finalisation de la première, ensuite j'enchaine au fur et à mesure, si tu veux qu'on fasse un point n'hésite pas.

**Comment by kara22** [comment]
Bonjour @R-Wann

Nous nous sommes rendu compte que pour cette feature, nous avons besoin de changer la base de données et d'ajouter un modèle Expert.

La difficulté que nous avons rencontrée est de rendre l'expert notifiable, notre modèle de données ne nous permet pas dans l'état de le faire correctement.

Cela va entraîner une migration de la table Avis. En effet, l'avis ne sera plus lié à un instructeur_id. mais à un expert_id.

J'avance dessus et vous tiendrai informé asap

**Comment by R-Wann** [comment]
Bonjour @kara22 
Philippe m'en a parlé. On est en phase. Donc OK pour moi.
je reste dispo pour échnager ou une petite démo préliminaire si tu le souhaites.
