### ISSUE TITLE
Rend accessible le champ Pays

### ISSUE THREAD

**Issue by krichtof** [betagouv/demarches-simplifiees.fr#5756]
Pour rendre accessible le champ Pays, nous allons remplacer `select2` par `@reach/combobox`

Cette issue est une sous-tâche de #4865

**Comment by tchak** [comment]
Aujourd'hui le champ pays est "inline" contrairement aux autres champs (regions, departments, etc.).

En pseudo-code on pourra faire un truc du genre et utiliser notre component search :

```js
async function defaultQueryFn(scope, term) {
  if (scope === 'pays') {
    const pays = await memoize(fetch('/pays.json'));
    return matchSorter(pays, term);
  }
  ...
}
```
