### ISSUE TITLE
Clonage démarche : table types_de_champ, colonne revision_id n'est pas mise à jour pour les sous-champs

### ISSUE THREAD

**Issue by myriamzbyt** [betagouv/demarches-simplifiees.fr#5769]
**Décrivez le bug**
Lors d'un clonage d'une démarche s'il y a des sous champs (exemple des champs dans un bloc répétable), le revision_id n'est pas mis à jour dans la table types_de_champ pour ces derniers (ils gardent l'ancienne valeur de la démarche d'origine).

**Reproduction**
Se connecter en tant qu'administrateur.
Créer une démarche avec un bloc répétable et des champs dans le bloc répétable. Publier la démarche.
Regarder dans la table types_de_champ, tous les champs sont bien créés avec un même revision_id.
Cloner la démarche. Une nouvelle démarche est bien créée.
Regarder dans la table types_de_champ, les nouveaux champs sont créés mais ils n'ont pas le même revision_id.
Notamment les champs dans le bloc répétable ont la valeur de revision_id de la démarche d'origine.

**Appareil et navigateur utilisé**
 - Navigateur : [Firefox, Chrome]

**Comment by R-Wann** [comment]
Anomalie constatée l'équipe DS du MinArm. Présent sur votre release de la semaine dernière
