### ISSUE TITLE
Distinguer la fermeture aux dépots de dossiers de l'archivage pour les procédures

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#579]
La fermeture aux dépots de dossiers et l'archivage sont deux choses différentes. On ne les distingue pas aujourd'hui.

Un des problème est qu'on peut vouloir fermer les dépots de dossier sur une procédure sans pour autant qu'elle soit archivée, ce qui n'est pas possible aujourd'hui.

La fermeture aux dépots de dossiers :
- empeche à quiconque de soumettre un nouveau dossier (pas possible de soumettre un brouillon par exemple)
- change le contenu de la page sur laquelle on arrive en suivant un lien vers une procédure ("Le dépot de dossiers pour cette procédure est désormais terminé")
- peut etre configurée à une date donnée lors de la création de la procédure
- doit pouvoir etre faite manuellement dans l'interface

L'archivage :
- signifie que tous les dossiers de la procédure ont été traités et qu'il n'y a plus rien à faire sur cette procédure
- fait passer une procédure du statut "publiée" au statut "archivée"
  * fait donc passer une procédure, dans l'interface, de la partie "Publiées" à la partie "Archivées"
- ferme le dépot des dossiers s'il n'avait pas été fermé auparavant

- [ ] Rajouter une colonne `fermee_aux_depots_at` à Procedure
- [ ] Renommer `AutoArchiveProcedureWorker` en `AutoFermetureAuxDepotsWorker`
- [ ] Utiliser la colonne `fermee_aux_depots_at` pour `AutoFermetureAuxDepotsWorker`
- [ ] Rajouter un bouton "Fermer les dépots de dossier" sur les procédures publiées
- [ ] Changer le comportement de Procedure#archive : passer le statut en archivé (remplir `archived_at`) mais également fermer le dépot de dossiers si ça n'a pas été fait (remplir `fermee_aux_depots_at`)

**Comment by kemenaran** [comment]
@tchak j'ai l'impression que tu as travaillé là dessus récemment. C'est encore quelque chose à faire ?

**Comment by tchak** [comment]
C'est fait. Pas selon le plan de cette issue, mais le résultat est le même. Je ferme.
