### ISSUE TITLE
Mise en oeuvre Object Storage instance Adullact

### ISSUE THREAD

**Issue by dzc34** [betagouv/demarches-simplifiees.fr#5824]
Bonjour,

Nous avons plusieurs questions pour l'instance Adullact. 
En résumé : comment mettre en oeuvre l'**Object Storage** ?

Nous avons identifié plusieurs points techniques (le proxy, les variables `FOG_*` et `DS_PROXY_*`, etc), mais rien n'est opérant pour nous. Ces points ont certainement déjà été adressés par les autres instances DS comme mes-demarches.gov.pf (@maatinito) et MinArm (@R-Wann / ...).

Si ma compréhension est bonne, @R-Wann, @tchak, @lesim et mon collègue @mfaure étaient présents à la même visio le 26/08/2020, et avaient évoqué une documentation partageable pour la mise en prod d'une instance DS.

Serait-il possible d'échanger ensemble sur ce sujet ? 
Quel moyen d'échange pouvons-nous utiliser (ticket Github, visio, mail...) ? 

----------------------------------

PS: nous aurons aussi d'autres sujets en attente comme les delayed_jobs et les mises à jour, mais dans un deuxième temps :)

/cc @etiquet @pengfeidong

**Comment by mfaure** [comment]
Les fêtes étant passées, je me permets de souhaiter une bonne année et de faire un ping sur le sujet ;)

**Comment by maatinito** [comment]
Je ne sais pas si cela pourra aider mais je mets en place un object storage sur du 3D OutScale (API S3).
J'ai eu d'ailleurs le problème de CORS, résolu par une configuration spécifique de l'object storage (et non de l'instance DS). 
Si cela peut vous intéresser, je reste disponible pour en parler.

**Comment by dzc34** [comment]
> Si cela peut vous intéresser, je reste disponible pour en parler.

oui  nous sommes intéressés pour en parler. 

- par visio (sur notre instance BBB, par exemple)
- par mail ---> `github-ds_contact-tmp@gangler.fr` (mail temporaire)

**Comment by dzc34** [comment]
@maatinito : réponse par mail envoyée

**Comment by dzc34** [comment]
Je ferme ce ticket pour ne pas encombrer inutilement la liste des tickets. La rencontre avec @LeSim  et @tchak nous a apporté quelques pistes intéressantes.

@maatinito nous avons bien reçu votre premier mail et envoyé une réponse. Vous l'avez reçue ?
