### ISSUE TITLE
ETQ Ops, je souhaite personnaliser le logo de pied de page des emails

### ISSUE THREAD

**Issue by dzc34** [betagouv/demarches-simplifiees.fr#5873]
##  Actuellement

Lorsqu'on installe sa propre instance DS sans modifier le code source,
l'image utilisé dans pied de page des emails n'est pas personnalisable.

L'image [ `app/assets/images/mailer/instructeur_mailer/logo-beta-gouv-fr.png`](https://raw.githubusercontent.com/betagouv/demarches-simplifiees.fr/dev/app/assets/images/mailer/instructeur_mailer/logo-beta-gouv-fr.png) 
est écrite en dur dans le fichier [`app/views/layouts/mailers/layout.html.erb`](https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/app/views/layouts/mailers/layout.html.erb#L170)

> ![image](https://raw.githubusercontent.com/betagouv/demarches-simplifiees.fr/dev/app/assets/images/mailer/instructeur_mailer/logo-beta-gouv-fr.png)

### Reproduction

- à partir d'une instance DS personnalisée
- utiliser le formulaire "Mot de passe oublié"
- consulter le message "Instructions pour changer le mot de passe" qui affiche l'image `logo-beta-gouv-fr.png`

![Sélection_025](https://user-images.githubusercontent.com/6709977/106557515-47a19f80-6522-11eb-9c12-4bc7baf8bbfc.png)

## Comportement attendu

Rendre configurable l'image utilisée dans pied de page des emails, via une variable d'environnement optionnelle :
```env
# Personnalisation d'instance - Logo dans le pied de page des emails ---> à placer dans "app/assets/images"
MAILER_FOOTER_LOGO_SRC="custom/logo-mail-footer.png"
MAILER_FOOTER_LOGO_ALT="Adulllact"
```

![Sélection_024](https://user-images.githubusercontent.com/6709977/106557551-5ab46f80-6522-11eb-8db5-70daebdaf09a.png)

## Proposition 

Ajouter au fichier [`config/initializers/images.rb`](https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/config/initializers/images.rb), deux variables d'environnements optionnelle pour cette image et les documenter dans le fichier  [`env.example.optional`](https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/config/env.example.optional).

Fichier `config/initializers/images.rb` :
```ruby
# Mailer logos
...
MAILER_FOOTER_LOGO_SRC = ENV.fetch("MAILER_FOOTER_LOGO_SRC", "mailer/instructeur_mailer/logo-beta-gouv-fr.png")
MAILER_FOOTER_LOGO_ALT = ENV.fetch("MAILER_FOOTER_LOGO_ALT", "Logo Beta Gouv Fr")
```

voir : PR #5874 / @adullact

**Comment by kemenaran** [comment]
Ça m'a l'air raisonnable sur le principe d'avoir des variables de configuration plutôt que d'écraser les fichiers 👍 

Là où j'en suis, c'est que j'ai l'impression qu'au début on ne savait pas trop où on allait avec le fichier de variables d'env optionnelles – mais que maintenant on voit que c'est essentiellement des variables de branding.

Les variables d'env n'ont pas l'air très adaptées à ça :

- C'est pas des secrets qui ont besoin d'être protégés ;
- C'est un peu fastidieux à rajouter à chaque fois (faut faire une modif du .env.example.optional, une modif du fichier Ruby, mettre à jour l'env chez vous).

Bon, ça marche, hein - mais on sent que c'est pas optimal.

Je me demande si une meilleure solution ne serait pas de créer un fichier "config/branding.yml", (sur le modèle des "secrets"), dans lequel on mettrait toutes ces variables de branding.

Sur le même modèle que le .env, seul un fichier `config/branding.example.yml` serait versionné dans git - avec des valeurs par défaut. Le fichier `config/branding.yml` serait lui non-versionné, et donc facilement configurable par les forks.

Ça permettrait d'avoir juste un fichier YML, sans avoir besoin de redéfinir les variables et les valeurs par défaut dans un fichier Ruby. Dans le code applicatif, on ferait juste un truc du genre `Rails.config.branding[:mailer_footer_logo]`, sans indirection supplémentaire.

Vous en pensez quoi ? Ça semblerait pertinent de votre côté ?

**Comment by dzc34** [comment]
Sur le principe, cela ne pose aucun problème pour nous. Notre déploiement (via Puppet) configure le fichier `.env` automatiquement, donc configurer 2 fichiers au lieu d'un, c'est la même chose.

Par contre, si on ajoute une variable dans `config/branding.example.yml`, cela vous oblige t'il à mettre à jour le fichier `config/branding.yml` pour `demarches-simplifiees.fr` lors de la mise en prod d'une nouvelle version ? A moins que l'idée est de charger les variables du fichier `config/branding.example.yml` et ensuite de les surcharger avec les variables présentes dans `config/branding.yml` ?

Si besoin, nous pouvons aider, une fois la mécanique mise en place, pour rapatrier toutes ces variables d'environnements optionnels dans ce fichier `config/branding.example.yml`.

**Comment by maatinito** [comment]
Moi je trouve l'idée très bonne: cela concentre tous les paramétrages dans un fichier, et cela permet de se concentrer sur cette tache etc... 
Je ne vois pas l'interet d'avoir un branding.example. Dans le fork, les imports successifs feront en sorte que l'appli tourne meme si on manque quelque chose, les conflits permettront de voir qu'il y a quelque chose à vérifier, un diff avec la version de la branche dev permettra de voir les différences etc... 
Après c'est peut être parce que j'ai choisi d'avoir des branches spécifiques (masterpf, devpf) que cela permet des imports/comparaisons faciles entre le branding pf et le branding fr.  Je ne sais pas. 
Mais l'idée est très cool et j'en profite pour saluer l'effort 'addulact' : cet effort de paramétrage que j'aurai bien aimé insuffler à l’époque :-)

**Comment by kemenaran** [comment]
Pour l'implémentation d'un fichier YML de branding, l'idée serait d'utiliser cette méthode intégrée à Rails : [Rails custom configuration](https://guides.rubyonrails.org/configuring.html#custom-configuration). 

---

> Par contre, si on ajoute une variable dans config/branding.example.yml, cela vous oblige t'il à mettre à jour le fichier config/branding.yml pour demarches-simplifiees.fr lors de la mise en prod d'une nouvelle version ? A moins que l'idée est de charger les variables du fichier config/branding.example.yml et ensuite de les surcharger avec les variables présentes dans config/branding.yml ?

@dzc34 dans un premier temps je dirais qu'on peut juste avoir un fichier `branding.example.yml` qu'on doit effectivement mettre à jour à chaque fois. Et dans un second temps on pourrait avoir un méchanisme pour charger directement dans l'appli les valeurs par défaut depuis `branding.example.yml`, ça a l'air assez simple.

---

>  Je ne vois pas l'interet d'avoir un branding.example. Dans le fork, les imports successifs feront en sorte que l'appli tourne meme si on manque quelque chose, les conflits permettront de voir qu'il y a quelque chose à vérifier, un diff avec la version de la branche dev permettra de voir les différences etc...

@maatinito je crois que l'idée pour l'adullact est d'éviter autant que possible d'avoir à maintenir des fichiers forkés, et d'être aussi proche de la source que possible. Pour ça, simplement copier le fichier 'branding.yml' au déploiement serait plus simple. Pour toi ça serait un fonctionnement possible ?
