### ISSUE TITLE
Renommage des branches par défaut

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#5876]
D'ici une semaine, nous allons renommer les branches par défaut de ce dépôt. Nous envisageons de renommer :

- La branche par défaut `dev` en `main`;
- La branche `master` en `production`.

Ce renommage fera automatiquement les changements nécessaires sur les PR déjà ouvertes.

## Côté équipe DS

Du côté de l'équipe DS, ça nécessitera juste de mettre à jour nos scripts internes. 

## Côté des forks

Du côté des forks, si vous avez des scripts qui récupèrent les branches dev ou master, ça nécessitera éventuellement de mettre à jour vos scripts (cc @dzc34 , @R-Wann, @maatinito). Cela dit vous n'aurez pas de risque d'erreur silencieuse : si une action de votre part essaie d'accéder à une des anciennes branches, Github vous lèvera une erreur, et vous vous en rendrez vite compte.

Et aussi vous n'êtes pas obligés de faire les mêmes renommages sur vos dépôts forkés. Ça peut aider pour la lisibilité, mais vous pourrez toujours faire des PRs, même en gardant vos noms de branches actuels.

**Comment by dzc34** [comment]
Merci pour les précisions. 

Dans notre cas, nous renommerons les branches sur nos clones
de la même manière quand ce sera effectif sur ce dépôt.

**Comment by kemenaran** [comment]
C'est fait, on a donc bien renommé sur ce repo :

- La branche par défaut `dev` en `main`;
- La branche `master` en `production`.

Sur vos forks en local, vous pouvez renommer les branches de DS avec :

```
git branch -m dev main
git branch -m master production
git fetch upstream
git branch -u upstream/main main
git branch -u upstream/production production
```
