### ISSUE TITLE
Vérifier que les records Procedure sont valides

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#5907]
En ce moment on a en base des records Procedure qui ne sont pas valides au sens Rails.

Les erreurs principales sont :

- Pas de lien vers la délibération
- Content-type invalide

Il faudrait :

- Corriger les erreurs dans notre base
- Éventuellement ajouter un job récurrent qui vérifie que les Procedures sont valides.

**Comment by krichtof** [comment]
J'aurai besoin de précision sur cette story.

Je comptais au 17/02 sur la dev 883 procedures sans lien vers une délib, ni delib attachée

```
Procedure.publiees.where.not(id: ActiveStorage::Attachment.where(name: 'deliberation', record_type: 'Procedure').pluck(:record_id)).where(cadre_juridique: '').count
```

Mais on a un flag juridique_required . Et parmi ces 883 procédures, seules 2 sont invalides (avec le flag juridique_required à true donc)

Et quand je regarde sur sentry, je ne vois pas d'exception lié à des procedures invalides

Du coup, je me pose la question. L'idée, c'est de virer le flag juridique_required? et considérer que toutes les procedures doivent passer le check_juridique?

**Comment by krichtof** [comment]
Il n'y a plus de procédures invalides. Des modifications en base ont été faites, et quelques règles de validations modifiées pour s'appliquer à partir d'une certaine date, et ainsi rendre valides quelques procédures anciennes.

#5957 et #5962

**Comment by krichtof** [comment]
Je propose qu'on implémente le job récurrent qui vérifie si toutes les procédures sont valides, au moment où l'on ajoutera un validateur à `Procedure`
