### ISSUE TITLE
ETQ super admin, je peux supprimer un compte utilisateur

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#5930]
# Fonctionnellement, un utilisateur supprimé
- ne peut plus se connecter
- ne reçoit plus de mail de demarches-simplifiees.fr
- a tous ces brouillons et dossiers en construction supprimés
- de manière plus globale, on essaye de supprimer le plus de chose possible
- peut recréer un compte

mais 
- les dossiers en instructions et terminés ne sont pas détruits et reste à disposition de l'administration
- l'administration conserve le mail de l'usager tant que ces dossiers sont présent sur la plateforme

# Techniquement

**Solution 1 : drapeau sur le modèle usager**
- on pose un drapeau sur le modèle user indiquant que l'usager est supprimé (`deleted_at` ?) puis
  - soit on repasse sur toutes les requêtes pour exclure les usagers supprimés
  - soit on met un `default scope`

moins 
- beaucoup de requêtes à écrire et on n'est pas à l'abri d'en louper dans le cas du drapeau simple
- on est pas non plus a l'abri de passer outre le `default scope` et d'envoyer un mail à un usager supprimé 

**Solution 2 : dénormalisation**
- on rajoute une colonne email dans les dossiers
- on rebranche tous les emails de l'UI / API sur cette colonne 
- on supprime le modèle `user`

moins
- 2 sources de vérité
- code de synchronisation à faire lorsque l'usager change d'email

** Dans tous les cas **
rajouter un job pour supprimer toute la donnée résiduelle une fois que l'administration a supprimé les derniers dossiers.

**Comment by LeSim** [comment]
après discussion

Fonctionnellement:
un instructeur ne peut plus contacter un usager supprimé par la messagerie

Techniquement
dans la solution 2:
- nommer clairement la colonne pour que ça soit nommer `email_do_not_use_or_you_ll_be_fired` ou un truc comme ça.
- denormalisation au niveau de la suppression pour éviter les problèmes de synchro.

A faire :
Regarder la liste de toutes les tables qui ont un lien vers user_id ,  et regarder s'il est plus simple de linker des dossier vers un user_supprimé ou simplement supprimer la relation

le user_supprimé peut aussi nous servir pour détecter les erreurs lorsqu'on envoie des mails qui faut pas.

**Comment by emsnytech** [comment]
A court terme, et qui nous simplifierait la vie:
- un compte sans dossier peut etre supprimé.

En effet, il semble que même quand on demande qu'un dossier soit supprimé par un agent traitant, et donc que du point de vue de l'usager plus aucun dossier de soit actif, il soit impossible de supprimer le compte.

Ce cas d'usage permet très rapidement de régler le pb du point de vue de l'usager.

Il n'est reste pas moins que cela devrait avoir un impact sur ce qui reste dans le tableau de bord de l'agent comme trace du dossier, et donc de la conservation, ou pas, du mail du déposant

**Comment by tchak** [comment]
@emsnytech il est déjà possible de supprimer un compte sans dossiers en instruction. De ce que je vois au support c’est surtout les usagers avec des dossiers traités qui demandent la fermeture de leur compte.

**Comment by tchak** [comment]
Les tables avec un lien vers `user_id` :

`commentaires`, `deleted_dossiers`, `dossiers`, `feedbacks`, `france_connect_informations`, `invites`

**Comment by tchak** [comment]
c'est fait
