### ISSUE TITLE
ETQ Ops, je souhaite connaitre les versions de PostgreSQL supportées

### ISSUE THREAD

**Issue by dzc34** [betagouv/demarches-simplifiees.fr#5952]
Dans les [prérequis du README](https://github.com/betagouv/demarches-simplifiees.fr#tous-environnements), la ou les versions de PostgreSQL ne sont pas précisées.

En regardant les différents fichiers de CI, 2 versions de PostgreSQL sont utilisées : 
- `12` pour GithubAction
- `10.12` pour CircleCI

[.github/workflows/ci.yml](https://github.com/betagouv/demarches-simplifiees.fr/blob/main/.github/workflows/ci.yml#L48) (ligne 48)
```
    services:
      postgres:
        image: postgres:12
```

[.circleci/config.yml](https://github.com/betagouv/demarches-simplifiees.fr/blob/main/.circleci/config.yml#L7) (ligne 7)
```
  docker:
    - image: circleci/ruby:2.7.1-node-browsers
    - image: circleci/postgres:10.12
```

Pour installer DS, pouvons-nous utiliser une version de PostgreSQL qui correspond 
à ce pattern : `>=10.12 < 13.0` ou la réponse est plus subtile ? 

---------------------------

> tracking : @adullact (question initiée par @jobygoude)

**Comment by tchak** [comment]
Circle CI n'est plus utilisé. Mais je vais laisser @LeSim répondre au sujet de quelle est la version de PostgreSQL utilisé en prod.

**Comment by dzc34** [comment]
> Circle CI n'est plus utilisé.

Merci @tchak pour l'information. 
Cela va nous simplifier la tâche au moment des PRs.

Pour la version la version de PostgreSQL, possible aussi d'échanger par mail.

**Comment by LeSim** [comment]
Bonjour,

Pour l'instant on est sur une version 10 mais il faudrait qu'on monte. A priori il n'y a on ne fait rien d'exotique et la montée de version devrait se faire sans trop de soucis.

**Comment by dzc34** [comment]
merci @LeSim pour cette précision.
