### ISSUE TITLE
ETQ usager, je veux connaitre le niveau d'accessibilité du service

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#6032]
Il s'agit de se mettre en règle avec la réglementation.

Rajouter une page d'information dans la doc ( fait ) https://doc.demarches-simplifiees.fr/declaration-daccessibilite

Revoir le footer, pour faire un lien vers la nouvelle page....

**Comment by kemenaran** [comment]
Fait : il y a maintenant un lien dans le footer vers la page qui va bien.
