### ISSUE TITLE
Problèmes de connexion / FranceConnect / mot de passe

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#6062]
## Impossible de se connecter par France Connect

* https://secure.helpscout.net/conversation/1469675745/87141/

_Pistes_

* Des gens qui essaient de ré-initialiser un mot de passe alors que c'est du France Connect ?

## Réinitialisation de mdp qui plante

Suivi ici : https://github.com/betagouv/demarches-simplifiees.fr/issues/6102

## Envoi du mail de réinitialisation qui échoue

* https://secure.helpscout.net/conversation/1475722123/87812/ (ça ressemble à un pb de filtres antispam serveur)

**Comment by emsnytech** [comment]
https://secure.helpscout.net/conversation/1475744206/87816
https://secure.helpscout.net/conversation/1471652804/87435/ ? reinitialisation...

**Comment by emsnytech** [comment]
https://secure.helpscout.net/conversation/1476575652/87882/

**Comment by kemenaran** [comment]
Corrigé via #6332
