### ISSUE TITLE
problème de lien dans vers l'annuaire-entreprise

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#6132]
Retour instructeur :

> Le lien est composé de la manière suivante https://annuaire-entreprises.data.gouv.fr/entreprise/#{etablissement.siren} mais il semblerait qu’il soit corrompu et atterisse sur https://annuaire-entreprises.data.gouv.fr/entreprise/ . Est ce que c’est possible que le lien ne soit pas correctement généré ?

**Comment by krichtof** [comment]
Il semble que annuaire-entreprises.data.gouv.fr a changé ses routes. Effectivement, le lien généré n'est plus correct. Le # est de trop dans l'url

**Comment by krichtof** [comment]
Le lien est cassé parce que notre objet `etablissement` n'a pas de siren . La récupération du siren avec API Entreprise n'a pas dû bien se passer.

On peut comme premier pas 
- si pas de siren, pointer vers la page d'accueil de l'annuaire https://annuaire-entreprises.data.gouv.fr/

On peut ensuite indiquer clairement dans l'interface que l'appel à API Entreprise a échoué, et proposer de réinterroger api entreprise.
