### ISSUE TITLE
ETQ Usager, je veux obtenir une preuve du dépôt et de l'historique du dossier

### ISSUE THREAD

**Issue by krichtof** [betagouv/demarches-simplifiees.fr#6146]
En tant qu'usager ou instructeur, je peux à tout moment générer un document sur lequel sont mentionnés chacune des étapes de la vie de mon dossier, ainsi que l'heure à laquelle chaque étape est survenue (dépôt du dossier, début d'instruction du dossier, validation, refus, ou classement sans suite)

## Étapes
- [x] Générer une attestation de dépôt, téléchargeable depuis le site (#7238)
- [x] Joindre l'attestation de dépôt dans l'email de confirmation de dépôt (#7283)

**Comment by kemenaran** [comment]
À rapprocher de https://demarches-simplifiees.featureupvote.com/suggestions/219460/usager-generer-un-recepisse-ou-une-attestation-prefectorale-pour-un-dossier-en-a : les gens qui ont besoin d'une preuve de dépôt de dossier quand les démarches prennent du temps.

**Comment by kemenaran** [comment]
105 votes sur cet item de FeatureUpvote, dis donc…

**Comment by kemenaran** [comment]
Juridiquement, ça correspond à l'accusé de dépôt. Les informations à y mentionner légalement sont ici : https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000031366350/LEGISCTA000031367334/

**Comment by kemenaran** [comment]
Petits mockups de l'attestation de dépôt : 

### Bouton pour la télécharger sur la page de dossier
<img width="853" alt="Dossier" src="https://user-images.githubusercontent.com/179923/164036525-34d7181d-01d9-4fe4-b135-f2306abceebf.png">

### Un prototype de l'attestation elle-même

<img width="573" alt="Attestation" src="https://user-images.githubusercontent.com/179923/164036554-34d537a7-1b86-4c83-9d54-0a13c4b637de.png">

---

Questions ouvertes :

- Est-ce qu'on veut que le bouton "Télécharger une attestation de dépot" soit sur cette page, ou à cet endroit de la page ?
- Est-ce que "Attestation de dépôt" est clair ?
- Est-ce qu'on veut un lien pour expliquer ce que c'est ?
- Est-ce qu'on peut améliorer les infos qu'on met sur le PDF ?

**Comment by kemenaran** [comment]
Exemple d'attestation émise par le ministère de l'intérieur :

<img width="469" alt="Capture d’écran 2022-04-19 à 17 23 50" src="https://user-images.githubusercontent.com/179923/164039375-b71412fd-2dea-4f0b-8f19-97fd77c4f0fb.png">

**Comment by kemenaran** [comment]
Nouveau prototype d'attestation générique, que j'envisage de proder (derrière un feature-flag), pour qu'on puisse itérer dessus en prod. Vous en pensez quoi ?

<img width="556" alt="Capture d’écran 2022-05-03 à 08 56 48" src="https://user-images.githubusercontent.com/179923/166414983-d8280697-c75e-4dfc-adf1-11bc4e96d9d4.png">

**Comment by kemenaran** [comment]
On a eu des retours de la Cimade sur l'attestation ! Je résumé :

- C'est top, merci
- S'il pouvait y avoir des infos spécifiques à la démarche (date de naissance, nationalité, AGDREF), ça serait encore plus utile

J'ai rempli une issue pour ça ici : #7402
