### ISSUE TITLE
Rendre public les délais de traitement pour chaque démarche

### ISSUE THREAD

**Issue by krichtof** [betagouv/demarches-simplifiees.fr#6149]
Pour chaque démarche, rendre public les délais de traitement (en séparant accepté, refusé et sans suite)

**Comment by PaulineVdY** [comment]
Issue qui va dans le sens des Tableaux de bord

**Comment by kemenaran** [comment]
En plus ça serait une super métrique de satisfaction utilisateur. Dire pour chaque démarche "Ça prend X minutes de remplir la démarche" et "Les dossiers sont instruits en X jours", c'est une bonne manière de dire si une démarche est satisfaisante ou pas, et de mesurer l'évolution.

**Comment by emsnytech** [comment]
top !!! et en plus, c'est légal...

**Comment by kemenaran** [comment]
## Cadrage en priorisation

Ce ticket vise à exposer deux indicateurs par démarche :
- l'évolution du temps moyen/médian/etc de remplissage d'un dossier
- l'évolution du temps moyen/médian/etc d'instruction d'un dossier

## Implémentation

À vue de nez, on envisage deux graphes, un peu comme sur www.demarches-simplifiees.fr/stats , pour pouvoir visualiser l'évolution dans le temps.

Ces données doivent être visibles par l'usager depuis la page de garde d'une démarche (avant même d'avoir un compte).

## Questions ouvertes

- Est-ce que ces graphes sont affichés directement sur la page de garde, ou sur une page séparée ?
- Est-ce qu'on affiche aussi des nombres précis "Délai de traitement **en ce moment**", en plus des graphes ?
- On affiche les graphes à quelle échelle ? 3 mois, 6 mois, toute la durée de la démarche ?

## Notes

- Faire attention à ne pas produire de bad-data (appels à projets qui sont tous en attente, démarches sans dossiers validé, etc)
- Rechercher les cas pathologiques avant de mettre en prod, pour ne pas avoir de surprises
- Éventuellement envisager un encart que l'administrateur de la démarche puisse remplir pour expliquer ces chiffres

**Comment by krichtof** [comment]
> Est-ce qu'on affiche aussi des nombres précis "Délai de traitement en ce moment", en plus des graphes ?

Je fais l'hypothèse que cette info est celle qui intéresse l'usager. Et que l'évolution dans le temps intéresse davantage les personnes (morales ou non) qui veulent aller plus loin (administrations, associations d'usagers, ...)

> Est-ce que ces graphes sont affichés directement sur la page de garde, ou sur une page séparée ?

Je verrai bien sur la page de garde uniquement les délais "en ce moment", sous forme de phrase : 
- "Habituellement, les dossiers de cette démarche sont traités dans un délai de ..."
- "Habituellement, les usagers mettent un délai de ... pour remplir un dossier de cette démarche"
suivi d'une explication du calcul de l'estimation.

Et sur la page de garde, un lien vers une page avec des stats plus fournies (avec graphes de l'évolution dans le temps, et possibilité de télécharger un csv des données brutes)

**Comment by kemenaran** [comment]
> Est-ce que ces graphes sont affichés directement sur la page de garde, ou sur une page séparée ?

Mmm, intéressant. Je suis pas trop sûr de moi, mais après y avoir réfléchi pendant la nuit, je crois que moi présenter ces chiffres en page d'accueil m'inquiète un peu, par crainte qu'ils soient trompeurs :
- Le temps de remplissage d'une démarche n'est pas vraiment le temps pour remplir la démarche si on le fait en une session, hop-hop – mais le temps que les usagers prennent habituellement, en ouvrant le brouillon, en le reprenant 2 jours plus tard… Du coup on va sans doute afficher la plupart du temps _"Habituellement, les usagers mettent 13 heures pour remplir un dossier"_, et ça va flipper tout le monde ^^
- Le temps d'instruction me semble plus fiable, mais comme il est calculé de manière automatique, il est parfois foireux aussi. Et même s'il est juste je me dis que le bon moment pour le présenter de manière très visible à l'usager, c'est plutôt à la fin du remplissage du dossier (mais pas avant de commencer à remplir la démarche).

Du coup je serais vaguement plus pour mettre ces données sur une page linkée depuis la page de garde - mais pas depuis la page de garde directement. Mais ça se discute :)

**Comment by krichtof** [comment]
Si l'on considère un indicateur comme foireux (et sur le temps de remplissage d'une démarche, je suis d'accord avec toi, il peut être très trompeur), qu'il soit indiqué en page de garde ou exposé plus discrètement dans une autre page, il reste un indicateur foireux.  Du coup, il s'agira de bien expliquer ce qu'indique réellement cet indicateur, et être au clair sur le pourquoi nous souhaitons l'exposer.

Sur le temps d'instruction, il me semble aussi plus fiable. Dans quelles situations il pourrait être foireux ?

**Comment by kemenaran** [comment]
Pour le temps de remplissage, c'est l'évolution dans le temps qui me semble intéressante – ou éventuellement la comparaison avec la moyenne/médiane/etc de _toutes les démarches_, pour savoir où la démarche actuelle se situe.

Et sur le temps d'instruction, on a eu des cas où les instructeurs :
- soit laissent des dossiers en instruction exprès (parce que c'est leur workflow)
- soit traitent tous les dossiers à la fin (appel à projet)
- d'autres cas dont je ne me souviens plus, mais qui avaient l'air légitimes

C'est à ça qu'il faudrait faire attention, je pense - mais à mon avis en prenant en compte tout ça y'a moyen d'exposer un chiffre assez fiable. C'est juste que je me dis que le bon moment pour l'exposer c'est plus quand on dépose le dossier que quand on commence à le remplir – mais ça se discute, p-ê que directement sur la page de garde c'est bien aussi…
