### ISSUE TITLE
Rendre public les stats de dossiers acceptés/refusés/sans-suite pour chaque démarche

### ISSUE THREAD

**Issue by krichtof** [betagouv/demarches-simplifiees.fr#6150]
## Le besoin

Pouvoir rendre public le taux d'acceptation et de refus des dossiers, et l'évolution de ce taux au cours du temps.

## Proposition

- Afficher un graphe avec trois courbes sur le même graphe : nombre de dossiers Accepté, Refusé, et Sans suite
- Affichage par semaine sur les 6 derniers mois

**Etape 1:**
- Dans la partie Instructeur > Statistiques de la démarche, on rajoute le graphe en question (en gardant les graphes existants pour l'instant, parce que les instructeurs veulent savoir le nombre de dossiers en brouillon)

**Etape 2:**
- Ajouter en bas de la page de garde publique des démarches un lien vers une nouvelle page "statistiques de la démarche"
- Afficher le graphe accepté/refuser/sans-suite sur cette page "statistiques de la démarche"

**Comment by PaulineVdY** [comment]
Issue qui va dans le sens des Tableaux de bord
