### ISSUE TITLE
ETQ usager, je veux être informé et choisir les cookies

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#6191]
![Capture d’écran 2021-05-10 à 09 15 50](https://user-images.githubusercontent.com/27733126/117620228-9178d200-b170-11eb-9a73-f5086ae2266e.png)
Proposer systématiquement aux usagers un bandeau  pour choisir les cookies qu'il souhaite utiliser.

Modèle: 

la gestion proposées par le site gouvernemental

**Comment by LeSim** [comment]
Je réécris ici pour la postérité : Pas chaud du tout.

Dans le détails, on dépose actuellement, pour le profil **usager** uniquement 2 trackers : 

le cookie de session DS pour authentifier une personne loggué. Ca rentre dans la catégorie indispensable de la CNIL.
le tracker matomo (mesure d'audience) qui ne sert qu'a produire des statistiques anonymes.

Il y a plus de tracker pour les autres profils, mais je crois que ce n'est pas le sujet ici.

**Comment by tchak** [comment]
D'accord avec @LeSim. Je ferme pour l'instant.
