### ISSUE TITLE
ETQ Usager, je veux transférer un dossier à un invité, pour qu'il en devienne propriétaire

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#6198]
Aujourd'hui, le transfert d'un dossier d'un usager à une autre personne est difficile.
Il s'agit de permettre le transfert de la propriété d'un dossier.

L'option proposée:
J'invite une personne dans un dossier
Je transfère la propriété du dossier à une personne invitée

**Comment by kemenaran** [comment]
Fermé par #6359
