### ISSUE TITLE
ETQ Administrateur, je veux relier ma démarche à un ministere / organisme

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#6275]
- le nom d'un ministère peut changer en cours de vie
- la démarche peut changer de ministère en cours de vie

implications techniques :

**table ministeres**
nom (non null unique)
actif (default true)

**table procedure_ministere** 
minsitere_id (non null)
procedure_id (non null)
attached_at (non null)

! trouver un autre nom que ministère car cela peut comprendre des ministères et des organismes.

**Comment by LeSim** [comment]
organisme de rattachement ?

**Comment by mfaure** [comment]
Hello @LeSim ton expression de besoin correspond bigrement à une partie de notre future contrib, que nous appelons "admin de groupe". Pour cette dernière, la description arrivera dans 2 semaines.

Nous avions aussi répéré l'issue [#6194 ETQ Administrateur, je veux correctement classifier l'organisme qui publie une procédure](https://github.com/betagouv/demarches-simplifiees.fr/issues/6194) qui se rapprochait.

Stay tuned :)

**Comment by emsnytech** [comment]
[REFRENTIEL STRUCTURES.xlsx](https://github.com/betagouv/demarches-simplifiees.fr/files/6661753/REFRENTIEL.STRUCTURES.xlsx)

**Comment by emsnytech** [comment]
Super, si on peut modéliser cela de manière conjointe  !!!!

**Comment by krichtof** [comment]
Doublon avec #6194
