### ISSUE TITLE
ETQ Expert, je ne peux plus me connecter après avoir accepté une demande d'avis

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#6281]
**Reproduction**

En tant que (futur) Expert :

1. Recevoir une demande d'avis par email (sans avoir de compte préalable) 
2. Cliquer sur le lien "Donner mon avis". Le formulaire pour créer un compte avec un mot de passe s'affiche.
3. Soumettre le formulaire pour créer mon compte, avec un mot de passe random
4. Me déconnecter
5. Essayer de me reconnecter avec le même email et mot de passe

**Comportement attendu**

Le site devrait me laisser me connecter avec le mot de passe que je viens de définir.

**Comportement observé**

Le site m'indique que mon mot de passe est invalide.

**Détails**

C'est apparemment parce que le mot de passe de l'expert n'est pas pris en compte au moment où il crée son compte.

J'ai créé un test sur une branche qui expose le problème : 

https://github.com/betagouv/demarches-simplifiees.fr/commit/535902e3f12f46a79fd2c6cc7056e2d1bda3f567

Maintenant il faut faire en sorte que le test passe :)

Poke @kara22 .

**Comment by kara22** [comment]
Il me semble que c'est aussi le cas pour les instructeurs lorsqu'ils sont crées si je me trompe pas ?

**Comment by kemenaran** [comment]
Heu, c'est possible aussi ; je n'ai pas vérifié.
