### ISSUE TITLE
ETQ Usager, je veux voir les statistiques d'une démarche sur un dossier que j'ai déposé même si elle a été archivée

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#6319]
**Reproduction**

1. Déposer un dossier sur une démarche
2. Archiver la démarche
3. Aller sur la page de son dossier, et cliquer sur le lien "Statistiques" dans le footer.

**Comportement attendu**

La page de statistiques de la démarche s'affiche.

**Comportement observé**

Une erreur "La démarche n'existe pas." s'affiche.

**Notes**

Je dirais qu'on peut :

1. Soit rendre les stats disponibles sur les démarches archivées,
2. Soit désactiver les stats sur les démarches archivées.

Je penche plutôt pour 1.

(/cc @krichtof @kara22)

**Comment by krichtof** [comment]
Je partage ton avis @kemenaran
