### ISSUE TITLE
ETQ utilisateur, je n'aimerais avoir à remplir mes informations d'identifications (Prénom, Nom, Date de naissance ) qu'une seule fois

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#634]

**Comment by benjaminhenkel** [comment]
A ANFR (point bloquant)

**Comment by benjaminhenkel** [comment]
A commission national du débat public

**Comment by kemenaran** [comment]
Une manière de faire ça serait, quand on affiche la page "identité", d'aller chercher un dossier existant avec un objet `identite`, et de pré-remplir le formulaire avec ça.
