### ISSUE TITLE
ETQ usager, je veux pouvoir supprimer les dossiers terminés

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#6536]
Ou a minima les cacher.

HS 117201

**Comment by LeSim** [comment]
HS 119115

**Comment by kara22** [comment]
En y réfléchissant, je me suis demandé pourquoi on voulait cacher les dossiers : ça devient vite le bordel car il y a des dossiers en construction, brouillon, et terminés dans le même endroit. Voici ma proposition : 

![image](https://user-images.githubusercontent.com/21340608/141123882-ffdae3a8-9fa6-4bb9-abd4-d62670d54af7.png)

On a  les dossiers : 

- en cours : dossiers qui ont les states  `brouillon`, `en construction`
- terminés : dossiers qui ont les statuts `acceptés`, `refusés`, `sans suite`

Ce qui permet à l'usager de mieux s'y retrouver à mon sens.

Maintenant la question c'est si l'usager veut cacher son dossier et qu'il le fait, on risque d'avoir des messages au support nous disant "ah je l'ai caché mais je me suis trompé, il y a moyen de le retrouver ??"

Ou alors on aurait encore une autre tab `dossiers-cachés` mais ça deviendrait une usinagaz...

Qu'en pensez-vous ? @tchak @kemenaran @LeSim @krichtof

**Comment by LeSim** [comment]
Ta proposition est sensé. Je suggère qu'on reprenne le terme `traités` au lieu de `terminé`.
Maintenant, il me semble que cela résout un autre problème.

Supprimer un dossier coté usager permet de savoir que l'usager ne veut plus de dossier. Et donc de pouvoir supprimer tranquillement le dossier un fois que l'administration décide de le supprimer également.

Je ne suis pas contre de faire les 2, mais pouvoir laisser l'usager supprimer son dossier me semble utile.

Oui on risque d'avoir du support, mais aujourd'hui on en a des gens qui veulent et ne peuvent pas supprimer leur dossier.

**Comment by kara22** [comment]
Ok ça marche. Donc dans l'onglet `traités` dans le bouton actions, on pourra "supprimer" le dossier mais en faite ça le cachera juste de l'interface utilisateur.

Par exemple si un instructeur retourne sur le dossier pour envoyer un message à l'usager, mais qu'il a supprimé son dossier, on le réouvre ? @LeSim

**Comment by LeSim** [comment]
on enlève la possibilité d'envoyer un message ?

**Comment by tchak** [comment]
Je suis aussi pour faire les deux. Je pense que c'est une bonne idée de commencer par les tabs. Nous avons déjà un tab dossiers supprimés pour les usagers. Idéalement dans le tab "dossiers supprimés”, il faudrait ajouter aux dossiers l'action "restaurer".

**Comment by tchak** [comment]
On peut essayer d'empêcher d'envoyer les messages sur les dossiers supprimés par l’usager, mais il faut aussi un marquage clair. Les dossiers supprimés par l'usager doivent avoir une pastille dans la vue instructeur.

**Comment by krichtof** [comment]
+1 pour le marquage clair des dossiers supprimés, via une pastille dans la vue instructeur
