### ISSUE TITLE
Des pièces jointes ne sont pas acceptée par DS

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#6547]
On constate qu'environ 1 pj par minute reste non analysée par l'antivirus.

La majorité de ces pièces jointes n'ont pas leur format analysé par rails non plus. Or c'est un pré requis à l'analyse antivirus https://github.com/betagouv/demarches-simplifiees.fr/blob/4002e1157d2cb21d9c0d1c6aaab0168e6ac2e901/app/jobs/virus_scanner_job.rb#L26 .

 Il faudrait comprendre pourquoi cette analyse de format n'a pas lieu

Proposition:
- Réaliser l'analyse de format dans le `VirusScannerJob` par un `blob.analyze`
- Mettre trouver l'erreur l'analyser de format ne digère pas et lui dire de réessayer

**Comment by kemenaran** [comment]
Yep, il faut gratter. Dans les questions ouvertes :

- Je crois qu'on n'a pas d'analyzers ActiveStorage qui tournent en prod (on les désactive tous). Du coup Rails est supposé marquer le fichier comme analysé en synchrone, sans passer par un job. Est-ce qu'il le fait bien en synchrone, ou pas ?
- Est-ce que l'analyse anti-virus en tant que tel prend tant de temps que ça ? Si c'est pas si long, est-ce qu'on ne ferait pas mieux de le faire en synchrone (genre avec un [validateur](https://github.com/mainio/ratonvirus/blob/master/app/validators/antivirus_validator.rb)) ?
- Tout le pb vient du fait que Rails ne va jamais exécuter qu'un seul analyzer pour un fichier, le premier qui matche (et nous on voudrait potentiellement pouvoir analyser les dimensions d'une image ET la scanner). Est-ce qu'une solution pourrait être de patcher les analyzers existants pour dire "Au passage fait aussi l'analyse AV" ?

**Comment by LeSim** [comment]
- il passe forcément l'analyzer de temps en temps, sinon on aurait pas d'antivirus. 

je vois qu'on a 

```
Rails.application.config.active_storage.analyzers.delete ActiveStorage::Analyzer::ImageAnalyzer
Rails.application.config.active_storage.analyzers.delete ActiveStorage::Analyzer::VideoAnalyzer
```
dans initializers/active_storage

- l'antivirus pas trop de temps, disons qq secondes. pourquoi pas en synchrone. 
- pourquoi pas patcer les analyzer, je suis assez surpris qu'il n'y ait pas de solution standard pour faire ca

**Comment by kemenaran** [comment]
Honnêtement je comprends l'inquiétude. Après je ne vois pas de solution qui soit aussi efficace et pragmatique…

**Comment by tchak** [comment]
@kemenaran je viens de proposer des solutions dans #6608
