### ISSUE TITLE
clé non traduite state.accepte sur la page personnes impliquées

### ISSUE THREAD

**Issue by adipasquale** [betagouv/demarches-simplifiees.fr#6554]
**Décrivez le bug**
Il manque une clé de traduction pour `fr.activerecord.attributes.traitement.state.accepte` ce qui fait apparaître du HTML non interprété sur la page `procedures/:procedure_id/dossiers/:dossier_id/personnes-impliquees`

**Reproduction**

1. soumettre un dossier de test
2. se connecter en tant qu'instructeur et accepter le dossier
3. aller sur l'onglet personnes impliquees du dossier

**Comportement attendu**
il devrait y avoir écrit "accepté"

**Capture d'écran**
<img width="946" alt="Screenshot 2021-10-19 at 10 14 12" src="https://user-images.githubusercontent.com/883348/137870533-e2f97bf1-fa86-4911-b149-5dc0f89cf1c7.png">

**Comment by tchak** [comment]
fixed with #6635
