### ISSUE TITLE
ETQ Usager je souhaiterais pouvoir trier mes dossiers selon certains champs 

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#657]

**Comment by mmagn** [comment]
Tu t'es endormis en écrivant le titre @benjaminhenkel ? 😄

**Comment by benjaminhenkel** [comment]
Même fonctionnalité qu'ETQ accompagnateur 
En effet, si on remplit différents dossiers pour la même procédure, cela devient vite illisible
![image003](https://user-images.githubusercontent.com/28590367/29671169-191975a2-88e9-11e7-8ba5-81556d2ec08b.jpg)

**Comment by benjaminhenkel** [comment]
A FranceAgrimer
(et éventuellement à ANFR quand ils reviendront car c'était une de leurs demandes également)

**Comment by AnthonyBrunelli** [comment]
Effectivement important d'un point de vue utilisateur-usager.

**Comment by red1bush** [comment]
Cette demande est revenue aujourdhui 
https://secure.helpscout.net/conversation/774107686/12097?folderId=1948973
