### ISSUE TITLE
ETQ qu'instructeur, la mise en page du tableau est "cassée" pour les dossiers supprimés

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/demarches-simplifiees.fr#6622]
**Décrivez le bug**
ETQ qu'instructeur, quand je consulte les dossiers supprimés, alors la mise en page du tableau est "cassée".

**Reproduction**
Comment reproduire le problème :
1. Aller sur la page '/procedures/xxx'
2. Cliquez sur 'archivé'
3. Cliquez sur 'Afficher les dossiers supprimés'
3. La mise en page du tableau est "cassée"

**Comportement attendu**
![image-2021-10-27-12-05-07-314](https://user-images.githubusercontent.com/9320719/140828538-1182939b-94c7-4001-b1cc-429fa8736ba2.png)

**Capture d'écran**
![image](https://user-images.githubusercontent.com/9320719/140828655-d88153ba-d9d5-478a-9e07-b9a628fa8a11.png)

**Appareil et navigateur utilisé**
 - Appareil :  PC
 - Navigateur :  Chrome

**Comment by tchak** [comment]
C'est curieux. Je reproduis en production mais pas en local :(

**Comment by kemenaran** [comment]
Fermé par  #6623
