### ISSUE TITLE
ETQ Usager : Rendre la suppression plus visible

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#6649]
Proposition :

coté usager (https://github.com/betagouv/demarches-simplifiees.fr/pull/6656 -> on peut shipper ça pr pas trop tarder)
- [x] pouvoir prolonger plusieurs fois la durée de vie d'un dossier
- [x] mettre le bandeau d'expiration sur le détail d'un dossier traité (sans possibilité de le prolonger)
- [x] trouver un système pour avoir une vue globale des dossiers qui être supprimer

coté instructeur : dans une nouvelle issue https://github.com/betagouv/demarches-simplifiees.fr/issues/6671

**Comment by tchak** [comment]
Nous avons eu un cas au support assez grave : nous avons supprimé des dossiers en construction expirés alors que l'administration pensait avoir fait deux actions pour empêcher la suppression suite aux alertes. Ils ont essayé de passer les dossiers en construction en instruction et les ont repassés en construction à nouveau. Ils espéraient que ça remet le compteur à zéro. Ça sera le cas depuis #6619, mais ce n'était pas le cas avant. Pire, les dossiers ont été supprimés sans autre avertissement alors que l'administration s'attendait à ce que la durée de conservation soit prolongée. L'administration a aussi augmenté la durée de conservation, mais n'avait pas de moyen de savoir que pour les dossiers pour lesquels la notification a déjà été envoyée ce changement n'a plus d'effet.
