### ISSUE TITLE
ETQ développeur, je voudrais pouvoir influer sur l'option `--no-sandbox` du pilote Selenium Chrome lors des tests

### ISSUE THREAD

**Issue by akarzim** [betagouv/demarches-simplifiees.fr#6857]
# Résumé

Des erreurs surviennent lorsque l'environnement de test est exécuté avec l'utilisateur `root`. Ce cas de figure a peu de chances de se produire dans un environnement de test standard, mais est déjà beaucoup plus probable dans un environnement Dockerisé où il est très courant que l'utilisateur par défaut soit `root`, du fait qu'il soit confiné à son seul container.

```
Unable to open browser with url: 'https://www.demarches-simplifiees.fr'
(Root cause: org.openqa.selenium.WebDriverException: unknown error: DevToolsActivePort file doesn't exist)
```

documentation : https://stackoverflow.com/questions/50642308/

mots-clés : capybara, chrome, driver, sandbox, selenium, test

# Actuellement

Actuellement, il n'y a aucun moyen de contourner cette limitation. Sauf à se contraindre à utiliser un autre utilisateur que `root` pour exécuter l'environnement de test. Chose sur laquelle il se peut que nous n'ayons pas la main en tant que développeur.

# Comportement attendu

Il serait apprécié de pouvoir contourner cette limitation à l'aide d'une variable d'environnement, par exemple, qui influerait sur le comportement de Selenium.

# Proposition

Créer une nouvelle variable d'environnement booléenne `SANDBOX` (activée par défaut) qui, si elle est désactivée, ajoute l'option `--no-sandbox` à la création du WebDriver.

> A common cause for Chrome to crash during startup is running Chrome as root user (administrator) on Linux. While it is possible to work around this issue by passing --no-sandbox flag when creating your WebDriver session, such a configuration is unsupported and highly discouraged. You need to configure your environment to run Chrome as a regular user instead.

Malgré les avertissements ci-dessus — qu'il serait de bon ton de rappeler en cas de désactivation de cette nouvelle variable d'environnement — force est de constater que cela résout notre problème.

--- 

voir : PR à venir / @adullact & @synbioz

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

---

`trackingAdullactContrib`

**Comment by dzc34** [comment]
Peut-être utiliser une variable d'environnement optionnelle ?
[`config/env.example.optional`](https://github.com/betagouv/demarches-simplifiees.fr/blob/main/config/env.example.optional)
```
# TEST_CHROME_SANDBOX_ENABLED="disabled" # "enabled" by default
```

**Comment by akarzim** [comment]
> Peut-être utiliser une variable d'environnement optionnelle ?

C'est exactement l'approche adoptée. La PR arrive.
En réalité, je me suis calqué sur un comportement déjà présent permettant d'activer l'option `--headless` sur ce même pilote.

**Comment by tchak** [comment]
fixed with #6899
