### ISSUE TITLE
[API Entreprise] Ajout du support des jetons JWT sans clé d'expiration

### ISSUE THREAD

**Issue by akarzim** [betagouv/demarches-simplifiees.fr#6859]
# Résumé

Un jeton JWT peut ne pas avoir de clé `exp` (date d'expiration) dans son _payload_.
 
Par exemple, ce jeton est valide et n'a pas de clé `exp`:

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ey
JzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ikpva
G4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKx
wRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```

documentation : https://jwt.io/

mots-clés : API Entreprise, jeton, JWT, token

# Actuellement

La clé `exp` du jeton JWT de l'API Entreprise est traitée comme si elle était obligatoire. Ce qui lève une exception lorsque la méthode `expired?` est appelée sur un jeton JWT ne disposant pas de cette clé.

# Comportement attendu

L'absence de la clé `exp` dans un jeton JWT devrait impliquer que le jeton n'expire jamais, et la méthode `expired?` devrait retourner `false` dans ce cas.

# Proposition

Ajuster la méthode `expired?` de la classe `APIEntrepriseToken` pour prendre en compte la possible absence de cette clé.

## Bonus

1. la mémoization de la méthode `decoded_token` éviterait de redécoder le jeton à chaque appel de cette méthode.
2. s'assurer que la méthode `roles` retourne systématiquement un `Array` éviterait la levée d'exception sur l'appel à la méthode `role?`.

--- 

voir : PR à venir / @adullact & @synbioz

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

---

`trackingAdullactContrib`

**Comment by tchak** [comment]
On sait pourquoi l'API entreprise émet des tokens sans date d'expiration ? Je trouve ça super flippant.

**Comment by akarzim** [comment]
Je ne dis pas que c'est le cas. Je dis que le standard JWT ne l'interdit pas et qu'en faisant des essais en prenant naïvement le jeton d'exemple sur la page de https://jwt.io/ j'ai été confronté à des erreurs 500.

**Comment by tchak** [comment]
Je pense qu'on ne va pas prendre cette PR. Ça introduit un problème de sécurité – les token JWT sans date d'expiration bien que ça soit dans la spec c'est une très mauvaise pratique. Si ce n’est pas explicitement demandé par l'API Entreprise on ne va pas l'introduire, désolé. Je pense que ce n’est pas trop de boulot de générer des token de test avec l’expiration. Ce qu'on pourrait prendre comme PR c'est de faire en sorte que ça ne soit pas une 500 mais une erreur plus lisible.

**Comment by tchak** [comment]
Je ferme l'issue – je reprendrai la PR #6901 pour garder les tests et les améliorations.
