### ISSUE TITLE
Les feature tests touchant aux emails échouent de manière aléatoire

### ISSUE THREAD

**Issue by akarzim** [betagouv/demarches-simplifiees.fr#6861]
# Résumé

Les _feature tests_ touchant aux emails échouent de manière aléatoire.

```
Failures:
 
  1) Inviting an expert: as an Instructeur I can invite an expert
     Failure/Error: invitation_email = open_email(expert.email.to_s)
       
Diff:
  -/procedures/2/avis/2/sign_up/email/expert1@expert.com
  +/procedures/1/avis/1/sign_up/email/expert1@expert.com
```

mots-clés : email, expert, test

# Actuellement

De manière aléatoire, les tests peuvent échouer lors l'invitation d'un expert en tant qu'instructeur.

# Comportement attendu

Lesdits tests devraient passer en toute occasion.

# Proposition

Nettoyer les emails avant toute exécution des tests incriminés. Pour cela, une méthode `clear_emails` est déjà à notre disposition.

--- 

voir : PR à venir / @adullact & @synbioz

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

---

`trackingAdullactContrib`

**Comment by tchak** [comment]
fixed with #6903
