### ISSUE TITLE
Des tests sur les instructeurs échouent aléatoirement

### ISSUE THREAD

**Issue by akarzim** [betagouv/demarches-simplifiees.fr#6865]
# Résumé

Il arrive que les tests de contrôleurs des groupes d'instructeurs échouent aléatoirement.

mots-clés : instructeur, rspec, test

# Actuellement

Les tests de contrôleurs des groupes d'instructeurs font par endroits une comparaison de liste à liste (`Array`). Or, il peut arriver que les éléments contenus dans ces listes soient ordonés différemment. Ce qui occasionne des échecs aléatoires lors de l'exécution de ces tests.

# Comportement attendu

Les tests devraient passer en toute circonstance.

# Proposition

Utiliser la méthode `contain_exactly` fournie par RSpec pour s'assurer de la présence d'une liste de valeurs dans un `Array`.

--- 

voir : PR à venir / @adullact & @synbioz

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

---

`trackingAdullactContrib`

**Comment by tchak** [comment]
fixed #6907
