### ISSUE TITLE
Tri alphabétique des règles Rubocop

### ISSUE THREAD

**Issue by akarzim** [betagouv/demarches-simplifiees.fr#6867]
# Résumé

Proposition de tri alphabétique des règles présentent dans la configuration de Rubocop.

mots-clés : rubocop

tickets liés : #6863, #6866

# Actuellement

Les règles de configuration de Rubocop sont déclarées dans un ordre aléatoire. Cela a deux conséquences :

- il est plus difficile de retrouver une règle en parcourant visuellement le fichier
- il peut arriver qu'une règle soit déclarée deux fois sans que l'on s'en aperçoive.

# Comportement attendu

Les règles de confiugration de Rubocop devraient être déclarées dans l'ordre alphabétique.

# Proposition

Réordonner les règles déclarées dans le fichier de configuration de Rubocop.

--- 

voir : PR à venir / @adullact & @synbioz

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

---

`trackingAdullactContrib`

**Comment by tchak** [comment]
fixed #6909
