### ISSUE TITLE
Déplacer toutes les mentions à la DINUM dans des variables

### ISSUE THREAD

**Issue by akarzim** [betagouv/demarches-simplifiees.fr#6873]
# Résumé

Les occurrences de la mention « DINUM » devrait être sujettes à configuration par le moyen de variables d'environnement.

mots-clés : dinum, env, provider

# Actuellement

La mention « DINUM » est inscrite en dur dans plusieurs _templates_ et feuilles de style. Or, lorsqu'il s'agit de l'instance d'une collectivité, il est nécessaire de faire apparaître le nom de celle-ci en lieu et place de cette mention.

# Comportement attendu

Aucune mention à la DINUM ne devrait figurer en dur dans les _templates_.

# Proposition

Ajout de variables d'environnement permettant de configurer l'identité du fournisseur du service Démarches Simplifiée.

```
PROVIDED_BY="la DINUM"
PROVIDER_NAME="DINUM"
PROVIDER_TITLE="Direction Interministérielle au Numérique"
PROVIDER_URL="https://numerique.gouv.fr/"
PROVIDER_LOGO_SRC="footer/logo-dinum.png"
PROVIDER_LOGO_ALT="Logo DINUM"
PROVIDER_LOGO_HEIGHT="161"
PROVIDER_LOGO_WIDTH="138"
```

--- 

voir : PR à venir / @adullact & @synbioz

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

---

`trackingAdullactContrib`

**Comment by tchak** [comment]
fixed with #6916
