### ISSUE TITLE
Amélioration du rendu du footer

### ISSUE THREAD

**Issue by akarzim** [betagouv/demarches-simplifiees.fr#6877]
# Résumé

Proposition d'amélioration du rendu du _footer_ lorsque l'intitulé du fournisseur du service Démarches Simplifiées excède le tiers de la lageur de la page.

mots-clés : css, footer, provider

# Actuellement

![75487747e5b64e83af00da1a13a74d7e](https://user-images.githubusercontent.com/130560/152194984-deea5cff-9b65-4abe-b4e6-09d89a568f8e.png)

# Comportement attendu

![d1f45f5e78ad4d8d9d5ea25601f1e8e5](https://user-images.githubusercontent.com/130560/152195049-3e9f484b-1856-40ff-baf8-ee97ba7ec058.png)

# Proposition

Une petite retouche sur l'attribut `flex` de l'élément `footer` suffit à rééquilibrer le rendu.

--- 

voir : PR à venir / @adullact & @synbioz

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

---

`trackingAdullactContrib`

**Comment by tchak** [comment]
fixed with #6919
