### ISSUE TITLE
Watermark depuis une URL distante

### ISSUE THREAD

**Issue by akarzim** [betagouv/demarches-simplifiees.fr#6886]
# Résumé

Cette proposition offre la possibilité de disposer d'un _watermark_ distant accessible en HTTP ou HTTPS.

mots-clés : assets, env, wartermark

# Actuellement

Le _watermark_ doit forcément se trouver dans le répertoire `app/assets/images`.

# Comportement attendu

Le _watermark_ devrait pouvoir être une image accessible en HTTP ou HTTPS depuis une URL donnée.

# Proposition

Adapter le job `titre_identite_watermark_job.rb` pour qu'il puisse prendre en charge un _watermark_ distant.

--- 

voir : PR à venir / @adullact & @synbioz

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

---

`trackingAdullactContrib`

**Comment by tchak** [comment]
fixed with #6928
