### ISSUE TITLE
Configuration de l'URL de l'iframe Matomo

### ISSUE THREAD

**Issue by akarzim** [betagouv/demarches-simplifiees.fr#6889]
# Résumé

Configuration de l'URL de l'iframe Matomo par le moyen d'une variable d'environnement.

mots-clés : env, iframe, matomo

# Actuellement

L'URL de l'iframe Matomo est inscrite en dur dans une constante.

# Comportement attendu

Cette URL devrait pouvoir être configurée à l'aide d'une variable d'environnement, comme toutes les autres.

# Proposition

Ajouter une variable d'environnement `MATOMO_IFRAME_URL`.

--- 

tickets liés : #5868, #6891

voir : PR à venir / @adullact & @synbioz

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

---

`trackingAdullactContrib`

**Comment by dzc34** [comment]
ticket complémentaire au sujet de l'iframe Matomo : #5868

**Comment by akarzim** [comment]
> ticket complémentaire au sujet de l'iframe Matomo :
> #5868 "L'iframe Matomo ne s'affiche pas (bloquée par les règles CSP) sur la page `demarches-simplifiees.fr/suivi`"

Ça fait le lien avec le ticket #6891.
J'en ai profité pour citer ces deux tickets dans la description de celui-ci, et réciproquement.
