### ISSUE TITLE
Renommage de STORAGE_TYPE en ACTIVE_STORAGE_SERVICE

### ISSUE THREAD

**Issue by akarzim** [betagouv/demarches-simplifiees.fr#6942]
# Résumé

@kemenaran propose de renommer la variable `STORAGE_TYPE` en `ACTIVE_STORAGE_SERVICE`

Cf. https://github.com/betagouv/demarches-simplifiees.fr/pull/6929#discussion_r801700035

mots-clés : env, storage, variable

--- 

voir : PR #6943 / @adullact & @synbioz & @betagouv

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

---

`trackingAdullactContrib`

**Comment by kemenaran** [comment]
Oui, on est bon !
