### ISSUE TITLE
ETQ Usager, ma visite sur demarches-simplifiees.fr est-elle comptabilisée par Matomo ? (bloquée par les règles CSP)

### ISSUE THREAD

**Issue by dzc34** [betagouv/demarches-simplifiees.fr#6949]
## Appareil et navigateurs utilisés

 - PC Ubuntu 18.04 avec **Firefox** 96, **Chrome** 98, **Edge** 99
 - PC Ubuntu 20.04 avec **Firefox** 96, **Chrome** 98
 - PC Windows 10 Famille avec  **Edge** 98
 - VM Windows 11 Entreprise avec  **Edge** 98 et  **Firefox** 97
  
## Description du problème

ETQ Usager, ma visite sur **demarches-simplifiees.fr** n'est pas comptabilitée par **Matomo** (bloquée par les règles **CSP**)

- le fichier piwik.js est bien chargé par le navigateur
- piwik.js fait une requête POST pour envoyer les informations sur le visiteur 
  - URL : `https://stats.data.gouv.fr/piwik.php?action_name=demarches-simplifiees.fr&idsite=...`
  - cette requête POST est **bloquée** par les règles CSP dans **Firefox**, **Chrome** et **Edge**
  - à priori il manque une directive CSP  `connect-src` pour que le navigateur puisse envoyer la statistique de visite à Matomo.
- piwik.js utilise une solution de repli en ajoutant une image au DOM 
  - URL : identique à la requête POST
  - ce fallback fonctionne dans **Firefox**
  - ce fallback **ne fonctionne pas** dans  **Chrome** et **Edge** 
  

## Reproduction

Comment reproduire le problème :
1. Ouvrir les devtools (F12 sous Ubuntu) 
2. Aller sur la page d'accueil : https://www.demarches-simplifiees.fr/ (sur les autres pages, le problème existe aussi)
3. Consulter les requêtes HTTP réalisées par le navigateur (voir copies d'écran)
4. Une erreur apparaît dans la console des devtools : 
```javascript
​    Refused to connect to 
   'https://stats.data.gouv.fr/piwik.php?action_name=demarches-simplifiees.fr&idsite=...' 
    because it violates the following Content Security Policy directive: 
   "connect-src 'self' wss://*.crisp.chat *.crisp.chat *.demarches-simplifiees.fr in-automate.sendinblue.com app.franceconnect.gouv.fr sentry.io geo.api.gouv.fr api-adresse.data.gouv.fr openmaptiles.geo.data.gouv.fr openmaptiles.github.io tiles.geo.api.gouv.fr wxs.ign.fr data.education.gouv.fr".
```

### Requêtes HTTP + erreur CSP dans FIREFOX
![Sélection_056](https://user-images.githubusercontent.com/6709977/153271180-59a70263-d006-4df6-b9e3-3863762b6aaf.png)

![Sélection_054](https://user-images.githubusercontent.com/6709977/153270515-6eda817f-c450-4f99-ac60-df044bcbc45c.png)

### Requêtes HTTP + erreur CSP dans CHROME
![Sélection_055](https://user-images.githubusercontent.com/6709977/153270939-b783d6e5-cfc1-49a4-b060-375c347d26f5.png)

### Requêtes HTTP + erreur CSP dans EDGE
![Sélection_058](https://user-images.githubusercontent.com/6709977/153271726-90850ae1-0c28-44c3-971a-0b1755740825.png)
![Sélection_057](https://user-images.githubusercontent.com/6709977/153271736-1f0ce471-0209-4cfb-aab0-61f04156f292.png)

## Comportement attendu

- La requête POST envoyée par piwik.js n'est pas bloquée par le navigateur
- Aucune erreur CSP n'est présente dans la console du navigateur

----------------------
> `trackingAdullactContrib`

**Comment by tchak** [comment]
Je viens de tester et je confirme :)
