### ISSUE TITLE
Activer l'expiration des dossiers terminée sur les nouvelles démarches

### ISSUE THREAD

**Issue by tchak** [betagouv/demarches-simplifiees.fr#6952]
Il y a un souci avec le message affiché sur les dossiers qui n’expirent pas :
https://github.com/betagouv/demarches-simplifiees.fr/blob/88e80e9e32bc11e3d085e4db60c9166eb0c060d0/app/models/dossier.rb#L551

Ça veut dire qu’un dossier terminé, mais sur une démarche qui n’a pas activé l’expiration des dossiers terminée, le dossier n’est pas `expirable`. C’est OK, mais le message affiché ici n’est pas bon :
https://github.com/betagouv/demarches-simplifiees.fr/blob/88e80e9e32bc11e3d085e4db60c9166eb0c060d0/app/views/instructeurs/dossiers/_expiration_banner.html.haml#L30

On affiche toujours que le dossier est en instruction. Il faut faire un message différent si le dossier est terminé. Pour les instructeurs je propose un message qui dit que si l’administration souhaite que les dossiers soient expirés il faut faire une demande au support. Pour les usagers je pense qu’il ne faut pas mettre de message sur les dossiers terminés dans ce cas.

**Comment by tchak** [comment]
corrigé avec #6955

Je continue de penser que ça serait cool de profiter de ce message pour encourager les administrations à demander l'activation de la suppression des dossiers terminée

**Comment by mfo** [comment]
@tchak ; je suis d'accord avec toi sur le principe qu'il faut encourager les admins a demander l'activation de l'expireration des données.  En revanche se sont des vues accessible pour les usagers & instructeurs ; p-e pas le meilleur endroit ? Voici deux propales :

On pourrait l'afficher sur la vue `admin/procedures#index` : 

<img width="1008" alt="Screen Shot 2022-02-18 at 1 48 40 PM" src="https://user-images.githubusercontent.com/125964/154685835-60b8d86e-bbdd-4d08-a96e-b960c169f7d1.png">

On pourrait l'afficher sur la vue `admin/procedures#show`:

<img width="1053" alt="Screen Shot 2022-02-18 at 1 47 35 PM" src="https://user-images.githubusercontent.com/125964/154685708-1555ce44-765e-4af1-b940-a28a8fdb7ebf.png">

Qu'en penses-tu ? as-tu une autre idée ? (sinon on peut simplement intégrer ça dans la newsletter) c'est peut être ce qui demande le moins d'effort et permettrait de bien présenter la chose ?

**Comment by dzc34** [comment]
Bonjour, 

j'ai une question : 
comment s'active l'expiration des données ?

**Comment by mfo** [comment]
Coté DS, pour le moment c'est à la demande en contactant notre support.
Techniquement, c'est un flip sur `procedures.procedure_expires_when_termine_enabled`.
A en parler je me dis que ça pourrait être l'occasion d'une migration pour permettre aux contributeur de définir la valeur par défaut qu'il souhaitent... un avis @mfaure / @akarzim

**Comment by mfaure** [comment]
Merci @mfo de m'inclure dans cette discussion. Pour notre instance, il faut que l'expiration soit activée par défaut, et pour tout le monde. @akarzim est-ce le cas aujourd'hui ?

**Comment by tchak** [comment]
Il faut activer globalement le flag `procedure_process_expired_dossiers_termine` sur votre instance

**Comment by emsnytech** [comment]
Vu les discussions actuelles avec le mi. L'option de suppression par défaut me paraît une bonne chose.
On inverserait alors le principe
Si on ne veut pas qu'elle soit activée il faut nous le demander 
Cela semble par ailleurs la solution pour les démarches de types "dossier permanent de structure " ou bien les dossiers d'investissement qui peuvent avoir des durées de vie de 5 ans, comme prévu par les textes

**Comment by akarzim** [comment]
> Il faut activer globalement le flag `procedure_process_expired_dossiers_termine` sur votre instance

@tchak je découvre l'existence de ce _feature flag_ et je peine à comprendre où il est utilisé ? En effet, les seules mentions explicites qui y sont faites sont celles-ci :
```
spec/system/users/brouillon_spec.rb:171:65:    allow(simple_procedure).to receive(:feature_enabled?).with(:procedure_process_expired_dossiers_termine).and_return(true) 
config/initializers/flipper.rb:36:4:  :procedure_process_expired_dossiers_termine                                                                                       
```

C'est-à-dire la déclaration de ce _feature flag_ à l'initialisation de la gem Flipper, et le _mock_ de celui-ci dans un test. Je passe certainement à côté de quelque chose… 🤔

**Comment by mfaure** [comment]
Information suite au point Équipe DS du 15/03/2022 : 

- le feature flag existant ne suffit pas actuellement
- PR en cours https://github.com/betagouv/demarches-simplifiees.fr/pull/6981
  - la suppression par des dossiers à l'expiration  est activée par défaut pour les nouvelles démarches
  - traitement à faire en plus (variable d'env ? modif en DB pour forcer la colonne)

Et c'est @mfo qui est à la manoeuvre

**Comment by mfaure** [comment]
Information suite au point Équipe DS du 15/03/2022 : 

- le feature flag existant ne suffit pas actuellement
- PR en cours https://github.com/betagouv/demarches-simplifiees.fr/pull/6981
  - la suppression par des dossiers à l'expiration  est activée par défaut pour les nouvelles démarches
  - traitement à faire en plus (variable d'env ? modif en DB pour forcer la colonne)

Et c'est @mfo qui est à la manoeuvre

**Comment by mfo** [comment]
Merci pour la relance Matthieu ; 

Je pense que l'incomprehension est dans les mots... Je me suis mal exprimé `flip` n'est pas lié a `Flipper`. L'active/désactivation (ce que j'entendais par flip) ; est porté par la table `procedures` ; ca s'opere par tuple au niveau de la colonne `procedure_expires_when_termine_enabled`. 

Aujourd'hui c'est un `flip` qui est par défaut a `FALSE` ; pour activer ca globalement il faut : 
- pour les nouvelles procédures : changer la valeur par default SQL
- pour les anciennes procédures : passer une migration (attention nous ne ferons pas ca nous même sinon c'est des millions de mails qui partent)

Est-ce plus clair @akarzim
