### ISSUE TITLE
Updown.io custom domain status page ne fonctionne pas

### ISSUE THREAD

**Issue by benoit-bernier** [betagouv/demarches-simplifiees.fr#7012]
**Décrivez le bug**
La page [https://status.demarches-simplifiees.fr/](https://status.demarches-simplifiees.fr/), accessible depuis le footer (lien *Disponibilité*) ne semble pas être correctement configurée.

**Capture d'écran**
![image](https://user-images.githubusercontent.com/43164960/157195944-48124d97-94cd-417a-b7bf-ef60d69428f5.png)

**Comment by kleph** [comment]
merci pour la remontée, c'est corrigé.

Suite à l'ajout d'une sous page pour un autre test technique à l'outil updown.io, je me suis trompé dans la visibilité de cette page et elle n'était plus accessible publiquement.
