### ISSUE TITLE
ETQ Administrateur je veux pouvoir imprimer un dossier vierge pour le mettre dans mon registre de traitement RGPD.

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#7131]
Situation actuelle:
Les administrateurs peuvent a tout moment imprimer un formulaire en PDF en ajoutant à la fin du lien /dossier_vide
Toutefois, la très grande majorité ne connaissent pas l'astuce.
Par ailleurs, l'édition de ce document pourrait représenter une avancée pour faciliter la vie des administrateurs afin d'inscrire la démarche au sein du registre de traitement.

Situation attendue.

Le lien vers le formulaire PDF est accessible à tout moment dans l'interface administrateur, que l'on soit en test, ou à la publication

**Comment by LeSim** [comment]
export en csv ?
