### ISSUE TITLE
db:migrate - Fail lors de l'application de 20220301160753

### ISSUE THREAD

**Issue by Remi-Frk** [betagouv/demarches-simplifiees.fr#7189]
Bonjour,

Sur "notre" instance demat-social et tr, nous rencontrons l'erreur suivante lors de l'application du db:migrate (tentative de migration de 20211127143736 à 20220407081538)

```
D, [2022-04-22T12:35:56.467840 #331] DEBUG -- :    (0.8ms)  SELECT "administrateurs_procedures"."administrateurs_procedure_id" FROM "administrateurs_procedures" LEFT OUTER JOIN "administrateurs_procedures" ON "administrateurs_procedures"."id" = "administrateurs_procedures"."administrateurs_procedure_id" WHERE "administrateurs_procedures"."id" IS NULL
D, [2022-04-22T12:35:56.468465 #331] DEBUG -- :   TRANSACTION (0.3ms)  ROLLBACK
D, [2022-04-22T12:35:56.469046 #331] DEBUG -- :    (0.3ms)  SELECT pg_advisory_unlock(80405764889057790)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateAlias: ERROR:  table name "administrateurs_procedures" specified more than once
/opt/ds/app/lib/database/migration_helpers.rb:124:in `block in delete_orphans'
/opt/ds/app/lib/database/migration_helpers.rb:114:in `delete_orphans'
/opt/ds/db/migrate/20220301160753_add_administrateur_foreign_key_to_administrateurs_procedure.rb:5:in `up'
```

La requête générée par 20220301160753_add_administrateur_foreign_key_to_administrateurs_procedure n'est pas valide.

Après analyse et test concluant, il semblerait que 

https://github.com/betagouv/demarches-simplifiees.fr/blob/f70344b89b45a78fb79c0266be767bf07ad100ca/db/migrate/20220301160753_add_administrateur_foreign_key_to_administrateurs_procedure.rb#L5-L6

devrait plutôt être (PR à venir en ce sens) :

```ruby
    delete_orphans :administrateurs_procedures, :administrateurs
    add_foreign_key :administrateurs_procedures, :administrateurs
```

La migration est alors passante / la requête de select correcte :

```sql
SELECT "administrateurs_procedures"."administrateur_id" FROM "administrateurs_procedures" LEFT OUTER JOIN "administrateurs" ON "administrateurs"."id" = "administrateurs_procedures"."administrateur_id" WHERE "administrateurs"."id" IS NULL
```

Ce problème n'a PAS d'incidence coté DS.fr ; néanmoins, les autres instances risquent de rencontrer la même situation que nous, en l'état.

PS : 1ère issue sur votre repo ; n'hésitez pas s'il manque quelque chose

**Comment by dzc34** [comment]
@Remi-Frk la PR étant fusionnée, il doit être possible de clôturer ce ticket ?

**Comment by mfo** [comment]
tu as raison @dzc34 ; merci
