### ISSUE TITLE
Si je souhaite m'inscrire à la Newsletter et que je suis déjà inscrit, un message d'erreur non pertinent apparaît

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#726]
![screen shot 2017-09-14 at 10 30 57](https://user-images.githubusercontent.com/28590367/30419785-e8c06a50-9937-11e7-945e-67fcbc1ee62b.png)

**Comment by tchak** [comment]
n'est plus d'actualité je pense
