### ISSUE TITLE
ETQ admin, je souhaite visualiser le recap des modifications apportées lorsque ma démarche close

### ISSUE THREAD

**Issue by CamilyaDellali** [betagouv/demarches-simplifiees.fr#7274]
Actuellement lorsque l'on souhaite modifier une démarche close, le récapitulatif des modifications n'apparait pas si la démarche n'est pas réactivée en amont. Dès lors, l'administrateur ne dispose d'aucune indication concernant la sauvegarde de ces modifications . Pour plus d'infos : https://mattermost.incubateur.net/betagouv/threads/kcrwj9bsjpb5xdrmqdyi3zz35r

**Comment by LeSim** [comment]
On n'arrive pas a voir les modifications que l'on fait sur une démarche que l'on rouvre

**Comment by LeSim** [comment]
Retrovuer les demarches qui utilisent cette features les contactes pour savoir ce qu'ils préfère (ARS bourgogne ...)
