### ISSUE TITLE
ETQ Invité, le système d'identification à TPS n'est pas clair si j'ai déjà un compte usager

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#733]
La personne invité qui a déjà un compte usager  est quand  même obligé de créer un compte TPS (en tant que gestionnaire invité) ==> mais pas de différence pour l'usager qui ne comprends donc pas et va cliquer sur le bouton "connexion" en haut à droite
![screen shot 2017-09-15 at 15 46 11](https://user-images.githubusercontent.com/28590367/30485760-af24de14-9a2e-11e7-9788-bd81f42d7438.png)

**Comment by gregoirenovel** [comment]
- Si je suis déjà connecté en tant qu'usager-> créer automatiquement le compte gestionnaire correspondant et rediriger vers les avis
- Si je ne suis pas connecté -> détecter que j'ai déjà un compte usager, me proposer de me logguer (et non pas de m'inscrire), au log, créer automatiquement le compte gestionnaire correspondant et rediriger vers les avis
