### ISSUE TITLE
regarder comment pousser nos donnée sur le meta-base de betagouv

### ISSUE THREAD

**Issue by mfo** [betagouv/demarches-simplifiees.fr#7337]
A qualifier : 
quelles données ?

**Comment by emsnytech** [comment]
Je dirais pour DS, à vue de nez:

En flux, des données par semaine
Nombre de démarches publiées
Nombre de démarches publiés par sphère ministérielle
Nombre de démarches closes
Nombre de démarches actives = les démarches publiées ou closes ayant eu plus de 3 dossiers déposés sur le dernier mois (glissant donc) c'est le chiffre qui donne le mieux l'activité de DS
Nombre de comptes usagers créés
Nombre de comptes usagers créées avec France connect
Nombre de dossiers commencés
Nombre de dossiers déposés
Nombre de comptes administrateurs créés
Nombre de comptes instructeurs créés

En stock
reprendre les statistiques que nous avons sur notre page....de stats...
