### ISSUE TITLE
ETQ administrateur, je veux que le service soit mieux renseigné et donc renseigner le SIRET du Service

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#7359]
Le dispositif d'enrôlement des services est inopérant quand on veut ensuite trier les démarches par service déployant des procédures.

Alors que nous avions enlevé le SIRET, je propose de le remettre en place, d'autant que depuis 2 ans maintenant on demande aux administrateurs de créer des compte avec leur SIRET, et que cela n'a posé aucun pb.

Les intérêts d'exiger le SIRET lors de la création d'un service sont multiples:
Normalisation
géolocalisation

**Comment by LeSim** [comment]
- voir si on peut récupérer les siret utilisé lors de la création des comptes administrateurs
- attention aux forks (polynésie par exemple) qui n'utilisent pas le siret

**Comment by colinux** [comment]
Liste des infos principales récupérables grâce au SIRET :

- adresse (on en déduira la géoloc)
- adresse du siège
- raison sociale, nom commercial
- forme juridique (nom + code)
- capital social
- effectifs
- code NAF
- état (en activité / en cessation)

A minima nous voulons stocker les coordonnées GPS grâce à l'adresse, les réafficher sur la page du service et les intégrer à l'open data (et plus tard créer une carte etc…)

@emsnytech vois-tu d'autres infos à conserver ? On peut aussi en complément prévoir un lien vers l'annuaire pour facilement visualiser l'ensemble des infos.
