### ISSUE TITLE
Pouvoir changer la description pour le type de champ Carte d'identité

### ISSUE THREAD

**Issue by Olivier-Marcellin** [betagouv/demarches-simplifiees.fr#7381]
Verbatim : « Quand on prend une pièce type carte d’identité le champ Description il est pas changeable, alors que le champ Titre identité il est parfois pratique car je crois qu’on peut mettre un recto et un verso qu’on peut pas mettre dans une pièce jointe classique, donc nous on a voulu faire permis de conduire et pièce d’identité, sauf que quand on voit le descriptif ben ça ne correspond pas du tout, donc on est obligé de revenir sur une pièce classique parce que ce n’est pas modifiable […] parce qu’on pas changé le descriptif »

US : En tant qu'administrateur je peux changer la description pour le type de champ Carte d'identité afin qu'il puisse répondre à mon cas d'usage

Suggestions d'amélioration : un champ description vide ? à remplir ? (plutôt que pré-rempli) ?

**Comment by LeSim** [comment]
pb juridique, on nous a demandé spécifiquement de ne pouvoir prendre que le recto.

On contourne avec #7381
