### ISSUE TITLE
ETQ usager je souhaite pouvoir modifier le SIRET lorsque mon dossier est en brouillon 

### ISSUE THREAD

**Issue by CamilyaDellali** [betagouv/demarches-simplifiees.fr#7386]
Les usagers ne peuvent pas modifier leur SIRET ( démarche s'adressant à des PM)  lorsque le dossier est en brouillon. Ils doivent ainsi déposer le dossier pour avoir la possibilité de le modifier... Idem lorsque la démarche s'adresse à des particuliers, ils peuvent simplement modifier les champs du formulaire et non la partie "identité" pour les dossiers en brouillon.

**Comment by colinux** [comment]
Pour l'instant je suis parti pour reprendre le partial "identité" (simplifié pour les entreprises ?) dans un dropdown 
![Capture d’écran 2022-07-12 à 16 33 22](https://user-images.githubusercontent.com/150279/178515616-b1e7e111-5d28-43c1-985a-8e22280b4d40.png)
