### ISSUE TITLE
Communiquer sur les développements au fur et à mesure

### ISSUE THREAD

**Issue by Olivier-Marcellin** [betagouv/demarches-simplifiees.fr#7396]
Besoin (de communication) exprimé par les équipes d'admin du Ministère de la Culture

Constat

Communication parfois trop tardive et par le seul intermédiaire de l'info-lettre DS

Les équipes aimeraient un canal direct et plus en amont

**Comment by LeSim** [comment]
sources d'info disponible :
- footer : nouveauté
- tchap
