### ISSUE TITLE
Améliorer la lisibilité de la liste déroulant des types de champs

### ISSUE THREAD

**Issue by Olivier-Marcellin** [betagouv/demarches-simplifiees.fr#7400]
Proposition UX

Constat : la liste des types de champs est longue avec 30 types de champs et en ordre alphabétique

Suggestion d'amélioration : ranger par catégories

Cependant il n'y a pas eu de remontées des testeurs sur une difficulté à repérer les champs

Ce serait donc du + en lisibilité 

Voir l'exemple ci-dessous sur l'application Alchemer
<img width="1312" alt="Capture d’écran 2022-05-24 à 15 24 40" src="https://user-images.githubusercontent.com/101646817/170045973-26594947-42bb-4005-8f2d-7d57df27c273.png">
<img width="1312" alt="Capture d’écran 2022-05-24 à 15 24 49" src="https://user-images.githubusercontent.com/101646817/170045987-da697686-315c-4df0-8289-6d72ee2f0138.png">

**Comment by tchak** [comment]
OK, pour grouper les types de champ dans le select html natif

**Comment by E-L-T** [comment]
Nouvelle proposition de liste dans ce pad : https://pad.incubateur.net/s/mOmqxFMby# 
Les types de champ ont été regroupés par catégorie (fonctionnelle ou sémantique) avec un nom pour chacune. Les catégories ont été classées par ordre d'importance, les plus utilisées en premier.

**Comment by mfo** [comment]
ça m'a l'air top !

**Comment by krichtof** [comment]
Très chouette !
Juste une petite remarque : il me semble que les champs Communes, Départements, Régions et Pays peuvent être utilisés pas uniquement pour des questions d'etat civil.

Que penses-tu d'ajouter une catégorie Localisation où l'on mettrait ces champs ?

**Comment by E-L-T** [comment]
Et je suis tenté de supprimer la catégorie Fichier, et de déplacer : 
-  Titre identité vers État civil
- Pièce justificative vers Standard

**Comment by krichtof** [comment]
+1 pour déplacer Adresse vers Localisation, Titre identié vers Etat civil et PJ vers Standard :)

**Comment by E-L-T** [comment]
@Olivier-Marcellin Voilà à quoi ça ressemble :

![Screenshot from 2022-09-27 15-20-36](https://user-images.githubusercontent.com/29131404/192537949-1342f2fa-91b8-45a8-bb65-5e3464649cf7.png)

**Comment by E-L-T** [comment]
Et 2 autres screenshots pour voir l'ordre de l'ensemble des types de champ

![Screenshot from 2022-09-28 11-21-39](https://user-images.githubusercontent.com/29131404/192742237-ef4fdec4-48f0-4713-a4c7-13498bd6fbeb.png)

![Screenshot from 2022-09-28 11-22-02](https://user-images.githubusercontent.com/29131404/192742526-0bc53b8f-c38a-4782-91f6-4708e3d9f0cd.png)

**Comment by Olivier-Marcellin** [comment]
Super ! quel est le comportement lorsque la sélection a été faite ? il y a-t-il une check-line ? si oui cela justifie les alinéas pour les types de champs, sinon aligner à la verticale de titres de catégories

**Comment by E-L-T** [comment]
> Super ! quel est le comportement lorsque la sélection a été faite ? ( il y a-t-il une check-line ? si oui cela justifie les alinéas pour les types de champs, sinon aligner à la verticale de titres de catégories)

Ça donne ça une fois la sélection faite. Il n'y a pas de ligne, le design (catégorie en gras et tdc en alinéas) est géré par le select natif, si on voulait aligner je pense qu'il faudrait passer sur un select custom :

![Screenshot from 2022-09-28 14-46-04](https://user-images.githubusercontent.com/29131404/192782251-1ef6198b-5a36-4923-9ab0-c3c69d323ca0.png)


> 
> Il y a un type de champ sélectionné par défaut à l'ouverture c'est bien ça ? on peut faire comme ça pour l'instant, conformément à l'existant.

Oui c'est le champ texte qui est sélectionné par défaut, comme c'était déjà le cas avant. Je ne sais pas si c'est idéal vu que maintenant il est au milieu de la liste, dans la 4e catégorie. Peut-être le remplacer par un autre, mais lequel ?  Le tout premier de la liste, "Titre de section", ne paraît pas une bonne option parce qu'il a un affichage particulier. À discuter...

> 
> Mais pour l'accessibilité et le passage au dsfr, je me demande si on devra pas mentionner "sélectionnez une option" (ou sélectionner), comme sur la charte (ci-joint capture écran du composant formulaire dans la version Beta
> 
> <img alt="Capture d’écran 2022-09-28 à 11 40 32" width="643" src="https://user-images.githubusercontent.com/101646817/192746500-ca71852f-51d1-4410-a1be-0c584b250fa0.png">

Ça me parait une bonne idée mais je ne me rends pas compte des possibles effets de bord. Je pense qu'il faudrait modifier le modèle de données pour qu'un nouveau type de champ n'ait pas encore de catégorie à sa création

**Comment by Olivier-Marcellin** [comment]
oui on peu faire ça en attendant le passage au dsfr et on se reposera le problème à ce moment, si on veut outrepasser le problème technique des catégories, alors il faudrait passer sur une liste customisée
