### ISSUE TITLE
ETQ Usager, je veux voir le champs date et heure sur une seule ligne

### ISSUE THREAD

**Issue by benoit-bernier** [betagouv/demarches-simplifiees.fr#7410]
## Problème
L'affichage du champ date et heure se fait de manière verticale : 
![image](https://user-images.githubusercontent.com/43164960/170233778-711a4acb-3ff6-4c74-b330-94b777014600.png)
Ce n'est pas très naturel et voir une longue liste de champs à remplir peut faire peur. Il serait plus judicieux de l'afficher en ligne horizontale comme ceci : 
![image](https://user-images.githubusercontent.com/43164960/170234219-2d9185f6-9752-4ca1-8991-0802131c8f83.png)

## Solution
Prototypé très rapidement comme ceci : 
```html
<div class="datetime" style="display: flex;
  justify-content: space-between;">
```
&nbsp;+ encapsulation des `<label>` et `<select>` dans des `<div>`

Une autre solution serait d'utiliser les sélecteurs natifs `<input type='date'>` et `<input type='time'>`, facilitant aussi l'accessibilité de ces composants.

**Comment by kemenaran** [comment]
Merci pour la remontée de bug ! Effectivement c'est une régression d'il y a quelques semaines, mais ce n'est pas normal. J'ai ouvert une PR, ça devrait être corrigé en prod dans les prochains jours.

On pense aussi à remplacer les select par des inputs date et time, à un moment – mais ça sera un chantier pour un peu plus tard.
