### ISSUE TITLE
ETQ instructeur, je ne comprends pas comment trier mes dossiers en mettant ceux qui ont une notif en premier

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#7476]
Par exemple, je suis un instructeur qui suit 6 dossiers. L'onglet suivi a une pastille orange qui m'indique qu'au moins 1 dossier à une notification

![Screenshot 2022-06-21 at 12-04-26 attestation · demarches-simplifiees fr](https://user-images.githubusercontent.com/907405/174774857-7364b03c-0e1e-4fbe-b0b8-f26ef645e564.png)

Ici, il est visible en bas de la liste, mais il pourrait être sur une autre page.

Si je clique sur le bouton noir
![Capture du 2022-06-21 12-05-19](https://user-images.githubusercontent.com/907405/174775086-29e618d7-550f-4f10-8f14-eaffcc053b44.png)

Je vais trier les dossier en mettant ceux avec des notifications en premier

![Screenshot 2022-06-21 at 12-05-36 attestation · demarches-simplifiees fr](https://user-images.githubusercontent.com/907405/174775187-258f6cd4-ea35-4420-af70-3dc53f697819.png)

Malheureusement, cette action est peu connue des instructeurs qui passent souvent à coté.

Une idée pour améliorer cette interface ?

**Comment by Olivier-Marcellin** [comment]
voici la conception ux https://www.figma.com/proto/4YFFD4qBLhBzJMYvwIMxTc/Tri-des-dossiers?page-id=1%3A2&node-id=2%3A2335&viewport=342%2C764%2C0.34&scaling=min-zoom&starting-point-node-id=2%3A2335
