### ISSUE TITLE
ETQ Instructeur, je veux avoir la possibilité d'être notifié par email à chaque nouvel avis déposé

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#7496]
Retour usager
Bonne idée

**Comment by emsnytech** [comment]
OK... mettre cela en option lors de la création des experts au niveau de l'administrateur certainement pour ne pas spamer... ou alors traiter cela dans le tableau de bord.. ou un tableau des notifications...
surtout que quand l'option est sélectionné ( les expert ne peuvent voir les avis déposés par d'autres experts) cette option est inutile.
A discuter en effet
En premier lieu, le plus simple... informer l'instructeur qui a saisi un expert que l'expert a donné son avis...
Le pb... c'est le spam potentiel ...

**Comment by kara22** [comment]
@emsnytech Ok ça marche. 

Je vois plusieurs choses à faire :
- ETQ Instructeur, lorsqu'un expert dépose un avis, je veux être notifié par mail (aujourd'hui ce n'est pas le cas)
- ETQ expert, lorsqu'un autre expert dépose un avis sur une démarche ou je suis sollicité, je veux être notifié par mail (aujourd'hui ce n'est pas le cas)

Je pense qu'il faudrait qu'on explore de plus près la page dédiée aux notifications (cc @tchak @Olivier-Marcellin ) car ça va faire beaucoup d'envois de mail sachant qu'il y a environ 1500 avis déposés par jour.

J'attends vos retours avant de continuer le code.

**Comment by tchak** [comment]
>Je pense qu'il faudrait qu'on explore de plus près la page dédiée aux notifications

Oui ! 💯

**Comment by kara22** [comment]
Merci pour ton retour @tchak. Du coup je peux archiver cette issue et reprendre celle du centre de notification pour cadrage ? @Olivier-Marcellin @emsnytech 

Mon avis serait de ne pas envoyer les e-mails (éviter le spam) pour l'instant et de cadrer plutôt l'issue sur les notifs

**Comment by kara22** [comment]
@dzc34 Ok je m'en occupe
