### ISSUE TITLE
ETQ instructeur l'export au format ZIP des dossiers d'une démarche est en erreur

### ISSUE THREAD

**Issue by akarzim** [betagouv/demarches-simplifiees.fr#7514]
**Décrivez le bug**
En tant qu'instructeur, l'export au format ZIP des dossiers d'une démarche reste dans l'état « est en train d'être généré », car le job asynchrone retourne une erreur 500 :

```
undefined method `in_batches' for [#<Dossier …>]:Array
```

**Reproduction**
Comment reproduire le problème :
1. Aller sur la page d'une démarche en tant qu'instructeur
2. Cliquer sur "Télécharger X dossiers"
3. Cliquer sur "Demander un export au format .zip"

Comment constater le problème :
1. Aller sur la page `manager/delayed_job/failed` en tant que super admin
2. Une erreur `undefined method 'in_batches'` apparaît

**Comportement attendu**
Un export des dossiers aurait dû être généré sans erreur.

**Analyse du comportement observé**
Le service `ProcedureExportService` (`app/services/procedure_export_service.rb`) possède une méthode `#to_zip` qui fait l'appel suivant : 

```ruby
attachments = ActiveStorage::DownloadableFile.create_list_from_dossiers(dossiers, true)
```

Les dossiers passés à la méthode sont manipulés comme ceci à l'initialisation du service : 

```ruby
@dossiers = dossiers.downloadable_sorted_batch
```

La méthode `#downloadable_sorted_batch`, appelée sur `dossier` (une instance de `Dossier::ActiveRecord_Relation`), retourne un `Array`.

Or, `ActiveStorage::DownloadableFile#create_list_from_dossiers` fait appel à : 

```ruby
PiecesJustificativesService.liste_documents(dossiers, for_expert)
```

Qui elle-même fait l'appel suivant : 

```ruby
docs = dossiers.in_batches.flat_map do |batch|
  # …
end
```

Et à ce moment-là, `dossiers` est un Array et non plus une relation ActiveRecord, d'où l'erreur.

Par ailleurs, il semblerait que cette méthode `ProcedureExportService#to_zip`, contrairement à `#to_csv` et `#to_xlsx`, ne fasse pas l'objet de tests automatisés, ce qui peut expliquer pourquoi ce bug est resté sous les radars jusqu'ici.

**Capture d'écran**

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/130560/176889959-e09c10b5-40d6-4545-9611-40e412225611.png">

<img width="1559" alt="image" src="https://user-images.githubusercontent.com/130560/176891895-ea3cae78-7589-4227-bea9-8c5d470ccab1.png">

**Logs**
```
--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper
job_data:
  job_class: ExportJob
  job_id: e684363f-50ab-41b5-82b0-144394e01aa7
  provider_job_id: 
  queue_name: exports
  priority: 
  arguments:
  - _aj_globalid: gid://tps/Export/2
  executions: 0
  exception_executions: {}
  locale: fr
  timezone: Paris
  enqueued_at: '2022-06-20T13:46:59Z'

undefined method `in_batches' for [#<Dossier id: 2, …>]:Array
/app/app/services/pieces_justificatives_service.rb:5:in `liste_documents'
/app/app/lib/active_storage/downloadable_file.rb:5:in `create_list_from_dossiers'
/app/app/services/procedure_export_service.rb:32:in `to_zip'
/app/app/models/export.rb:178:in `blob'
/app/app/models/export.rb:67:in `compute'
/app/app/jobs/export_job.rb:7:in `perform'
```

**Appareil et navigateur utilisé**
 - Appareil : Mac
 - Navigateur : Firefox

--- 

@adullact & @synbioz

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités.
> - C'est dans ce cadre que @synbioz nous propose certains correctifs et autre remontées de bug comme celle-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

---

`trackingAdullactContrib`

**Comment by tchak** [comment]
j'ai bien l'impression que le problème à était corrigé par le commit suivant https://github.com/betagouv/demarches-simplifiees.fr/commit/79c473ecf9f8f7c6312af8c3be6ef40f08aaab44

**Comment by akarzim** [comment]
> j'ai bien l'impression que le problème à était corrigé par le commit suivant [79c473e](https://github.com/betagouv/demarches-simplifiees.fr/commit/79c473ecf9f8f7c6312af8c3be6ef40f08aaab44)

Mais tout à fait ! Comment ai-je pu passer à côté !?
C'est donc corrigé par la PR https://github.com/betagouv/demarches-simplifiees.fr/pull/7183, elle-même mergée  et disponible depuis la version 2022-04-27-01 (https://github.com/betagouv/demarches-simplifiees.fr/pull/7204).

Merci @tchak pour avoir retrouvé ce commit 🙇
