### ISSUE TITLE
ETQ super admin, je veux activer la suppression automatique pour les vieilles démarches

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#7562]
En partant des démarches les plus anciennes, l'interface manager propose une une sélection de (10, 100, 1000) démarches ou activer la suppression automatiques

en plus il affiche le nombre de dossiers concernée par démarche

le super admin peut accepter le batch, exclure une procédure, activer que pour une procédure.

un mail est envoyé à l'administrateur que le processus est activée, y préciser qu'un export est disponible (envoyer vers la doc pour les exports)

Par ailleurs, une alerte est présente sur l'interface d'admin de la démarche précisant que l'on a activé pour lui la suppression automatique

**Comment by mfo** [comment]
Condition spéciale. 

Les dossier liés ; quid si je supprime un dossier lié
