### ISSUE TITLE
ERROR: update or delete on table "services" violates foreign key 

### ISSUE THREAD

**Issue by tchak** [betagouv/demarches-simplifiees.fr#7626]
https://sentry.io/organizations/demarches-simplifiees/issues/3207553897/?project=1429550&query=is:unresolved+is:for_review+assigned_or_suggested:%5Bme,+none%5D&sort=inbox

**Comment by colinux** [comment]
Ça arrive lorsqu'un admin veut supprimer un service, alors qu'il est encore rattaché à une procédure `hidden` (alors que du point de vue de l'admin la démarche a déjà été supprimée).
Je pense unset le service_id de ces procédures discarded pour pouvoir supprimer le service tout en gardant le flow normal des suppressions de procédures.
