### ISSUE TITLE
L'URL de direct upload expire si la page est ouverte trop longtemps

### ISSUE THREAD

**Issue by tchak** [betagouv/demarches-simplifiees.fr#7663]
Si la page reste ouverte trop longtemps, l'URL de direct upload expire. On devrait rafraîchir ces URL en cas d'erreur.

**Comment by colinux** [comment]
@tchak Est-ce que tu un as truc en particulier qui te fait penser qu'il ya une d'expiration de l'url ? A première vue je ne vois que le CSRF Token qui pourrait expirer… au bout d'1 an.

Est-ce que ce ticket fait référence à cette erreur, ou s'en est une autre ?
https://sentry.io/organizations/demarches-simplifiees/issues/3393937019/?project=1429547&query=is%3Aunresolved
