### ISSUE TITLE
ETQ administrateur ; je dois être informé que les liens de documents hébergés (ex: modele de PJ, guide démarche) ne sont pas partageables

### ISSUE THREAD

**Issue by mfo** [betagouv/demarches-simplifiees.fr#7681]
cf: https://secure.helpscout.net/conversation/1962196122/1984435/

~idée : mettre des liens publiques sur les modeles de piece jointe~

On prévient qu'on est pas dropbox, c'est pas autorisé/possible

**Comment by emsnytech** [comment]
Oups !!!! Règle de sécu...
Pas ok 
On en discute ?
