### ISSUE TITLE
Traduction manquante sur une option de conditionnel

### ISSUE THREAD

**Issue by mfo** [betagouv/demarches-simplifiees.fr#7683]
![y3sEHVBPmFyKFA5a](https://user-images.githubusercontent.com/125964/185930033-4d1b4908-8f2f-4c28-b076-b5bd87c42c8f.png)

**Comment by LeSim** [comment]
tu actives la logique conditonnel poru ton utilisateur `Flipper.enable(:conditional, ton_user)`
tu vas dans l'éditeur de champ
tu fais un premier champ de type `choix parmi une liste`
tu fais un second champ de type text
sur le second champ tu actives la logique conditionnel et tu rajoutes une condition de type non equal
tu retournes sur le premier champ et tu change son type en nombre entier

**Comment by sebastiencarceles** [comment]
À mon avis ce bug n'existe plus : 

![image](https://user-images.githubusercontent.com/1193334/188803954-7463f978-1592-4a54-8192-794ed1a43fdb.png)

La traduction a peut-être été ajoutée dans l'intervalle ?

![image](https://user-images.githubusercontent.com/1193334/188803834-700125b2-1b0e-49fc-9d40-271460936012.png)



https://user-images.githubusercontent.com/1193334/188803862-dd8289bd-2201-4ec2-af73-e00fea878826.mp4

**Comment by LeSim** [comment]
ah merde, déso pour le temps perdu, merci pour la belle vidéo

**Comment by sebastiencarceles** [comment]
> ah merde, déso pour le temps perdu, merci pour la belle vidéo

Aucun problème, ça me permet de découvrir du périmètre :)
