### ISSUE TITLE
ETQ admin, je veux pouvoir associer plusieurs zones à une démarche

### ISSUE THREAD

**Issue by krichtof** [betagouv/demarches-simplifiees.fr#7692]

**Comment by Olivier-Marcellin** [comment]
Ajouts UX/UI pour l'accessibilité :

- Tags sur les résultats filtrés
- fil d'ariane depuis la page se connecter (N1)
- barre sticky (retour en arrière en page N3)
 https://www.figma.com/file/nYx0J2lQKGVZDN13apcWLV/Mes-d%C3%A9marches-par-zone?node-id=519%3A20456
