### ISSUE TITLE
ETQ super-admin, problèmes démarches <> admin/instructeur

### ISSUE THREAD

**Issue by colinux** [betagouv/demarches-simplifiees.fr#7699]
J'ai relevé ces problèmes pour s'associer à une démarche existante depuis le manager :

1. le form "Ajouter un administrateur" ignore l'email saisi, à la place ça associe le super-admin connecté https://github.com/betagouv/demarches-simplifiees.fr/blob/8cd8e6064ab8384b6c5aaed4a558f8d674c39e00/app/controllers/manager/procedures_controller.rb#L68  Je ne sais plus quel comportement doit être conservé. De + le wording explicatif n'est pas clair: _ETQ support quand un **usager** (?) a besoin de devenir administrateur sur une démarche_ 
2. On peut s'associer ETQ admin + instructeur, en revanche à la suppression ça ne supprime que l'admin et pas l'instructeur, ce qui provoque une duplicate entry error si on ré-essaie de s'associer ETQ instructeur => #7738
3. est-ce qu'on ne rajouterait pas un cheat en dev pour by-passer la confirmation par un autre super-admin ? Par exemple https://github.com/betagouv/demarches-simplifiees.fr/blob/8cd8e6064ab8384b6c5aaed4a558f8d674c39e00/app/controllers/manager/procedures_controller.rb#L76 on rajouterait `|| Rails.env.development?` c'est moche mais sinon en environnement de dev on peut plus faire de support, alors que justement ce serait à favoriser car on a des données anonymisées
4. sur le même principe, les exports sont bloqués ETQ instructeur super-admin, mais en dev avec des données anonymes ça pourrait aider à résoudre des problèmes support liés aux exports. Est-ce qu'on ne les ré-autoriserait pas en dev ?

**Comment by mfo** [comment]
Merci pour cette issue, ca vient de moi ce micmac.

pour répondre.

1. un bug, clairement a fixer
2. un angle mort, en gros : ETQ super admin, je peux m'ajouter a une démarche (dans un context de support/bug) pour la journée. La nuit un cron nettoie ca. cf: https://github.com/betagouv/demarches-simplifiees.fr/blob/main/app/jobs/cron/purge_manager_administrateur_sessions_job.rb. L'angle mort vient de la fonction "se retirer de la démarche" ; qui ne devrait s'appliquer qu'aux instructeur/admin non flaggé via `manager: true`
3. ok
4. ok

**Comment by sebastiencarceles** [comment]
@mfo je serais preneur d'informations plus détaillées ici stp. Éventuellement ça pourrait être censé d'éclater ce ticket en 4, histoire de ne pas tout mélanger pour moi qui arrive sur le projet :)

Considérons que le présent ticket concerne le bug évoqué en 1. Je n'arrive pas à le reproduire. Est-ce que tu peux me décrire une procédure ?

De mon côté, j'ai : 
1. créé une nouvelle démarche avec un user "test@exemple.fr"
2. ajouté l'administrateur "test2@exemple.fr"

Ce que je constate, c'est qu'il est bien ajouté : 

![image](https://user-images.githubusercontent.com/1193334/188809150-d06bb68a-d663-4c54-a82f-b3ea8bb586f8.png)

Donc je ne constate pas le bug décrit : 
> le form "Ajouter un administrateur" ignore l'email saisi, à la place ça associe le super-admin connecté

**Comment by colinux** [comment]
Sur le bug 1, il s'agit d'être connecté ETQ **super-admin** (c'est à dire grosso modo, l'équipe DS). On s'y connecte depuis `/manager`, mais pour ça au préalable il faut que tu t'es créé un compte en base (cf seeds.rb). A la connexion ça te demandera d'activer l'OTP (ce qui peut être assez relou en dev la première fois) :
- il faut set dans .env un `OTP_SECRET_KEY` bidon mais suffisamment long
- a priori c'est bypassable si `SUPER_ADMIN_OTP_ENABLED` faut autre chose qu`enabled`.

**Comment by sebastiencarceles** [comment]
Merci pour ces précisions @colinux !

Du coup le form qui pose problème c'est celui-ci ?

![Screenshot 2022-09-07 at 10-09-21 Détails démarche de test #1 - Tps](https://user-images.githubusercontent.com/1193334/188825925-75a18881-e65d-4c27-91f5-ebd8f6337773.png)

Je pense bien que oui car :

![image](https://user-images.githubusercontent.com/1193334/188826093-35a0025c-a35f-4df8-ae2a-97ce2b200870.png)

Ce n'est pas la bonne adresse email qui est indiquée ici.

**Comment by colinux** [comment]
c'est bien ça ! de mémoire dans le controller on cherche pas à récupérer le param mais on utilise le current user

**Comment by sebastiencarceles** [comment]
@colinux est-ce que ce serait possible de détailler les points 2, 3 et 4 dans de nouveaux tickets, avec plus d'infos de contexte ? En l'état, je vais avoir des questions sur chaque point, et ça va vite se mélange si j'aborde tout ici. Qu'en penses-tu ?

**Comment by colinux** [comment]
@sebastiencarceles  pour le 2: #7738
