### ISSUE TITLE
ETQ Usager, je souhaite visualiser un footer au DSFR

### ISSUE THREAD

**Issue by kara22** [betagouv/demarches-simplifiees.fr#7718]

**Comment by Olivier-Marcellin** [comment]
voici les corrections pour le footer vue par les seuls usagers suite à l'échange avec Camille Come :

La recommandation a été : ce footer ne doit pas être le même que "Liens - item" du DSFR (on ne peut pas copier l'identité graphique d'un autre footer)

Corrections :
- footer sur fond blanc (meilleure lisibilité du logo France Services)
- surlignement des liens externes
- une seule couleur de texte "defaultgrey" (noir) pour les informations et titres de catégories
- version du footer en mode sombre 
- version du logo France Services en mode sombre (intégration ultérieure de cette version pour l'accessibilité)

Remarque : à vérifier avec philippe, il me semble qu'il nous a dit de ne pas mettre de liens pour l'instant vers France Services

<img width="871" alt="Capture d’écran 2022-09-27 à 13 05 10" src="https://user-images.githubusercontent.com/101646817/192511668-0a3e60cb-b517-4fa8-9a97-5c00bbad01ca.png">

<img width="761" alt="Capture d’écran 2022-09-27 à 13 16 41" src="https://user-images.githubusercontent.com/101646817/192511676-562f3b32-ba80-4a63-9124-0c3e112150f8.png">

**Comment by Olivier-Marcellin** [comment]
les liens vers la doc et la FAQ sont sur le footer générique (accessible sur la page d'accueil), faut-il ajouter ces liens sur le footer usagers aussi ?

**Comment by colinux** [comment]
@kara22 @Olivier-Marcellin juste pour info dans une autre PR que que je finirai lundi ou mardi : 
- j'ai réglé le pb du surlignement de certains liens qui n'apparaissait pas correctement à certains endroits (comme dans le footer et le lien etalab),
- un léger décalage vertical sur la position de l'icône externe et la ligne de soulinement.
- certains liens en noir qui doivent bien être en gris

Y a pas mal de conflits entre le DSFR et le reset css qu'on utilise.
