### ISSUE TITLE
ETQ Administrateur je peux associer des tags à une démarche

### ISSUE THREAD

**Issue by colinux** [betagouv/demarches-simplifiees.fr#7733]
et 

ETQ Administrateur je peux créer un tag (qui sera utilisable ensuite par l'ensemble des administrateurs, toute zone confondue)

(cf meta issue #7588)

**Comment by kara22** [comment]
Je trouve cette fonctionnalité intéressante qui va même nous servir à faire des statistiques par tags pour savoir quel sujet de démat remonte le plus pour pouvoir orienter (pourquoi pas) le bizdev dessus.

J'ai un premier travail de conception de la base :

<img width="740" alt="image" src="https://user-images.githubusercontent.com/21340608/193510402-b924934f-b7a7-40e5-890a-4364fe505dd2.png">

Dans une V1 l'idée serait simplement d'associer une démarche à un tag et que les admins puissent voir la listes des tags disponibles (toute zone confondue).


Questions :

- @colinux @krichtof @mfo @tchak que pensez-vous de la conception du modèle ? Des booléens à rajouter ou autre ?

- Est-ce que pour les nouvelles features de ce type, un design est préalablement nécessaire @Olivier-Marcellin @emsnytech  ?

**Comment by krichtof** [comment]
Oui, c'est aussi le modèle que j'ai en tête :)
Dit autrement, l'idée est de créer une relation `has_and_belongs_to_many` entre `Procedure` et `Tag`

**Comment by mfo** [comment]
J'ai pas suivis la collecte du besoin donc mon commentaire sera peut-être inutile : @krichtof 
- j'ai juste une petite crainte concernant le fait de laisser les admins choisir les tags. Ne pourrions nous pas recupérer une liste "fermée", ça pourrait eviter trop de tags ou des doublons etc...
- de la même manière, possible d'avoir cette liste dans un yaml (l'idée serait de permettre aux instance de personnaliser up-front)

**Comment by kara22** [comment]
+1 pour la liste fermée mais à concevoir avec quelques admins ? @mfo @Olivier-Marcellin ?

**Comment by krichtof** [comment]
Voici ce qu'on s'est dit en point du 7/10/2022 avec @tchak @LeSim @Olivier-Marcellin 

- un admin peut associer des tags à une démarche (des tags déjà existants ou pas). 
- un superadmin peut également associer des tags à une démarche (#7877 )

Pour associer des tags à une démarche, l'admin utilisera un autocomplete (qui l'incitera à utiliser des tags déjà existants, mais il pourra également saisir un nouveau tag). 

On peut imaginer que les tags créés par les superadmins seront présentés en premier dans la liste renvoyée par l'autocomplete (peut-être pas dans la première itération)
