### ISSUE TITLE
ETQ ADMINISTRATEUR je veux pouvoir proposer un numéro RNA dans un formulaire

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#7762]
Des démarches demandent le numéro RNA, indépendamment d'un numéro SIRET

Dans un premier temps, la création d'un numéro RNA comme un nouveau type de champs semble le plus faisable.

**Comment by damienlethiec** [comment]
Je me lancerais bien là dedans. Je peux bien me baser sur ce qui est fait pour le SIRET en l'adaptant au format (notamment) du RNA ? Aussi, @LeSim (ou quelqu'un d'autres) tu pourrais me donner les droits pour que je puisse m'assigner à une issue ? Je n'ai pour l'instant pas le droit de faire ça (ni d'ajouter des labels, changer de statut, etc.)

**Comment by damienlethiec** [comment]
N'hésitez pas aussi si j'ai des infos complémentaires à savoir

**Comment by damienlethiec** [comment]
Est-ce qu'on doit mettre en  place une sécurité particulière pour éviter qu'un formulaire soit créé avec SIRET + RNA et que les infos rentrées ne soient pas cohérentes (2 structures différentes renvoyées par l'API) ? Ou alors c'est le problème des personnes qui recevront les dossiers ?

**Comment by damienlethiec** [comment]
Pas de besoins pour la question au dessus
