### ISSUE TITLE
ETQ Usager, je peux déposer un dossier avec une entrée SIRET ou un champ SIRET alors que l'api est cassé

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#7766]
- on prend la siret
- on rajoute un lien vers l annuaire entreprise (ou on le scrappe) pour faire un affichage à l'admin et l'usager pour qu'il confirme
- on refait les appels plus tard

Remarques, parfois juste certaines parties de l'api sont cassées

**Comment by emsnytech** [comment]
ne pourrions nous pas ajouter à la fin que dès que le basse de l'insse sera disponible, les information seront mises à jours dans le dossier, et qu'il pourra revenir vérifier ces dernières.
