### ISSUE TITLE
ETQ usager connecté, je ne devine pas le menu déroulant sous mon email

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#7774]
![Screenshot 2022-09-19 at 10-06-54 demarches-simplifiees fr](https://user-images.githubusercontent.com/907405/190975024-1e66f9dc-cb67-46c6-ab5f-b7324a9d2b70.png)

le petit triangle a coté de la langue permet de supposer un menu déroulant. Il n'y a aucun indice autour de l'email qui permet de deviner un menu déroulant

**Comment by DanteZ5** [comment]
@LeSim : si tu peux check la [PR](https://github.com/betagouv/demarches-simplifiees.fr/pull/7785) ^^
