### ISSUE TITLE
ETQ visiteur, je souhaite voir le footer au DSFR

### ISSUE THREAD

**Issue by kara22** [betagouv/demarches-simplifiees.fr#7780]

**Comment by Olivier-Marcellin** [comment]
Quelques correction suite à l'échange avec l'UI de l'équipe DSFR Camille Come

Ajouter le bloc lettre d'information

Bloc liens :
- Ajouter à la colonne Communication "Contactez-nous" (pas de mise en avant de la page contact dans le header, seulement depuis le footer)

Bloc marque :
- Modifier la phrase : Démarches (é accent aigu à Démarches) simplifiées "est un service" propulsé par la
- Ajouter à la fin de la phrase entre parenthèses (DINUM).
- Surligner "direction interministérielle du numérique."
- Surligner "Le code source"

<img width="850" alt="Capture d’écran 2022-09-26 à 22 48 22" src="https://user-images.githubusercontent.com/101646817/192379325-47f59640-3c14-4765-b951-29675f4ef194.png">

**Comment by emsnytech** [comment]
L'abonnement à la lettre n'est pas ouverte aux usagers
