### ISSUE TITLE
Etq Instructeur, je n'arrive pas à télécharger le tableau Excel "tous les dossiers"

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/demarches-simplifiees.fr#799]
![image001-1](https://user-images.githubusercontent.com/28590367/31332277-099a8d8e-ace6-11e7-8973-0a6ed726e9bd.png)

**Comment by gregoirenovel** [comment]
Je suppose que c'est car les perfs sont mauvaises, donc timeout de unicorn au bout de 30 secondes -> 502.

On a parfois des erreurs identiques pour des recherches sur des procédures avec beaucoup de volume (d'après @icollombet).

Vous en pensez-quoi @LeSim et @mmagn ?

Pistes :
- améliorer nos requetes
- utiliser puma au lieu d'unicorn en prod

**Comment by mmagn** [comment]
On a également le problème sur la recherche ?

**Comment by gregoirenovel** [comment]
Oui, des 502 sur les procédures avec bcp de dossiers : tu vas sur le compte de prod d'Ivan, partie accompagnateur, tu recherches "a" -> 502. Là c'est un cas particulier mais ça doit se produire sur des requetes classiques en cas de forte affluence sur le site

**Comment by gregoirenovel** [comment]
Dernier problème : on n'a (il me semble) aucune remontée des 502

**Comment by gregoirenovel** [comment]
Première solution : #809

**Comment by LeSim** [comment]
proposition: passer en async ... ou faire du rust

**Comment by Keirua** [comment]
on a dupliqué cette issue dans https://github.com/betagouv/demarches-simplifiees.fr/issues/4059 plus récente
