### ISSUE TITLE
L'API Carto renvoie des 500

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#810]
https://sentry.apientreprise.fr/apientreprise/tps/issues/1869/

**Comment by kemenaran** [comment]
C'est toujours le cas – mais ça indique vraiment que l'API carto a des soucis.

Est-ce qu'on va y faire quelque chose ?

**Comment by gregoirenovel** [comment]
Ça serait pas mal qu'on identifie s'il y a des cas problématiques qui reviennent, les notifier à l'équipe qui gère l'API, suivre leur investigation du sujet, etc.
