### ISSUE TITLE
Passer le cadastre de API Carto à API Géo

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#814]

**Comment by mmagn** [comment]
Nous sommes les derniers utilisateurs de cette version de l'api. Le service n'est plus assuré. La migration prend 15 min d'après Jérôme.

Plus de détails dans la discussion sur `#etalab-geo` du 05/07/2018.

**Comment by kemenaran** [comment]
@jdesboeufs Il parait que l'API Carto va bientôt couper :) Mais on a perdu les infos de migration dans Slack.

Il y a un chemin de migration de l'API Carto à l'API Geo ?

**Comment by Keirua** [comment]
Suite à notre discussion, nous utilisons l'API carto pour le cadastre et les quartiers prioritaires:
```ruby
# config/initializers/urls.rb
3:API_CARTO_URL = ENV.fetch("API_CARTO_URL", "https://apicarto.sgmap.fr")

# app/lib/api_carto/api.rb
3:    url = [API_CARTO_URL, "quartiers-prioritaires", "search"].join("/")
8:    url = [API_CARTO_URL, "cadastre", "geometrie"].join("/")
```
Il semble qu'il suffise de remplacer simplement le domaine chez `sgmap` par `apicarto.ign.fr`. On a des tests automatisés, je vais regarder.

**Comment by Keirua** [comment]
- idéalement il faudrait remplacement le endpoint RPG (à quoi ça sert exactement ?) par un équivalent du portail IGN :

```ruby
url = [API_GEO_SANDBOX_URL, "rpg", "parcelles", "search"].join("/")
```
 - l'API adresse et le reste de l'API géo ne sont pas concernés par le débranchement qui aura lieu au plus tard le 31/08.

**Comment by kemenaran** [comment]
En ce moment l'API IGN n'expose pas certaines fonctionnalités de l'API Carto – notamment la recherche dans le cadastre par zones géographiques. @Keirua est en train de voir comment préserver la fonctionnalité.

**Comment by Keirua** [comment]
C'est encore en cours de discussions mais 2 options se dessinent:

 - passer aux APIs de l'IGN, mais en l'état elles ne sont pas identiques ou semblent ne pas fournir tout ce dont on a besoin. Il faut discuter avec eux pour faire un point là dessus
 - rester sur les apis Dinsic, et suivre les évolutions et décommissionnements de services qui arrivent

Concernant le cadastre, on utilise actuellement https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/config/initializers/urls.rb#L3

Il faut désormais utiliser https://sandbox.geo.api.gouv.fr/apicarto (qui utilise https://github.com/etalab/apicarto#docker)
Dans quelques semaines, on pourra éventuellement passer à https://geo.api.gouv.fr/ (qui fournit des données plus récentes) mais actuellement il y a des fonctionnalités qui manquent.

**Comment by kemenaran** [comment]
À priori l'IGN envisage d'ouvrir certaines APIs à DS, qui feraient ce dont on a besoin pour remplacer l'API Carto. À voir avec eux si ca colle niveau features et timing.

**Comment by jdesboeufs** [comment]
Faudrait surtout expliciter ce dont vous avez besoin avant tout.
Il y a 1000 manières de faire une API "cadastre".

**Comment by emsnytech** [comment]
Le besoin est le même depuis 4 ans.... mais il peut être traité en effet différemment.
Fonctionnement actuel, à minima.
A partir du dessin (lasso fermé) réalisé avec Léaflet sur le module de carte de ds, je fais remonter les parcelles cadastrales croisées par le dessin. Les informations sur les parcelles sont intégrées dans le dossier.
Variante:
A partir d’un niveau de zoom à définir, on fait apparaître les parcelles cadastrales et l’usager les sélectionne en cliquant dessus.
Les informations sont remontées dans le formulaire.
Au delà de ces informations cadastrales, nous devrions être en mesure de faire remonter d’autres info d’autres api, qui pourront être définies dans l’interface administrateur (l’idee est bien d’ajouter d’autres ressources que celles actuelles pour couvrir d’autres besoins , nature 2000, zone constructible etc, etc....

**Comment by kemenaran** [comment]
Mise à jour :

- L'API Carto va toujours bien être coupée au 31 décembre 2019
- @jdesboeufs est chaud pour bosser sur les sujets cartos
- On était supposé avoir un financement de DGALN, mais signature de la convention est retardée par le changement de nom de la DINUM 🤦‍♂ 
- On pourrait aussi travailler avec l'IGN :
    - Ça serait bien car les APIs seraient maintenues de leur côté ;
    - Mais pour l'instant l'IGN n'a pas les APIs dont on a besoin ;
    - Et leurs API sont régulièrement coupées (par exemple indisponibilité pendant 6 jours en décembre 2019)

**Comment by kemenaran** [comment]
@Keirua c'est quoi le statut là dessus ?

**Comment by tchak** [comment]
@kemenaran nous sommes en discussion avec l'API Geo.

**Comment by kemenaran** [comment]
État des lieux pour le cadastre :

- L'ancienne API carto a une API cadastre, mais qui envoie des données périmées et qui va expirer.
- L'équipe API Geo n'est plus en train de travailler sur l'API "Cadastre" dont on aurait besoin (elle est presque finie, mais ils n'ont plus de budget).
- L'IGN n'a pas d'API "Cadastre".

On est donc bloqués.

**Comment by tchak** [comment]
done
