### ISSUE TITLE
ETQ Admin, dans les attestations, je veux que TPS me prévienne si j'utilise des balises qui n'existent pas

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#867]
faire une verification au moment de la sauvegarde et afficher une erreur flash si besoin.

**Comment by fredZen** [comment]
@LeSim je le ferais bien via une validation ActiveRecord, ça te parait OK ou trop coercitif ?

**Comment by LeSim** [comment]
avec un before_save ou qqchose du genre ? ca me paraît bien.
