### ISSUE TITLE
Le tri sur des colonnes "nombre" ne marche pas

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#875]
<img width="1280" alt="tps tri marche pas" src="https://user-images.githubusercontent.com/1333173/31720777-cdf92798-b417-11e7-99e2-aa5802020360.png">

Ça fait un tri alphabétique, pas numérique

**Comment by mmagn** [comment]
Même remarque pour les dates 
HS `4797`

**Comment by gregoirenovel** [comment]
@mmagn on fait 2 issues ou on renomme celle-ci ?
