### ISSUE TITLE
ETQ usager, je veux pouvoir distinguer mes dossiers en ajoutant des colonnes dans la liste de mes dossiers

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#903]
pb pour un usager qui a beaucoup de dossiers

**Comment by AnthonyBrunelli** [comment]
L'idéal serait d'avoir la même fonctionnalité de paramétrage de tableau (choix des colonnes) que pour le profil accompagnateur nouvelle version.

Effectivement, pour certaines démarches, l'usager devra s'occuper du suivi de plusieurs dossiers (ex. secrétariat qui s'occupe de transmettre des formulaires pour chaque nouvel arrivant dans la structure, correspondant Cerfa dans les ministères qui envoie une demande d'homologation pour chaque nouveau formulaire, etc.).

**Comment by CamilleGarrigue** [comment]
M.L (CCI Pays de la Loire)
