### ISSUE TITLE
Expliquer pour chaque onglet accompagnateur à quoi il correpond

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/demarches-simplifiees.fr#907]
Quels sont les dossiers affichés ?

À communiquer : MEL

**Comment by mmagn** [comment]
Remonté également par la Pref. Martinique

**Comment by mmagn** [comment]
Voir si les titres d'onglets sont compréhensibles, ex : "suivis" il n'est pas évident pour tout le monde que c'est les dossiers "suivis par vous"
