### ISSUE TITLE
ETQ Instructeur, je souhaite sélectionner les champs des dossiers que j'exporte

### ISSUE THREAD

**Issue by emsnytech** [betagouv/demarches-simplifiees.fr#918]
Aujourd'hui, je suis obligé de tout exporter, et ensuite d'enlever les colonnes qui ne me sont pas utiles.
Quand je dois faire cela pour X procédure, cela est fastidieux et long.

**Comment by kemenaran** [comment]
J'ai l'impression qu'Excel est malgré tout un meilleur outil pour sélectionner les colonnes qu'une UI spécifique qu'on pourrait faire dans DS.

On ferme ?
