### ISSUE TITLE
ETQ Expert, je souhaite être notifié de modification sur les dossiers que je suis

### ISSUE THREAD

**Issue by LeSim** [betagouv/demarches-simplifiees.fr#975]
notification lors de nouveaux messages dans la messagerie ou de changement dans la demande.

**Comment by gregoirenovel** [comment]
On ne notifie l'expert que s'il n'a pas encore rendu son avis ? (formulé autrement : est-ce qu'on fout la paix à ceux qui ont donné leur avis ?)

**Comment by canonne** [comment]
S'agissant de la notification des suites données aux dossiers aux personnes invitées, cela correspond dans le cas de "ma" procédure à une instruction d'une demande d'accès à des données au niveau d'une direction régionale (DREAL) avec une livraison des données par les géomaticiens des directions départementales (DDT) lorsque les données concernent une échelle inférieure ou égale au département. Il est donc important que la DDT ait l'information de l'acceptation de la demande.

**Comment by CamilleGarrigue** [comment]
@A.Ortega (DEA) Dans son cas l'expert ne nécessite pas d'être notifié une fois son avis rendu.

**Comment by CamilleGarrigue** [comment]
@gregoirenovel oui jusqu'à ce qu'il ait rendu son avis. C'est au cours de cette phase que l'expert est susceptible d'envoyer des messages à l'usager et d'avoir besoin de suivre les modifications apportées dans le dossier.

**Comment by gregoirenovel** [comment]
Ça marche, merci pour les précisions :)
